### DISCUSSION TITLE
Automated container image updates

### DISCUSSION THREAD

**Discussion by gbartolini** [cloudnative-pg/cloudnative-pg#1153] [Ideas]
CloudNativePG supports rolling updates when the content of the `imageName` changes. Normally this happens in two occasions:

- a minor update of PostgreSQL (e.g. from 15.1 to 15.2)
- a security update of the container image

When this happens, the operator first updates the standby servers, then if the `primaryUpdateStrategy` is set to `unsupervised` it chooses to automatically perform a switchover or a simple restart of the primary, based on the `primaryUpdateMethod` option.

A feature that has been requested when speaking with customers through my company is to support automated image updates by specifying maintenance windows. The general idea that we've discussed internally with some maintainers, particularly @leonardoce and @mnencia, is to introduce the concept of catalog of PostgreSQL images, organized by major version, as well as a way to configure maintenance windows down to the Postgres cluster level.

Consider this stub of configuration that defines a new resource:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: PostgresImageCatalog
metadata:
  name: postgresql
spec:
  # base name of the registry (to support air-gapped installations too)
  baseName: …
  versions:
   - major: “15”
      fullVersion: “15.1”
      imageID: xxxx
      tag: 15.1-2-debian
     # architectures?
     # ...
```

Ideally, users can customize their own (we could also find ways to generate them from container registries), and we can ship with each patch version of the operator a catalog.

Then in the cluster we allow this:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: xxx

  # PostgreSQL image catalog
  imageCatalog:
    major: 15
    name: postgresql

  # Automated updates section
  automatedUpdates:
    # This requires that primaryUpdateStrategy is unsupervised
    enabled: true
    maintenanceWindows:
    - dow: 0
      start_at: 02:00
      end_at: 08:00
    - dow: 6
      start_at: 03:00
      end_at: 09:30

  storage:
    size: 1Gi
```

In the above example, the cluster is potentially updated if the image contained in the catalog differs from the image in the cluster.

We can obviously elaborate more on maintenance windows (the above example is on a weekly basis).

The idea is to have a separate controller that manages all the Postgres catalogs and takes care of the updates, by changing the imageName of the Postgres clusters as part of maintenance windows.

Let's use this to trigger conversations and ideas.
