### DISCUSSION TITLE
Unable to restore cluster

### DISCUSSION THREAD

**Discussion by onedr0p** [cloudnative-pg/cloudnative-pg#1163] [Q&A]
I recently re-provisioned my k8s cluster and I am trying to get my cnpg postgres instances back up and running from a backup.

## Configuration

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  bootstrap:
    recovery:
      source: postgres-v1
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.default.svc.cluster.local:9000
      serverName: postgres-v2
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
  externalClusters:
    - name: postgres-v1
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://postgresql/
        endpointURL: http://minio.default.svc.cluster.local:9000
        s3Credentials:
          accessKeyId:
            name: postgres-minio
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: postgres-minio
            key: MINIO_SECRET_KEY

```

I notice the recovery pods starts but then has this in the logs:

```
❯ k logs postgres-1-full-recovery-84tmb -f
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":1670718130.802665,"msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"postgres-1"}
{"level":"info","ts":1670718131.1264455,"msg":"Recovering from external cluster","logging_pod":"postgres-1","sourceName":"postgres-v1"}
{"level":"info","ts":1670718131.504308,"msg":"Target backup found","logging_pod":"postgres-1","backup":{"backup_label":"'START WAL LOCATION: 97/A5000028 (file 0000001B00000097000000A5)\\nCHECKPOINT LOCATION: 97/A520DFC8\\nBACKUP METHOD: streamed\\nBACKUP FROM: primary\\nSTART TIME: 2022-12-04 00:00:23 UTC\\nLABEL: Barman backup cloud 20221204T000000\\nSTART TIMELINE: 27\\n'","begin_time":"Sun Dec  4 00:00:00 2022","end_time":"Sun Dec  4 00:02:46 2022","BeginTime":"2022-12-04T00:00:00Z","EndTime":"2022-12-04T00:02:46Z","begin_wal":"0000001B00000097000000A5","end_wal":"0000001B00000097000000A5","begin_xlog":"97/A5000028","end_xlog":"97/A5298BD0","systemid":"7126289626021969944","backup_id":"20221204T000000","error":"","timeline":27}}
{"level":"info","ts":1670718131.504349,"msg":"Starting barman-cloud-restore","logging_pod":"postgres-1","options":["--endpoint-url","http://minio.default.svc.cluster.local:9000","s3://postgresql/","postgres-v1","20221204T000000","--cloud-provider","aws-s3","/var/lib/postgresql/data/pgdata"]}
{"level":"info","ts":1670718163.3468072,"msg":"Restore completed","logging_pod":"postgres-1"}
{"level":"info","ts":1670718163.3468983,"msg":"Creating new data directory","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_99467945","initDbOptions":["--username","postgres","-D","/controller/recovery/datadir_99467945","--no-sync"]}
{"level":"info","ts":1670718163.872612,"logger":"initdb","msg":"The files belonging to this database system will be owned by user \"postgres\".\nThis user must also own the server process.\n\nThe database cluster will be initialized with locale \"en_US.utf8\".\nThe default database encoding has accordingly been set to \"UTF8\".\nThe default text search configuration will be set to \"english\".\n\nData page checksums are disabled.\n\nfixing permissions on existing directory /controller/recovery/datadir_99467945 ... ok\ncreating subdirectories ... ok\nselecting dynamic shared memory implementation ... posix\nselecting default max_connections ... 100\nselecting default shared_buffers ... 128MB\nselecting default time zone ... Etc/UTC\ncreating configuration files ... ok\nrunning bootstrap script ... ok\nperforming post-bootstrap initialization ... ok\n\nSync to disk skipped.\nThe data directory might become corrupt if the operating system crashes.\n\n\nSuccess. You can now start the database server using:\n\n    pg_ctl -D /controller/recovery/datadir_99467945 -l logfile start\n\n","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1670718163.8726363,"logger":"initdb","msg":"initdb: warning: enabling \"trust\" authentication for local connections\nYou can change this by editing pg_hba.conf or using the option -A, or\n--auth-local and --auth-host, the next time you run initdb.\n","pipe":"stderr","logging_pod":"postgres-1"}
{"level":"info","ts":1670718163.8763604,"msg":"Installed configuration file","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_99467945","filename":"pg_hba.conf"}
{"level":"info","ts":1670718163.8764112,"msg":"Ignore minSyncReplicas to enforce self-healing","logging_pod":"postgres-1","syncReplicas":-1,"minSyncReplicas":0,"maxSyncReplicas":0}
{"level":"info","ts":1670718163.8774724,"msg":"Installed configuration file","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_99467945","filename":"custom.conf"}
{"level":"info","ts":1670718164.010987,"msg":"Generated recovery configuration","logging_pod":"postgres-1","configuration":"recovery_target_action = promote\nrestore_command = 'barman-cloud-wal-restore --endpoint-url http://minio.default.svc.cluster.local:9000 s3://postgresql/ postgres-v1 --cloud-provider aws-s3 %f %p'\n"}
{"level":"info","ts":1670718164.0488245,"msg":"enforcing parameters found in pg_controldata","logging_pod":"postgres-1","parameters":{"max_connections":"100","max_locks_per_transaction":"64","max_prepared_transactions":"0","max_wal_senders":"10","max_worker_processes":"32"}}
{"level":"info","ts":1670718164.0670683,"msg":"Starting up instance","logging_pod":"postgres-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000","-o","-c listen_addresses='127.0.0.1'"]}
{"level":"info","ts":1670718164.0941658,"logger":"pg_ctl","msg":"waiting for server to start....2022-12-11 00:22:44.094 UTC [34] FATAL:  data directory \"/var/lib/postgresql/data/pgdata\" has invalid permissions","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1670718164.0941908,"logger":"pg_ctl","msg":"2022-12-11 00:22:44.094 UTC [34] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1670718164.1826944,"logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1670718164.182727,"logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"postgres-1"}
{"level":"info","ts":1670718164.1827502,"logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"postgres-1"}
{"level":"info","ts":1670718164.1830752,"msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"postgres-1"}
{"level":"error","ts":1670718164.1830952,"msg":"Error while restoring a backup","logging_pod":"postgres-1","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:71\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func1\n\tinternal/cmd/manager/instance/restore/cmd.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/proc.go:250"}
```

When that pod errors another one is created and that errors out with saying `Cannot restore, PGDATA exists`,several more pods are created but also error with that, after which it looks like cnpg just gives up. I couldn't find anything in the operator logs that looked relevant to this problem.

```
❯ k logs postgres-1-full-recovery-tcxtn
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":1670766913.182979,"msg":"PGData already exists, can't overwrite","logging_pod":"postgres-1"}
```

Thanks for the help.

**Comment by bjw-s** [comment]
Just chiming in here to say that I am experiencing the same issue.

This is the output of the `bootstrap` initContainer:
```
{"level":"info","ts":1674197614.6689262,"msg":"Installing the manager executable","destination":"/controller/manager","version":"1.18.1","build":{"Version":"1.18.1","Commit":"202661aa","Date":"2022-12-21"}}
{"level":"info","ts":1674197614.919629,"msg":"Setting 0750 permissions"}
{"level":"info","ts":1674197614.9197462,"msg":"Bootstrap completed"}
```

Then the actual restore starts, but that eventually errors out:
```
{"level":"info","ts":1674197615.8552766,"msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"postgres-1"}
{"level":"info","ts":1674197616.2599518,"msg":"Recovering from external cluster","logging_pod":"postgres-1","sourceName":"postgres-v1"}
{"level":"info","ts":1674197616.972753,"msg":"Target backup found","logging_pod":"postgres-1","backup":{"backup_label":"'START WAL LOCATION: AF/E3000060 (file 0000001F000000AF000000E3)\\nCHECKPOINT LOCATION: AF/E33C7430\\nBACKUP METHOD: streamed\\nBACKUP FROM: primary\\nSTART TIME: 2023-01-15 00:00:25 CET\\nLABEL: Barman backup cloud 20230115T000000\\nSTART TIMELINE: 31\\n'","begin_time":"Sun Jan 15 00:00:01 2023","end_time":"Sun Jan 15 00:02:30 2023","BeginTime":"2023-01-15T00:00:01Z","EndTime":"2023-01-15T00:02:30Z","begin_wal":"0000001F000000AF000000E3","end_wal":"0000001F000000AF000000E3","begin_xlog":"AF/E3000060","end_xlog":"AF/E34E2D90","systemid":"7129857460837388312","backup_id":"20230115T000000","error":"","timeline":31}}
{"level":"info","ts":1674197616.9727988,"msg":"Starting barman-cloud-restore","logging_pod":"postgres-1","options":["--endpoint-url","http://s3.bjw-s.dev","s3://postgresql/","postgres-v1","20230115T000000","--cloud-provider","aws-s3","/var/lib/postgresql/data/pgdata"]}
{"level":"info","ts":1674197665.919963,"msg":"Restore completed","logging_pod":"postgres-1"}
{"level":"info","ts":1674197665.9200919,"msg":"Creating new data directory","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_2819869012","initDbOptions":["--username","postgres","-D","/controller/recovery/datadir_2819869012","--no-sync"]}
{"level":"info","ts":1674197666.7991185,"logger":"initdb","msg":"The files belonging to this database system will be owned by user \"postgres\".\nThis user must also own the server process.\n\nThe database cluster will be initialized with locale \"en_US.utf8\".\nThe default database encoding has accordingly been set to \"UTF8\".\nThe default text search configuration will be set to \"english\".\n\nData page checksums are disabled.\n\nfixing permissions on existing directory /controller/recovery/datadir_2819869012 ... ok\ncreating subdirectories ... ok\nselecting dynamic shared memory implementation ... posix\nselecting default max_connections ... 100\nselecting default shared_buffers ... 128MB\nselecting default time zone ... Europe/Amsterdam\ncreating configuration files ... ok\nrunning bootstrap script ... ok\nperforming post-bootstrap initialization ... ok\n\nSync to disk skipped.\nThe data directory might become corrupt if the operating system crashes.\n\n\nSuccess. You can now start the database server using:\n\n    pg_ctl -D /controller/recovery/datadir_2819869012 -l logfile start\n\n","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1674197666.7991612,"logger":"initdb","msg":"initdb: warning: enabling \"trust\" authentication for local connections\nYou can change this by editing pg_hba.conf or using the option -A, or\n--auth-local and --auth-host, the next time you run initdb.\n","pipe":"stderr","logging_pod":"postgres-1"}
{"level":"info","ts":1674197666.8116536,"msg":"Installed configuration file","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_2819869012","filename":"pg_hba.conf"}
{"level":"info","ts":1674197666.8117638,"msg":"Ignore minSyncReplicas to enforce self-healing","logging_pod":"postgres-1","syncReplicas":-1,"minSyncReplicas":0,"maxSyncReplicas":0}
{"level":"info","ts":1674197666.8158941,"msg":"Installed configuration file","logging_pod":"postgres-1","pgdata":"/controller/recovery/datadir_2819869012","filename":"custom.conf"}
{"level":"info","ts":1674197670.7981627,"msg":"Generated recovery configuration","logging_pod":"postgres-1","configuration":"recovery_target_action = promote\nrestore_command = 'barman-cloud-wal-restore --endpoint-url http://s3.bjw-s.dev s3://postgresql/ postgres-v1 --cloud-provider aws-s3 %f %p'\n"}
{"level":"info","ts":1674197670.8237412,"msg":"enforcing parameters found in pg_controldata","logging_pod":"postgres-1","parameters":{"max_connections":"100","max_locks_per_transaction":"64","max_prepared_transactions":"0","max_wal_senders":"10","max_worker_processes":"32"}}
{"level":"info","ts":1674197670.8383853,"msg":"Starting up instance","logging_pod":"postgres-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000","-o","-c listen_addresses='127.0.0.1'"]}
{"level":"info","ts":1674197670.8681226,"logger":"pg_ctl","msg":"waiting for server to start....2023-01-20 07:54:30.867 CET [39] FATAL:  data directory \"/var/lib/postgresql/data/pgdata\" has invalid permissions","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1674197670.8681579,"logger":"pg_ctl","msg":"2023-01-20 07:54:30.867 CET [39] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1674197670.953033,"logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"postgres-1"}
{"level":"info","ts":1674197670.953159,"logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"postgres-1"}
```

**Comment by dspeck1** [comment]
We have a similar issue.  We had this error and also it is stuck in recovery mode.  How do we bring the server out of recovery mode?

**Comment by Katana-github-rakuten** [comment]
We have the same issue as well. Please help with the solution

**Comment by dspeck1** [comment]
Is there a way to interact with the CNPG controller directly?  kubectl cnpg promote, restart, and reload do not bring the cluster back to a working state.  We have had  restore from backup on three different clusters because CNPG gets stuck.

**Comment by FlosseJonsson** [comment]
We also have the same issue as well. Please help with the solution! Anyone?

**Comment by relhajja** [comment]
I have the same issue ! :°)

**Comment by Ofirfr** [comment]
I am having a similar issue, but with trying to `import` data from an `externalCluster`.
It also fails on `PGData already exists, can't overwrite`.

Someone has any workaround / solution?

**Comment by dperetti** [comment]
Sharing my (tested) procedure to create a fresh cluster from a broken one.
The idea is to use a basic, non cnpg, postgresql server to serve the database from the recovered pgdata and use is as an externalCluster for the fresh cluster.


## How to rescue a db from a volume.

Step 1: spawn a quick & dirty postgres server with the rescued pgdata
- Make sure the volume is detached from any cluster.
- Create an ubuntu server. (from the web console)
- Attach the volume to the server. (from the web console)
- The `pgdata` directory should be visible at something like: `/mnt/HC_Volume_100568173/pgdata/` .
- Delete or rename the following files:
  - `custom.conf`
  - `override.conf`
- touch `recovery.signal` ?
- Launch the server with: <br>`docker run -ti -v /mnt/HC_Volume_100568173/pgdata/:/var/lib/postgresql/data -p 5432:5432 postgres`

Step 2: Create a fresh cnpg cluster and use that server as an external bootstrap source:

```yaml

apiVersion: v1
kind: Secret
metadata:
  name: rescue-user-secret
data:
  password: UWdGcqsdeFVjd2ZlMEhUWUdHVUNMZF4MG5VN2d2NlJ5TU5FalVER04zZ0xHdqsdpNWZzaGVLU3BsSm9KYg==

---

spec:
  instances: 1

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - app
        source:
          externalCluster: cluster-rescue

  externalClusters:
  - name: cluster-rescue
    connectionParameters:
      # Use the correct IP or host name for the source database
      host: 162.55.185.121
      port: '5432'
      user: postgres
      dbname: app
    password:
      name: rescue-user-secret
      key: password
```
