### DISCUSSION TITLE
Unable to connect to the cluster using kubectl port-forward

### DISCUSSION THREAD

**Discussion by wascript3r** [cloudnative-pg/cloudnative-pg#1171] [General]
Hello, I have recently deployed CNPG operator & Postgres cluster locally on my **kind** k8s cluster. Everything looks great at first, the operator and the cluster are running successfully, without errors, the DB migration service inside cluster is also able to connect to postgres instance without any issues (using `postgres-cluster-rw` service).

The issue I'm facing right now is that I cannot connect to postgres cluster on my host machine when using `kubectl port-forward svc/postgres-cluster-rw 5432:5432` and trying to create a DB connection on GoLand IDE. Speaking in detail, when creating a connection in GoLand, it show that connection has succeeded, but then the `kubectl port-forward` command terminates with an error (almost always the error is `read: connection reset by peer`,  but a couple of times I encountered something like `write: broken pipe`):

<img width="809" alt="image" src="https://user-images.githubusercontent.com/26647188/206717060-22f1f2a5-de66-46bf-ae4c-810803a7224f.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/26647188/206717109-c392db38-5346-433f-ac58-42c8e2232b97.png">

In fact, whether I provide the correct postgres credentials or incorrect ones, the port forwarding command fails every time a connection is attempted. I also tried to reproduce the issue on remote k3s cluster - same thing happens, so my guess is that it's not related to kind or k3s specifically. Interesting thing - the port-forward cmd does not terminate when I am creating a connection from a simple Go application (on my **host** machine). I'm not facing this issue when deploying basic postgres stateful set. Could this issue be related to CNPG? Or maybe `kubectl` itself (or even GoLand)?

The environment I'm using:
- macOS Ventura **13.0**
- GoLand IDE **2022.3**
- kind version **0.17.0**
- `kubectl version -o yaml`:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/26647188/206711155-7e927403-f5d9-42b0-a130-a1feca1687ca.png">

- CNPG **1.18** (https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.18/releases/cnpg-1.18.0.yaml)
- CNPG Cluster resource:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 2
  superuserSecret:
    name: pg-root-cred
  bootstrap:
    initdb:
      database: app
      owner: app
  storage:
    size: 1Gi
```

**Comment by sxd** [comment]
hi @wascript3r 

This it's not related to the operator, and probably neither kind, this it's more a network layer and probably on how you run kind, are you using a virtual machine to run it? do you have permissions on the machine to open ports? It's more related to a configuration issue than something else

**Reply by wascript3r** [reply]
Kind runs in a single Docker container on my MacBook. My macOS user has full permissions to open ports, as I mentioned before, I have never had any issue connecting to postgres service on my mac when it was deployed as a basic statefulset (not using cnpg) on both kind and remote k3s clusters. Also, by looking at the tcpdump, I could see that the port on my mac was opened successfully and is receiving packets when trying to open a new postgres connection (in addition, if the port failed to open, I wouldn't get a "connection succeeded" message in GoLand).

**Reply by wascript3r** [reply]
I think this issue could be related to default postgres configuration (pg_hba.conf):
```
postgres@postgres-cluster-1:/$ cat /var/lib/postgresql/data/pgdata/pg_hba.conf

# Grant local access
local all all peer map=local

# Require client certificate authentication for the streaming_replica user
hostssl postgres streaming_replica all cert
hostssl replication streaming_replica all cert
hostssl all cnpg_pooler_pgbouncer all cert




# Otherwise use the default authentication method
host all all all scram-sha-256
```
because if I try to append `?sslmode=disable` to pg connection string in GoLand, the connection is successful and port-forward does not terminate. Probably just need to append another line to pg_hba.conf, which allows remote SSL connections.

**Reply by sxd** [reply]
"connection reset by peer" <-- that's a network error, if you're rejected by PostgreSQL the error will be other kind of error, also, GoLand it's not part of the equation, it's an IDE nothing to do here and a lot of people will have problems connecting, so no it's not an issue related to `pg_hba.conf` file.

Can you set `spec.logLevel` to `debug` and also enable the postgresql logs with pg_audit and from there check the logs and see if the connection reach your cluster?

**Reply by wascript3r** [reply]
Cluster yaml:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  logLevel: debug
  instances: 2
  superuserSecret:
    name: pg-root-cred
  bootstrap:
    initdb:
      database: cryptogame
      owner: cryptogame
      secret:
        name: pg-cryptogame-cred
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
  storage:
    size: 1Gi
```

postgres-cluster-1 logs:
```
{"level":"info","ts":1670882182.0971506,"logger":"pgaudit","msg":"record","logging_pod":"postgres-cluster-1","record":{"log_time":"2022-12-12 21:56:22.096 UTC","user_name":"cryptogame","database_name":"cryptogame","process_id":"422","connection_from":"127.0.0.1:53478","session_id":"6397a385.1a6","session_line_num":"1","command_tag":"BIND","session_start_time":"2022-12-12 21:56:21 UTC","virtual_transaction_id":"4/223","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","backend_type":"client backend","query_id":"0","audit":{"audit_type":"SESSION","statement_id":"1","substatement_id":"1","class":"READ","command":"SELECT","statement":"select version()","parameter":"<none>"}}}
{"level":"info","ts":1670882182.2717452,"logger":"pgaudit","msg":"record","logging_pod":"postgres-cluster-1","record":{"log_time":"2022-12-12 21:56:22.271 UTC","user_name":"cryptogame","database_name":"cryptogame","process_id":"422","connection_from":"127.0.0.1:53478","session_id":"6397a385.1a6","session_line_num":"2","command_tag":"BIND","session_start_time":"2022-12-12 21:56:21 UTC","virtual_transaction_id":"4/225","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","application_name":"GoLand 2022.3","backend_type":"client backend","query_id":"0","audit":{"audit_type":"SESSION","statement_id":"2","substatement_id":"1","class":"READ","command":"SELECT","statement":"SELECT 'keep alive'","parameter":"<none>"}}}
```
