### DISCUSSION TITLE
Can't enable pg_cron via bootstrap section

### DISCUSSION THREAD

**Discussion by loktionovam** [cloudnative-pg/cloudnative-pg#1173] [General]
Hello, I am trying to install and enable pg_cron extension like this

1. Build custom docker image with preinstalled pg_cron extension 
```shell
FROM ghcr.io/cloudnative-pg/postgresql:14.5

USER root
RUN apt-get update \
    && apt-get install -y postgresql-14-cron

USER postgres
```

2. Use the image and enable pg_cron extension in bootstrap.initdb section:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cls-1
spec:
  instances: 1
  imageName: loktionovam/postgresql-cls:14.5
  bootstrap:
    initdb:
      database: cls
      owner: cls
      postInitApplicationSQL:
       # here the problem
        - CREATE EXTENSION pg_cron;
        - GRANT USAGE ON SCHEMA cron TO cls;
  storage:
    # storageClass: local-path
    size: 15Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "200m"
  postgresql:
    shared_preload_libraries:
      - pg_cron
    parameters:
      shared_buffers: 512MB
      cron.database_name: cls

```

I am getting an error:

```json
{"level":"error","ts":1668786612.3641598,"msg":"Error while bootstrapping data directory","logging_pod":"postgres-cls-1-1","error":"while configuring new instance: could not execute init Application queries: ERROR: can only create extension in database postgres (SQLSTATE P0001)","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:134\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:94\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/proc.go:250"}
Error: while configuring new instance: could not execute init Application queries: ERROR: can only create extension in database postgres (SQLSTATE P0001)
```

It looks like postgres parameters are ignored by the operator during bootstrap stage:
```yaml
  postgresql:
    shared_preload_libraries:
      - pg_cron
    parameters:
      shared_buffers: 512MB
      # need to setup cron.database_name = 'cls' as it described here https://github.com/citusdata/pg_cron#setting-up-pg_cron 
      cron.database_name: cls
```

because I can create an extension manually later if I remove ` CREATE EXTENSION pg_cron;` from bootstrap

I use 1.17.1 operator version:

```shell
helm list                                                                                                                                             ─╯
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
cloudnative-pg  default         1               2022-11-18 11:21:51.21236371 +0000 UTC  deployed        cloudnative-pg-0.15.1   1.17.1  
```
