### DISCUSSION TITLE
recovery from backup with 1.18 doesn't work

### DISCUSSION THREAD

**Discussion by ns-jhu** [cloudnative-pg/cloudnative-pg#1189] [Q&A] [answered]
I have created a cluster with this:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: cnpg-1
  namespace: cnpg-system
  annotations:
    categories: database
  labels:
    environment: dev
    workload: database
    app: clickhouse

spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:15.0


  # Parameters and pg_hba configuration will be append
  # to the default ones to make the cluster work
  postgresql:
    parameters:
      max_connections: "300"
      max_worker_processes: "60"
      shared_buffers: "1GB"
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"

    #pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      #- host all all all md5


  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  logLevel: debug 

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30

  #superuserSecret:
  #  name: cnpg-1-superuser

  bootstrap:
    initdb:
      database: app
      owner: app
      #secret:
      #  name: cnpg-1-app

  backup:
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-1/"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip # WAL compression is enabled
        #maxParallel: 8
        #encryption: AES256
    retentionPolicy: "30d"
```

and then created backup like this:
```
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-1-backup
  namespace: cnpg-system
spec:
  immediate: true # Backup starts immediately after ScheduledBackup has been created
  schedule: "0 0 0 * * *"
  cluster:
    name: cnpg-1

---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cnpg-1-backup
  namespace: cnpg-system
spec:
  cluster:
    name: cnpg-1

```
which produced the backup files:

gsutil ls gs://clickhouse-backup-restore/cnpg-1/cnpg-1/

gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/wals/

gsutil ls gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base

gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010443/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010444/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010445/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010446/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010447/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010448/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010533/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010534/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010535/
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/base/20221213T010536/

gsutil ls gs://clickhouse-backup-restore/cnpg-1/cnpg-1/wals
gs://clickhouse-backup-restore/cnpg-1/cnpg-1/wals/0000000100000000/

but when I try to restore with this:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: cnpg-restore-1
  namespace: cnpg-system
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:15.0
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  logLevel: debug 

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30

  superuserSecret:
    name: cnpg-1-superuser

  bootstrap:
    recovery:
      source: cnpg-1
      database: app
      owner: app
      secret:
        name: cnpg-1-app



  externalClusters:
  - name: cnpg-1
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-1"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        maxParallel: 8

#  backup:
#    barmanObjectStore:
#      destinationPath: "gs://clickhouse-backup-restore/cnpg-restore-1/"
#      serverName: "cnpg-restore-1"
#      googleCredentials:
#        applicationCredentials:
#          name: backup-creds
#          key: gcsCredentials
#      wal:
#        compression: gzip # WAL compression is enabled
        #maxParallel: 8
        #encryption: AES256
#    retentionPolicy: "30d"

```

the restore cluster  cnpg-restore-1 came up without any data, not even the table. even though I see the log
```
{"level":"info","ts":1670969589.3477504,"logger":"postgres","msg":"record","logging_pod":"cnpg-restore-1-1","record":{"log_time":"2022-12-13 22:13:09.347 UTC","process_id":"46","session_id":"6398f86f.2e","session_line_num":"12","session_start_time":"2022-12-13 22:10:55 UTC","virtual_transaction_id":"1/0","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"restored log file \"00000001000000000000001D\" from archive","backend_type":"startup","query_id":"0"}}
```

then I tried another approach:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: cnpg-restore-backup-1
  namespace: cnpg-system
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:15.0
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30

  superuserSecret:
    name: cnpg-1-superuser

  bootstrap:
    recovery:
      backup:
        name: cnpg-1
      secret:
        name: cnpg-1-app


  externalClusters:
  - name: cnpg-1
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-1"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-restore-backup-1/"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip # WAL compression is enabled
        #maxParallel: 8
        #encryption: AES256
    retentionPolicy: "30d"
```

this time , the cluster  cnpg-restore-backup-1 doesn't even come up. I see the log 
```
{"level":"info","ts":1670976015.7175598,"msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-restore-backup-1","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"cnpg-restore-backup-1","reconcileID":"78b7cf23-7c62-4fe7-933d-dd81ecf249e1","uuid":"49f48a49-7b42-11ed-b697-da3d1d696ee8","latestGeneratedNode":1}
```

I am using 1.18 release version , does anybody know how to solve this problem ? I need to get this working one way or another.

**Comment by sxd** [comment, marked as answer]
Hi @ns-jhu 

What you're looking for it's answered in the following documentation https://cloudnative-pg.io/documentation/1.18/bootstrap/#bootstrap-from-a-backup-recovery

**Reply by gbartolini** [reply]
You need to have a consistent replica configuration (PostgreSQL configuration I mean) in the restored cluster. Make sure you reapply the same settings at least at the start of the recovered cluster. This is a requirement of PostgreSQL, not the operator BTW (that's how physical backups work).

**Comment by ns-jhu** [comment]
Thanks. after I made sure all configuration same as the original cluster, the restore worked. I think we probably should @gbartolini's comment into https://cloudnative-pg.io/documentation/1.18/bootstrap/#bootstrap-from-a-backup-recovery to save future grief from potential user.

**Reply by ns-jhu** [reply]
however, I continued the test with replica cluster, this worked fine:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-replica-ostore-1
  namespace: cnpg-system
spec:
  instances: 1

  # Parameters and pg_hba configuration will be append
  # to the default ones to make the cluster work
  postgresql:
    parameters:
      max_connections: "300"
      max_worker_processes: "60"
      shared_buffers: "1GB"
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"

    #pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      #- host all all all md5


  #certificates:
  #  serverCASecret: cnpg-1-ca
  #  serverTLSSecret: cnpg-1


  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  logLevel: debug 

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30

  bootstrap:
    recovery:
      source: cnpg-1
      database: app
      owner: app
      secret:
        name: cnpg-1-app

  replica:
    enabled: true
    source: cnpg-1


  externalClusters:
  - name: cnpg-1
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-1/"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials


  backup:
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-replica-ostore-1/"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip # WAL compression is enabled
        #maxParallel: 8
        #encryption: AES256
    retentionPolicy: "30d"
```

with initial data, and subsequent delta replicated over. 

However, if I change the bootstrap to streaming:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-replica-streaming-1
  namespace: cnpg-system
spec:
  instances: 1

  # Parameters and pg_hba configuration will be append
  # to the default ones to make the cluster work
  postgresql:
    parameters:
      max_connections: "300"
      max_worker_processes: "60"
      shared_buffers: "1GB"
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"

    #pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      #- host all all all md5


  #certificates:
  #  serverCASecret: cnpg-1-ca
  #  serverTLSSecret: cnpg-1


  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  logLevel: debug 

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30



  bootstrap:
    pg_basebackup:
      source: cnpg-1
      database: app
      owner: app
      secret:
        name: cnpg-1-app

  replica:
    enabled: true
    source: cnpg-1

  externalClusters:
  - name: cnpg-1
    connectionParameters:
      host: cnpg-1-rw.cnpg-system.svc
      user: streaming_replica
      sslmode: verify-full
    sslKey:
      name: cnpg-1-replication
      key: tls.key
    sslCert:
      name: cnpg-1-replication
      key: tls.crt
    sslRootCert:
      name: cnpg-1-ca
      key: ca.crt


  backup:
    barmanObjectStore:
      destinationPath: "gs://clickhouse-backup-restore/cnpg-replica-streaming-1/"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip # WAL compression is enabled
        #maxParallel: 8
        #encryption: AES256
    retentionPolicy: "30d"


```

the initial records  bootstrapped via streaming showed up, but when I inserted the new records into the primary cluster, the delta doesn't show up. 

the only difference of these 2 replica cluster is that the former is via object store. while the latter is via streaming during streaming. there is no difference for anything else. What can cause the delta in the streaming replica cluster not show up ? is this a bug ?
