### DISCUSSION TITLE
Add post-install and post-upgrade hooks

### DISCUSSION THREAD

**Discussion by mofirouz** [cloudnative-pg/cloudnative-pg#1226] [General]
We'd like to run TimescaleDB deployed by CNPG; As part of this setup, we'd need to:

1. On new cluster installation, activate the Extension:

```
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit;
```

2. On existing cluster, for upgrades of TSDB (whether leaving Postgres as it is or post-Postgres upgrade):

```
ALTER EXTENSION timescaledb UPDATE;
ALTER EXTENSION timescaledb_toolkit UPDATE;
```

As we'd run these in an automated fashion (internally), it would be great if we could have this as part of the Cluster YAML submitted to CNPG that it will auto-run deterministically based on the state of the cluster.

**Comment by gbartolini** [comment]
The first one can already be done using the post install script (`postInitApplicationSQL`) in the `initdb` bootstrap.

The second one is a bit more complex to implement. Some food for thought here. Ideally we should be able to query the catalog of installed extensions in the system and detect any discrepancy between the available extension (`pg_available_extension_versions` view) and the one installed in the app database (`pg_extension`). Given that in an immutable world the availability of a newer extension requires a restart, we could think of a process to run during restarts that verifies the above and calls the `UPDATE` for a list of given extensions. Another interesting function to check is `pg_extension_update_paths('extension_name')`.

References:

- https://www.postgresql.org/docs/current/view-pg-available-extension-versions.html
- https://www.postgresql.org/docs/current/catalog-pg-extension.html
- https://www.postgresql.org/docs/current/extend-extensions.html#id-1.8.3.20.14

**Comment by VeeeneX** [comment]
If someone stumbles upon this this is example config:
  
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgis-example
spec:
  instances: 3
  # Currenly only supported version I can maintain that repo 
  imageName: ghcr.io/veeenex/postgis-timescale-containers:14

  postgres:
    shared_preload_libraries: ["timescaledb"]
  
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;

      postInitApplicationSQL:
        - "CREATE EXTENSION IF NOT EXISTS timescaledb;"
  storage:
    size: 1Gi
```

Currenly only supported version I can maintain that repo, if needed:
  
```imageName: ghcr.io/veeenex/postgis-timescale-containers:14```
