### DISCUSSION TITLE
Support for VolumeSnapshot recovery

### DISCUSSION THREAD

**Discussion by BerkayIlhan** [cloudnative-pg/cloudnative-pg#1286] [Ideas]
I'm testing a backup solution by making VolumeSnapshots of the PVC of my primary PostgresCluster with the vmware-csi-driver. 

I would like to use these VolumeSnapshots as a recovery solution to restore my database in a disaster scenario. Our storage backend replicates the volumes to a secondary site.

The only options available now are to recover from an existing Postgres cluster or from a object storage with Barman. But backups take very long especially with multiple terabytes databases.

I thought that the  **_spec.storage.pvcTemplate.dataSource_** field was supposed to be used to recover from a VolumeSnapshot but when I refer to the VolumeSnapshot the operator tries to init the cluster but exits with the following error: 

```bash
{"level":"info","ts":1666623431.0327022,"msg":"PGData already exists, can't overwrite","logging_pod":"cluster-example-1"}
Error: PGData directories already exist
```

Here is an example of what I tried:

**VolumeSnapshot:**
```bash 
NAME       READYTOUSE   SOURCEPVC         SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS    SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snapshot   true         vmaas-vri-rec-1                           50Gi          snapshot-class   snapcontent-39ba123b-dd3f-4016-89c4-17091a26b2f0   118m           118m
apiVersion: postgresql.cnpg.io/v1
```

**PostgresCluster:**
```
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  storage:
    storageClass: fast-thin
    size: 50Gi
    pvcTemplate:
      dataSource:
        name: snapshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
```

I would really like to see the support for VolumeSnapshots because they can be created instantaneously and they are immediately available at the recovery site.
