### DISCUSSION TITLE
restore cluster health when replica pods are not healthy

### DISCUSSION THREAD

**Discussion by ns-jhu** [cloudnative-pg/cloudnative-pg#1351] [Q&A]
I created a cluster with primaryUpdateStrategy: supervised and 3 pods. 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: pg-app01
  namespace: tpdata
  annotations:
    categories: database
  labels:
    environment: dev
    workload: database
    app: clickhouse

spec:
  instances: 5
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: supervised


```

then I noticed my disk is full, so I increased it to bigger storage. then I noticed that the primary pod pg-app01-1 storage increased, and the 2 replica pods storage did not. and the status report says: 
waiting for manual switch over. 

so I issued a promotion command to promote pg-app01-2 to primary. however, that pod  shows CrashLoopBackOff and never come up, the original primary pg-app01-1  became Standby. and the switchover never completes. 

so I finally promote the original primary pg-app01-1  back to become primary again, the trouble is, the pg-app01-2 pod stays  CrashLoopBackOff forever.  is there anyway I can do  to restore the health of the cluster ? I attempted to set the instance count from 3 to 1, in the hope that the 2 replica can be cleaned up,  it doesn't help.

so I am stuck with this:

Status:             Switchover in progress Switching over to pg-app01-1

Instances status
Name        Database Size  Current LSN  Replication role     Status             QoS        Manager Version  Node
----        -------------  -----------  ----------------     ------             ---        ---------------  ----
pg-app01-1  30 MB          0/58000000   Primary              OK                 Burstable  1.18.1           knode01
pg-app01-3                              Standby (pg_rewind)  OK                 Burstable  1.18.1           knode01
pg-app01-2  -              -            -                    pod not available  Burstable  -                knode01

is  there anything I can do to restore health of the cluster ?

I also attempted to set instance count from 1 to 5 , in the hope that I can get another 2 good replica for reading, no luck either. 

in the cnpg-controller-manager log, I see this

"name":"pg-app01-2","error":"Get \"http://10.114.221.2:8000/pg/status\": dial tcp 10.114.221.2:8000: connect: connection refused"
and  the IP 10.114.221.2 is the IP of the dead pod pg-app01-2. which of course, is un-reachable. 

does that mean if the pg-app01-2 doesn't come back, we are totally screwed and can't recover at all ?
