### DISCUSSION TITLE
How to "reset" Last Failed WAL?

### DISCUSSION THREAD

**Discussion by onedr0p** [cloudnative-pg/cloudnative-pg#1402] [Q&A] [answered]
Hi 👋🏼 

I am using the suggested `PrometheusRule` and noticed I keep getting alerted on `LastFailedArchiveTime` even though the WALs are being successfully backed up now. Is there anyway to clear this metric back to `-1` so I don't keep getting alerted?

# Rule from docs

```yaml
...
        - alert: LastFailedArchiveTime
          annotations:
            description: Archiving failed for {{ $labels.pod }}
            summary: Checks the last time archiving failed. Will be -1 when it has not failed.
          expr: |-
            cnpg_pg_stat_archiver_last_failed_time > 1
          for: 1m
          labels:
            severity: warning
...
```

# Status

```
❯ k cnpg status postgres
Cluster Summary
Name:               postgres
Namespace:          default
System ID:          7126289626021969944
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:14.5
Primary instance:   postgres-2
Status:             Cluster in healthy state
Instances:          3
Ready instances:    3
Current Write LSN:  E4/260FB560 (Timeline: 43 - WAL File: 0000002B000000E400000026)

Certificates Status
Certificate Name      Expiration Date                Days Left Until Expiration
----------------      ---------------                --------------------------
postgres-ca           2023-04-08 04:45:04 +0000 UTC  60.31
postgres-replication  2023-04-08 04:45:04 +0000 UTC  60.31
postgres-server       2023-04-08 04:45:04 +0000 UTC  60.31

Continuous Backup status
First Point of Recoverability:  2023-01-08T05:20:10Z
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              0000002B000000E400000025   @   2023-02-06T21:15:49.938802Z
Last Failed WAL:                0000002B000000E0000000C1   @   2023-02-04T14:02:44.92051Z

Streaming Replication status
Name        Sent LSN     Write LSN    Flush LSN    Replay LSN   Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority
----        --------     ---------    ---------    ----------   ---------  ---------  ----------  -----      ----------  -------------
postgres-1  E4/260FB560  E4/260FB560  E4/260FB560  E4/260FB560  00:00:00   00:00:00   00:00:00    streaming  async       0
postgres-3  E4/260FB560  E4/260FB560  E4/260FB560  E4/260FB560  00:00:00   00:00:00   00:00:00    streaming  async       0

Unmanaged Replication Slot Status
No unmanaged replication slots found

Instances status
Name        Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----        -------------  -----------  ----------------  ------  ---         ---------------  ----
postgres-2  2786 MB        E4/260FB560  Primary           OK      BestEffort  1.18.1           k8s-5
postgres-1  2786 MB        E4/260FB560  Standby (async)   OK      BestEffort  1.18.1           k8s-0
postgres-3  2786 MB        E4/260FB560  Standby (async)   OK      BestEffort  1.18.1           k8s-2
```

# Prometheus

```
cnpg_pg_stat_archiver_last_failed_time{container="postgres", endpoint="metrics", instance="10.42.152.226:9187", job="default/postgres", namespace="default", pod="postgres-1"} | -1
cnpg_pg_stat_archiver_last_failed_time{container="postgres", endpoint="metrics", instance="10.42.173.28:9187", job="default/postgres", namespace="default", pod="postgres-2"} | 1675519364.92051
cnpg_pg_stat_archiver_last_failed_time{container="postgres", endpoint="metrics", instance="10.42.200.210:9187", job="default/postgres", namespace="default", pod="postgres-3"} | -1
```
