### DISCUSSION TITLE
Question: PVC reuse

### DISCUSSION THREAD

**Discussion by simonoff** [cloudnative-pg/cloudnative-pg#1464] [Q&A]
Hello guys,

First of all thank you for such great software! 

I have a small question.
We using Kubernetes in local development and do the deployment though skaffold.
When we starting the dev mode again we want to reuse a PVC.
I have tried to do the same logic with your cluster, but all the time it stacked on postgres init stage. 
Is it possible to reuse PVC without running init all the time? We are all the time creating and removing cluster due to the behaviour of skaffold.

**Comment by gbartolini** [comment]
Can you please elaborate more? Maybe even by sharing the commands you are trying to execute? This will allow us to walk down the ladder of inference and get to a common ground, removing any misunderstandings or wrong assumptions, while also help everyone understand what you are trying to achieve. Thanks!

P.S.: Thanks for the nice words!

**Reply by simonoff** [reply]
Good morning. 
Generally i'm using skaffold + helm combination.

I have a next one manifest:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "sep.postgres.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "sep.labels" . | nindent 4 }}
spec:
  description: 'SEP postgres database cluster'
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  instances: {{ .Values.cnpg.instances }}
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: {{ .Values.cnpg.clusterDatabase }}
      owner: {{ .Values.cnpg.databaseOwner }}
      secret:
        name: {{ include "sep.postgres.userSecretName" . }}
  superuserSecret:
    name: {{ include "sep.postgres.superUserSecretName" . }}
  backup:
    {{- toYaml .Values.cnpg.backup | nindent 4 }}
  storage:
    {{- toYaml .Values.cnpg.storage | nindent 4 }}
  resources:
    {{- toYaml .Values.cnpg.resources | nindent 4 }}
```

Skaffold in dev mode all the time cleaning resources. So it will create a cluster via helm and after remove the all resources helm created. 
For such thing we found a way to run a shell script before which creates a PVC for storing ruby gems and node_modules.
Like this:
```yaml
apiVersion: 'v1'
kind: PersistentVolumeClaim
metadata:
  name: yarn-modules
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '1Gi'
```

So I have tried to create a PVC with similar name as operator creates, but all the time initdb said that folder is exists.
