### DISCUSSION TITLE
Backup to Backblaze S3

### DISCUSSION THREAD

**Discussion by xoxys** [cloudnative-pg/cloudnative-pg#1664] [Q&A]
I've tried to use Backblaze S3 for backups, but can't get it to work:

```
{"level":"info","ts":"2023-03-04T13:45:08Z","msg":"WAL archiving is working","logging_pod":"drone-server-postgres-1"}
{"level":"info","ts":"2023-03-04T13:45:08Z","msg":"Backup started","backupName":"drone-server-postgres-backup","backupNamespace":"drone-server-postgres-backup","logging_pod":"drone-server-postgres-1","options":["--user","postgres","--gzip","--endpoint-url","https://s3.us-west-004.backblazeb2.com","--cloud-provider","aws-s3","s3://drone-server/","drone-server-postgres"]}
{"level":"info","ts":"2023-03-04T13:45:16Z","logger":"barman-cloud-backup","msg":"2023-03-04 13:45:16,948 [194889] ERROR: Barman cloud backup exception: An error occurred (500) when calling the HeadBucket operation (reached max retries: 4): Internal Server Error","pipe":"stderr","logging_pod":"drone-server-postgres-1"}
{"level":"error","ts":"2023-03-04T13:45:17Z","msg":"Backup failed","backupName":"drone-server-postgres-backup","backupNamespace":"drone-server-postgres-backup","logging_pod":"drone-server-postgres-1","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:281"}
```

I've already tried multiple combinations of `destinationPath` and `endpointURL` but so far without success. Is Backblaze S3 not supported or something wrong with the configuration?

```
backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://drone-server/
      endpointURL: https://s3.us-west-004.backblazeb2.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: cnpg-backup-s3
        inheritFromIAMRole: false
        secretAccessKey:
          key: SECRET_ACCESS_KEY
          name: cnpg-backup-s3
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: 30d
    target: primary
```

**Comment by ilbarone87** [comment]
Hello have you found the solution for this error?
I'm trying to backup to MinIO but getting similar error

**Reply by xoxys** [reply]
For Backblaze S3 no, but these settings are working with minio for me:

```Yaml
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cloud-infra-backup/cnpg/drone-server/github
      endpointURL: https://s3.cloud-infra.example.com/
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 8
      data:
        compression: gzip
```
