### DISCUSSION TITLE
Replica cluster pod stuck in CrashLoopBackOff state on OpenShift

### DISCUSSION THREAD

**Discussion by ghost** [cloudnative-pg/cloudnative-pg#1697] [Q&A] [answered]
We'd like to construct replica cluster using CloudNativePG Operator on OpenShift but it fails.

When constructing a replica cluster based on a backup saved in S3-compatible storage, the pod under construction may be in the CrashLoopBackOff state and the construction of the replica cluster may be failed. It doesn't always fail, sometimes it succeeds.

If there is a way to resolve it, could you please let me know.

* Versions
  * OpenShift : v4.11.12
  * CloudNativePG Operator : v1.19.0
    * Same error occurred in v1.18.1
  * rook-ceph : v1.10.5
    * Using as S3-compatible storage

* Procedure
  1. Build a Primary cluster using CloudNativePG Operator on OpenShift environment
  2. Save primary cluster backup to rook-ceph
  3. Based on the backup, build a replica cluster using CloudNativePG Operator on another OpenShift environment connected by L2

* Pod status
```
$ oc get pod
NAME                                     READY   STATUS             RESTARTS     AGE
replica-cluster-1                       1/1     Running            0            3m31s
replica-cluster-1-full-recovery-x7nrl   0/1     Completed          0            4m
replica-cluster-2                       1/1     Running            0            2m45s
replica-cluster-2-join-2hs98            0/1     Completed          0            3m11s
replica-cluster-3                       0/1     CrashLoopBackOff   4 (9s ago)   2m17s
replica-cluster-3-join-nrj6t            0/1     Completed          0            2m34s
```

* Error log for the pod in CrashLoopBackOff state
```
{"level":"error","ts":"2023-03-10T02:29:40Z","logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *v1.Cluster Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/source/source.go:148\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\tpkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.poll\n\tpkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:582\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\tpkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/source/source.go:136"}
```

* YAML file to construct replica cluster
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: replica-cluster
spec:
  instances: 3

  minSyncReplicas: 2
  maxSyncReplicas: 2

  superuserSecret:
    name: primary-cluster-superuser

  bootstrap:
    recovery:
      source: primary-cluster

  replica:
    enabled: true
    source: primary-cluster

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 600Gi
      selector:
        matchLabels:
          <PV labels>
      volumeMode: Filesystem

  externalClusters:
  - name: primary-cluster
    barmanObjectStore:
      destinationPath: s3://<rook-ceph bucket name>/primary/
      endpointURL: http://<rook-ceph endpoint>
      s3Credentials:
        accessKeyId:
          name: <rook-ceph secret name>
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: <rook-ceph secret name>
          key: AWS_SECRET_ACCESS_KEY
    connectionParameters:
      host: <primary cluster host>
      user: streaming_replica
      sslmode: prefer
      dbname: postgres
    sslKey:
      name: primary-cluster-replication
      key: tls.key
    sslCert:
      name: primary-cluster-replication
      key: tls.crt
    sslRootCert:
      name: primary-cluster-ca
      key: ca.crt

  backup:
    barmanObjectStore:
      destinationPath: s3://<rook-ceph bucket name>/replica/
      endpointURL: http://<rook-ceph endpoint>
      s3Credentials:
        accessKeyId:
          name: <rook-ceph secret name>
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: <rook-ceph secret name>
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
```
