### DISCUSSION TITLE
Proposed changes to default behaviours in 1.20

### DISCUSSION THREAD

**Discussion by gbartolini** [cloudnative-pg/cloudnative-pg#1707] [Ideas]
Over time we have introduced new features in CNPG, like replications for example, and we have been conservative in their adoptions with the main goal not to disrupt the existing behaviours.

For example, when we introduced HA replication slots in 1.18, we decided not to make them the default behaviour.

Please list in this tickets the important changes to the default behaviours you see in CloudNativePG that you want to make happen in 1.20.0 so that we can add them to the release notes.

**Comment by gbartolini** [comment]
Enable replication slots for high availability by default:

```
spec:
   ...
   replicationSlots:
     highAvailability:
       enabled: true
```

**Comment by gbartolini** [comment]
Make the backup from a standby the default option when available:

```
spec:
   ...
   backup:
     target: "prefer-standby"
```
