### DISCUSSION TITLE
Bootstrapping  cluster from backup

### DISCUSSION THREAD

**Discussion by jakovistuk** [cloudnative-pg/cloudnative-pg#175] [General]
Hi, I have a problem to spin up a new cluster from backup..

This Cluster is ok, and sends WAL files to Minio.

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-cluster
spec:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  backup:
    barmanObjectStore:
      destinationPath: 's3://postgres01'
      endpointURL: 'https://minio-api-lab:9000'
      endpointCA:
        name: "certname"
        key: "ca.crt"
      s3Credentials:
        accessKeyId:
          key: 'MINIO_ACCESS_KEY'
          name: 'minio-creds'
        secretAccessKey:
          key: 'MINIO_SECRET_KEY'
          name: 'minio-creds'
```

I try to spin up recovery cluster, with yaml, but always get ,"error":"no target backup found".

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recover-my-cluster
spec:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  bootstrap:
    recovery:
      source: my-cluster
  externalClusters:
    - name: my-cluster
      barmanObjectStore:
        destinationPath: 's3://postgres01'
        endpointURL: 'https://minio-api-lab:9000'
        endpointCA:
          name: "certname"
          key: "ca.crt"
        s3Credentials:
          accessKeyId:
            key: 'MINIO_ACCESS_KEY'
            name: 'minio-creds'
          secretAccessKey:
            key: 'MINIO_SECRET_KEY'
            name: 'minio-creds'
      wal:
         maxParallel: 6
```

What I am doing wrong?
