### DISCUSSION TITLE
Create LoadBalancer / Private Network / port 5432 failed: Connection timed out

### DISCUSSION THREAD

**Discussion by reefland** [cloudnative-pg/cloudnative-pg#1928] [Q&A]
I use kube-vip to create / manage my loadbalancers to expose services on my local private network.  Using K3s v1.25.8+k3s1.
Created loadBalancer as follows:
```
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: cloudnative-pg

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.10.247"
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
```

```
$ k get svc -n cloudnative-pg
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)          AGE
cnpg-webhook-service   ClusterIP      10.43.190.79    <none>           443/TCP          5h45m
postgres-any           ClusterIP      10.43.89.206    <none>           5432/TCP         5h44m
postgres-lb            LoadBalancer   10.43.198.58    192.168.10.247   5432:30804/TCP   161m
postgres-r             ClusterIP      10.43.221.216   <none>           5432/TCP         5h44m
postgres-ro            ClusterIP      10.43.10.111    <none>           5432/TCP         5h44m
postgres-rw            ClusterIP      10.43.63.109    <none>           5432/TCP         5h44m
```
I can ping the loadbalancer:
```
$ ping -c 4 192.168.10.247
PING 192.168.10.247 (192.168.10.247) 56(84) bytes of data.
64 bytes from 192.168.10.247: icmp_seq=1 ttl=64 time=0.136 ms
64 bytes from 192.168.10.247: icmp_seq=2 ttl=64 time=0.125 ms
64 bytes from 192.168.10.247: icmp_seq=3 ttl=64 time=0.141 ms
64 bytes from 192.168.10.247: icmp_seq=4 ttl=64 time=0.145 ms

--- 192.168.10.247 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3052ms
rtt min/avg/max/mdev = 0.125/0.136/0.145/0.007 ms
```

```
$ k describe svc postgres-lb -n cloudnative-pg
Name:                     postgres-lb
Namespace:                cloudnative-pg
Labels:                   argocd.argoproj.io/instance=cloudnative-pg
Annotations:              kube-vip.io/vipHost: k3s03
Selector:                 cnpg.io/cluster=postgres,role=primary
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.198.58
IPs:                      10.43.198.58
IP:                       192.168.10.247
LoadBalancer Ingress:     192.168.10.247
Port:                     <unset>  5432/TCP
TargetPort:               5432/TCP
NodePort:                 <unset>  30804/TCP
Endpoints:                10.42.3.62:5432
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31810
Events:                   <none>
```

The selector from above, finds the correct pod, Endpoint matches:
```
$ k get pods -n cloudnative-pg -l cnpg.io/cluster=postgres,role=primary -o wide
NAME         READY   STATUS    RESTARTS   AGE    IP           NODE    NOMINATED NODE   READINESS GATES
postgres-2   1/1     Running   0          157m   10.42.3.62   k3s04   <none>           <none>
```

From my desktop, this works fine:
```
$ kubectl cnpg psql postgres -n cloudnative-pg
psql (14.7 (Debian 14.7-1.pgdg110+1))
Type "help" for help.

postgres=# 
```

Trying a client directly against the loadbalancer:
```
$ psql -h 192.168.10.247

psql: error: connection to server at "192.168.10.247", port 5432 failed: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?
```

The cluster is defined as:
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cloudnative-pg

spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  
  primaryUpdateStrategy: unsupervised
  
  storage:
    size: 20Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: ceph-block
      volumeMode: Filesystem

  superuserSecret:
    name: cloudnative-pg-secret
  
  bootstrap:
    initdb:
  
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  
  monitoring:
    enablePodMonitor: true
  
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: https://<redacted>:9000
      serverName: postgres-v3
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
```
