### DISCUSSION TITLE
Skip initdb on cluster

### DISCUSSION THREAD

**Discussion by jollyekb** [cloudnative-pg/cloudnative-pg#2250] [Q&A]
Hi all. How to launch a cluster on existing pvc by skipping the initdb phase. For some unknown reason, the cluster was removed, but the pv remained.

**Comment by jollyekb** [comment]
```
initdb {"level":"info","ts":"2023-06-09T06:58:28Z","msg":"PGData already exists, can't overwrite","logging_pod":"postgres-awx-1-initdb"}                                                                                                                                               
initdb Error: PGData directories already exist
```

**Comment by sxd** [comment]
Hi @jollyekb 

What you can do it's set the cluster in hibernation mode, and from there you can then remove the hibernation mode, but you will have to mimic all the process.

Another possible solution will be mount the pv in alternate docker, run PostgreSQL manually and take a dump, that could help you to retrieve the data.

I'm turning into a discussion since we can't see an issue here, yet

Regards!

**Reply by tahahawa** [reply]
I have the same issue and this didn't work for me:
```
Error: no primary instance found, cannot proceed with the hibernation
```

I could manually dump it, but the data is all there, the layout is all there. It just needs to skip the init process

**Comment by yandzee** [comment]
I have similar case. I was trying deploying cnpg into cluster in kind a debug/probing mode and was doing `helm install/uninstall` repeatedly and faced the same message `
Error: PGData directories already exist`. 

In my view it would be cool to have some kind of `bootstrap.enabled` flag that would allow to skip bootstrap phase and try to run postgres instance using PV as is. Because clearly, if I was managed to start postgres first, I should be able to start it next time after dropping the whole installation on just created files..

**Comment by weikinhuang** [comment]
I'm also running into this issue, especially for when rebuilding a kubernetes cluster in a homelab setup after a failure. It would be great to be able to reuse existing data directories much like the bitnami chart with 1 replica.

**Comment by gbartolini** [comment]
Just to be cleared. Are you referring to an existing PGDATA (with optional additional volumes) that was previously created by CloudNativePG?

**Comment by weikinhuang** [comment]
@gbartolini correct, I'm running NFS PVs in my homelab, and rebuild my cluster every so often. I usually reuse data directories between rebuilds with pre defined PV resources. That way I don't lose data for the pods themselves. Right now, I always have to restore from backup when rebuilding, it would be nice to be able to just repoint the data pvc to the existing pv and the primary will just continue along as if the pod just restarted instead of having to re-init everything.

**Reply by gbartolini** [reply]
The operator is designed to look for persistent volume claims matching the naming conventions - this is basically how resuming from hibernation works. Have you ever tried to do that?

**Reply by weikinhuang** [reply]
So, your suggestion is when I rebuild my kubernetes (not cnpg) cluster, pre-create the PVC as well as the PV?

**Comment by jlimai** [comment]
@gbartolini  Can you provide some step guidance ?  I have the same issue where my database is detached from cluster.  PVC is still intact.  How do I recreate a new cluster but reusing an existing PVC ?  This seems to be a very frequent issue when I search issue in CloudNative-PG.  I saw `pvcTemplate` has a `volumeName` property, when i assign that to my existing PVC, it says `PGData already exists`. 

@weikinhuang did you find any solution for this issue ?

**Reply by sherlant** [reply]
same issue, @jlimai have you found a solution ?

**Reply by jlimai** [reply]
Unfortunately no.  I hope the CNPG team could shed some light and guide or help us on how to reuse existing PVC if recreating an entire new PG cluster

**Reply by sherlant** [reply]
oh, so sad...
I have a homelab i want to create/destroy with terraform on demand, and i need this to persist data

**Reply by Wolfgang76214** [reply]
> @gbartolini Can you provide some step guidance ? I have the same issue where my database is detached from cluster. PVC is still intact. How do I recreate a new cluster but reusing an existing PVC ? This seems to be a very frequent issue when I search issue in CloudNative-PG. I saw `pvcTemplate` has a `volumeName` property, when i assign that to my existing PVC, it says `PGData already exists`.
> 
> @weikinhuang did you find any solution for this issue ?

https://github.com/cloudnative-pg/cloudnative-pg/discussions/2250#discussioncomment-10910765

**Comment by Wolfgang76214** [comment]
In fact, some change con cnpg cluster and inside init image before pod running, it will check pgdata exist or not. If it exists, it will move the old with format name pgdata_xxx and auto create new pgdata.
Its step inside image define on entrypoint. So i think we can custom new argument with check if exist, not move but bypass init database and end of check.

Any update or new information until now ?

**Comment by Wolfgang76214** [comment]
Found another solution, maybe it's tricky but it's works.

when you have still keep original data in PV, it will have 2 kind of data: pgdata and pg_wal
we will just work on primary pgdata and pg_wal, for replica, cloudnative pg will help to replica again.

How it's work?

Cluster define -> Init Job (create db with user permission define) -> pod starting. If just only 1 pod, it become primary and replica if primary existed.

Step 1: copy rm pg_wal to help job can initdb normaly. we must help job success running as if job fail, pod never start.
Step 2: start cluster with prameter: 
```
Instance: 1
```
When it start with instance 1. pgdata will be copied to backup folder like pgdata_ddmmyyyy and new pgdata folder will be created with empty data.
Step 3: 

copy all pgdata_ddmmyyyy overwrite again pgdata with correct permission:
```
cp -rp pgdata_ddmmyy/* pgdata/
```
 
when restart pod,, it will running but failure as checkpoint for wal log was failure.

try to running temp pod with mount pgdata and pgwal with example:

```
apiVersion: v1
kind: Pod
metadata:
  name: postgres-dev-cluster-clientpod
  namespace: group-cloudnative-postgres
spec:
  containers:
    - command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POD_NAME
          value: postgres-dev-cluster-1
        - name: NAMESPACE
          value: group-cloudnative-postgres
        - name: CLUSTER_NAME
          value: postgres-dev-cluster
        - name: PGPORT
          value: '5432'
        - name: PGHOST
          value: /controller/run
      image: 'ghcr.io/cloudnative-pg/postgresql:16'
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8000
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: postgres
      ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        - containerPort: 9187
          name: metrics
          protocol: TCP
        - containerPort: 8000
          name: status
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: 8000
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      startupProbe:
        failureThreshold: 360
        httpGet:
          path: /healthz
          port: 8000
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
        - mountPath: /run
          name: scratch-data
        - mountPath: /controller
          name: scratch-data
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/superuser-secret
          name: superuser-secret
        - mountPath: /etc/app-secret
          name: app-secret
        - mountPath: /var/lib/postgresql/wal
          name: pg-wal
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: postgres-dev-cluster-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 26
    runAsGroup: 26
    runAsNonRoot: true
    runAsUser: 26
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: postgres-dev-cluster
  serviceAccountName: postgres-dev-cluster
  terminationGracePeriodSeconds: 1800
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: postgres-dev-cluster-1
    - emptyDir: {}
      name: scratch-data
    - emptyDir:
        medium: Memory
      name: shm
    - name: superuser-secret
      secret:
        defaultMode: 420
        secretName: postgres-dev-cluster-superuser
    - name: app-secret
      secret:
        defaultMode: 420
        secretName: group-idm
    - name: pg-wal
      persistentVolumeClaim:
        claimName: postgres-dev-cluster-1-wal
```

Mandatory:
- Permission same with cluster pod you running previous cluster.
- mount 2 pv contain pgdata and pgwal same with instance pod
- Version image same with previous data folder
- command alway running in sleep mode to make us can interact command inside pod.

Step 4:
Run command interact login:
```
kubectl exec postgres-dev-cluster-clientpod -it -- /bin/bash 
```
run command to get data folder:

```
printenv | grep PGDATA
```

run pg_reset wal log to help postgres can start again.
example:
```
pg_resetwal /var/lib/postgresql/data/pgdata
```
result : 
``` Write-ahead log reset```

Be careful with pg_resetwal as will have risk and please backup you pgdata before do anything.

Step 5:  just restart pod again and see it start again as normal.
Step 6: remove all pg_wal on others pv replica
Increase parameter again to your expectation instance:
example for me is 3

```
instance: 3
```

sync again and wait it replica gain. 

Please make sure pg_wal remove as it will block initdb job and your instance never start

Replica will need take time to replica and svc-r and svc-ro will maybe not work as expect until full replica.

Hope it will help you ( my 1 days T_T)!
