### DISCUSSION TITLE
Operator deletes the PVC preventing the volume to be remounted when the cluster has been deleted in error

### DISCUSSION THREAD

**Discussion by simonmacklin** [cloudnative-pg/cloudnative-pg#2251] [Q&A]
Hi All,

It appears when deleting a cluster, the operator cleans up all resources as expected, but also deletes the PVC even when the storage class reclaim policy is set to retain.

Do you think it would be better to delegate the PVC lifecycle back to the storage provisioner?

Many thanks

**Comment by sxd** [comment]
hi @simonmacklin 

Can you provide a example of the storageclass and the cluster you were deploying?
Also, the reclaim policy affects the PVs not the PVC, the PVC will be deleted but the PV will remain, is that the case?

Turning into discussion since isn't an issue.

Regards!

**Comment by simonmacklin** [comment]
Hey @sxd 

Thanks for the replay, much appreciated and sorry for the brief original description.  

Below is the SC 

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-encrypted
parameters:
  encrypted: "true"
  kmsKeyId: xxxxxxxxxxxxxx
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

Correct it only deletes the PVC and not the PV.  What I hoped the operator would do is keep the PVCs or at least be able to figure out the disks belonged to a cluster with the same name and reattach.  I do appreciate the operator supports backups and they can be used if someone accidentally deleted the cluster.

The Elasticsearch (ECK) operator tackles this problem with a option in the CRD 
```
volumeClaimDeletePolicy: DeleteOnScaledownOnly
```

https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-volume-claim-templates.html

This basically allows an option to only remove the PVCs when the cluster scales down from replicas being changed ect, but not when deleted.  This would make recover much faster then trying to re create the PVCs and makes me sleep a little easier :)
