### DISCUSSION TITLE
PITR not working with external cluster

### DISCUSSION THREAD

**Discussion by 53d117460ec63d70** [cloudnative-pg/cloudnative-pg#2371] [Q&A]
Hello,
I have a cluster configured to backup WAL to an S3 bucket. When coming to restore this cluster I notice that two of the WAL files are 0 bytes:
```
2023-06-15 13:13:30   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000A8
2023-06-15 13:13:32   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000A9
2023-06-15 13:13:35   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AA
2023-06-15 13:13:37   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AB
2023-06-15 13:13:39   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AC
2023-06-15 13:13:41   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AD
2023-06-15 13:13:43   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AE
2023-06-15 13:13:45   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000AF
2023-06-15 13:13:46          0 cnpg/example/pg-cluster-13/wals/0000002800000002/00000028000000020000008F
2023-06-15 13:13:49   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000B0
2023-06-15 13:13:50          0 cnpg/example/pg-cluster-13/wals/0000002800000002/000000280000000200000090
2023-06-15 13:13:53   16777216 cnpg/example/pg-cluster-13/wals/0000002700000002/0000002700000002000000B1
```
I use the following cluster manifest for a PITR from an external cluster barman object store, setting the ```targetTime``` to 2023-06-15 13:13:45, the timestamp of the WAL file before the first 0 byte WAL file:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: example
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://my-bucket/cnpg/example
      endpointURL: http://my-cluster.example.co.uk:9999
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: pg-backup
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: pg-backup
      serverName: pg-cluster-14
  bootstrap:
    recovery:
      recoveryTarget:
        targetTime: "2023-06-15 13:13:45"
      source: pg-cluster-13
  externalClusters:
  - barmanObjectStore:
      destinationPath: s3://my-bucket/cnpg/example
      endpointURL: http://my-cluster.example.co.uk:9999
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: pg-backup
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: pg-backup
    name: pg-cluster-13
  imageName: cloudnative-pg/postgresql:15.1-6
  instances: 3
  storage:
    size: 10Gi
    storageClass: postgres
  walStorage:
    size: 10Gi
    storageClass: postgres
```
The recovery pod log shows the correct recovery target time:
```
{
  "level": "info",
  "ts": "2023-06-22T08:33:38Z",
  "msg": "Generated recovery configuration",
  "logging_pod": "pg-cluster-1-full-recovery",
  "configuration": "recovery_target_action = promote\nrestore_command = 'barman-cloud-wal-restore --endpoint-url http://my-cluster.example.co.uk:9020 s3://nppcmppostgrespreprod-bucket/cnpg/example pg-cluster-13 --cloud-provider aws-s3 %f %p'\nrecovery_target_time = '2023-06-15 13:13:45'\nrecovery_target_inclusive = true\n"
}

--[snip]--

{
  "level": "info",
  "ts": "2023-06-22T08:33:42Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "pg-cluster-1-full-recovery",
  "record": {
    "log_time": "2023-06-22 08:33:42.224 UTC",
    "process_id": "37",
    "session_id": "64940762.25",
    "session_line_num": "9",
    "session_start_time": "2023-06-22 08:33:38 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "starting point-in-time recovery to 2023-06-15 13:13:45+00",
    "backend_type": "startup",
    "query_id": "0"
  }
}
```
I can see WAL are successfully restored:
```
{
  "level": "info",
  "ts": "2023-06-22T08:33:58Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "pg-cluster-1-full-recovery",
  "record": {
    "log_time": "2023-06-22 08:33:58.372 UTC",
    "process_id": "37",
    "session_id": "64940762.25",
    "session_line_num": "31",
    "session_start_time": "2023-06-22 08:33:38 UTC",
    "virtual_transaction_id": "1/0",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "00000",
    "message": "restored log file \"00000027000000020000008E\" from archive",
    "backend_type": "startup",
    "query_id": "0"
  }
}
```
However the restore doesn't stop at the configured ```targetTime``` and fails when trying to restore the 0 byte file (00000028000000020000008F):
```
{
  "level": "info",
  "ts": "2023-06-22T08:33:58Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "pg-cluster-1-full-recovery",
  "record": {
    "log_time": "2023-06-22 08:33:58.886 UTC",
    "process_id": "37",
    "session_id": "64940762.25",
    "session_line_num": "32",
    "session_start_time": "2023-06-22 08:33:38 UTC",
    "virtual_transaction_id": "1/0",
    "transaction_id": "0",
    "error_severity": "FATAL",
    "sql_state_code": "XX000",
    "message": "archive file \"00000028000000020000008F\" has wrong size: 0 instead of 16777216",
    "backend_type": "startup",
    "query_id": "0"
  }
}
```
I get the same result if I give the ```targetTime``` in the format ```2023-06-15 13:13:45.00000+00```. Is there anything missing in my cluster manifest preventing the restore stopping at the configured ```targetTime``` or have I misunderstood this process?

CNPG operator 1.20.1
K8S v1.21.12-mirantis-2

Many thanks,
Rob
