### DISCUSSION TITLE
Working linode object storage backup example?

### DISCUSSION THREAD

**Discussion by danielluke** [cloudnative-pg/cloudnative-pg#254] [Q&A]
I've been trying to setup backups to linode object storage, but so far haven't been successful. The docs mention linode specifically, so I'm presumably just doing something wrong.

I set backup.barmanObjectStore.destination (s3://example-db) and backup.barmanObjectStore.endpointURL (https://my-awesome-bucket-name.us-southeast-1.linodeobjects.com/) and see errors like this for wal-archive:
`{"level":"info","ts":1654785968.5569975,"logger":"barman-cloud-check-wal-archive","msg":"2022-06-09 14:46:08,556 [3266] ERROR: Barman cloud WAL archive check exception: An error occurred (400) when calling the HeadBucket operation: Bad Request","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":1654785968.624854,"logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-1","targetPrimary":"cluster-example-1","options":["--endpoint-url","https://my-awesome-bucket-name.us-southeast-1.linodeobjects.com/","--cloud-provider","aws-s3","s3://example-db","cluster-example"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:234\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:381\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
{"level":"error","ts":1654785968.6250222,"msg":"while barman-cloud-check-wal-archive","logging_pod":"cluster-example-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:382\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}`

If I exec sh in cluster-example-1 and set AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY in the environment both of these succeed: 

`barman-cloud-check-wal-archive -vv --endpoint-url https://my-awesome-bucket-name.us-southeast-1.linodeobjects.com/ --cloud-provider aws-s3 s3://example-db cluster-example`
`barman-cloud-wal-archive -j -e AES256 --endpoint-url https://my-awesome-bucket-name.us-southeast-1.linodeobjects.com/ --cloud-provider aws-s3 s3://example-db cluster-example /var/lib/postgresql/data/pgdata/pg_wal/000000010000000000000001`

**Comment by danielluke** [comment]
Note that I see the same logging when setting things more like what the documentation suggests -  backup.barmanObjectStore.destination (s3://my-awesome-bucket-name/example-db) and backup.barmanObjectStore.endpointURL (https://my-awesome-bucket-name.us-southeast-1.linodeobjects.com/ or https://us-southeast-1.linodeobjects.com/)

**Comment by sxd** [comment]
Hi @danielluke 

Sorry for missing this, I actually tested Linode objects a long time ago and it worked, is it working for you now? otherwise I can try to make an experiment for testing purposes!

Regards!

**Comment by danielluke** [comment]
Hi @sxd, I haven't gotten it working yet - if you could take a look I'd appreciate it!

**Comment by sxd** [comment]
@danielluke I've created an example that actually works, here's the backup section you may need

```
  backup:
    barmanObjectStore:
      data:
        immediateCheckpoint: true
      destinationPath: s3://cnpg-test/
      endpointURL: https://cnpg-test.us-southeast-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: cnpg-test
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: cnpg-test
      wal:
        compression: snappy
```

Can you share your backup section configuration?

Regards!

**Comment by danielluke** [comment]
```
  backup:
    barmanObjectStore:
      destinationPath: "s3://bucket-name/"
      endpointURL: "https://bucket-name.us-southeast-1.linodeobjects.com/"
      s3Credentials:
        accessKeyId:
          name: pg-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        encryption: AES256
        maxParallel: 8
    retentionPolicy: "30d"
```

I've tried a bunch of variants on destinationPath and endpointURL (along with removing compression, encryption, and maxParallel). I'll try again today - I always see barman-cloud-check-wal-archive errors, though (the destination is empty, if that makes a difference).

**Comment by danielluke** [comment]
Yeah, still seeing the same error:
```
{"level":"info","ts":1655391285.8771408,"msg":"Waiting for the first WAL file to be archived","logging_pod":"cluster-example-1"}
{"level":"info","ts":1655391298.1636896,"logger":"wal-archive","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"cluster-example-1"}
{"level":"info","ts":1655391299.0428748,"logger":"barman-cloud-check-wal-archive","msg":"2022-06-16 14:54:59,042 [244] ERROR: Barman cloud WAL archive check exception: An error occurred (400) when calling the HeadBucket operation: Bad Request","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":1655391299.2071,"logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-1","targetPrimary":"cluster-example-1","options":["--endpoint-url","https://bucket-name.us-southeast-1.linodeobjects.com/","--cloud-provider","aws-s3","s3://bucket-name/","cluster-example"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:234\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:381\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
{"level":"error","ts":1655391299.2072856,"msg":"while barman-cloud-check-wal-archive","logging_pod":"cluster-example-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:382\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
{"level":"error","ts":1655391299.2563996,"logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"cluster-example-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:82\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
{"level":"info","ts":1655391299.268159,"logger":"postgres","msg":"record","logging_pod":"cluster-example-1","record":{"log_time":"2022-06-16 14:54:59.267 UTC","process_id":"28","session_id":"62ab4315.1c","session_line_num":"1","session_start_time":"2022-06-16 14:49:57 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"archive command failed with exit code 1","detail":"The failed archive command was: /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/000000010000000000000001","backend_type":"archiver","query_id":"0"}}
```

If I connect to the container and run /controller/manager with the args as above it generates the same error (as expected). If i manually run barman-cloud-check-wal-archive it runs with an exit code of 0 (I can also manually run barman-cloud-wal-archive and it works).

**Comment by sxd** [comment]
Hi @danielluke 

It is possible to schedule a live debug of this case? we're really worry about this.
On the other hand, it is possible that you remove the `"` in the yaml file and the `retentionPolicy` section?

Regards!

**Comment by danielluke** [comment]
No difference with removing the "s.

To reproduce:
- Create LKE cluster (default of 3 2G linodes is fine)
- Create Object Storage bucket
- create access key w/ read/write access to the bucket
- kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.15.1.yaml
- create 'example-db' namespace
- create pg-backup-creds with access_key_id and access_secret_key from earlier
- create cluster with this yaml:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: example-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.3
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: example-db

  postgresql:
    parameters:
      # should be 1/4 of total memory
      shared_buffers: "128MB"

  storage:
    #10G appears to be the smallest linode volume
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: "s3://bucket-name/"
      endpointURL: "https://bucket-name.us-southeast-1.linodeobjects.com/"
      s3Credentials:
        accessKeyId:
          name: pg-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        encryption: AES256
        maxParallel: 8
    retentionPolicy: 30d
```
- kubectl logs -f -n example-db cluster-example-1

... I do notice an ALTER ROLE error being logged because it wasn't quoting the db name (which has a hyphen), I opened https://github.com/cloudnative-pg/cloudnative-pg/issues/271 for that. Trying again with 'exampledb' as the database name instead of 'example-db'  gives me the same error messages, though.
