### DISCUSSION TITLE
issues with replica cluster - can't start secondary cluster

### DISCUSSION THREAD

**Discussion by simonebenati** [cloudnative-pg/cloudnative-pg#2568] [Q&A]
Hello,

I'm currently having issues deploying a secondary replicated cluster according to the following piece of documentation:
https://cloudnative-pg.io/documentation/1.20/replica_cluster/

I'm using the following code to setup the replicated cluster:
```
bootstrap:
    recovery:
      source: postgresql-cluster-reggio
  replica:
    enabled: true
    source: postgresql-cluster-reggio
  externalClusters:
    - name: postgresql-cluster-reggio
      barmanObjectStore:
        endpointURL: https://s3.scalablestorage.it
        destinationPath: "s3://dacdaga32ga42b/reggio/"
        s3Credentials:
          accessKeyId:
            name: reggio-backup-cred
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: reggio-backup-cred
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
```
When I apply the code to the cluster this is what I get from the logs: 

```
{"level":"info","ts":"2023-08-11T08:32:07Z","logger":"postgres","msg":"record","logging_pod":"postgresql-cluster-reggio-dr-mode-1","record":{"log_time":"2023-08-11 08:32:07.660 UTC","user_name":"postgres","database_name":"postgres","process_id":"261","connection_from":"[local]","session_id":"64d5f207.105","session_line_num":"1","session_start_time":"2023-08-11 08:32:07 UTC","transaction_id":"0","error_severity":"FATAL","sql_state_code":"57P03","message":"the database system is not yet accepting connections","detail":"Consistent recovery state has not been yet reached.","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2023-08-11T08:32:07Z","msg":"Instance status probe failing","logging_pod":"postgresql-cluster-reggio-dr-mode-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: server error (FATAL: the database system is not yet accepting connections (SQLSTATE 57P03))"}
```
I tried deploying in the same namespace, a different namespace, using postgres as user, a different superuser user but without any luck. How can I debug further? Or what may be causing the issue?
