### DISCUSSION TITLE
Configure Azure AD Workload Identity for Backups

### DISCUSSION THREAD

**Discussion by andreas-meier** [cloudnative-pg/cloudnative-pg#2637] [Q&A] [answered]
Hi all

First of all cnpg looks very promising and i like the ease of setting it up etc. I always struggle with Azure and its security aspects, like doing a scheduled backup to an azure blob storage. 

In the cnpg documentation we have the comment that with:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
spec:
  backup:
    barmanObjectStore:
      destinationPath: "<destination path here>"
      azureCredentials:
        inheritFromAzureAD: true
``` 

Now for Azure AD Workload Identity to work i always as well needed to define following two things on the deployment.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    azure.workload.identity/use: "true"
spec:
  template:
    spec:
      serviceAccountName: "azure-workload-identity-account"
```

How do i achieve this in cnpg cluster cr? Or do i see this completely wrong? Would be nice to get some hints.

**Comment by andreas-meier** [comment, marked as answer]
After digging into the CRD i've found the answer to my question, and got cnpg backup working with Azure AD Workload Identity.

Cluster Configuration:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: some-name
  namespace: some-namespace
spec:

  inheritedMetadata:
    labels:
      azure.workload.identity/use: "true"

  serviceAccountTemplate:
    metadata:
      annotations:
        # This is the GUID to the Client-ID of the App Registration where you have registerd the federated credentials
        azure.workload.identity/client-id: "fdb5203a-5b05-4253-93a9-843d1df1665e"  
      labels:
        azure.workload.identity/use: "true"

  backup:
    barmanObjectStore:
      destinationPath: "https://<storage-account-name>.blob.core.windows.net/<container-name>"
      azureCredentials:
        inheritFromAzureAD: true
    retentionPolicy: "30d"
``` 

So:

- serviceAccountTemplate needs to have the connection to the client-id of the application registration in Azure AD. 
- The ServiceAccount that is generated from cnpg is equal to the cluster name in the above example it would be "some-name" this needs to be connected in federated credentials -> subject identifier -> system:serviceaccount:some-namespace:some-name
- In the Storage Account this application registration needs to not only get contributor permission, it needs to have Storage Blob Data Contributor permissions -> can be configured in IAM of the Storage Account.

Like this i managed to be able to get cnpg backup and wal working.

Would be nice if the cnpg documentation would be extended with at least the yaml configuration hint to add the workload identity stuff to the service account and the pod label.
