### DISCUSSION TITLE
Very slow recovery - ability to only load basebackups, not WAL archives?

### DISCUSSION THREAD

**Discussion by maaft** [cloudnative-pg/cloudnative-pg#2692] [Q&A]
As the title says. For staging deployment I import the main database on a regular basis.

The database is currently ~5.5 GB in size.

I do daily base-backups.

Looking at the logs, the base-backup is loaded very fast (< 5 minutes).

But afterwards, WAL archives are streamed at a very slow pace (~1 archive every 30 sec) to get the cluster to the latest state of my prod database.

Anything I can do about this?

Can I somehow specify to **only load the base backup** and stop after that? Often enough, I don't need the latest prod database and the snapshot from previous night would be more then enough.

Here's my cluster spec:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hasura
spec:
  bootstrap:
    recovery:
      database: hasura
      owner: hasura
      source: hasura
  description: Cluster for Hasura
  enableSuperuserAccess: true
  externalClusters:
  - barmanObjectStore:
      azureCredentials:
        inheritFromAzureAD: false
        storageAccount:
          key: AZURE_STORAGE_ACCOUNT
          name: azure-secrets
        storageKey:
          key: AZURE_STORAGE_KEY
          name: azure-secrets
      data:
        compression: gzip
      destinationPath: https://foobarblub.blob.core.windows.net/hasura-cluster-backups/
      wal:
        compression: gzip
        maxParallel: 8
    name: hasura
  failoverDelay: 0
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  storage:
    resizeInUseVolumes: true
    size: 16Gi
  switchoverDelay: 40000000
  
```

**Comment by Lennart01** [comment]
Hey, yes you can specify a recovery point. 
Taken from the [docs](https://cloudnative-pg.io/documentation/1.20/bootstrap/#point-in-time-recovery-pitr)
```yaml
  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        targetTime: "2020-11-26 15:22:00.00000+00"
```
You would set your recovery target close to the time of your base backup.
The WALs will be recovered up until the specified timestamp. Everything after will be ignored.
