### DISCUSSION TITLE
Any best practices on how to run db migration script after init?

### DISCUSSION THREAD

**Discussion by pedroteixeira** [cloudnative-pg/cloudnative-pg#2787] [Q&A]
Hi, can anyone suggest a mechanism for running a script after a db cluster is created?

I see ways for declaring sql in the manifest, but what about running a sh script after init?

For example, I would like to run `dbmate` sql migrations files against the db when it's ready.

Perhaps allow a hook into the database pod?

Was going to look into running a Job and see how to wait for the pod is ready, but asking here for some advice too.

Thanks,
Pedro

**Comment by pedroteixeira** [comment]
At the moment, experimenting using a Job with Argo CD to run migrations: but job would run on every sync, and script using `pg_isready` to check when db service available.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: pg-cluster-schema
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```
