### DISCUSSION TITLE
authentication failed for user postgres - User "postgres" has no password assigned - Wrong Username in Secret

### DISCUSSION THREAD

**Discussion by MarkCupitt** [cloudnative-pg/cloudnative-pg#280] [Q&A] [answered]
**Problem 1** - Super user has no password - unable ot login with pghAdmin4
**Problem 2** - wrong username "bonanza" in secret, expected Ym9uYW56YQ==

I guess we have missed something in the config. We do want to set our own passwords, as they will be managed by an external secrets manger

**Logs**
```
"level":"info","ts":1655349703.359565,"logger":"postgres","msg":"record","logging_pod":"postgres-database-1","record":{"log_time":"2022-06-16 03:21:43.359 UTC","user_name":"postgres","database_name":"postgres","process_id":"323","connection_from":"192.168.1.242:20073","session_id":"62aaa1c7.143","session_line_num":"1","command_tag":"authentication","session_start_time":"2022-06-16 03:21:43 UTC","virtual_transaction_id":"4/114","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched pg_hba.conf line 14: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
```
```
{"level":"error","ts":1655349568.334511,"msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","cluster":{"name":"postgres-database","namespace":"postgres"},"namespace":"postgres","name":"postgres-database","reconcileID":"8db2ab2c-6ce9-4c71-98df-1068f98018c7","error":"while updating database owner password: wrong username 'bonanza' in secret, expected 'Ym9uYW56YQ=='","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"}

```

**Yaml Spec**

```
---
apiVersion: v1
kind: Secret
metadata:
  name: $DB_CLUSTER_NAME.app.user
  namespace: $POSTGRES_NAMESPACE
type: kubernetes.io/basic-auth
data:
  password: $POSTGRES_APP_PASSWORD # base64 encoded
  username: $POSTGRES_APP_USER # base64 encoded value of "bonanza"
---
# user name MUST ALWAYS be postgres, base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: $DB_CLUSTER_NAME.superuser
  namespace: $POSTGRES_NAMESPACE
type: kubernetes.io/basic-auth
data:
  password: $POSTGRES_SUPER_PASSWORD # base64 encoded
  username: $POSTGRES_SUPER_USER # base64 encoded of value = postgres
---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: $DB_CLUSTER_NAME-database
  namespace: $POSTGRES_NAMESPACE
spec:
  instances: $postgres_number_of_instances
  imageName: ghcr.io/cloudnative-pg/postgresql:14.3
  startDelay: 0
  stopDelay: 0
  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: $DB_CLUSTER_NAME.superuser
 
 postgresql:
    parameters:
      max_worker_processes: "60"
      shared_buffers: "1GB"
      auto_explain.log_min_duration: '10s'
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    
    pg_hba:

  bootstrap:
    initdb:
      database: bonanza
      owner: $POSTGRES_APP_USER # value = bonanza
      secret:
        name: $DB_CLUSTER_NAME.app.user
      dataChecksums: true
      encoding: 'UTF8'
 
  resources:
    requests:
      cpu: "$postgres_request_cpu"
      memory: "$postgres_request_memory"
    limits:
      cpu: "$postgres_limits_cpu"
      memory: "$postgres_limits_memory"
    
  affinity:
    enablePodAntiAffinity: false #unrestricted affinity
    topologyKey: kubernetes.io/hostname #defaul value
    podAntiAffinityType: preferred #default value

  storage:
    size: $POSTGRES_DB_SIZE
#    storageClass: $PostgresStorageClass

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  monitoring:
    disableDefaultQueries: false
    customQueriesConfigMap:
    customQueriesSecret:
    enablePodMonitor: true
---



```

**Comment by phisco** [comment, marked as answer]
I tried reproducing the issue, but I could not, this is the configuration I've tried applying, should be a stripped down version of yours.
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  superuserSecret:
    name: superuser

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: bonanza
      owner: bonanza
      secret:
        name: user
      dataChecksums: true
      encoding: 'UTF8'

---
apiVersion: v1
kind: Secret
metadata:
  name: superuser
type: kubernetes.io/basic-auth
data:
  password: cGFzc3dvcmQ=
  username: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: user
type: kubernetes.io/basic-auth
data:
  password: Ym9uYW56YQ==
  username: Ym9uYW56YQ==
```

I am then correctly able to access the postgres database as user postgres from the second instance to the primary instance as follows: kubectl exec -ti cluster-example-2 -- psql 'host=cluster-example-rw user=postgres password=password dbname=postgres'`.

I can not spot any issue with your configuration, but it's using variables, so maybe something could have gone wrong there.

**Comment by sxd** [comment]
I'm converting this into a discussion since doesn't look like an issue but a problem creating the YAML file

**Reply by MarkCupitt** [reply]
Thanks for checking into this, appreciate it. YAML looks sames as what we used so a little bit of a mystery here. Will shelve this given issue #269 raised re multiple databases, but will look into this more when time permits

**Comment by kasvith** [comment]
im also facing a similar problem

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
  namespace: prod
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXMK # postgres
  password: cG9zdGdyZXMK # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-secret
  namespace: prod
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: ZGItdXNlcgo= # db-user
  password: NWVVKjBBe1VUM2M2Cg== # 5eU*0A{UT3c6
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-runner-db
  namespace: prod
spec:
  description: "PG Runner DB for Prod"
  # Choose your PostGres Database Version
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  # Number of Replicas
  instances: 3
  startDelay: 300
  stopDelay: 300
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 300
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: "10s"
    pg_hba:
      # - hostssl app all all cert
      - host app app all password
  logLevel: debug
  storage:
    storageClass: ebs-sc
    size: 5Gi
  walStorage:
    storageClass: ebs-sc
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb: # Deploying a new cluster
      database: data
      owner: db-user
      secret:
        name: db-user-secret

  managed:
    roles:
      - name: db-user
        ensure: present
        superuser: true
        createdb: true
        login: true
        passwordSecret:
          name: db-user-secret

  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: prod-pg-runner-pooler-rw
  namespace: prod
spec:
  cluster:
    name: pg-runner-db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "15"
```

and when i try to connect any of users with db-rw service it gives me an error about password

```bash
root@psql-client:/# psql -h pg-runner-db-rw -U postgres -d data
Password for user postgres:
psql: error: connection to server at "pg-runner-db-rw" (10.100.164.44), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "pg-runner-db-rw" (10.100.164.44), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```
