### DISCUSSION TITLE
fix proposal for issues regarding replica with broken wal replication

### DISCUSSION THREAD

**Discussion by Lennart01** [cloudnative-pg/cloudnative-pg#2842] [Ideas]
Hey,
as outlined in #2800 if a replica is not able to replicate due to a timeline change it will loop WAL recovery but does not crash.
The Operator considers this replica as healthy as it is technically accepting connections and is running.
As documented in the codebase
```
//  Column "Replication role"
//  If instance is primary, print "Primary"
//  	Otherwise, it is considered a standby
//  else if it is not replicating:
//  	if it is accepting connections: # readiness OK
//      	print "Standby (file based)"
```
proposals:
- add an option to prevent file-based replicas from being promoted to a primary.
- add a grace period for those replicas (for example 15mins) after which the replica will be force terminated (new replica join is forced if the cluster is healthy)
- potentially improve health checks to guard against this edge case

I'd love to get your thoughts on this and I'd be happy to help implement them :D.

**Comment by gbartolini** [comment]
Can you please share the startDelay, stopDelay and switchoverDelay options you have?

**Reply by Lennart01** [reply]
Default values. The version installed is  1.20.2.

**Reply by gbartolini** [reply]
Do you mind retrying - if you can recreate it - with the proposed new default values and provide feedback? See #2835 for details.

**Reply by Lennart01** [reply]
```
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  instances: 3
  minSyncReplicas: 2
  maxSyncReplicas: 2
  stopDelay: 1800
  switchoverDelay: 3600
  startDelay: 3600
  ```
  values used for reference. Will try

**Reply by Lennart01** [reply]
Im still able to reproduce this

**Reply by gbartolini** [reply]
Can you please try reducing `minSyncReplicas` and `maxSyncReplicas`?

Then, also try again with the original spec, but without the WAL archive?

The symptom you are seeing (file based replication) is just an effect, I don't think it is the cause (the replica cannot connect so Postgres retries indefinitely to fetch from the archive).

**Reply by gbartolini** [reply]
Not proposing this as a fix, just curious to see if setting a small failoverDelay changes the outcome.

**Comment by Lennart01** [comment]
Im still able to reproduce this behaviour.
Howto:
1) Create a Postgres Cluster with 3 replicas and an s3 bucket:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: test
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  instances: 3
  minSyncReplicas: 2
  maxSyncReplicas: 2
  stopDelay: 1800
  switchoverDelay: 3600
  startDelay: 3600
  storage:
    storageClass: <your-storage-class>
    size: 10Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 10
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://<your_s3_url>
      endpointURL: https://<your_s3_endpoint>
      s3Credentials:
        accessKeyId:
          name:  s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-postgres-backup
          key: SECRET_ACCESS_KEY
  postgresql:
    parameters:
      shared_buffers: 256MB
      max_connections: '200'
  bootstrap:
    initdb:
      database: test_db
      owner: test_user
      secret:
        name: postgresql-creds
```
2) Now we create some load on the cluster
```python
import subprocess
DB_URL = "postgres://user:pw@localhost:5432/change-me"
def main():
    query = "\dt"
    result = subprocess.check_output(f"kubectl exec --namespace=change-me -it change-me-postgres-cluster-1 -- bash -c \"psql {DB_URL} -c '{query}'\"", shell=True)
    if "test2" not in result.decode("utf-8"):
        print("Database is empty")
        print("creating test tables")
        query = "CREATE TABLE test2 (id serial PRIMARY KEY, num integer);"
        subprocess.call(f"kubectl exec --namespace=change-me -it change-me-postgres-cluster-1 -- bash -c \"psql {DB_URL} -c '{query}'\"", shell=True)
        print("Database populated")
    
    i = 0
    while True:
        query = f"INSERT INTO test(num) VALUES ({i});"
        full_query = f"kubectl exec --namespace=change-me -it change-me-postgres-cluster-1 -- bash -c \"psql {DB_URL} -c '{query}'\""
        print(full_query)
        subprocess.call(f"kubectl exec --namespace=change-me -it change-me-postgres-cluster-1 -- bash -c \"psql {DB_URL} -c '{query}'\"", shell=True)
        i += 1
        print(f"Inserted {i} rows")

if __name__ == "__main__":
    main()
```
3) Force terminate the primary pod.
```sh
kubectl delete -n change-me pod change-me-postgres-cluster-1 --grace-period=0 --force
```
Now one replica should become "file-based" and will loop wal recovery
