### DISCUSSION TITLE
Safe Application Users - Best Practice Howto

### DISCUSSION THREAD

**Discussion by darktempla** [cloudnative-pg/cloudnative-pg#2856] [Q&A]
Hi all. Any help would be greatly appreciated.

I am looking for some advice/suggestions on how to best handle configuring the "application" user with least privilege but more so how to best approach this with the CNPG operator.

To set the scene by default CNPG creates 2 users for you and makes them available via K8s secrets for convenience. By convention an "app" database is also created.

- sentimental-pg-test-**superuser**
- sentimental-pg-test-**app**

I want to use the **superuser** for database migrations create/alter tables etc and to own the tables.
For the normal least privilege user I want to use the **app** user to only be able to select, insert and update records in the table that are owned by the **superuser (postgres)** user.

Via some testing it looks like the **app** user has full permissions over the "app" database.  By creating the tables using the superuser the app user does not have permission to drop them. This is desired. Unfortunately the app user does not have any access to any tables created in the "app" database by the **superuser (postgres)**.

Below is the Cluster config I was using in a attempt to achieve the desired outcome with no luck. 
I am not even sure the initdb scripts are being executed I couldn't see them in the logs. It is possible I am missing some GRANTS as well but I have seen examples that only specify the two statements I have tried that are meant to get the job done. 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentimental-pg-test
  labels:
    app: sentimental
    role: database
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  minSyncReplicas: 1
  maxSyncReplicas: 1
  monitoring:
    enablePodMonitor: true
  storage:
    size: 500Mi
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - GRANT USAGE ON SCHEMA public TO app;
        - GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO app;
```
