### DISCUSSION TITLE
Error while restoring a backup - first WAL file not found

### DISCUSSION THREAD

**Discussion by ksyblast** [cloudnative-pg/cloudnative-pg#2989] [Q&A] [answered]
Hello!

Probably I misunderstand how Barman backup works, would appreciate if anybody clarifies how this could happen:

I have created a backup and configured S3 storage, backup startedAt: "2023-09-29T14:42:03Z"
```
{"level":"info","ts":"2023-09-29T14:42:01Z","msg":"WAL archiving is working","logging_pod":"cnpg-cluster-pg13-2"}
{"level":"info","ts":"2023-09-29T14:42:01Z","msg":"Backup started","backupName":"backup-example","backupNamespace":"backup-example","logging_pod":"cnpg-cluster-pg13-2","options":["--user","postgres","--cloud-provider","aws-s3","s3://postgres-cnpg/","cnpg-cluster-pg13"]}
{"level":"info","ts":"2023-09-29T14:43:04Z","msg":"Backup completed","backupName":"backup-example","backupNamespace":"backup-example","logging_pod":"cnpg-cluster-pg13-2"}
```
I tried to restore the cluster from object store and got this error:
```
{"level":"info","ts":"2023-10-04T14:52:21Z","msg":"Recovering from external cluster","logging_pod":"cnpg-restore-pg13-1-full-recovery","sourceName":"cnpg-cluster-pg13"}
{"level":"info","ts":"2023-10-04T14:52:23Z","msg":"Target backup found","logging_pod":"cnpg-restore-pg13-1-full-recovery","backup":{"backup_label":"'START WAL LOCATION: 1/59ADF6C0 (file 0000003D0000000100000059)\\nCHECKPOINT LOCATION: 1/5B7D2840\\nBACKUP METHOD: streamed\\nBACKUP FROM: standby\\nSTART TIME: 2023-09-29 14:42:03 UTC\\nLABEL: Barman backup cloud 20230929T144203\\nSTART TIMELINE: 61\\n'","begin_time":"Fri Sep 29 14:42:03 2023","end_time":"Fri Sep 29 14:42:56 2023","BeginTime":"2023-09-29T14:42:03Z","EndTime":"2023-09-29T14:42:56Z","begin_wal":"0000003D0000000100000059","end_wal":"0000003D000000010000005C","begin_xlog":"1/59ADF6C0","end_xlog":"1/5C000000","systemid":"7281241487361605658","backup_id":"20230929T144203","error":"","timeline":61}}
{"level":"error","ts":"2023-10-04T14:52:24Z","msg":"Error while restoring a backup","logging_pod":"cnpg-restore-pg13-1-full-recovery","error":"encountered an error while checking the presence of first needed WAL in the archive: file not found 0000003D0000000100000059: WAL not found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:89\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/proc.go:250"}
```
I tried to find this WAL file name in the logs and I see: 
```
 {"level":"info","ts":"2023-09-29T13:47:50Z","logger":"wal-archive","msg":"Backup not configured, skip WAL archiving","logging_pod":"cnpg-cluster-pg13-1","walName":"pg_wal/0000003D0000000100000059","currentPrimary":"cnpg-cluster-pg13-1","targetPrimary":"cnpg-cluster-pg13-1"}
```

And indeed this file is missing at S3. How could that happen that barman starts with an unexisting WAL file? 
Recovery config:
```
  bootstrap:
    recovery:
      source: cnpg-cluster-pg13
      recoveryTarget:
        targetTime: "2023-10-01 15:22:00.00000+00"


  externalClusters:
  - name: cnpg-cluster-pg13
    barmanObjectStore:
      destinationPath: "s3://postgres-cnpg/"
...

```

Backup config:
```
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
  namespace: cnpg-cluster
spec:
  cluster:
    name: cnpg-cluster-pg13
status:
  backupId: 20230929T144203
  beginLSN: 1/59ADF6C0
  beginWal: 0000003D0000000100000059
  destinationPath: s3://postgres-cnpg/
  endLSN: 1/5C000000
  endWal: 0000003D000000010000005C
  instanceID:
    ContainerID: containerd://e3e933f390dd64c9fd0a2442eca78e20b0a4b41707704bb6102f085d2f462dc1
    podName: cnpg-cluster-pg13-2
  phase: completed
  s3Credentials:
    accessKeyId:
      key: ACCESS_KEY_ID
      name: aws-creds
    inheritFromIAMRole: false
    secretAccessKey:
      key: ACCESS_SECRET_KEY
      name: aws-creds
  serverName: cnpg-cluster-pg13
  startedAt: "2023-09-29T14:42:03Z"
  stoppedAt: "2023-09-29T14:42:56Z"
```
