### DISCUSSION TITLE
Allow declarative management of Databases

### DISCUSSION THREAD

**Discussion by red-lichtie** [cloudnative-pg/cloudnative-pg#3109] [Ideas]
It should be possible for a DBA to manage the databases in a cluster using CRDs.
I put my ideas together in this, very rough, set of definition examples:
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-main
  namespace: production
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterRole
metadata:
  name: owner
  namespace: production
spec:
  cluster: prodServer
  privileges:
    - ALL
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: joplin
  namespace: joplin-server
spec:
  cluster: prodServer
# In Cluster prodServer - CREATE DATABASE joplin;
  admins:
    - user: joplinAdmin
      password:
        - type: Secret # Also ConfigMap ?
          name: joplin-admin-password
          key: password
# In Database joplin - grant all privileges on database joplin to joplinAdmin;
---
apiVersion: v1
kind: Secret
metadata:
  name: joplin-admin-password
  namespace: joplin-server
stringData:
  password: verySecret
---
apiVersion: postgresql.cnpg.io/v1
kind: Users
metadata:
  name: joplin
  namespace: joplin-server
spec:
  database: joplin
  users:
    - user: joplinAdmin
      password:
        - type: Secret # Also ConfigMap ?
          name: joplin-admin-password
          key: password
# In Database joplin - create user joplinAdmin with encrypted password 'verySecret';
---
apiVersion: postgresql.cnpg.io/v1
kind: Privileges
metadata:
  name: joplin
  namespace: joplin-server
spec:
  database: joplin
  users:
    - joplinAdmin:
      roles:
        - owner
# In Database joplin - grant all privileges on database joplin to joplinAdmin;
...
```
This would allow these kinds of resources to be managed easily on a "per service" basis, and dropping a user and/or roles is as easy as removing the definition.
