### DISCUSSION TITLE
add db creds in manifest explicitly? kube secrets failedMount: failed  to sync secret cache: timed out waiting for the condition

### DISCUSSION THREAD

**Discussion by Rammurthy5** [cloudnative-pg/cloudnative-pg#3372] [Q&A] [answered]
Hi guys,
I have installed CloudNativePG operator and used the below manifest to deploy secrets, and postgres cluster. 
Secrets and postgres cluster are deployed in the same namespace. however, i see `failed to sync secret cache: timed out waiting for the condition` with pod stuck in INIT state. 
So, i thought i could directly add the secret in the manifest. Looked up the examples, and the documentation could not spot anything about direct secrets inclusion in YAML. Please advise. 
thanks.

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  bootstrap:
    initdb:
      database: pgdb
      owner: pg
      secret:
        name: secret/pgdb-secret
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 300
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone
```
