### DISCUSSION TITLE
How to read original csvlog ?

### DISCUSSION THREAD

**Discussion by fmiqbal** [cloudnative-pg/cloudnative-pg#3385] [Ideas]
From my current understanding, the instance manager "catch" the csvlog, process it and then out it in /dev/stdout.
I need to implement logging collector using elastic agent that support the original file log from postgres (without much parsing, csvlog)

**Comment by gbartolini** [comment]
We are not supporting this at the moment, and we have never discussed about this feature so far.

**Comment by fmiqbal** [comment]
I end up writing my own processor for elastic agent

### The config

`agent.yaml`
```yaml
agent: ...
providers: ...
outputs: ...
inputs:
...
  - id: filestream-container-logs-d30d20e3-c909-4856-819c-117a9fea4647
    name: kubernetes-2
    type: filestream
    condition: ${kubernetes.labels.cnpg.io/instanceRole} == 'primary'
    data_stream:
      namespace: kubernetes
    streams:
      - data_stream:
          type: logs
          dataset: postgresql.log
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        prospector.scanner.symlinks: true
        parsers:
          - container:
              stream: all
              format: auto
        processors:
          - decode_json_fields:
              fields: ["message"]
              process_array: false
              max_depth: 2
              target: "message_d"
              overwrite_keys: true
              add_error_key: true
          - script:
              lang: javascript
              source: >
                function process(event) {
                    var log_time = event.Get("message_d.record.log_time");
                    var user_name = event.Get("message_d.record.user_name");
                    var database_name = event.Get("message_d.record.database_name");
                    var sql_state_code = event.Get("message_d.record.sql_state_code");
                    var process_id = event.Get("message_d.record.process_id");
                    var message = event.Get("message_d.record.message");
                    var cleanedMessage = message.replace(/\n/g, ' ');
                    var message_grok = log_time + " " + "[" + process_id + "] " + user_name + "@" + database_name + " " + sql_state_code + ":  " + cleanedMessage;

                    event.Delete("message");
                    event.Put("message", message_grok);
                    event.Put("message_grok", message_grok);
                
                    return event;
                }
```

### The grok pattern by elastic

the log_time is needed for the first grok pattern 
```
^%{DATETIME:postgresql.log.timestamp}%{CHAR:separator}%{GREEDYDATA:raw_message}
```

the second grok pattern work seamlessly, and with note on double space after `sql_state_code:  `
```
^(\\[%{NUMBER:process.pid:long}(-%{BASE16FLOAT:postgresql.log.session_line_number:long})?\\] ((\\[%{USERNAME:user.name}\\]@\\[%{POSTGRESQL_DB_NAME:postgresql.log.database}\\]|%{USERNAME:user.name}@%{POSTGRESQL_DB_NAME:postgresql.log.database}) )?)?%{WORD:log.level}:  (?:%{POSTGRESQL_ERROR:postgresql.log.sql_state_code}|%{SPACE})(duration: %{NUMBER:temp.duration:float} ms  %{POSTGRESQL_QUERY_STEP}: %{GREEDYDATA:postgresql.log.query}|: %{GREEDYDATA:message}|%{GREEDYDATA:message})
```

### Result

Original decoded json:
```json
{
...
    "message_d": {
      "msg": "record",
      "logging_pod": "postgresql-1",
      "level": "info",
      "record": {
        "transaction_id": "0",
        "backend_type": "client backend",
        "process_id": "292754",
        "error_severity": "LOG",
        "sql_state_code": "00000",
        "database_name": "app",
        "query_id": "4454796909286141957",
        "user_name": "monitor",
        "session_start_time": "2023-11-22 09:02:24 UTC",
        "session_line_num": "34",
        "session_id": "655dc3a0.47792",
        "command_tag": "SELECT",
        "message": "duration: 2.709 ms",
        "log_time": "2023-11-22 09:07:56.776 UTC",
        "virtual_transaction_id": "4/0",
        "connection_from": "10.1.252.22:46388"
      },
      "logger": "postgres",
      "ts": "2023-11-22T09:07:56Z"
    },
...
}
```

grok ready:
```
{
...
    "message_grok": "2023-11-22 09:07:56.776 UTC [292754] monitor@app 00000:  duration: 2.709 ms",
...
}
```

Now elastic is happy

```json
{
...
    "postgresql": {
      "log": {
        "database": "app",
        "timestamp": "2023-11-22 09:07:56.776 UTC"
      }
    },
...
}
```

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/8409391/e85c4658-48d0-4e32-9476-d5a84434441b)

I maybe need to filter the user_name so it will drop event from internal monitoring, but im happy for now
