### DISCUSSION TITLE
Recovery to a specific time

### DISCUSSION THREAD

**Discussion by Ipicky22** [cloudnative-pg/cloudnative-pg#3450] [Q&A] [answered]
I created a cluster, with a PG database. I perform a scheduledBackup on it. The databases and wal files are stored in a minio.

Here are the operations in detail : 

```
10h23 => DB empty / + 1 wals folder with 4 files (001/002/003/0028.backup) / + 1 base 20231128T092355
10h33 => add Users table
10h36 => + 1 wal 0000000100000000 à 1 fichier 004
10h40 => + 1 base 20231128T094000
10h41 => + 1 wal 0000000100000000 à 1 fichier 005
10h41 => + 1 user A
10h46 => + 1 wal 0000000100000000 à 1 fichier 006
10h47 => + 1 user B
10h47 => + 1 user C
10h51 => + 1 wal 0000000100000000 à 1 fichier 007
11h00 => + 1 base 20231128T100000
11h02 => + 1 user D
11h06 => + 1 wal 0000000100000000 à 1 fichier 008

Recovery from Backup Object to 11h00 base 20231128T100000
```
I create a new cluster which takes my base 20231128T100000 as a reference point.

```
apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: cluster-object
  spec:
    enableSuperuserAccess: true
    instances: 2
    bootstrap:
      recovery:
        source: cluster-pg
        recoveryTarget:
          backupID: 20231128T100000
    imageName: ghcr.io/cloudnative-pg/postgresql:13.6
    storage:
      size: 1Gi
    backup:
      barmanObjectStore:
        destinationPath: s3://dbstorage/
        endpointURL: http://minio.infrastructure.svc.cluster.local:9000
        wal:
          compression: gzip
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: minio-creds
            key: MINIO_SECRET_KEY
    externalClusters:
    - name: cluster-pg
      barmanObjectStore:
        destinationPath: s3://dbstorage/
        endpointURL: http://minio.infrastructure.svc.cluster.local:9000
        wal:
          compression: gzip
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: minio-creds
            key: MINIO_SECRET_KEY
```

The expected result is a DB which contains users A,B and C.
The result is a DB which contains users A,B,C and D.

Thank you in advance for your help.
