### DISCUSSION TITLE
extra annotations for secrets

### DISCUSSION THREAD

**Discussion by fenio** [cloudnative-pg/cloudnative-pg#3653] [Q&A]
Does anyone know if it is possible to somehow automatically annotate secrets created using cluster manifests?
It would be useful for projects like kubernetes-replicator so chosen secrets could be automatically replicated to other namespaces for other apps.

**Comment by fenio** [comment]
Ok nevermind. I dropped that idea and went with initialization of Postgres with my own password to have full control over it.

**Comment by mrclrchtr** [comment]
Could you please reopen the Question? I have the same question and would be very grateful for an answer.

**Comment by maxemann96** [comment]
I opened an issue for that problem. See #5883. Also I fgured out, that my specific use case (Creation of a read only role to access with Grafana) is also possible with the usage of the managed roles feature. For this I created a secret containing my annotations.

Cluster:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ...
spec:
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: grafana
        passwordSecret:
          name: THE_GRAFANA_SECRET
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: app
```

Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: THE_GRAFANA_SECRET
  labels:
    cnpg.io/reload: 'true'
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: grafana
data:
  dbname: YXBw (app)
  host: ...
  jdbc-uri: ...
  password: ...
  pgpass: ...
  port: NTQzMg== (5432)
  uri: ...
  user: Z3JhZmFuYQ== (grafana)
  username: Z3JhZmFuYQ== (grafana)
type: Opaque
```

Hope it helps @mrclrchtr
