### DISCUSSION TITLE
HTTP exception with Barman object store backup

### DISCUSSION THREAD

**Discussion by kecskesalbert** [cloudnative-pg/cloudnative-pg#3658] [Q&A]
Hello,

I get an exception when trying to define a S3 compatible object storage service for backup:

```{
  "level": "info",
  "ts": "2024-01-03T11:33:25Z",
  "logger": "wal-archive",
  "msg": "barman-cloud-check-wal-archive checking the first wal",
  "logging_pod": "cloudnative-pg-postgresdb-1"
}
{
  "level": "info",
  "ts": "2024-01-03T11:33:26Z",
  "logger": "barman-cloud-check-wal-archive",
  "msg": "2024-01-03 11:33:26,161 [94] ERROR: Barman cloud WAL archive check exception: An HTTP Client raised an unhandled exception: Invalid header value b'AWS4-HMAC-SHA256 Credential=CDBX0MR2Y0YSC787K919\\n/20240103/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f55a9a030e70dc95b3472655764e2983dcdd70e8b50bf0f1c85423833e60eac0'",
  "pipe": "stderr",
  "logging_pod": "cloudnative-pg-postgresdb-1"
}
{
  "level": "error",
  "ts": "2024-01-03T11:33:26Z",
  "logger": "wal-archive",
  "msg": "Error invoking barman-cloud-check-wal-archive",
  "logging_pod": "cloudnative-pg-postgresdb-1",
  "currentPrimary": "cloudnative-pg-postgresdb-1",
  "targetPrimary": "cloudnative-pg-postgresdb-1",
  "options": [
    "--endpoint-url",
    "https://har-ceph-s3storage.nuvolaservices.net",
    "--cloud-provider",
    "aws-s3",
    "s3://keycloak-backup/pg01",
    "cloudnative-pg-postgresdb"
  ],
  "exitCode": -1,
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:257\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:391\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:208\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:89\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/proc.go:267"
}
```

it is cnpg version 1.21, with the following configuration:

```
{
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.nameOverride }}
spec:
  description: "Keycloak PG cluster"
  imageName: {{ .Values.imageName }}
  instances: {{ .Values.instances }}
  primaryUpdateStrategy: {{ .Values.primaryUpdateStrategy }}

  postgresql:
    parameters:
      max_worker_processes: {{ .Values.postgresql.parameters.max_worker_processes }}
      shared_buffers: {{ .Values.postgresql.parameters.shared_buffers }}
    pg_hba:
      - host all all all scram-sha-256

  storage:
    storageClass: {{ .Values.storage.storageClass }}
    size: {{ .Values.storage.size }}

  walStorage:
    storageClass: {{ .Values.walStorage.storageClass }}
    size: {{ .Values.walStorage.size }}

  backup:
    barmanObjectStore:
      destinationPath: s3://keycloak-backup/
      endpointURL: "https://har-ceph-s3storage.nuvolaservices.net"
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-objstore-creds
          key: access_key
        secretAccessKey:
          name: cloudnative-pg-objstore-creds
          key: secret_key
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
```

I am able to connect to the mentioned `endpointURL` with the credentials defined in `cloudnative-pg-objstore-creds` secret using python3-boto3.
I have found a similar discussion: https://github.com/cloudnative-pg/cloudnative-pg/discussions/409. I also had to add the `s3://` prefix to avoid `Invalid s3 URL address` errors. 
It seems that barman is still trying to connect to AWS us-east, despite of the existing `endpointURL` override. Or am I overlooking something?
Any assistance would be appreciated.
