### DISCUSSION TITLE
Cluster not restoring secrets

### DISCUSSION THREAD

**Discussion by ilbarone87** [cloudnative-pg/cloudnative-pg#3714] [Q&A]
Recently I had to restore a cluster from an object storage (minIO), 2 things caught my eyes:

- the restore was bootstrapping a db with these values
```
bootstrap:
    recovery:
      database: app
      owner: app
      source: postgres-cluster-wikijs
```
but i have not set database and owner value in my yaml.

- due to the issue mentioned above, the secret of the DB set in my yaml were not working and i had to use kubectl cnpg reload <cluster_name> to fix the connection
this is my yaml:
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster-wikijs
  namespace: cnpg-system
spec:
  description: postgres-cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn
    size: 7Gi
  monitoring:
    enablePodMonitor: true
  secret:
     name: postgres-wikijs-user
  superuserSecret:
    name: postgres-cluster-superuser

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all all password

  bootstrap:
   #initdb: 
    #  database: wikijs
    #  owner: wikijs
    recovery:
      source: postgres-cluster-wikijs

  externalClusters:
    - name: postgres-cluster-wikijs
      barmanObjectStore:
        destinationPath: "s3://cnpg-cluster-backup/"
        endpointURL: "https://api-minio.mydomain.com/"
        s3Credentials:
          accessKeyId:
            name: backup-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backup-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-cluster-backup/"
      endpointURL: ""https://api-minio.mydomain.com/"
      serverName: "postgres-cluster-wikijs-v2"
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        maxParallel: 8
        #encryption: AES256
      data:
        compression: bzip2
        #encryption: AES256
        jobs: 2 
    retentionPolicy: "30d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
```

What i'm missing here? Is there anything that I should have configured or is this an issue that should be flagged?

Thanks
