### DISCUSSION TITLE
importing databases with (unused?) extensions

### DISCUSSION THREAD

**Discussion by sylvainOL** [cloudnative-pg/cloudnative-pg#3723] [Q&A] [answered]
Hello,
I'm currently using Zalando operator but it doesn't behave as expected.

I've tried CNPG and it seems to be far more stable so I decided to switch :)

My issue is that I'd like to import some datas from my previous databases.

I've tried to use the documentation and did the following:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydb-pg
  namespace: mydb
spec:
  bootstrap:
    initdb:
      database: mydb
      import:
        databases:
        - mydb
        source:
          externalCluster: mydb-legacy
        type: microservice
      owner: mydb
  ephemeralVolumesSizeLimit:
    shm: 100Mi
    temporaryData: 100Mi
  externalClusters:
  - connectionParameters:
      dbname: postgres
      host: mydb-db.mydb.svc.cluster.local
      user: postgres
    name: mydb-legacy
    password:
      key: password
      name: postgres.mydb-db.credentials.postgresql.acid.zalan.do
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-15
  imagePullPolicy: Always
  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: mydb
      app.kubernetes.io/version: 16.1-15
      version: 16.1-15
  instances: 3
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      memory: 411M
    requests:
      cpu: 33m
      memory: 200Mi
  storage:
    size: 1Gi
    storageClass: hdd
  walStorage:
    size: 1Gi
    storageClass: fast
```

import is launched but it fails with the following issue:

<details>
 <summary>part of the logs</summary>

```json
[
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_dump",
    "msg": "pg_dump: dumping contents of table \"public.trust_indicators\"",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_dump",
    "msg": "pg_dump: dumping contents of table \"public.users\"",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "msg": "dropping user-defined extensions from the target (empty) database",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "msg": "temporarily granting superuser permission to owner user",
    "logging_pod": "mydb-pg-1-import",
    "owner": "mydb"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pgaudit",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.791 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "49",
      "connection_from": "[local]",
      "session_id": "65afd1af.31",
      "session_line_num": "1",
      "command_tag": "ALTER ROLE",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/15",
      "transaction_id": "732",
      "error_severity": "LOG",
      "sql_state_code": "00000",
      "application_name": "cnpg-instance-manager",
      "backend_type": "client backend",
      "query_id": "0",
      "audit": {
        "audit_type": "SESSION",
        "statement_id": "1",
        "substatement_id": "1",
        "class": "ROLE",
        "command": "ALTER ROLE",
        "statement": "ALTER USER \"mydb\" SUPERUSER",
        "parameter": "<none>"
      }
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "msg": "executing database importing section",
    "logging_pod": "mydb-pg-1-import",
    "databaseName": "mydb",
    "section": "pre-data"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "msg": "Running pg_restore",
    "logging_pod": "mydb-pg-1-import",
    "cmd": "pg_restore",
    "options": [
      "-U",
      "postgres",
      "--no-owner",
      "--no-privileges",
      "--role=mydb",
      "-d",
      "mydb",
      "--section",
      "pre-data",
      "/var/lib/postgresql/data/pgdata/dumps/mydb.dump"
    ]
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pgaudit",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.879 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "1",
      "command_tag": "SELECT",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/17",
      "transaction_id": "0",
      "error_severity": "LOG",
      "sql_state_code": "00000",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0",
      "audit": {
        "audit_type": "SESSION",
        "statement_id": "1",
        "substatement_id": "1",
        "class": "READ",
        "command": "SELECT",
        "statement": "SELECT pg_catalog.set_config('search_path', '', false);",
        "parameter": "<none>"
      }
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pgaudit",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.938 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "8",
      "command_tag": "CREATE EXTENSION",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/39",
      "transaction_id": "0",
      "error_severity": "LOG",
      "sql_state_code": "00000",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0",
      "audit": {
        "audit_type": "SESSION",
        "statement_id": "8",
        "substatement_id": "1",
        "class": "DDL",
        "command": "CREATE EXTENSION",
        "statement": "CREATE EXTENSION IF NOT EXISTS pg_stat_kcache WITH SCHEMA public;\n\n\n",
        "parameter": "<none>"
      }
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "postgres",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.938 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "9",
      "command_tag": "CREATE EXTENSION",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/39",
      "transaction_id": "0",
      "error_severity": "ERROR",
      "sql_state_code": "0A000",
      "message": "extension \"pg_stat_kcache\" is not available",
      "detail": "Could not open extension control file \"/usr/share/postgresql/16/extension/pg_stat_kcache.control\": No such file or directory.",
      "hint": "The extension must first be installed on the system where PostgreSQL is running.",
      "query": "CREATE EXTENSION IF NOT EXISTS pg_stat_kcache WITH SCHEMA public;\n\n\n",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0"
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "pg_restore: error: could not execute query: ERROR:  extension \"pg_stat_kcache\" is not available",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "DETAIL:  Could not open extension control file \"/usr/share/postgresql/16/extension/pg_stat_kcache.control\": No such file or directory.",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "HINT:  The extension must first be installed on the system where PostgreSQL is running.",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "Command was: CREATE EXTENSION IF NOT EXISTS pg_stat_kcache WITH SCHEMA public;",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "postgres",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.941 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "10",
      "command_tag": "COMMENT",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/40",
      "transaction_id": "0",
      "error_severity": "ERROR",
      "sql_state_code": "42704",
      "message": "extension \"pg_stat_kcache\" does not exist",
      "query": "COMMENT ON EXTENSION pg_stat_kcache IS 'Kernel statistics gathering';\n\n\n",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0"
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "pg_restore: error: could not execute query: ERROR:  extension \"pg_stat_kcache\" does not exist",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "Command was: COMMENT ON EXTENSION pg_stat_kcache IS 'Kernel statistics gathering';",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pgaudit",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.941 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "11",
      "command_tag": "CREATE EXTENSION",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/41",
      "transaction_id": "0",
      "error_severity": "LOG",
      "sql_state_code": "00000",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0",
      "audit": {
        "audit_type": "SESSION",
        "statement_id": "9",
        "substatement_id": "1",
        "class": "DDL",
        "command": "CREATE EXTENSION",
        "statement": "CREATE EXTENSION IF NOT EXISTS set_user WITH SCHEMA public;\n\n\n",
        "parameter": "<none>"
      }
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "postgres",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.942 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "12",
      "command_tag": "CREATE EXTENSION",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/41",
      "transaction_id": "0",
      "error_severity": "ERROR",
      "sql_state_code": "0A000",
      "message": "extension \"set_user\" is not available",
      "detail": "Could not open extension control file \"/usr/share/postgresql/16/extension/set_user.control\": No such file or directory.",
      "hint": "The extension must first be installed on the system where PostgreSQL is running.",
      "query": "CREATE EXTENSION IF NOT EXISTS set_user WITH SCHEMA public;\n\n\n",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0"
    }
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "pg_restore: error: could not execute query: ERROR:  extension \"set_user\" is not available",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "DETAIL:  Could not open extension control file \"/usr/share/postgresql/16/extension/set_user.control\": No such file or directory.",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "HINT:  The extension must first be installed on the system where PostgreSQL is running.",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "Command was: CREATE EXTENSION IF NOT EXISTS set_user WITH SCHEMA public;",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "pg_restore: error: could not execute query: ERROR:  extension \"set_user\" does not exist",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "pg_restore",
    "msg": "Command was: COMMENT ON EXTENSION set_user IS 'similar to SET ROLE but with added logging';",
    "pipe": "stderr",
    "logging_pod": "mydb-pg-1-import"
  },
  {
    "level": "info",
    "ts": "2024-01-23T14:48:15Z",
    "logger": "postgres",
    "msg": "record",
    "logging_pod": "mydb-pg-1-import",
    "record": {
      "log_time": "2024-01-23 14:48:15.943 UTC",
      "user_name": "postgres",
      "database_name": "mydb",
      "process_id": "51",
      "connection_from": "[local]",
      "session_id": "65afd1af.33",
      "session_line_num": "13",
      "command_tag": "COMMENT",
      "session_start_time": "2024-01-23 14:48:15 UTC",
      "virtual_transaction_id": "3/42",
      "transaction_id": "0",
      "error_severity": "ERROR",
      "sql_state_code": "42704",
      "message": "extension \"set_user\" does not exist",
      "query": "COMMENT ON EXTENSION set_user IS 'similar to SET ROLE but with added logging';\n\n\n",
      "application_name": "pg_restore",
      "backend_type": "client backend",
      "query_id": "0"
    }
  }
]
```
</details>

as you can seen, I've got two extensions (`pg_stat_kcache` and `set_user`) that are present (but unused by the actual database I guess, it's a rails application without big needs) and that makes the import failing.

I used `pg_dump -Fp -f test-pg.sql -d "host='localhost' user='postgres' dbname='mydb'" -v --section=pre-data --section=data --section=post-data` to see what's inside and I also see some functions and acls that may be problematic (?):

```
pg_dump: creating SCHEMA "metric_helpers"
pg_dump: creating SCHEMA "user_management"
pg_dump: creating EXTENSION "pg_stat_statements"
pg_dump: creating COMMENT "EXTENSION pg_stat_statements"
pg_dump: creating EXTENSION "pg_stat_kcache"
pg_dump: creating COMMENT "EXTENSION pg_stat_kcache"
pg_dump: creating EXTENSION "set_user"
pg_dump: creating COMMENT "EXTENSION set_user"
pg_dump: creating FUNCTION "metric_helpers.get_btree_bloat_approx()"
pg_dump: creating FUNCTION "metric_helpers.get_table_bloat_approx()"
pg_dump: creating FUNCTION "metric_helpers.pg_stat_statements(boolean)"
pg_dump: creating FUNCTION "user_management.create_application_user(text)"
pg_dump: creating COMMENT "user_management.FUNCTION create_application_user(username text)"
pg_dump: creating FUNCTION "user_management.create_application_user_or_change_password(text, text)"
pg_dump: creating COMMENT "user_management.FUNCTION create_application_user_or_change_password(username text, password text)"
pg_dump: creating FUNCTION "user_management.create_role(text)"
pg_dump: creating COMMENT "user_management.FUNCTION create_role(rolename text)"
pg_dump: creating FUNCTION "user_management.create_user(text)"
pg_dump: creating COMMENT "user_management.FUNCTION create_user(username text)"
pg_dump: creating FUNCTION "user_management.drop_role(text)"
pg_dump: creating COMMENT "user_management.FUNCTION drop_role(username text)"
pg_dump: creating FUNCTION "user_management.drop_user(text)"
pg_dump: creating COMMENT "user_management.FUNCTION drop_user(username text)"
pg_dump: creating FUNCTION "user_management.random_password(integer)"
pg_dump: creating FUNCTION "user_management.revoke_admin(text)"
pg_dump: creating COMMENT "user_management.FUNCTION revoke_admin(username text)"
pg_dump: creating FUNCTION "user_management.terminate_backend(integer)"
pg_dump: creating COMMENT "user_management.FUNCTION terminate_backend(pid integer)"
pg_dump: creating VIEW "metric_helpers.index_bloat"
pg_dump: creating VIEW "metric_helpers.pg_stat_statements"
pg_dump: creating VIEW "metric_helpers.table_bloat"
...
pg_dump: creating ACL "SCHEMA metric_helpers"
pg_dump: creating ACL "SCHEMA user_management"
pg_dump: creating ACL "metric_helpers.FUNCTION get_btree_bloat_approx(OUT i_database name, OUT i_schema_name name, OUT i_table_name name, OUT i_index_name name, OUT i_real_size numeric, OUT i_extra_size numeric, OUT i_extra_ratio double precision, OUT i_fill_factor integer, OUT i_bloat_size double precision, OUT i_bloat_ratio double precision, OUT i_is_na boolean)"
pg_dump: creating ACL "metric_helpers.FUNCTION get_table_bloat_approx(OUT t_database name, OUT t_schema_name name, OUT t_table_name name, OUT t_real_size numeric, OUT t_extra_size double precision, OUT t_extra_ratio double precision, OUT t_fill_factor integer, OUT t_bloat_size double precision, OUT t_bloat_ratio double precision, OUT t_is_na boolean)"
pg_dump: creating ACL "metric_helpers.FUNCTION pg_stat_statements(showtext boolean)"
pg_dump: creating ACL "pg_catalog.FUNCTION pg_switch_wal()"
pg_dump: creating ACL "public.FUNCTION pg_stat_statements_reset(userid oid, dbid oid, queryid bigint)"
pg_dump: creating ACL "public.FUNCTION set_user(text)"
pg_dump: creating ACL "user_management.FUNCTION create_application_user(username text)"
pg_dump: creating ACL "user_management.FUNCTION create_application_user_or_change_password(username text, password text)"
pg_dump: creating ACL "user_management.FUNCTION create_role(rolename text)"
pg_dump: creating ACL "user_management.FUNCTION create_user(username text)"
pg_dump: creating ACL "user_management.FUNCTION drop_role(username text)"
pg_dump: creating ACL "user_management.FUNCTION drop_user(username text)"
pg_dump: creating ACL "user_management.FUNCTION revoke_admin(username text)"
pg_dump: creating ACL "user_management.FUNCTION terminate_backend(pid integer)"
pg_dump: creating ACL "metric_helpers.TABLE index_bloat"
pg_dump: creating ACL "metric_helpers.TABLE pg_stat_statements"
pg_dump: creating ACL "metric_helpers.TABLE table_bloat"
pg_dump: creating ACL "pg_catalog.TABLE pg_stat_activity"
```

What would be the "best" way for import?
pre destroy of function / acl and extensions or creating an image with the two extensions (I've not found how ^_^) and clean the mess "after"?

thanks!

**Comment by sylvainOL** [comment]
Hello @gbartolini,

I'm sorry to ping you this way but do you have any clues?

thanks!

**Reply by svieujot** [reply]
We have the same issue.

Did you find a solution ?

**Reply by sylvainOL** [reply]
Hello, nope sorry :/

I'll try this week to create an image with the two extensions and then remove them and restart with vanilla image

I'll keep you posted

**Reply by svieujot** [reply]
Ok, thank you.

I am trying to see if importing from a `VolumeSnapshot` would help.

**Reply by sylvainOL** [reply]
I managed to make it work but am on a business trip today.
I'll make an update tomorrow!

**Reply by svieujot** [reply]
Geat. Thank you.

**Comment by gbartolini** [comment]
At the end of the day, the `import` process is nothing magic. It is just running `pg_dump` in custom format and then use `pg_restore`. What you can do is to create an empty cluster, then run `pg_restore` (you can use the list feature that allows you to filter out items in the table of contents of the dump).

Also, if those images are not used ... you can remove them from the source directly.

**Comment by sylvainOL** [comment, marked as answer]
Hello,

I managed to have something to work in a way it's reversible up to the moment we've finished the move. As said @gbartolini, it can be simpler but here it allows to be sure we can move back to Zalando if needed in the middle.


## Specific container creation

I followed `pg_stat_kcache` and `set_user` github page and add them into cnpg image:

```Dockerfile
FROM ghcr.io/cloudnative-pg/postgresql:16.1-19

USER root

RUN set -xe; \
  apt-get update ; \
  apt-get install -y --no-install-recommends \
    "build-essential" \
    "clang-11" \
    "git" \
    "llvm-11" \
    "postgresql-server-dev-16" \
  ; \
  git clone -b REL4_0_1 https://github.com/pgaudit/set_user.git  /tmp/set_user; \
  cd /tmp/set_user; \
  make USE_PGXS=1; \
  make USE_PGXS=1 install; \
  cd - ; \
  apt-get purge -y \
    "build-essential" \
    "clang-11" \
    "git" \
    "llvm-11" \
    "postgresql-server-dev-16" \
  ; \
  apt-get autopurge -y; \
  apt-get install -y --no-install-recommends \
    "postgresql-16-pg-stat-kcache" \
  ; \
  rm -fr /tmp/* ; \
  rm -rf /var/lib/apt/lists/*;

USER 26
```

## Import phase

I've changed my cluster declaration with following:

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydb-pg
  namespace: mydb
spec:
  bootstrap:
    initdb:
      database: mydb
      import:
        databases:
        - mydb
        source:
          externalCluster: mydb-legacy
        type: microservice
      owner: mydb
  ephemeralVolumesSizeLimit:
    shm: 100Mi
    temporaryData: 100Mi
  externalClusters:
  - connectionParameters:
      dbname: postgres
      host: mydb-db.mydb.svc.cluster.local
      user: postgres
    name: mydb-legacy
    password:
      key: password
      name: postgres.mydb-db.credentials.postgresql.acid.zalan.do
  # path to your container
  # version MUST start with postgres version (16.1 here) and after `-` you
  # can put whatever you want
  imageName: myregistry.tld/cnpg-with-extensions:16.1-specific-1.0.0
  imagePullPolicy: Always
  # only if your registry is private
  imagePullSecrets:
  - name: docker-auth
  inheritedMetadata:
    annotations:
      # because I'm using Istio
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: mydb
      app.kubernetes.io/version: 16.1-19
      version: 16.1-19
  instances: 3
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    shared_preload_libraries:
    - set_user
    - pg_stat_statements
    - pg_stat_kcache
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      memory: 411M
    requests:
      cpu: 33m
      memory: 200Mi
  storage:
    size: 1Gi
    storageClass: hdd
  walStorage:
    size: 1Gi
    storageClass: fast
```

Now, when launching, `import` and then `start` works like a charm.

## Cleaning phase

In parallel, I've created the same database with onboarding created by my app (a ruby on rail application) and looked at the diff.

I now launch a job using this SQL file:

```sql
DROP VIEW IF EXISTS metric_helpers.table_bloat;
DROP VIEW IF EXISTS metric_helpers.pg_stat_statements;
DROP VIEW IF EXISTS metric_helpers.index_bloat;
DROP FUNCTION IF EXISTS user_management.terminate_backend(pid integer);
DROP FUNCTION IF EXISTS user_management.revoke_admin(username text) ;
DROP FUNCTION IF EXISTS user_management.random_password(length integer);
DROP FUNCTION IF EXISTS user_management.drop_user(username text);
DROP FUNCTION IF EXISTS user_management.drop_role(username text);
DROP FUNCTION IF EXISTS user_management.create_user(username text);
DROP FUNCTION IF EXISTS user_management.create_role(rolename text);
DROP FUNCTION IF EXISTS user_management.create_application_user_or_change_password(username text, password text);
DROP FUNCTION IF EXISTS user_management.create_application_user(username text);
DROP FUNCTION IF EXISTS metric_helpers.pg_stat_statements(showtext boolean);
DROP FUNCTION IF EXISTS metric_helpers.get_table_bloat_approx(OUT t_database name, OUT t_schema_name name, OUT t_table_name name, OUT t_real_size numeric, OUT t_extra_size double precision, OUT t_extra_ratio double precision, OUT t_fill_factor integer, OUT t_bloat_size double precision, OUT t_bloat_ratio double precision, OUT t_is_na boolean) ;
DROP FUNCTION IF EXISTS metric_helpers.get_btree_bloat_approx(OUT i_database name, OUT i_schema_name name, OUT i_table_name name, OUT i_index_name name, OUT i_real_size numeric, OUT i_extra_size numeric, OUT i_extra_ratio double precision, OUT i_fill_factor integer, OUT i_bloat_size double precision, OUT i_bloat_ratio double precision, OUT i_is_na boolean);
DROP EXTENSION IF EXISTS set_user;
DROP EXTENSION IF EXISTS pg_stat_kcache;
DROP EXTENSION IF EXISTS pg_stat_statements;
DROP SCHEMA IF EXISTS user_management;
DROP SCHEMA IF EXISTS metric_helpers;
```

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: mydb-clean
    kustomize.toolkit.fluxcd.io/force: enabled
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: mydb-clean
  namespace: mydb
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app.kubernetes.io/name: mydb-clean
        job-name: mydb-clean
    spec:
      containers:
      - command:
        - psql
        - -f
        - /sql/clean.sql
        env:
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: dbname
              name: mydb-pg-app
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: host
              name: mydb-pg-app
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: mydb-pg-app
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mydb-pg-app
        image: ghcr.io/cloudnative-pg/postgresql:16.1-19
        imagePullPolicy: Always
        name: mydb-clean
        resources:
          limits:
            ephemeral-storage: 100Mi
            memory: 100Mi
          requests:
            cpu: 200m
            ephemeral-storage: 100Mi
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /sql/
          name: clean-database
      - args:
        - '-envoy.port=15020'
        - '-container=mydb-clean'
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Make sure istio proxy stop when main container has finished
        # yamllint disable-line rule:line-length
        image: myregistry.tld/envoy-sidecar-helper:1.0.33@sha256:d5c3e8662804f6565b3952f427944c162afc88bf309d96f45c531a27001e439f
        imagePullPolicy: Always
        name: envoy-sidecar-helper
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Mi
            memory: 20Mi
          requests:
            cpu: 200m
            ephemeral-storage: 1Mi
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-auth
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 10000
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: mydb
      volumes:
      - configMap:
          name: clean-database
        name: clean-database
```

I'm using kustomize (and flux) to tie that together:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - clean.sql
  name: clean-database
  namespace: mydb
kind: Kustomization
resources:
- clean-job.yaml
```

## Finish

Now, I can edit my cluster definition to use official image from cnpg and remove the specific:

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydb-pg
  namespace: mydb
spec:
  bootstrap:
    initdb:
      database: mydb
  ephemeralVolumesSizeLimit:
    shm: 100Mi
    temporaryData: 100Mi
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-19
  imagePullPolicy: Always
  inheritedMetadata:
    annotations:
      # because I'm using Istio
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: mydb
      app.kubernetes.io/version: 16.1-19
      version: 16.1-19
  instances: 3
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      memory: 411M
    requests:
      cpu: 33m
      memory: 200Mi
  storage:
    size: 1Gi
    storageClass: hdd
  walStorage:
    size: 1Gi
    storageClass: fast
```

hope it helps
