### DISCUSSION TITLE
Help correct networkpolicies for cluster

### DISCUSSION THREAD

**Discussion by maxweisspoker** [cloudnative-pg/cloudnative-pg#3738] [Q&A]
Hello, I cannot seem to get my network policies correct. I have installed the operator in the "postgres" namespace, and then I install my clusters in another namespace, often with the application.  I have an open network policy for the operator "postgres" namespace, since it needs to be able to send to and receive from all namespaces. I have verified that that works.

However, for my application and cluster pod policies, I try to lock them down. Below is an example set of policies for an app that has its pod in the same namespace as the cluster pods, and allows traefik to send it traffic. It doesn't need to connect to any other pods except the cluster pods, but I also allow DNS so it can lookup the service FQDN. Likewise, the cluster pods should have communication in the namespace in order to talk to the app, and also be able to send and receive from the postgres namespace in order to communicate with the operator.

When the cluster is healthy, things are fine, the app works and connects, and data is replicated between the primary and additional cluster pods. But when a failover is needed or the number of cluster instances is scaled up or down, that does not work..... until I delete my networkpolicies from the app namespace.  SO clearly I am missing some allow-rule, but for the life of me, I cannot figure out what it is.

If anybody can help me determine what I need to do to correct my application-namespace networkpolicies in place, I'd really appreciate it!!

Here is the set of policies that allow the app to work, but prevent the cluster from failing-over or doing other things like adding another instance:

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-policy
  namespace: app-namespace
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - myapp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: traefik-traefik
          app.kubernetes.io/name: traefik
    ports:
    - port: 80
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app-namespace
      podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-psql-policy
  namespace: app-namespace
spec:
  podSelector:
    matchExpressions:
    - key: cnpg.io/cluster
      operator: In
      values:
      - app-pg-cluster-name
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app-namespace
      podSelector: {}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres
      podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app-namespace
      podSelector: {}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres
      podSelector: {}
---
```
