### DISCUSSION TITLE
PodDisruptionBudget is warning for primary instance

### DISCUSSION THREAD

**Discussion by grahamboyle** [cloudnative-pg/cloudnative-pg#3865] [Q&A]
Hi

I'm new to the K8s and Postgres world
I've created a database with 3 instances called pg-graham-dev3

Two pod disruption budgets get created by CNPG when I do this: 
pg-graham-dev3 and pg-graham-dev3-primary

pg-graham-dev3 is fine, min available is 1 and allowed disruptions is 1
pg-graham-dev3-primary is in warning , min available is 1 and allowed disruptions is 0

"Insufficient Pods" is the alert, I don't understand why its saying that where there are two replicas available.

Any advice on what's wrong?
```
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.22.1
  name: pg-graham-dev3-primary
  generation: 1
  namespace: cloudnativepg
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: pg-graham-dev3
      controller: true
  labels:
    cnpg.io/cluster: pg-graham-dev3
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: pg-graham-dev3
      role: primary
status:
  observedGeneration: 1
  disruptionsAllowed: 0
  currentHealthy: 1
  desiredHealthy: 1
  expectedPods: 1
  conditions:
    - type: DisruptionAllowed
      status: 'False'
      observedGeneration: 1
      lastTransitionTime: '2024-02-22T15:23:56Z'
      reason: InsufficientPods
      message: ''
```

**Comment by ilabrovic** [comment]
hello, we have same issue. this is cause by .spec.enablePDB which creates 2 PDB's: 1 for primary and 1 for replicas.
There is only 1 primary, so that PDB will trigger an alert immediately because the running primaries (1!) is already at the minimum described in the PDB.
the .spec.enablePDb can be turned off, but that removes both PDB's at least we want to have the PDB on de replicas.

Is it possible to add a feature to have enablePDB a value of 'replicaonly'?

Now we choose to turn enablePDB off, and create a pdb for the replicas ourselves, but we would rather see the operator handle this.

**Reply by gbartolini** [reply]
Hello, please let me understand. If you have just one instance in the cluster, why would you need PDBs for replicas? Can you please elaborate on the use case? Thanks.

**Reply by JordanP** [reply]
@gbartolini I think the problem is that by default (design ?) with `enablePDB` 2 PDBs are created, one PDB for the primary and one PDB for the replica(S). But in some systems a PDB that allows 0 disruption (like the one for the primary pod) triggers an alert/warning.

**Comment by grahambo2005** [comment]
we ended up disabling the default PDB and creating our own one

```
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: pg-grahambo2005-dev3-pdb
  namespace: postgres
  labels:
    app.kubernetes.io/instance: pg-grahambo2005-dev3
    cnpg.io/cluster: pg-grahambo2005-dev3
spec:
  minAvailable: 1
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: In
        values:
          - pg-grahambo2005-dev3
      - key: role
        operator: In
        values:
          - primary
          - replica
```
