### DISCUSSION TITLE
How to specify nodes for Primary Pod and replicas using Pod Affnity?

### DISCUSSION THREAD

**Discussion by retrogaming457** [cloudnative-pg/cloudnative-pg#3985] [Q&A]
I have three worker nodes on my cluster, worker1, worker2 and worker3. I have added below label to each:
```
kubectl label nodes worker1 postgres=db-instance1
kubectl label nodes worker2 postgres=db-instance2
kubectl label nodes worker3 postgres=db-instance3
```
And in the manifest, I have defined which ones to use:
```
spec:
  description: "pgcluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 2
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: postgres
            operator: In
            values:
            - db-instance1
            - db-instance2
```
However, after deployment, the primary pod is deployed on worker2 and the standby on worker1.

```
Name        Database Size  Current LSN  Replication role  Status  QoS        Manager Version  Node
----       -------------  -----------  ----------------  ------  ---        ---------------  ----
pgcluster-1  29 MB          0/5000000    Primary           OK      Burstable  1.22.1           worker2
pgcluster-2  29 MB          0/5000000    Standby (async)   OK      Burstable  1.22.1           worker1
```

How can I specifically define which pod goes where?  
I want the primary on the worker1 and standby on worker2.
