### DISCUSSION TITLE
Recovery issues using CEPH self hosted S3

### DISCUSSION THREAD

**Discussion by tgumleo** [cloudnative-pg/cloudnative-pg#4175] [General]
Hi. 

We are running cloudnative-pg version 1.22.1 on-prem with k8s version 1.26. For backup & recovery we have an on-prem CEPH solution, providing the S3 interface.

Backups are written to S3 without issue, however when we try to recover a DB from the S3 storage, we are consistently presented with the message that the backup WALs can not be found.

I've put debug on CEPH to understand what calls are being made via Barman/Boto and can see that every GET request coming from the operator has a Prefix of **clustername/base**. No where in the documentation (that I've found) is this **/base** structure listed, but more importantly the call also includes a Delimiter of '/'. After having reproduced the problem by running Boto manually against the s3 backup bucket, it's the delimiter which stops the WAL results being returned to whatever function is doing the call.

Has anyone encountered something similar / am I being an idiot!?

Relevant bits of config listed below: - NB /base has been added to serverName post investigation, it's also been tested without.

**Original Cluster**
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
blah
backup:
   barmanObjectStore:
      serverName: bob-postgres-cluster/base
      destinationPath: "s3://bucketname"
  wal:
     compression: gzip
```
**Recovery Cluster**
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: 
    name: bob-postgres-cluster-restore
spec:
  bootstrap:
     recovery:
        source: bob-postgres-cluster
    externalClusters:
       - name: bob-postgres-cluster
         barmanObjectStore:
              serverName: bob-postgres-cluster
              destinationPath: "s3://bucketname"
          wal:
             compression: gzip
```

Structure found within S3 store:

<bucketname>/bob-postgres-cluster/base/wals/xxxxx/xxxxx.gz

CEPH Beast logs shows inbound connection logs as follows on a recovery request:

_GET /bucketname?list-type=2&prefix=bob-postgres-cluster%2Fbase%2F&delimiter=%2F&encoding-type=url HTTP/1.1 200 347 - "Boto3/1.34.51 md/Botocore#1.34.51 ua/2.0 os/linux blah blah_
