### DISCUSSION TITLE
Enable configuration to run primary node and synchronous replication on same subnet

### DISCUSSION THREAD

**Discussion by fdolsky321** [cloudnative-pg/cloudnative-pg#4220] [Q&A]
Is there any way to easily configure synchronous replication and primary node to be running on the node with the same topology key?
Let's say I have 3 zones:`topology.kubernetes.io/zone`: zone-1, zone-2, zone-3
To make the network latency as small as possible, I wanna run synchronous replication in the same zone like primary (e.g. zone-1) and then other asynchronous replicas on zone-2 and zone-3.

If there is existing smooth solution, sorry for this question.

**Comment by fdolsky321** [comment]
Reffering to @gbartolini comment how to achieve actually anti-desired state:

```yaml
spec:
  instances: 3
  postgresql:
    syncReplicaElectionConstraint:
      enabled: true
      nodeLabelsAntiAffinity:
      - topology.kubernetes.io/zone
```
By this, I achieve that my synchronous replication is in different zone than my primary one. What I would need is to have option to use `nodeLabelsAntiAffinity` so the sync replicas would be on the same node as primary.
