### DISCUSSION TITLE
Cannot backup to Wasabi S3 but I have no idea what the problem is

### DISCUSSION THREAD

**Discussion by UntouchedWagons** [cloudnative-pg/cloudnative-pg#4249] [Q&A]
I'm trying to set up streaming backups to a Wasabi S3 bucket and am not having much success because I have no idea what the problem is:

Possibly relevant log:

    {"level":"info","ts":"2024-04-08T19:43:35Z","logger":"postgres","msg":"record","logging_pod":"postgresql-cluster-2","record":{"log_time":"2024-04-08 19:43:35.893 UTC","process_id":"595","session_id":"66118c5b.253","session_line_num":"41","session_start_time":"2024-04-06 17:54:35 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"archive command failed with exit code 1","detail":"The failed archive command was: /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/000000040000000D000000DB","backend_type":"archiver","query_id":"0"}}
    {"level":"info","ts":"2024-04-08T19:43:37Z","logger":"barman-cloud-wal-archive","msg":"2024-04-08 19:43:37,561 [297561] ERROR: Barman cloud WAL archiver exception: An error occurred (400) when calling the HeadBucket operation: Bad Request","pipe":"stderr","logging_pod":"postgresql-cluster-2"}
    {"level":"error","ts":"2024-04-08T19:43:37Z","msg":"Error invoking barman-cloud-wal-archive","logging_pod":"postgresql-cluster-2","walName":"pg_wal/000000040000000D000000DB","currentPrimary":"postgresql-cluster-2","targetPrimary":"postgresql-cluster-2","options":["--endpoint-url","https://s3.us-west-1.wasabisys.com","--cloud-provider","aws-s3","s3://BUCKET_NAME/","postgresql-cluster","pg_wal/000000040000000D000000DB"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).Archive\n\tpkg/management/barman/archiver/archiver.go:186\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).ArchiveList.func1\n\tpkg/management/barman/archiver/archiver.go:131"}
    {"level":"info","ts":"2024-04-08T19:43:37Z","logger":"wal-archive","msg":"Failed archiving WAL: PostgreSQL will retry","logging_pod":"postgresql-cluster-2","walName":"pg_wal/000000040000000D000000DB","startTime":"2024-04-08T19:43:36Z","endTime":"2024-04-08T19:43:37Z","elapsedWalTime":0.638576147,"error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4"}
    {"level":"error","ts":"2024-04-08T19:43:37Z","logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"postgresql-cluster-2","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:95\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:267"}

Cluster object:

    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: postgresql-cluster
      namespace: database
    spec:
      instances: 3

      storage:
        size: 25Gi
        storageClass: local-path

      monitoring:
        enablePodMonitor: true

      enableSuperuserAccess: true
      superuserSecret:
        name: postgresql-cluster-superuser

      backup:
        barmanObjectStore:
          destinationPath: "s3://BUCKET_NAME/"
          endpointURL: "https://s3.us-west-1.wasabisys.com"
          s3Credentials:
            accessKeyId:
              name: aws-creds
              key: ACCESS_KEY_ID
            secretAccessKey:
              name: aws-creds
              key: ACCESS_SECRET_KEY
        retentionPolicy: "30d"

**Comment by UntouchedWagons** [comment]
I can't backup to minio either

**Comment by sxd** [comment]
Hi @UntouchedWagons 

This is clear an error in your permissions 

{"level":"info","ts":"2024-04-08T19:43:37Z","logger":"barman-cloud-wal-archive","msg":"2024-04-08 19:43:37,561 [297561] ERROR: Barman cloud WAL archiver exception: An error occurred (400) when calling the HeadBucket operation: Bad Request","pipe":"stderr","logging_pod":"postgresql-cluster-2"}

You have a 400 error there a "Bad Request" so or your not allow or your object storage it's not ok

Regards!

**Comment by UntouchedWagons** [comment]
Why is an error being reported in a json message with a level of info? In any case I'm able to upload to the specified bucket manually using the credentials I've supplied to the cnpg operator.

**Comment by UntouchedWagons** [comment]
```
{"level":"error","ts":"2024-04-09T14:59:00Z","msg":"while getting recover credentials","logging_pod":"postgresql-cluster-2","error":"while getting secret wasabi-creds: secrets \"wasabi-creds\" is forbidden: User \"system:serviceaccount:database:postgresql-cluster\" cannot get resource \"secrets\" in API group \"\" in the namespace \"database\"","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).updateWALRestoreSettingsCache\n\tinternal/management/controller/cache.go:71\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).updateCacheFromCluster\n\tinternal/management/controller/cache.go:47\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```
Looks like the ServiceAccount doesn't have the right permissions to access Secrets?

**Comment by sxd** [comment]
Clearly you should handle that =) did you installed in the standard way ?

**Comment by UntouchedWagons** [comment]
I don't know what "the standard way" you're referring to, I've defined a Cluster object as shown in the opening post.

**Comment by sxd** [comment]
How did you installed the operator ?

**Comment by UntouchedWagons** [comment]
I installed the operator through the cloudnative-pg/cloudnative-pg helm chart

**Comment by sxd** [comment]
Then clearly a permission is missing in the process =)

**Comment by MatthiasWinzeler** [comment]
@UntouchedWagons the `while getting recover credentials` error is misleading here - what was missing in my case was specifying the `region`:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://my-bucket-name/cnpg/
      endpointURL: https://s3.endpoint.com
      s3Credentials:
        region:
          name: secret-name
          key: REGION
        accessKeyId:
          name: secret-name
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: secret-name
          key: ACCESS_SECRET_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: foundry-db-backup-secret
  namespace: ${local.foundry_namespace}
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  ACCESS_KEY_ID: ${var.backup_s3_access_key}
  ACCESS_SECRET_KEY: ${var.backup_s3_secret_key}
  REGION: "custom-region"
```

**Comment by lebe-dev** [comment]
Another workaround is to specify `AWS_DEFAULT_REGION` in `cluster` helm chart values:

```yaml
cluster:
  env:
  - name: AWS_DEFAULT_REGION
    value: "CHANGE-ME"
```

Also it won't update existing `Cluster` object, so you must edit it manually.
