### DISCUSSION TITLE
Cannot create PodMonitor using the same name as Cluster.

### DISCUSSION THREAD

**Discussion by Magicloud** [cloudnative-pg/cloudnative-pg#4262] [Q&A]
Due to the PodMonitor created by Cluster resource via `.spec.monitoring.enablePodMonitor` could not satisfy my selectors, I created my own in the way described [here](https://cloudnative-pg.io/documentation/1.22/monitoring/). Example manifests is at the end.

But seems to me, I cannot use a PodMonitor named the same as the Cluster. The PodMonitor would be deleted immediately after applying the manifests.  After I recreated the PodMonitor, it would be deleted again at a "random" time. After setting the operator logLevel to "debug", there was still no more information than the following log. And if I renamed the PodMonitor, it did not got deleted as far as I can see.

```log
{"level":"info","ts":"2024-04-09T15:12:55Z","msg":"no orphan PVCs found, skipping the restored cluster reconciliation","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"jianxai","namespace":"default"},"namespace":"default","name":"jianxai","reconcileID":"83fa8685-4cfd-4b6f-bd6c-40d044b4f6c2","uuid":"a4531a3c-f683-11ee-b68a-9e1707788a7a"}
{"level":"info","ts":"2024-04-09T15:12:55Z","msg":"Deleting PodMonitor","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"jianxai","namespace":"default"},"namespace":"default","name":"jianxai","reconcileID":"83fa8685-4cfd-4b6f-bd6c-40d044b4f6c2","uuid":"a4531a3c-f683-11ee-b68a-9e1707788a7a"}
{"level":"info","ts":"2024-04-09T15:12:55Z","msg":"Creating new Job","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"jianxai","namespace":"default"},"namespace":"default","name":"jianxai","reconcileID":"83fa8685-4cfd-4b6f-bd6c-40d044b4f6c2","uuid":"a4531a3c-f683-11ee-b68a-9e1707788a7a","name":"jianxai-1-initdb","primary":true}
```

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jianxai
spec:
  instances: 1
  storage:
    size: 4Gi
  bootstrap:
    initdb:
      database: jianai
      owner: jianai
      secret:
        name: db-jianai

---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jianxai
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": jianai
  podMetricsEndpoints:
  - port: metrics
```

**Comment by AruPersia** [comment]
We are also awaiting the feature [Specify addtional labels for PodMonitor](https://github.com/cloudnative-pg/cloudnative-pg/pull/4438), which allows you to configure the operator to create the PodMonitor for you, including support for 'podMonitorAdditionalLabels'.

Anyway the operator must be designed to only manage and modify resources it is responsible for. It should not delete or interfere with any resources outside its own management scope.

**Reply by Magicloud** [reply]
I forgot the version I used when I opened the discussion. Now with 1.25.1, it is still there.

**Comment by SuperCoolAlan** [comment]
I have worked around this bug by exposing the metrics port via Kubernetes Service and creating a ServiceMonitor in place of the PodMonitor.

My version of CNPG:
app.kubernetes.io/version=1.24.1
helm.sh/chart=cloudnative-pg-0.22.1

**Reply by adelowo** [reply]
In case anyone needs actual documentation on this. Should be straight forward but just in case


```
---
apiVersion: v1
kind: Service
metadata:
  name: xxxxx
  namespace: services
  labels:
    cnpg.io/cluster: xxxx
spec:
  selector:
    cnpg.io/cluster: xxxx
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xxxx
  namespace: services
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: xxxx
  endpoints:
    - port: metrics
      interval: 30s
```
