### DISCUSSION TITLE
S3 SSL validation failure

### DISCUSSION THREAD

**Discussion by moondersen** [cloudnative-pg/cloudnative-pg#431] [Q&A] [answered]
Configured endpointCA to a secret with the certificate as suggested from the doc but still getting this error:

```{"level":"info","ts":1658175442.9876552,"logger":"barman-cloud-check-wal-archive","msg":"2022-07-18 20:17:22,987 [2548] ERROR: Barman cloud WAL archive check exception: SSL validation failed for https://s3url/bucketname [X509: NO_CERTIFICATE_OR_CRL_FOUND] no certificate or crl found (_ssl.c:4265)","pipe":"stderr","logging_pod":"cluster1"}```

Config:
```
  backup:
    barmanObjectStore:
      endpointCA:
        key: ca-bundle.crt
        name: ca-bundle
      destinationPath: s3://bucketname/
      endpointURL: https://s3url
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
```
Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: ca-bundle
data:
  ca-bundle.crt: |-
    xxxsafsdfzxdzfzxdfzfsdfasfasd
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
data:
  ACCESS_KEY_ID: asdfasfsdfasdfasdfasdf
  ACCESS_SECRET_KEY: asdfasfasdfasfasdfasdf
```
