### DISCUSSION TITLE
Recovery after rm -rf /var/lib/postgresql/data/pgdata

### DISCUSSION THREAD

**Discussion by godunko-mikhail** [cloudnative-pg/cloudnative-pg#4344] [Q&A] [answered]
Hi! 
I'm new to cnpg, so this question might be weird.
Let's look at the case of a simple cluster from docs

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  storage:
    size: 1Gi
```
I ran `rm -rf/var/lib/postgresql/data/pgdata` to see how failover works, and as I saw it works well, but the pod was left in an endless restart
So I'm wondering how can the pod be recovered after that?
