### DISCUSSION TITLE
IRSA support for backup in barmanObjectStore

### DISCUSSION THREAD

**Discussion by ruzickap** [cloudnative-pg/cloudnative-pg#442] [Q&A] [answered]
Hello.

Does cnpg support [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) instead using s3Credentials (`ACCESS_KEY_ID`/`ACCESS_SECRET_KEY`) for backups for AWS S3? 

```yaml
    barmanObjectStore:
...
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
```

Thank you

**Comment by sxd** [comment, marked as answer]
Hi! @ruzickap 

Short answer: yes
You need to enable the `inheritFromIAMRole` option in the `s3Credentials` section https://cloudnative-pg.io/documentation/1.16/api_reference/#s3credentials
There's a sample file here https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-backup-aws-inherit.yaml

Hope this will help you!

**Comment by ruzickap** [comment]
Thanks a lot.
I missed it in the documentation.

I used this example https://github.com/valeriodelsarto/kubecon-eu-2022-cloudnativepg-demo/blob/main/README.md and combined it `inheritedMetadata`:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-db01
  namespace: cnpg-db01
spec:
  inheritedMetadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-irsa-cnpg-db01
```
