### DISCUSSION TITLE
High cache memory usage values reported

### DISCUSSION THREAD

**Discussion by stevenmasci** [cloudnative-pg/cloudnative-pg#4489] [Q&A]
Hi all, I have the following config for CNPG with a shared buffers and resource memory limits configured. However Kubernetes is reporting cache memory usage above what I'd expect to see. 

```yaml
...
spec:
  description: postgres-cluster
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    resizeInUseVolumes: false
  imageName: ghcr.io/cloudnative-pg/postgresql:12.16
  postgresql:
    parameters:
      shared_buffers: "2048MB"
  resources:
    requests:
      memory: "8192Mi"
    limits:
      memory: "8192Mi"
  monitoring:
    enablePodMonitor: true
...
```

CloudNativePG Grafana dashboard shows the shared buffers and effective cache size, which seams correct(?).

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/7891587/27bcbfdd-09bf-48ec-9ca4-75e899873ca7)

Compute resources Grafana dashboard (created by the [prometheus-community](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)) shows high values for "Memory Usage (Cache)".

![Screenshot 2024-05-09 at 10 35 00 am](https://github.com/cloudnative-pg/cloudnative-pg/assets/7891587/c12eee8c-81ba-4909-9241-ad6b055a2700)

What is this "Memory Usage (Cache)" value referring to if not shared buffers or effective cache? Is it anything to be concerned about, will my pods run out of memory?

Any advice or direction would be greatly appreciated, thank you.
