### DISCUSSION TITLE
What is the recommended approach to enable the plpython3u extension with a customized python3 environment in cloudnative-pg postgresql images?

### DISCUSSION THREAD

**Discussion by cameronraysmith** [cloudnative-pg/cloudnative-pg#4510] [Q&A] [answered]
I have reviewed this [post regarding the creation of custom postgresql container images for CloudNativePG](https://cloudnative-pg.io/blog/creating-container-images/). I have also seen https://github.com/cloudnative-pg/cloudnative-pg/issues/3672, where it is implied that others are using cloudnative-pg with the [plpython3u](https://www.postgresql.org/docs/current/plpython.html) extension.

I understand one should not plan to update the python environment in the immutable default images. However, it is also clear that these images already include [the installation of custom python libraries](https://github.com/cloudnative-pg/postgres-containers/blob/cdc86b77be5ac72bbce39136a5e56e140d2aad2a/Debian/16/bookworm/Dockerfile#L50-L52), [barman in particular](https://github.com/cloudnative-pg/postgres-containers/blob/main/Debian/requirements.in), as part of the build process.

Would the most highly recommended approach to enabling and working with plpython3u with custom python dependencies be to

1. maintain a fork of https://github.com/cloudnative-pg/postgres-containers with customized [Debian/requirements.in](https://github.com/cloudnative-pg/postgres-containers/blob/cdc86b77be5ac72bbce39136a5e56e140d2aad2a/Debian/requirements.in) from which customized images can be built and sourced as a custom [(Cluster)ImageCatalog](https://cloudnative-pg.io/documentation/current/image_catalog/#postgresql-container-images)?

2. More simply, as outlined in [the post](https://cloudnative-pg.io/blog/creating-container-images/), one could build an image from a Dockerfile like

```Dockerfile
FROM ghcr.io/cloudnative-pg/postgresql:16.2-bookworm

USER root

COPY requirements.txt /

RUN set -xe; \
	pip3 install --break-system-packages --no-deps -r requirements.txt;

USER 26
```

build/push

```bash
docker build -t postgresql-plpython3u:16 .
docker push ghcr.io/userorg/postgresql-plpython3u:16 
```

and, by analogy to the manner in which it is [recommended to create PostGIS clusters](https://cloudnative-pg.io/documentation/current/postgis/#create-a-new-postgresql-cluster-with-postgis), use something like the following to create a cloudnative-pg Cluster resource with plpython3u-enabled database(s)

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: plpython3u-cluster-example
spec:
  instances: 3
  imageName: ghcr.io/userorg/postgresql-plpython3u:16
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION plpython3u;

  storage:
    size: 1Gi
```

...

Or, is there another recommendation for working with cloudnative-pg clusters whose database(s) require(s) plpython3u postgresql functions?
