### DISCUSSION TITLE
Using locales

### DISCUSSION THREAD

**Discussion by kamikaze** [cloudnative-pg/cloudnative-pg#4813] [Q&A]
Hi. How can I set:

```
  bootstrap:
    initdb:
      ...
      localeCollate: "lv_LV.utf8"
      localeCType: "lv_LV.utf8"
```

raises an error:

```
initdb: error: invalid locale name "lv_LV.utf8"
```

while cloudnative image has:

```
$ locale -a
C
C.UTF-8
en_US.utf8
POSIX
```

I saw there are no locales and nobody gonna add them to the image. But what's the point of having locale settings for initdb if we can't use them?
