### DISCUSSION TITLE
Error while bootstrapping data directory

### DISCUSSION THREAD

**Discussion by samhamilton** [cloudnative-pg/cloudnative-pg#493] [Q&A] [answered]
I am trying to setup a basic test database using Microk8s with hostpath-storage but getting an unclear (to me) `Bus error` message.

1) 
`microk8s.kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.16/releases/cnpg-1.16.0.yaml`

2)
```
microk8s.kubectl get deploy -n cnpg-system cnpg-controller-manager
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cnpg-controller-manager   1/1     1            1           15m
```

3) 
`microk8s.kubectl apply -f app.yaml` using the following config copied from your docs 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-initdb
spec:
  instances: 3

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 1Gi

---
apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth
```

This gives the following error on the pod
```
Defaulted container "initdb" out of: initdb, bootstrap-controller (init)
{"level":"info","ts":1657601898.3462715,"msg":"Creating new data directory","logging_pod":"cluster-example-initdb-1","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"info","ts":1657601899.735596,"logger":"initdb","msg":"The files belonging to this database system will be owned by user \"postgres\".\nThis user must also own the server process.\n\nThe database cluster will be initialized with locales\n  COLLATE:  C\n  CTYPE:    C\n  MESSAGES: en_US.utf8\n  MONETARY: en_US.utf8\n  NUMERIC:  en_US.utf8\n  TIME:     en_US.utf8\nThe default text search configuration will be set to \"english\".\n\nData page checksums are disabled.\n\ncreating directory /var/lib/postgresql/data/pgdata ... ok\ncreating subdirectories ... ok\nselecting dynamic shared memory implementation ... posix\nselecting default max_connections ... 20\nselecting default shared_buffers ... 400kB\nselecting default time zone ... Etc/UTC\ncreating configuration files ... ok\nrunning bootstrap script ... ","pipe":"stdout","logging_pod":"cluster-example-initdb-1"}
{"level":"info","ts":1657601899.735628,"logger":"initdb","msg":"Bus error (core dumped)\nchild process exited with exit code 135\ninitdb: removing data directory \"/var/lib/postgresql/data/pgdata\"\n","pipe":"stderr","logging_pod":"cluster-example-initdb-1"}
{"level":"error","ts":1657601899.7356534,"msg":"Error while bootstrapping data directory","logging_pod":"cluster-example-initdb-1","error":"error while creating the PostgreSQL instance: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:124\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:88\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/proc.go:255"}
Error: error while creating the PostgreSQL instance: exit status 1
```

The pvc is showing:
```
microk8s.kubectl get pvc -A
NAMESPACE   NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
default     cluster-example-initdb-1   Bound    pvc-166d897f-4c9d-49cb-aa13-2290a892aa2a   1Gi        RWO            microk8s-hostpath   6m15s
```

Thanks
Sam
