### DISCUSSION TITLE
"no target backup found" while trying to recover from backup.

### DISCUSSION THREAD

**Discussion by Magicloud** [cloudnative-pg/cloudnative-pg#518] [Q&A] [answered]
The backup was previously generated by CNPG. By mistake, I removed that cluster. Now I can see the backup files in S3://cnpg-backup/mydb-jr/mydb-jr-db/wals and base. But the pods just terminated on error. Logs shows:

```
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":1659544033.1327655,"msg":"Recovering from external cluster","logging_pod":"mydb-jr-db-1","sourceName":"clusterBackup"}
{"level":"error","ts":1659544033.9317522,"msg":"Error while restoring a backup","logging_pod":"mydb-jr-db-1","error":"no target backup found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:69\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func1\n\tinternal/cmd/manager/instance/restore/cmd.go:48\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
```

Remove the `recoveryTarget` did not help. I used a ScheduledBackup to generate those base/wals.

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydb-jr-db
spec:
  instances: 2
  storage:
    size: 4Gi

  superuserSecret:
    name: mydb-jr-db-su

  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        targetTime: "2022-08-03 15:22:05.00000+00"

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://cnpg-backup/mydb-jr/
        wal:
          maxParallel: 8
        s3Credentials:
          accessKeyId:
            name: s3-cnpg-backup-full-access
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: s3-cnpg-backup-full-access
            key: ACCESS_SECRET_KEY
```

**Comment by sxd** [comment]
Hi! @Magicloud 

Did you took a backup before the delete? this sounds pretty much like you didn't have a backup, the files you can see in the directory `wals/` are just that, WAL files, you need a previous backup to apply those WAL files, otherwise, you will not be able to fully restore a database.

Regards

**Reply by Magicloud** [reply]
I had. I have ScheduledBackup every hour, in `S3://cnpg-backup/mydb-jr/mydb-jr-db/base`. I can see the backup list and some info, by barman CLI. But I could not get recovery work.

**Comment by leonardoce** [comment, marked as answer]
Hi!

What was the name of the cluster you are trying to restore? If the name was `mydb-jr` you need to use the `serverName` option inside the external clusters section, and to remove that from the `destinationPath`, something like:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydb-jr-db
spec:
  instances: 2
  storage:
    size: 4Gi

  superuserSecret:
    name: mydb-jr-db-su

  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        targetTime: "2022-08-03 15:22:05.00000+00"

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://cnpg-backup/
        serverName: mydb-jr
        wal:
          maxParallel: 8
        s3Credentials:
          accessKeyId:
            name: s3-cnpg-backup-full-access
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: s3-cnpg-backup-full-access
            key: ACCESS_SECRET_KEY
```
