### DISCUSSION TITLE
Prevent PVC Deletion when Cluster deleted

### DISCUSSION THREAD

**Discussion by kholisrag** [cloudnative-pg/cloudnative-pg#5253] [Q&A]
Hi, is there a way to prevent PVC Deletion when kind `Cluster` (postgresql.cnpg.io/v1 ) deleted?
we need this kind of feature, when somehow our Cluster Manifest  managed in GitOps / Argocd and someone do the replace sync, to avoid cluster re-creation from scratch.

Thanks!

**Comment by mixxor** [comment]
Searching for the same solution, you can always patch the PV after deploying the Cluster. 
You could utilize Argo Events in your pipeline or a Kyverno rule to automate this process. 

Alternatively, you can modify your StorageClass to set `reclaimPolicy: Retain` by default, which will ensure that all PVs created by that StorageClass are retained even if the PVCs are deleted.

**Comment by devops72-sre** [comment]
Hi guys, If you get any update pls do post.

**Comment by zohairraza** [comment]
Hi Everyone
I also have similar question, I can see that the PVs are retained after cluster deletion but I can not figure out how to re use the same PVs when re-creating the cluster

for example I want to use these PVs again while recreating cluster:
pvc-15ed48c9-cf71-4d01-b780-6c917234de79   10Gi       RWO            Retain           Released    cnpg-system/pg-cluster-1    ebs-sc         <unset>                          6d19h   Filesystem 
pvc-168b4345-5328-44ae-bf41-30c77439f94a   10Gi       RWO            Retain           Released    cnpg-system/pg-cluster-2    ebs-sc         <unset>                          6d19h   Filesystem
pvc-6afc39a6-cc2a-4c52-b379-0e6c870830e6   10Gi       RWO            Retain           Released    cnpg-system/pg-cluster-3    ebs-sc         <unset>                          6d19h   Filesystem

I tried to patch the pod but it doesnt allow and I think another problem will be the initdb. There must be a way to re-use an old volume and it should already skip initdb process.

Not sure if this already exists but I couldnt find the information.

Please let me know if anyone knows
Thanks

**Reply by nadiamoe** [reply]
I'd also love for CNPG to offer an automated way of reusing an existing PV (i.e. skipping initdb). I personally have a manual procedure to reuse a PVC, but there's no way to skip the initidb reinitialization: The initdb code will unconditionally reinitialize the database if the associated `Cluster` CR does not have a `status` field.

My manual procedure is as follows:
1. In the (existing) PV's `claimRef`, keep the PVC name/namespace, but remove the `uid` and `resouceVersion`. This will cause this PV to be rebound to a PVC with the matching name/namespace when it is created.
1. Recreate the `Cluster` object with `instances: 1` and a `initdb` type bootstrap, **reusing the same credentials**. If different credentials are used, further manual intervention is required.
1. Hibernate the new cluster, as old credentials are persisted in the PV.
1. Manually mount the PVC for the primary and inspect the `data` directory. There should be a `pgdata` directory, containing the new empty database created by initdb, and a `pgdata_20241103T132141Z` (or similar) directory containing the old contents of `pgdata`. Rename the timestamped directory to `pgdata` and de-hibernate the cluster.

**Comment by zig** [comment]
Could this  help ? The command `kubectl cnpg destroy` has  a `--keep-pvc` flag. Apparently it removes `metadata.ownerReferences` .

Cf. https://cloudnative-pg.io/documentation/1.25/kubectl-plugin/

However, from testing, removing metadata.ownerReferences on a still running cluster will confuse the operator which won't be able to update the state of instances anymore. 

If the aim is to protect from accidental deletion the PVCs of a running cluster, adding a custom finalizer on the PVCs might be a way to go, it does not seem to interfere with the operator and ensure PVCs won't be finalized as soon as the Cluster CR is deleted. These PVCs will then be in a kind of zombie state (no way to use them as is, because they have a deletion timestamp) but their underlying PV will be kept so it will be possible to recreate new working PVC from them.

**Comment by ghost** [comment]
I'd love an answer to this as well.  All I want to be able to do is keep the PV and remount it if my Cluster resource is deleted and then recreated with the exact same credentials and configurations.  God forbid you accidentally delete your Cluster resource and then suddenly all of your data is gone too?  This could be a real issue in my customers' production environments.

**Reply by drewhemm** [reply]
I've hit this issue twice in the space of two weeks. Making changes to ArgoCD caused the application to momentarily delete and re-deploy, and that is enough to lose the PVCs and the data. This makes CNPG unsuitable for hosting anything other than throwaway data. Even if the PVCs are patched with custom finalizers, even if the PVs use a storage class that is configured with `retain`, it looks like there is no simple way for a new cluster to resume from where an old one left off. If there was, this would not be a huge issue, as we would only face a few minutes of downtime. As it stands, we have disaster by design. 

Compare this to AWS RDS, which has a simple mechanism for deletion protection:

https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-rds-now-provides-database-deletion-protection/

**Reply by sarendipitee** [reply]
@drewhemm I've ran into this exact same situation as you and I'm losing sleep over it haha. Did you ever figure out a solution?

**Comment by sxd** [comment]
Hello,

I'm may sound a bit too hard on this but, if you delete something, why are you expecting that just part of isn't deleted it? For me is kind of hard to understand these can of mixed behavior, and also, there's tools for that kind of things, we provide the hibernation (for these situations that I'm not fully agree) and you can have expected behavior, but also, have you read the documentation? now that someone mentioned ArgoCD, probably is something we can include and work with ArgoCD to improve this? because if ArgoCD is deleting stuff there's nothing we can do here.

Regards,

**Reply by drewhemm** [reply]
I'll run through a few scenarios with different settings for ArgoCD's related options and report back:

https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-resource-deletion
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#resource-deletion-with-confirmation
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#resource-pruning-with-confirmation

**Reply by ChristianCiach** [reply]
Please keep in mind that a StatefulSet (by default) also doesn't delete the PVCs when the StatefulSet gets deleted. A new StatefulSet will happily re-use an existing PVC as long as the name matches the volumeClaimTemplate of the StatefulSet. This is done to prevent accidental data loss, according to the kubernetes documentation. 

I think a cnpg `Cluster` object is, in concept, very similar to a StatefulSet. In fact, other database operators often utilise a StatefulSet to spawn the database pods. (I am not saying that's a good thing. I think CNPG does this much better by managing the pods directly. I just want to demonstrate the close relation between a Cluster and a StatefulSet resource). 

Viewing it from this perspective, I was surprised to see that CNPG deletes all data of a cluster when somebody or something accidentally deletes the Cluster object. After this happened to us, I was absolutely sure that there *has to be* a way to opt-out from the automatic PVC deletion, but here we are :) 

> For me is kind of hard to understand these can of mixed behavior, 

The same could be said about a StatefulSet. But Kubernetes made the conscious decision to *not* automatically delete the PVCs owned by a StatefulSet, because the risk of data loss just was too high. They recently made PVC deletion opt-in though.

**Reply by sxd** [reply]
I think we should be more integrated with other tools rather than blame all on the operator, there's tools to prevent this kind of "accidental deletes" which is something that by definition shouldn't happen, if you have that kind of deletions, you have another problem, like properly managing the security and integrity of your entire cluster, but that's another issue, and there's tools to prevent that. On the other side, I was recently (yesterday) aware that we didn't have any inclusion with ArgoCD, which is on the work within a PR on the ArgoCD repo, so, I think we should go with the integration with other tools on the environment to enrich the environment of Cloud Native tools.

With that being said, words apart, if you allow someone to delete something, well, except that things may go wrong.

Regards,

**Reply by ChristianCiach** [reply]
> I think we should be more integrated with other tools

Maybe, but I think this is mostly unrelated. I don't really care who or what may delete the Cluster object. I just want the expected StatefulSet behaviour, which means that the PVCs are retained even when the workloads are deleted. There is not a single built-in kubernetes workload resource that (by default) deletes the (possibly dynamically provisioned) PVCs when the associated workload resources are removed. This behavior is exclusive to CNPG.

**Reply by zig** [reply]
Could we imagine that the operator somehow ignore the deletionTimestamp if there's at least one finalizer on the CR object ? This way, we could protect a CNPG cluster by adding a custom finalizer on it.

**Reply by drewhemm** [reply]
First result: I patched the cluster with a [finalizer](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/):

```shell
kubectl patch cluster postgresql-cluster --type merge -p '{"metadata":{"finalizers": ["deletion-protection.cloudnative-pg.io"]}}' 
```

I then marked the ArgoCD app for deletion. The cluster resource was not automatically deleted, but the pods and PVCs were. So this still resulted in a complete data loss. The finalizer would need to be added to the pods and PVCs, but the Helm chart does not expose any values for this, so will need to be tested out-of-band. I will test with the k8s native finalizers before moving onto the ArgoCD specific features.

**Reply by zig** [reply]
It is probably necessary to also remove the ownerReferences on the PVC, but the operator might put them back ? Could we imagine an option in the spec of the cluster CR to require the operator to not set ownerReferences on the PVC ?

**Reply by drewhemm** [reply]
This is what I have so far:

```yaml
  - apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: cnpg-deletion-protection
    spec:
      emitWarning: true
      mutateExistingOnPolicyUpdate: true
      rules:
        - name: cluster-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - Cluster
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=confirm
                finalizers:
                  - cloudnative-pg.io/deletion-protection
            targets:
              - apiVersion: postgresql.cnpg.io/v1
                kind: Cluster
                name: '{{ `{{ request.object.metadata.name }}` }}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
        - name: pod-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - Pod
                  selector:
                    matchLabels:
                      cnpg.io/podRole: instance
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=confirm
                finalizers:
                  - cloudnative-pg.io/deletion-protection
            targets:
              - apiVersion: v1
                kind: Pod
                name: '{{ `{{ request.object.metadata.name }}` }}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
        - name: pvc-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - PersistentVolumeClaim
                  selector:
                    matchLabels:
                      cnpg.io/pvcRole: PG_DATA
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=confirm
                finalizers:
                  - cloudnative-pg.io/deletion-protection
            targets:
              - apiVersion: v1
                kind: PersistentVolumeClaim
                name: '{{ `{{ request.object.metadata.name }}`}}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
```

I am applying this as an additional Kyverno policy, hence why the whole manifest is a list item. For some reason, the cluster mutation does not get triggered by the Background Controller for me, only when passing through the Admission Controller. The pod and PVC mutations do get triggered by the Background Controller. 

I need to do some more testing, but this should prevent the accidental deletions by ArgoCD. The finalizers are an extra touch for belt and braces. Even if someone agrees to let ArgoCD delete the resources, the finalizers will need to be removed before the cluster, pods and PVCs are removed. Whether a final backup could be taken at that point, either with native PG tools, or with a PVC tool like Velero remains to be seen.

**Reply by drewhemm** [reply]
This is heading in the right direction. When simulating an 'accidental' ArgoCD deletion, the cluster, pods and PVCs don't just immediately disappear. Because the cluster owns resources such as the services and secrets, the Postgres cluster remains accessible and useable. This means a final backup can be taken and total data loss is not possible without explicit human intervention. 

This is similar to the approach taken by Rook Ceph. You have to jump through several hoops in order to delete all the data:

https://rook.io/docs/rook/latest/Getting-Started/ceph-teardown/

There is no possibility of just 'pressing a button' or pushing a bad commit and losing everything in a multi-node cluster. 

I think this journey of exploration does raise the question though as to whether this is the right approach, or whether I should just look for a different operator that uses Kubernetes StatefulSets and therefore total data loss is mitigated against in the same way it is for all our other stateful applications. Being able to simply re-deploy and app and have it effectively resume with existing storage is a highly valuable benefit of StatefulSets.

I am genuinely curious: what are the benefits to spinning up raw pods, versus using a StatefulSet? Why have CNPG (and other operators) gone down that route?

**Reply by drewhemm** [reply]
This is my Kyverno policy now:

```yaml
  - apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: cnpg-deletion-protection
    spec:
      emitWarning: true
      mutateExistingOnPolicyUpdate: true
      rules:
        - name: cluster-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - Cluster
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=confirm
                finalizers:
                  - cloudnative-pg.io/deletion-protection
            targets:
              - apiVersion: postgresql.cnpg.io/v1
                kind: Cluster
                name: '{{ `{{ request.object.metadata.name }}` }}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
        - name: pod-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - Pod
                  selector:
                    matchLabels:
                      cnpg.io/podRole: instance
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=false
            targets:
              - apiVersion: v1
                kind: Pod
                name: '{{ `{{ request.object.metadata.name }}` }}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
        - name: pvc-deletion-protection
          match:
            any:
              - resources:
                  kinds:
                    - PersistentVolumeClaim
                  selector:
                    matchExpressions:
                      - key: cnpg.io/pvcRole
                        operator: In
                        values:
                          - PG_DATA
                          - PG_WAL
          mutate:
            patchStrategicMerge:
              metadata:
                annotations:
                  argocd.argoproj.io/sync-options: Delete=false
                finalizers:
                  - cloudnative-pg.io/deletion-protection
            targets:
              - apiVersion: v1
                kind: PersistentVolumeClaim
                name: '{{ `{{ request.object.metadata.name }}`}}'
                namespace: '{{ `{{ request.namespace }}` }}'
          skipBackgroundRequests: false
```

I realised I should not use a finalizer on the pods, as that prevented the operator from managing their lifecycles. I also added deletion protection for the WAL PVCs. I added twice-daily `barmanObjectStore` backups to S3, so we have disaster recovery in place. I also added a once-daily PVC snapshot. I have yet to test the recovery process, but will do so ASAP.

I did some reading up on CNPG vs the Bitnami PostgreSQL Helm Chart and there are clear benefits to the former. With this policy in place and with the automated backups, I am much more comfortable trusting CNPG with our data!

I still haven't worked out why Kyverno does not apply the deletion protection to existing `cluster` resources with the background controller. That requires further investigation. For now, a workaround is to apply a trivial, non-breaking change to the cluster that prompts the admission controller to do its thing. I added a `foo: bar` label to the cluster and then removed it. No workaround is needed if the policy is already in place _before_ a new cluster is created.

**Reply by Stevenpc3** [reply]
we have been using bitnami postgresql-ha for years now and are moving off it.  The charts are not great even with modifications.  Split-brain happens and other issues.  We have been planning on moving to CNPG for a year or so now and are forced to move anyway because of the recent bitnami cost changes and only supporting latest unless you pay.

The pvc "disappearing" is a major concern for us.  We also are mid switch to argocd which is an extra concern.  We also use helm and we also have multi-node clusters and many clusters and we cannot use the cnpg plugin... so this is getting more and more bleak.

We also have been searching for a way to ensure it stays... backups are fine, but devs like to teardown and reattch.  It is still manageable, but it really seems odd that the cluster deployment doesn't have a "keep pvc" flag.  The plugin code for keeping the pvc literally just adjusts the references, labels, and annotations https://github.com/cloudnative-pg/cloudnative-pg/blob/main/internal/cmd/plugin/destroy/destroy.go#L78

**Comment by AT92** [comment]
I found a way, to not delete the data by using a custom storage class with the retain policy. However, I cannot find a way, that a new postgres cluster reuses the existing volumes, instead of creating new volumes

**Comment by lucasvmiguel** [comment]
I understand if the operator cannot automate this situation of recovering from an existent PV (with `retain` policy) in case someone wrongly delete a cluster. However, it'd be super useful to have some official documentation (maybe in [troubleshooting section](https://cloudnative-pg.io/documentation/1.26/troubleshooting/)) of how to recover from this scenario if that happens.

I'm more than happy to raise a PR explaining how to recover from that, it's just unclear to me what's the best/correct way. Is @nadiamoe [way](https://github.com/cloudnative-pg/cloudnative-pg/discussions/5253#discussioncomment-12651012) the correct approach?

**Reply by lucasvmiguel** [reply]
Thanks to @nadiamoe, I was also able to recover a cluster following these steps:
1. deleted field `.claimRef` from PV that was retained after the cluster deletion
2. created a PVC with `volumeName={{PV_NAME}}`
3. created a `VolumeSnapshot` with this new PVC
4. create a new cluster with the following config:
```
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: {{VOLUME_SNAPSHOT_NAME}}
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
```

After that, the cluster was up and running without any issues. I'll raise a PR to add these to the [troubleshooting doc page](https://cloudnative-pg.io/documentation/1.26/troubleshooting/) as I think that can be useful for someone in the future.
