### DISCUSSION TITLE
Full recovery cluster from backup

### DISCUSSION THREAD

**Discussion by thiagogabriell** [cloudnative-pg/cloudnative-pg#5309] [General]
Hi, I have a problem to create a new cluster from backup.

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-ha-postgres
  namespace: core
spec:
  storage:
    size: 15Gi
  bootstrap:
    recovery:
      source: app-ha-postgres-periodically-20240817000000
      recoveryTarget:
        targetTime: "2024-08-16 20:30:00.00000+00"
  externalClusters:
    - name: app-ha-postgres-periodically-20240817000000
      barmanObjectStore:
        destinationPath: gs://cnpg-app-ha-postgres-us/app-ha-postgres/
        googleCredentials:
          gkeEnvironment: true
        wal:
          maxParallel: 8
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: postgres-backup@testenv.iam.gserviceaccount.com
  walStorage:
    size: 15Gi
    pvcTemplate:
      resources:
        requests:
          storage: 15Gi

``` 
I try to recovery cluster, with yaml, but always get ,"error":"no target backup found".

```
17-8-2024 14:33:59.096
{"level":"error","ts":"2024-08-17T17:33:59Z","msg":"Error while restoring a backup","logging_pod":"app-ha-postgres-1-full-recovery","error":"no target backup found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:89\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:267"}
17-8-2024 14:33:58.286
{"level":"info","ts":"2024-08-17T17:33:58Z","msg":"Recovering from external cluster","logging_pod":"app-ha-postgres-1-full-recovery","sourceName":"app-ha-postgres-periodically-20240817000000"}
``` 

The backup and wal files are in the bucket:

```
gsutil ls -r gs://cnpg-app-ha-postgres-us/app-ha-postgres/
gs://cnpg-app-ha-postgres-us/app-ha-postgres/:

gs://cnpg-app-ha-postgres-us/app-ha-postgres//base/:

gs://cnpg-app-ha-postgres-us/app-ha-postgres//base/20240816T201108/:
gs://cnpg-app-ha-postgres-us/app-ha-postgres//base/20240816T201108/backup.info
gs://cnpg-app-ha-postgres-us/app-ha-postgres//base/20240816T201108/data.tar

gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/:

gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/:
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000001
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000002
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000002.00000028.backup
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000003
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000004
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000004.00000028.backup
gs://cnpg-app-ha-postgres-us/app-ha-postgres//wals/0000000100000000/000000010000000000000005
``` 

What am I doing wrong?
