### DISCUSSION TITLE
How to use AES256 encryption for backups?

### DISCUSSION THREAD

**Discussion by NiklasRosenstein** [cloudnative-pg/cloudnative-pg#5315] [Q&A]
I'm struggling to figure out how the AES256 encryption for data/wal backups work, because I can't find the place where the encryption key would be specified. Could I be pointed into the right direction for passing that secret? And will it be encrypted on the client side or make use of S3 SSE-C?

Thank you!

**Comment by maxpain** [comment]
The encryption option will just inform the S3 bucket which method to use to store the data encrypted. Encrypted data cannot be read by any other AWS user but the owner of the bucket. Barman cloud does not encrypt any object before sending it to S3, it just asks the bucket to store them encrypted if S3 has been properly configured.

**Reply by tcurdt** [reply]
Relying on server side encryption is ... awkward.
It's not really acceptable for many use cases.

CNPG has no support at all for client side encrypted backups?

**Reply by NiklasRosenstein** [reply]
I get that barman just instructs the server to do encryption, but does it mean it only supports KMS encryption? I was asking specifically about SSE-C (i.e. the client provides a secret for the server to use for encryption). 🙁

**Comment by Gerharddc** [comment]
I am trying to use https://github.com/Intrinsec/s3proxy/tree/main as a proxy to encrypt backups before they get sent to the remote object store but have not had any luck yet. It would be great if Barman could just natively encrypt backups with a given key though.

**Reply by tcurdt** [reply]
It seems `wal-g` supports this https://github.com/wal-g/wal-g ...but I don't think cnpg supports wal-g.

**Reply by Gerharddc** [reply]
Ok so I finally managed to get this working with the following s3proxy.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      volumes:
        - name: ca-certificates
          hostPath:
            path: /etc/ssl/certs
      containers:
        - name: s3proxy
          image: ghcr.io/intrinsec/s3proxy
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs
              readOnly: true
          args:
            - --no-tls
            - --level=-4
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: access_key_secret
            - name: S3PROXY_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: encrypt_key
            - name: S3PROXY_HOST
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: endpoint
            - name: S3PROXY_DEKTAG_NAME
              value: s3proxy
          ports:
            - containerPort: 4433
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4433
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4433
              scheme: HTTP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy
spec:
  type: ClusterIP
  ports:
    - port: 4433
      targetPort: 4433
  selector:
    app: s3proxy
```

Then it is possible to connect from CNPG with:

```
  backup:
    barmanObjectStore:
      destinationPath: "s3://zammad-postgres/"
      endpointURL: http://s3proxy:4433
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: access_key_id
        secretAccessKey:
          name: s3-creds
          key: access_key_secret
```

**Reply by Gerharddc** [reply]
Ah damn turns out this does not fully work due to multipart uploads not being supported as per https://github.com/Intrinsec/s3proxy/blob/1518dd6f46dc63beb3c5041bdc7b59da013e3df7/s3proxy/internal/router/handler.go#L172. Basically it fails when you try to do a full backup

**Reply by krisztiansala** [reply]
@Gerharddc what did you end up using? Do you think this proxy would be a better solution? https://github.com/gaul/s3proxy

**Reply by Gerharddc** [reply]
@krisztiansala in the end I just gave up and used a storage provider that provides encrypted buckets. Not ideal because it means I have to trust them, but yeah

**Comment by playments-admin** [comment]
Do i understand it right that there is no built-in way to encrypt data before sending to S3?
We have CEPH (DigitalOcean uses it for its S3 service)

**Comment by cometship** [comment]
EDIT: I found out that the pg_backup_(start|stop) commands have to run in the same (psql) session, else they basically do nothing. So the below workaround is even less useful.

I have found a "workaround" using Velero and its built-in client-side encryption (using Kopia):

### Setup

_Prerequisites: Setup Volume Snapshots for your CSI and BackupStorageLocation for Velero._

Recommendations:
- Enable SSE-C for BackupStorageLocation
- Set a strong repo password **before** doing the first backup by editing the `velero-repo-credentials` secret

### Backup

1. Add Velero backup hooks to taint DB:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    post.hook.backup.velero.io/command: '["/bin/bash", "-c", "psql -U postgres -c \"SELECT pg_backup_stop(true);\""]'
    pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "psql -U postgres -c \"SELECT pg_backup_start(quote_literal($EPOCHSECONDS), true);\""]'
[...]
```

_Don't forget to add/adapt `INHERITED_ANNOTATIONS` in your cnpg config._
E.g. using the cnpg helm chart:
```yaml
config:
  data:
    INHERITED_ANNOTATIONS: "*.hook.backup.velero.io/command"
```
2. Create backup (or schedule) of the DB:
`velero --kubeconfig kubeconfig backup create <db-backup-name> --include-resources pvc,pv --include-namespaces <namespace> --selector role=replica --snapshot-move-data`

### Restore

1. Now to restore (for example to a new namespace):
`velero --kubeconfig kubeconfig restore create <restore-name> --from-backup <backup-name> --namespace-mappings old-ns:new-ns`

2. And then (re-)create/restore the Cluster like so:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
  namespace: new-ns
spec:
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: <restore-db-pvc-name>
          kind: PersistentVolumeClaim
          apiGroup: ""
        walStorage:
          name: <restore-db-wal-pvc-name>
          kind: PersistentVolumeClaim
          apiGroup: ""
[...]
```

---

I tested it and it seems to work. But **use at your own risk**. Hopefully this is helpful for somebody in the meantime.
