### DISCUSSION TITLE
Hostname to Configure in Client application

### DISCUSSION THREAD

**Discussion by BalaMuralibi** [cloudnative-pg/cloudnative-pg#5394] [Q&A]
Hi,

I am testing postgres & pooler to set as backend for apache airflow. I need airflow to connect through pooler to postgres cluster. And following is the configuration 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster
  namespace: airflow
spec:
  instances: 1

  bootstrap:
    initdb:
      database: airflow
      owner: airflow     
      encoding: 'UTF8'

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 16
  storage:
    storageClass: storageclass
    size: 200Gi
  
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all    
    pg_hba:
      - host all all samehost trust
      - local all all trust
      - host airflow airflow ip/16 trust
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pgpooler
  namespace: airflow
spec:
  cluster:
    name: pgcluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"      
    pg_hba:
      - host all all samehost trust
      - local all all trust
      - host airflow airflow ip/16 trust 


``` 

I would like client app (apache airflow) connect to airflow database as airflow user with autogenerated password (by bootstrap spec) or without using password (see pg_hba config to allow trusted connection based on ip).

Currently when i use connection as 
Conn1.**postgresql://airflow:@pgcluster-rw.airflow:5432/airflow** my airflow is working fine Conn2.**postgresql://airflow:@pgpooler.edwairflow:5432/airflow** airflow is not responding.

Question- If i use conn1 , will my airflow connections are automatically pooled through pgbouncer ?
