### DISCUSSION TITLE
LDAP Configuration

### DISCUSSION THREAD

**Discussion by dspeck1** [cloudnative-pg/cloudnative-pg#540] [Q&A] [answered]
Getting a kubernetes validation error when trying to apply ldap config `error: error validating "cnpg-ldap-new-image4.yaml": error validating data: ValidationError(Cluster.spec.postgresql.parameters.ldap): invalid type for io.cnpg.postgresql.v1.Cluster.spec.postgresql.parameters: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`

Here is the config with info redacted on OU and domain.  Any input on why this may not be working.  The odd thing is sometimes the operator will take the configuration, but most times it does not.  Made sure everything is spaced and not tabbed.
```
  postgresql:
    parameters:
      ldap:
        bindAsAuth:
          prefix: 'uid='
          suffix: ',ou=Accounts,dc=test,dc=test,dc=edu'
        port: '636'
        scheme: ldaps
        server: ldap.test.com
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      shared_buffers: 16GB
```

If turn off validation get this error admission webhook. 

```
for: "cnpg-ldap-new-image4.yaml": admission webhook "mcluster.kb.io" denied the request: json: cannot unmarshal object into Go struct field PostgresConfiguration.spec.postgresql.parameters of type string
```

**Comment by leonardoce** [comment, marked as answer]
I think the example we include into our documentation is not correct. As you can see here: https://github.com/cloudnative-pg/cloudnative-pg/blob/71cbf052e73d5b1e948af7c31e4df955a290c1ff/api/v1/cluster_types.go#L609 the "ldap" stanza is not inside `parameters` but directly under `postgresql`.

And **port** is a number and not a string. Given that, can you try this?

```
  postgresql:
    ldap:
      bindAsAuth:
        prefix: 'uid='
        suffix: ',ou=Accounts,dc=test,dc=test,dc=edu'
      port: 636
      scheme: ldaps
      server: ldap.test.com
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      shared_buffers: 16GB
```
