### DISCUSSION TITLE
Update manifest Cluster

### DISCUSSION THREAD

**Discussion by mnasruul** [cloudnative-pg/cloudnative-pg#5490] [Q&A]
Hello, If I update the Cluster manifest from apiVersion: postgresql.cnpg.io/v1, for example I change the initial spec.instances from 2 to 3, will it affect the Cluster that is already running?
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-pgsql-keycloak
spec:
  instances: 2
```
  to
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-pgsql-keycloak
spec:
  instances: 3
  ```

I just gave an example, but my question is if I change the field in the spec, will there be a problem with my Postgresql Cluster?
