### DISCUSSION TITLE
No instance is created when applying Cluster manifest

### DISCUSSION THREAD

**Discussion by re0udjat** [cloudnative-pg/cloudnative-pg#5562] [Q&A]
Hi folks,

I have a problems when creating Cluster with cloudnative-pg. I installed cloudnative-pg Operator with Operator Framework by creating and applying two manifest:

**operatorgroup.yaml:**
```yaml
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: postgresql-og
  namespace: postgresql
spec:
  targetNamespaces:
    - default
```
**subscription.yaml:**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql
  namespace: postgresql
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
```

After applying above manifest files, an operator pod is running:
```console
NAME                                       READY   STATUS    RESTARTS   AGE
cnpg-controller-manager-5769c6f79b-h77nb   1/1     Running   0          29m
```
Then, I define a simple Cluster manifest as the following:

**simple-cluster.yaml:**
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql
spec:
  instances: 2
  imageName: postgres:16.4
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
```

After applying this manifest, a cluster is created but it does not create any instance:
```console
NAME                 AGE   INSTANCES   READY   STATUS   PRIMARY
postgresql-cluster   3s
```

I also checked logs inside operator Pod and see this warning:
```console
Warning  FailedToRetrieveImagePullSecret  3m30s (x26 over 31m)  kubelet            Unable to retrieve some image pull secrets (cnpg-pull-secret); attempting to pull the image may not succeed.
```

Did I miss any configuration or steps when installing cloudnative-pg Operator and Cluster?

**Comment by re0udjat** [comment]
I have found that the Subscription must be installed into operators namespace. I have remove operatorgroup manifest and change file  **subscription.yaml** to this:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: operators
spec:
  channel: stable-v1
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
```

Then the Pod will be created :D
