### DISCUSSION TITLE
How to configure with linkerd?

### DISCUSSION THREAD

**Discussion by 99hops** [cloudnative-pg/cloudnative-pg#5633] [Q&A] [answered]
Hello friends, anyone had a problem when recreating cluster from externalClusters where the -join operation is stuck at the end (logger":"initdb","msg":"syncing data to disk ... ok\n","pipe":"stdout","logging_pod":"postgresql-1-import"}) and requires manual pod delete? It makes me do the same for all 3 -import instances then everything works fine but I am 100% sure this was working on it's own before. Now using 0.22.0 chart with cloudnative-pg:1.24.0

I see the "problem" is gone with adding this annotation

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      linkerd.io/inject: disabled <----- HERE
  instances: 3
```

I suspect some linkerd annotations are needed like `config.linkerd.io/opaque-ports`

**Comment by 99hops** [comment, marked as answer]
Found solution here https://github.com/linkerd/linkerd2/discussions/13105

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      config.linkerd.io/proxy-admin-shutdown: enabled
```
