### DISCUSSION TITLE
How do I create a cluster?

### DISCUSSION THREAD

**Discussion by whizyrel** [cloudnative-pg/cloudnative-pg#5760] [General]
I really would appreciate some help,
This is the log entry from the job when I attempted to create a cluster with the manifest below:
```json
{"level":"info","ts":"2024-10-08T14:12:19Z","msg":"DB not available, will retry","logging_pod":"postgres-2-join","err":"failed to connect to `user=streaming_replica database=postgres`: 10.104.100.105:5432 (postgres-rw): dial error: timeout: context deadline exceeded"}
```
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  postgresql:
    synchronous:
      method: any
      number: 1
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  ...
  resources:
    ...
  storage:
    size: ...
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ...
      storageClassName: ...
      selector:
        matchLabels:
          label: label-value
  affinity:
    nodeSelector:
      label: label-value
```

One instance gets created like so but no further than that.

NAME            |          READY  | STATUS   |   RESTARTS |  AGE
postgres-1                1/1     Running     0          46m
postgres-1-initdb-4dg7d   0/1     Completed   0          46m
postgres-2-join-c27qr     1/1     Running     0          45m

Thanks everybody.
