### DISCUSSION TITLE
Failing backup after move to new s3 bucket

### DISCUSSION THREAD

**Discussion by mrclrchtr** [cloudnative-pg/cloudnative-pg#5798] [Q&A]
Hi,

I have moved to a new S3 bucket. The base backup is created as expected, but the wal backup does not work:

```
{"level":"info","ts":"2024-10-12T00:01:46Z","msg":"WAL archiving is working","logging_pod":"cluster-1"}
{"level":"info","ts":"2024-10-12T00:01:46Z","msg":"Starting barman-cloud-backup","backupName":"cluster-20241012020146","backupNamespace":"cluster-20241012020146","logging_pod":"cluster-1","options":["--user","postgres","--name","backup-20241012000146","--gzip","--jobs","2","--endpoint-url","https://my.fsn1.your-objectstorage.com","--cloud-provider","aws-s3","s3://cnpg-cluster-backups-test/backups","cluster"]}
{"level":"info","ts":"2024-10-12T00:01:57Z","msg":"Backup completed","backupName":"cluster-20241012020146","backupNamespace":"cluster-20241012020146","logging_pod":"cluster-1"}
{"level":"error","ts":"2024-10-12T00:01:58Z","logger":"barman","msg":"Can't extract backup id","logging_pod":"cluster-1","command":"barman-cloud-backup-show","options":["--format","json","--endpoint-url","https://my.fsn1.your-objectstorage.com","--cloud-provider","aws-s3","s3://cnpg-cluster-backups-test/backups","cluster","backup-20241012000146"],"stdout":"","stderr":"2024-10-12 00:01:57,997 [341] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20241012000146' for server 'cluster'\n","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.executeQueryCommand\n\tpkg/management/barman/backuplist.go:87\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.GetBackupByName\n\tpkg/management/barman/backuplist.go:140\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).getExecutedBackupInfo\n\tpkg/management/postgres/backup.go:370\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:344\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:261"}
{"level":"error","ts":"2024-10-12T00:01:58Z","msg":"Backup failed","backupName":"cluster-20241012020146","backupNamespace":"cluster-20241012020146","logging_pod":"cluster-1","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:265"}
{"level":"info","ts":"2024-10-12T00:01:58Z","msg":"Applying backup retention policy","backupName":"cluster-20241012020146","backupNamespace":"cluster-20241012020146","logging_pod":"cluster-1","retentionPolicy":"30d"}
```

```yaml
backups:
  enabled: true
  secret:
    create: false
    name: "hetzner-s3-credentials"
  data:
    encryption: "" # Hetzner does not support encryption
  wal:
    encryption: "" # Hetzner does not support encryption
  retentionPolicy: "30d"
  endpointURL: "https://my.fsn1.your-objectstorage.com"
  destinationPath: "s3://cnpg-cluster-backups-test/backups/"
  scheduledBackups:
    - name: daily
      schedule: "0 */5 * * * *" # Every 5 minutes for testing
      backupOwnerReference: self
```

Does anyone have any ideas?

**Comment by NiklasRosenstein** [comment]
Hm, I face a similar issue with using Rclone as an S3 proxy for a Hetzner StorageBox. Maybe interesting for you @mrclrchtr but my current setup is to use Hetzner Object Storage and that has been working well for me so far.

Using HCloud Object Storage:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: affine-db
  namespace: affine
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://my-bucket-name/
      endpointURL: https://hel1.your-objectstorage.com
      s3Credentials:
        accessKeyId:
          key: accessKey
          name: affine-db-backup-creds
        secretAccessKey:
          key: secretKey
          name: affine-db-backup-creds
      serverName: affine-affine-db
      wal:
        compression: gzip
    retentionPolicy: 5d
    target: prefer-standby
  # ...
```

Now targeting the Rclone S3 proxy, I'm using essentially the same configuration. The WALs and Backups get created correctly, but I get the same "Backup failed" error:

```
2025-06-02 12:53:42,381 [2247] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20250602125329' for server 'dbtest-test'
```

<details><summary>Full logs</summary>

```
{"level":"info","ts":"2025-06-02T12:53:29.944146268Z","msg":"Starting barman-cloud-backup","backupName":"test-test-backup","backupNamespace":"dbtest","logging_pod":"test-1","options":["--user","postgres","--name","backup-20250602125329","--gzip","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test"]}
{"level":"info","ts":"2025-06-02T12:53:36.873044454Z","logger":"wal-archive","msg":"Executing barman-cloud-wal-archive","logging_pod":"test-1","walName":"pg_wal/000000010000000000000007","options":["--gzip","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test","pg_wal/000000010000000000000007"]}
{"level":"info","ts":"2025-06-02T12:53:38.191432325Z","logger":"wal-archive","msg":"Executing barman-cloud-wal-archive","logging_pod":"test-1","walName":"pg_wal/000000010000000000000007.00000028.backup","options":["--gzip","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test","pg_wal/000000010000000000000007.00000028.backup"]}
{"level":"info","ts":"2025-06-02T12:53:38.968451695Z","logger":"wal-archive","msg":"Archived WAL file","logging_pod":"test-1","walName":"pg_wal/000000010000000000000007.00000028.backup","startTime":"2025-06-02T12:53:38.191404187Z","endTime":"2025-06-02T12:53:38.968371915Z","elapsedWalTime":0.77696784}
{"level":"info","ts":"2025-06-02T12:53:39.657737512Z","logger":"postgres","msg":"record","logging_pod":"test-1","record":{"log_time":"2025-06-02 12:53:39.657 UTC","user_name":"postgres","database_name":"postgres","process_id":"2128","connection_from":"[local]","session_id":"683d9eca.850","session_line_num":"1","command_tag":"SELECT","session_start_time":"2025-06-02 12:53:30 UTC","virtual_transaction_id":"33/98","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"restore point \"barman_20250602T125330\" created at 0/9000090","query":"SELECT pg_create_restore_point('barman_20250602T125330')","application_name":"barman_cloud_backup","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-06-02T12:53:40.438901144Z","logger":"wal-archive","msg":"Executing barman-cloud-wal-archive","logging_pod":"test-1","walName":"pg_wal/000000010000000000000008","options":["--gzip","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test","pg_wal/000000010000000000000008"]}
{"level":"info","ts":"2025-06-02T12:53:41.812676349Z","msg":"Completed barman-cloud-backup","backupName":"test-test-backup","backupNamespace":"dbtest","logging_pod":"test-1","options":["--user","postgres","--name","backup-20250602125329","--gzip","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test"]}
{"level":"info","ts":"2025-06-02T12:53:41.812724177Z","msg":"Backup completed","backupName":"test-test-backup","backupNamespace":"test-test-backup","logging_pod":"test-1"}
{"level":"error","ts":"2025-06-02T12:53:42.487133132Z","logger":"barman","msg":"Can't extract backup id","backupName":"test-test-backup","backupNamespace":"dbtest","logging_pod":"test-1","command":"barman-cloud-backup-show","options":["--format","json","--endpoint-url","http://s3proxy.s3proxy","--cloud-provider","aws-s3","s3://cnpg-backups/fracture/","dbtest-test","backup-20250602125329"],"stdout":"","stderr":"2025-06-02 12:53:42,381 [2247] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20250602125329' for server 'dbtest-test'\n","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.1.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.executeQueryCommand\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.1.0/pkg/command/backuplist.go:88\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.GetBackupByName\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.1.0/pkg/command/backuplist.go:141\ngithub.com/cloudnative-pg/barman-cloud/pkg/backup.(*Command).GetExecutedBackupInfo\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.1.0/pkg/backup/backup.go:153\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:248\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:174"}
{"level":"error","ts":"2025-06-02T12:53:42.487313464Z","msg":"Backup failed","backupName":"test-test-backup","backupNamespace":"test-test-backup","logging_pod":"test-1","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.1.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:178"}
{"level":"info","ts":"2025-06-02T12:53:42.522890502Z","msg":"Applying backup retention policy","backupName":"test-test-backup","backupNamespace":"test-test-backup","logging_pod":"test-1","retentionPolicy":"5d"}
```

</details>

<details><summary>Cluster resource</summary>

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test
  namespace: dbtest
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://cnpg-backups/fracture/
      endpointURL: http://s3proxy.s3proxy
      s3Credentials:
        accessKeyId:
          key: accessKey
          name: test-backup-creds
        secretAccessKey:
          key: secretKey
          name: test-backup-creds
      serverName: dbtest-test
      wal:
        compression: gzip
    retentionPolicy: 5d
    target: prefer-standby
  # ...
```

</details>

<details><summary>Backup resource</summary>

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: test-test-backup
  namespace: dbtest
spec:
  cluster:
    name: test
  method: barmanObjectStore
status:
  backupName: backup-20250602125329
  destinationPath: s3://cnpg-backups/fracture/
  endpointURL: http://s3proxy.s3proxy
  error: exit status 4
  instanceID:
    ContainerID: containerd://01e31571fcd106f033b71442e3564516453b0e927fa5dbc5992a431f89713499
    podName: test-1
  method: barmanObjectStore
  phase: failed
  s3Credentials:
    accessKeyId:
      key: accessKey
      name: test-backup-creds
    secretAccessKey:
      key: secretKey
      name: test-backup-creds
  serverName: dbtest-test
  stoppedAt: "2025-06-02T12:53:41Z"
```

</details>

![image](https://github.com/user-attachments/assets/7c468c00-2d80-4a22-9153-e3b71179e187)

What seems a bit odd is that the timestamp in the folder names created by the backup procedure do not match the timestamp in the backup resource (`20250602T125330` vs `backup-20250602125329`), but I believe I've observed the same behavior in the working Object Storage setup before.
