### DISCUSSION TITLE
LDAPS Authentication not working

### DISCUSSION THREAD

**Discussion by dspeck1** [cloudnative-pg/cloudnative-pg#583] [General]
Has anyone successfully used LDAPS with the operator?  We have tried Bind As Auth and Bind Search Auth.  Both return LDAP unknown errors.  We have other applications using LDAPS for authentication.  Do we need to load a certificate into CNPG or anyone have input?

**Comment by dspeck1** [comment]
This might be the cause.  Article from your company recommends setting the environment variable to `LDAP_TLS_VERIFY_CLIENT=try` How can I set this with the operator?  I could not find environment variable section in API spec and to manually test would not allow me to edit pod.

https://www.enterprisedb.com/postgres-tutorials/how-connect-postgres-ldap-starttls
https://github.com/osixia/docker-openldap/issues/105#issuecomment-279673189

**Reply by leonardoce** [reply]
Hi @dspeck1. Can you please share with me an extract of the PostgreSQL log showing that error?

**Comment by dspeck1** [comment]
@leonardoce Below is error.  Redacted the IP and LDAP URL.  Thanks!

{"level":"info","ts":1660243407.4527934,"logger":"postgres","msg":"record","logging_pod":"db-1","record":{"log_time":"2022-08-11 18:43:27.452 UTC","user_name":"dspeck","database_name":"db1","process_id":"71704","connection_from":"192.168.x.x:34632","session_id":"62f54dcf.11818","session_line_num":"1","command_tag":"authentication","session_start_time":"2022-08-11 18:43:27 UTC","virtual_transaction_id":"6/515","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"LDAP login failed for user \"uid=dspeck,ou=Accounts,dc=company,dc=company,dc=edu\" on server \"ldap.company.edu\": Can't contact LDAP server","detail":"LDAP diagnostics: (unknown error code)","backend_type":"client backend","query_id":"0"}}

**Reply by leonardoce** [reply]
`Can't contact LDAP server` seems like a connectivity error between your cluster and the LDAP server. That could depend on TLS handshaking as you were supposing.

The LDAP_TLS_VERIFY_CLIENT environment variable shown in the document is related to the LDAP server (openldap) and not to PostgreSQL. if I understand it correctly.

I bet having a look at the logs of the LDAP server will help, too.

**Reply by dspeck1** [reply]
Thanks.  We cannot see much on LDAP server side.  We did packet capture and TCP reset is coming from client after TLS setup and before a LDAP bind is attempted.  Is there a way to load trusted certificate for LDAP on operator?  Either that if we could turn off the SSL verification that seems to be a requirement from Postgres.  Our other LDAP clients work fine connecting without a trusted cert and ldapsearch works fine so this appears to be an extra requirement from Postgres.

**Comment by dspeck1** [comment]
Is there a way to configure the LDAP client on this image?  The base postgres image for alpine has open ldap installed.  The base image for debian bullseye not appear to have open ldap installed and is not added by the CNPG dockerfile.  There are some open LDAP settings to change how certificate checking is performed, but can't find the open ldap configuration on the container.

**Reply by leonardoce** [reply]
You can create a custom imagine using the CloudNative PG one as a base, and adding the packages you need. The image requirements are documented here: https://cloudnative-pg.io/documentation/1.16/container_images/

**Reply by hdeadman** [reply]
We enabled LDAPS and it isn't working due to SSL trust. (In our environment, it isn't really feasible to get the SSL cert on the LDAP server to be trusted by the default CAs in the OS trust bundle). We could build a custom image with the CA trust built-in but for every other thing we deploy in Kubernetes we are able to map in trust bundles from a secret (in whatever format is required for the software running in the pod). Could the k8s operator support a volume-mount of an externally managed secret into the database pods (into a configurable location such as /etc/ssl/certs/ca-certificates.crt)?

**Comment by ksyblast** [comment]
I have the same issue with LDAPs. I can confirm the Root CA from the LDAP server certificate chain is present in `/etc/ssl/certs/ca-certificates.crt` within the container. 
Also, 
`postgres@cnpg-cluster-pg13-2:/$ openssl s_client -connect ldap.mycompany.com -port 636`  gives
 `   Verify return code: 0 (ok)`
I also get the `Can't contact LDAP server","detail":"LDAP diagnostics: (unknown error code)"` error. 
Packet capture shows that the client (cnpg) closes the TCP session. LDAP server logs show only 'ACCEPT from...'. It looks like a trust problem.

**Comment by ksyblast** [comment]
Hi everyone! I could fix this by adding to the spec:
```  env:
  - name: LDAPTLS_CACERT
    value: "/etc/ssl/certs/ca-certificates.crt"
```

**Reply by hdeadman** [reply]
Is adding that environment variable possible with the current cloudnative-pg operator? The operator would also need to let users mount their own secret to /etc/ssl/certs/ca-certificates.crt in case the certificate on the LDAP server is not trusted by the default bundle.

**Reply by bradley-baker** [reply]
@hdeadman did you manage to get LDAPs working? We're trying to do so now but having a lot of difficulty. If you did would you happen to share your whole configuration (sanitized is fine) just for reference?

We managed to get our root CA mounted in the container and we're using  LDAPTLS_CACERT but postgres seems to completely ignore it. Any help you could provide would be appreciated.

**Reply by bradley-baker** [reply]
I FINALLY got this working with ldaps. Some notes for anyone else struggling with this in the future:

1) You must mount your CA certificate and create an environment variable. You do not need your intermediate certificate (if you have one)

```
...
  projectedVolumeTemplate:
    sources:
      - secret:
          name: root-ca
          items:
            - key: root.crt
              path: root.crt
  env:
    - name: LDAPTLS_CACERT
      value: /projected/root.crt
...
----
apiVersion: v1
data:
  root.crt: 
# replace with your base64 encoded CA certificate)
kind: Secret
metadata:
  name: root-ca
type: Opaque
```

Up until this part, this is exactly what was recommended by 
[@Jonathan Gonzalez V.](https://cloudnativepg.slack.com/team/U03AZUN2K8A)
 So thank you for helping us get this far!
However, this does NOT work:


```
  postgresql:
    ldap:
      server: '10.45.30.28'
      port: 3269
      scheme: 'ldaps'
      bindSearchAuth:
        baseDN: 'DC=mydomain,DC=local'
        bindDN: 'CN=postgres,OU=Special Accounts,OU=145 King St W,DC=mydomain,DC=local'
        bindPassword:
          name: 'ldapbindpassword'
          key: 'bindpassword'
        searchAttribute: "sAMAccountName"
```

This DOES work:

```
  postgresql:
    ldap:
      server: 'mydomain.local'
      port: 3269
      scheme: 'ldaps'
      bindSearchAuth:
        baseDN: 'DC=mydomain,DC=local'
        bindDN: 'CN=postgres,OU=Special Accounts,OU=145 King St W,DC=mydomain,DC=local'
        bindPassword:
          name: 'ldapbindpassword'
          key: 'bindpassword'
        searchAttribute: "sAMAccountName"
```

Couple notes:

I had to use port 3269 (LDAPS Global Catalog Server) instead of 636 (the standard LDAP port) to get this to work. Your mileage may vary. I'm unclear as to why using GC LDAPS is necessary.

The only difference between these configs is the server value. In the first, it's an IP address, and in the second, it's a DNS name. The TLS certificate we have installed from our domain controller has both values in the SAN (subject alternative name); however, openldap/openssl/Postgres seems not to like the IP address for whatever reason.

And what's infuriating about this is that the only error returned by openldap search with the IP address is this:
`ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
`

The only thing that shows up in the Postgres logs is:
```
    "message": "could not perform initial LDAP bind for ldapbinddn \"CN=postgres,OU=Special Accounts,OU=145 King St W,DC=mydomain,DC=local\" on server \"10.45.30.28\": Can't contact LDAP server",
    "detail": "LDAP diagnostics: (unknown error code)",
```

Even when cranking logging all the way up. This is all I could get - super helpful OpenLDAP/Postgres! :angry:

The way we were able to figure this out was to create a custom version of the CloudNative postgres image using this:
https://cloudnative-pg.io/blog/creating-container-images/. Thanks to 
[@Zekiye Aydemir](https://cloudnativepg.slack.com/team/U03LUE7BD19)
!

Then, in the custom image, I installed the ldaputils so we could run ldapsearch queries and find a query that worked. Here's the docker file we used:


```
FROM ghcr.io/cloudnative-pg/postgresql:17-bullseye

LABEL maintainer="you@youremail.com"

# To install any package we need to be root
USER root

RUN apt-get update && \
    apt-get install -y wget curl ldap-utils 

# Change the uid of postgres to 26
RUN usermod -u 26 postgres
USER 26
```

Hopefully, my notes above save someone else from the same headache I went through. :exploding_head:
