### DISCUSSION TITLE
Can you teach me how to properly configure my pgbouncer? Also question about storage and multi region support

### DISCUSSION THREAD

**Discussion by ember11498** [cloudnative-pg/cloudnative-pg#5930] [Q&A]
Before I give you context of the yaml files I will present the questions:

**Question 1:** Read/Write and Read-Only Setup for PgBouncer
I’ve deployed PgBouncer on Kubernetes, and it automatically created a Digital Ocean Load Balancer. I can connect to it via the external IP on port 5432, but it seems to only route to the primary database (as I specified type: rw in the YAML).

Issue: I’m unsure how to set up PgBouncer to handle both read-write (RW) and read-only (RO) traffic. Do I need to create another deployment YAML for additional PgBouncer instances with type: ro, or can I use the same PgBouncer instances for both RW and RO by creating separate services? How would I configure this in the most efficient way?

**Question 2**: Geo-Distributed Setup with PgBouncer and CloudNativePG
My current setup probably does not automatically consider the geographic location of the user (e.g., selecting the nearest PgBouncer and Postgres replica based on user location)? I probably need to create a new kubernetes cluster and specify that I want the nodes to run in a different datacenter. Then I need to create pgbouncer and cloudnative in this cluster as well but I would need to connect to the same Volume Block Storage and somehow tell cloudnativepg to not create primary postgres in this cluster since there can only exist 1 primary? Can someone shed some light on how to create regional aware backend architecture in kubernetes/pgbouncer/cloudnativepg?

**Question 3:** Backups and Storage Configuration on DigitalOcean
I’m using DigitalOcean Volumes Block Storage for persistence and DigitalOcean Spaces Object Storage for backups. I noticed that CloudNativePG allows backup management via its cluster deployment YAML, but I’m unsure why I should use this method over the built-in backup options in the DigitalOcean GUI, which seem very straightforward.

Is there an advantage to managing backups through CloudNativePG as opposed to relying on DigitalOcean’s one-click backup solution for Block Storage?

CONTEXT

I use DigitalOcean and I have creatd a kubernetes cluster for now with 1 node since I am still testing but I will increase it to more later. The node is located in ams datacenter.

Regarding the yaml files that I applied via kubectl apply -f, they look like this (note, goal is to have pgbouncer connected to cloudnativepg that uses postgis image with primary and replicas):

**StorageClass file:**

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage
provisioner: dobs.csi.digitalocean.com
parameters:
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

**this is the cloudnativepg cluster:**

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres-cluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgis:14

  bootstrap:
    initdb:
      database: mydb # This should be the name of the database you want to create.
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;

  storage:
    size: 1Gi # Specify storage size for each instance
    storageClass: do-block-storage # Use your specific storage class for DigitalOcean

  postgresql:
    parameters:
      shared_buffers: 256MB # Adjust shared buffers as needed
      work_mem: 64MB # Adjust work memory as needed
      max_connections: "100" # Adjust max connections based on load
    pg_hba:
      - hostssl all all 0.0.0.0/0 scram-sha-256

  startDelay: 30 # Delay before starting the database instance
  stopDelay: 100 # Delay before stopping the database instance
  primaryUpdateStrategy: unsupervised # Define the update strategy for the primary instance
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://plot-bucket/backup/"
      endpointURL: "https://plot-bucket.ams3.digitaloceanspaces.com"
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
```

**This is the pgbouncer:**

```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-example-rw
spec:
  cluster:
    name: my-postgres-cluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  serviceTemplate:
    metadata:
      labels:
        app: pooler
    spec:
      type: LoadBalancer

```

After deploying all of this a load balancer and a volume with 3 pvc are created in DigitalOcean which I can confirm by looking at the DigitalOcean GUI.

Then I did "kubectl get svc" in order to get the EXTERNAL-IP of the load balancer which then I used to connect to port 5432.

I managed to successefully connect to my database however it only connects to the primary!
