### DISCUSSION TITLE
Creating a cluster and users in several namespaces

### DISCUSSION THREAD

**Discussion by IngwiePhoenix** [cloudnative-pg/cloudnative-pg#5939] [Q&A]
Hello!

I had so far used the Zalando Postgres Operator, but it recently imploded as I moved my cluster; kind of my fault, the whole DB got corrupted, and since it's just a toy project, I had no backups. Nothing lost though. However, I kinda didn't like the way I had to declare everything in a single cluster definition, especially for "users" outside the cluster namespace itself.

For instance, I have namespaces for Piped and Shiori. Both of them need a PostgresQL database and I would like to use one central cluster rather than running a bunch of individual Postgres...es (is that even the right plural?). To visualize:

```
|- ns: postgres
   |- cluster deployment
   |- backup configuration/schedule
|- ns: shiori
   |- dp: shiori-app
   |- secret: shiori-postgres-user
|- ns: piped
   |- dp: piped-backend/-frontend/-proxy
   |- secret: piped-postgres-user
```

That way, there is only one Postgres instance to worry about, and many apps to use it. 

In the Zalando operator, this was achieved by activating cross-namespace secret creation - but, how do I do that with cnpq? I've gone through the docs, but could not find exactly what I was after. I understand that I just would leave most details in the `initdb` field empty or unused - but how do I create the users, thus spawning the respective secrets to be consumed by the other deployments?

Thank you and kind regards,
Ingwie

**Comment by gbartolini** [comment]
Why do you think that concentrating apps in the same cluster is an improvement? Have you thought about backups and recovery? Upgrades? Security?

CloudNativePG doesn't currently plan to enable cross-namespace access to resources, or to copy them in multiple namespaces (which, by the way, is a Kubernetes-level problem).

**Comment by jaredcdep** [comment]
> In the Zalando operator, this was achieved by activating cross-namespace secret creation - but, how do I do that with cnpq? 

I am using external secrets operator to replicate cnpg secrets to the application namespace https://external-secrets.io/latest/
I have to use one namespace for cnpg because the Barman Cloud plugin needs to be in the same namespace as the cluster.

eg

setup the ClusterSecretStore once

```
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cnpg-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: cnpg-system
      auth:
        serviceAccount:
          name: external-secrets-sa
          namespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
```

Then in my application helm I add a ExternalSecret (cnpgvector is the chart name in this example)

```
{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpgvector.fullname" . }}-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cnpg-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "cnpgvector.fullname" . }}-app  # name for the secret in application namespace
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ include "cnpgvector.fullname" . }}-app
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
```
