### DISCUSSION TITLE
Planning the Replica Cluster for DR, confused with the aftermath

### DISCUSSION THREAD

**Discussion by alexbarcelo** [cloudnative-pg/cloudnative-pg#6054] [Q&A]
Hi! I have a use case which maybe is a bit unique but I hope it is not off topic here. I have a "low-stakes" cluster and I am planning migrating its current databases to CloudNativePG. I have been reading the backup options, WALL to S3 with Barman, etc. Everything seems to be good and preliminary tests are ok. Awesome architecture and awesome documentation by the way :)

I don't have the budget nor the necessity to establish an always-on Replica Cluster. When there is a "disaster", losing some minutes of operations is ok. A manual procedure to start the Replica Cluster and tell it to bootstrap with the object backups seems to be what I need, so that's golden (that's the next thing to test in my checklist). Note that there won't be a nice promotion token because I am planning for "full disaster", not a controlled switchover.

Once the disaster has passed (between one day and one month) I want to restart the original cluster. But the original cluster might be dirty. The promotion token is nowhere to be seen. I might be able to perform a controlled switchover of promotion token from the "DR Replica Cluster" (an ephemeral cluster started after the disaster). But the first handover was dirty.  So... will this affect? Documentation states:

> If the promotion token is omitted, a failover will be triggered, necessitating a rebuild of the former primary.

It is ok to rebuild the original cluster that way? Do I need to state the Replica Cluster in the Cluster CRD? Can I state a Replica Cluster in the CRD even if it doesn't exist yet (and won't exist until a disaster)? The DR Replica Cluster will be obliterated after finishing the handover to the original cluster, but I don't know how it may affect a subsequent disaster (would I need to change the replica definition in the Cluster? will everything work again?)

Of course I plan to test everything and experiment. But it is my first time working with full-fledged operators so maybe I have some fundamental misconceptions or I am doing something very wrong from the beginning. Some pointers (documentation I may have missed or misconceptions I may have built up) will be appreciated!

**Comment by alexbarcelo** [comment]
I have been able to make DR work:

- Primary k8s has a cnpg cluster with barmanObjectStore
- Secondary k8s is started when primary is offline and starts with a cnpg cluster with the following

```yaml
  bootstrap:                                                                  
    recovery:                                                                 
      source: myk8s-main
  replica:
    primary: spot-dr                                                          
    source: myk8s-main                                                     
    self: spot-dr                                                                                                                                            
```

and it starts properly.

However, when the main k8s comes back online, I don't see what steps should I follow. Because if I blink, I get the dreaded "requested timeline is not a child of...". The manifests will be incorrect, as it was primary when it was on but now they are not, so they will dirty history. I could remove all clusters and start again them with recovery from the DR, but is that advisable? Because eventually the all the DR k8s will be wiped out, including the objects in the object store, so I will either have a cluter manifest pointing to non-existing object backups OR I will need to create yet another cnpg cluster pointing locally...

I feel like I am missing a more natural approach and shooting myself in the foot.
