### DISCUSSION TITLE
S3-compatible backup failing – virtual host style vs. path style access

### DISCUSSION THREAD

**Discussion by flypenguin** [cloudnative-pg/cloudnative-pg#6063] [General]
Hi CNPG folks,

we have an issue with our database backup. It seems that CNPG / barman is using S3 "path style" access to save files, which is unsupported by our cutomer's S3 system (a "Huawei OceanStor Pacific Scale-Out Cluster, Type 9550"). We were able to replicate the error message we get from CNPG backup jobs using rclone, so this seems to be a strong indication.

Is there any way to tell CNPG / barman to use S3 virtual-host-style access? This seems to be the default method for all S3 libs, yet ... our replication indicates it's not being used.

Replication method:

- Configure rclone `force_path_style` to `TRUE` and `FALSE` on two separate but otherwise identical backends
- Perform an `rclone sync` from `virtual-host-backend:bucket/path` to `virtual-host-backend:bucket/path2` (works)
- Perform an `rclone sync` from `virtual-host-backend:bucket/path` to `path-style-backend:bucket/path3` (fails)

The error message is: `An error occurred (AccessForbidden) when calling the PutObject operation: The passive+ site cannot access the write request when the active site is normal.` (That is a Huawei specific error message).

Any help appreciated!

Thanks in advance,
Axel.

**Comment by flypenguin** [comment]
nobody? :(

**Comment by sxd** [comment]
Hello @flypenguin 

We rely on barman cloud for the path and support so if Barman Cloud (for reference look into barman-cloud-* https://docs.pgbarman.org/release/3.11.1/) so if they support it, the operator will support it.

Probably your question should be redirected to the Barman team at https://github.com/EnterpriseDB/barman and get a more proper answer from them if they support it or not. 

On the other side, please if you need help, share configuration and a way to read the issue, because as I can see there's nothing that we can read to say "probably this can be done", keep in mind that not every one knows all the technologies, and always help to save time that you provide the documentation and/or examples so people can help.

Regards,

**Reply by flypenguin** [reply]
@sxd thanks for the answer! I will "go to" barman cloud as well. we are a bit further in debugging now, so this is what we have (shortened for stuff which isn't relevant):

```yaml
# REF: https://cloudnative-pg.io/documentation/1.23/cloudnative-pg.v1/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-test
  namespace: deploy-test
spec:
  instances: 1
  env:
  # HAS NO EFFECT (apparently)
  - name: AWS_S3_ADDRESSING_STYLE
    value: virtual

  enableSuperuserAccess: true
  superuserSecret:
    name: db-superuser-test

  backup:
    barmanObjectStore:
      destinationPath: s3://backup-bucket/db/pg-test/
      endpointURL: https://our.internal-s3.net
      s3Credentials:
        accessKeyId:
          name: s3-credentials-teset
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: s3-credentials-teset
          key: AWS_SECRET_ACCESS_KEY
```

What I can see in the DNS logs I enabled is that the backup process _only_ requests "`our.internal-s3.net`", and not (which would be required for virtual-host-style access) "`backup-bucket.our.internal-s3.net`".

So the question is: How do I make barman address the bucket using the virutual host style addressing – i.e. using `backup-bucket.our.internal-s3.net` as the service endpoint?

what we tried:

```yaml
# does not work: "invalid s3 URL"
destinationPath: /backup-bucket/db/pg-test/
endpointURL: https://backup-bucket.our.internal-s3.net

# does not work: "invalid s3 URL"
destinationPath: s3:///db/pg-test/
endpointURL: https://backup-bucket.our.internal-s3.net
```

we are _really_ thankfor for any hints here – even if the answer is "oh, that's a known issue – that does not work" (then we'd finally know ...).

since AWS wanted to deprecate path-style-access in 2019 we thougth that would be the default by today, and "should" be possible :) .
