### DISCUSSION TITLE
ERROR: Barman cloud WAL archiver exception: SSL validation failed

### DISCUSSION THREAD

**Discussion by pfaelzerchen** [cloudnative-pg/cloudnative-pg#6138] [Q&A]
About a month ago, I've setup several Clusters with `barmanObjectStore` Backup. The backup target is a cluster internal S3 object store provided by rook-ceph with a self-signed https endpoint. The TLS certificate is created by cert-manager.io based on a self-signed certificate. The ClusterIssuer provides a secret with the ca.crt which is reflected (emberstack reflector) to the databases namespace.

So far, this worked fine:
```yaml
 backup:
    # Volume snapshot backups
    volumeSnapshot:
       className: ceph-block
       online: false
       snapshotOwnerReference: backup
    # WAL archive
    barmanObjectStore:
      serverName: lldap-db
      destinationPath: s3://cnpg-backup-lldap/
      endpointURL: https://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
      endpointCA:
        name: selfsigned-ca
        key: ca.crt
      s3Credentials:
        accessKeyId:
          name: cnpg-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
        maxParallel: 8
      data:
        compression: bzip2
        jobs: 2
    retentionPolicy: "60d"
```

About two weeks ago, the WAL archiving stopped (and the disk ran full). The logs tell me: 
```
{"level":"info","ts":"2024-11-19T10:47:23.293549716Z","logger":"barman-cloud-wal-archive","msg":"2024-11-19 10:47:23,290 [2190445] ERROR: Barman cloud WAL archiver exception: SSL validation failed for https://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc/cnpg-backup-lldap [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)","pipe":"stderr","logging_pod":"lldap-db-1"}
{"level":"error","ts":"2024-11-19T10:47:23.670459262Z","logger":"wal-archive","msg":"Error invoking barman-cloud-wal-archive","logging_pod":"lldap-db-1","walName":"pg_wal/00000007.history","options":["--bzip2","--endpoint-url","https://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc","--cloud-provider","aws-s3","s3://cnpg-backup-lldap/","lldap-db","pg_wal/00000007.history"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/walarchive.(*BarmanArchiver).Archive\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/walarchive/cmd.go:83\ngithub.com/cloudnative-pg/barman-cloud/pkg/walarchive.(*BarmanArchiver).ArchiveList.func1\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/walarchive/cmd.go:115"}
```

I did some updates to the image catalog, but cannot see from my gitops repo that I changed everything else on this deployment. And I wasn't able to restore the TLS connection. So I temporarily switched to the unencrypted http-endpoint to get everything up and running again.

When inspecting the pod's definition I do not see where the ca.crt from the secret gets mounted. There is no reference to the secret under endpointCA.

Any idea what I can try or check next? Is there an option to get at least TLS encryption without Certificate Verification?
