### DISCUSSION TITLE
Controller doesn't restore app secret when bootstrapping with password reset

### DISCUSSION THREAD

**Discussion by rlex** [cloudnative-pg/cloudnative-pg#615] [General]
Hello! First of all, thanks for great product.
While evaluating it, i noticed following (maybe bug, maybe expected?) behaviour: 

If you bootstrap postgres cluster from backup with following specified: 

```  
spec:
  bootstrap:
    recovery:
      source: outline-db
      database: app
      owner: app
      secret:
        name: reset-password
```
where secret named reset-password contains username and password, the secret with -app (which contains pgpass, username and password) is not getting recreated after cluster bootstrap. superuser, replication and etc are all here. 
Might be case with overriding superuser password too, but i hasn't checked it.

**Comment by rlex** [comment]
Apparently it got recreated, but with some delay: 
```
outline-db-app                  kubernetes.io/basic-auth   3      5m41s
outline-db-ca                   Opaque                     2      40m
outline-db-pooler               kubernetes.io/tls          2      40m
outline-db-replication          kubernetes.io/tls          2      40m
outline-db-server               kubernetes.io/tls          2      40m
outline-db-superuser            kubernetes.io/basic-auth   3      40m
```
-app was recreated after 35 minutes.

**Comment by phisco** [comment]
Can you share the logs of the operator between the secret deletion and its recreation?

**Comment by rlex** [comment]
I'll try to dig them up. Also, it wasn't just recreation, it changed password off app user to new one for some reason.

**Comment by phisco** [comment]
yes, that's expected behavior, deletion of that secret results in password rotation

**Reply by gbartolini** [reply]
@rlex can you please confirm that @phisco answered your question? thanks

**Comment by benweet** [comment]
Hi @phisco @gbartolini 

I have the same problem here. After restoring from a backup, the app secret is not recreated (even after 35 min..) :

```
$ kubectl get secret -n ejbca | grep postgres
ejbca-postgres-ca            Opaque                                2      53m
ejbca-postgres-replication   kubernetes.io/tls                     2      53m
ejbca-postgres-secret        kubernetes.io/basic-auth              2      53m
ejbca-postgres-server        kubernetes.io/tls                     2      53m
ejbca-postgres-superuser     kubernetes.io/basic-auth              3      53m
ejbca-postgres-token-qx8jw   kubernetes.io/service-account-token   3      53m
```

I've used the following conf to create the cluster :

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ejbca-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    # initdb:
    #   database: ejbca
    #   owner: dbuser
    recovery:
      source: ejbca-postgres
      recoveryTarget:
        targetTime: "2023-04-21 15:31:00+00:00"
  externalClusters:
    - name: ejbca-postgres
      barmanObjectStore:
        destinationPath: s3://ejbca/pg-backup
        endpointURL: http://ejbca-minio:9000
        s3Credentials:
          accessKeyId:
            name: ejbca-app-vaultsecret
            key: S3_ACCESS_KEY_ID
          secretAccessKey:
            name: ejbca-app-vaultsecret
            key: S3_SECRET_ACCESS_KEY
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://ejbca/pg-backup1
      endpointURL: http://ejbca-minio:9000
      serverName: ejbca-postgres
      s3Credentials:
        accessKeyId:
          name: ejbca-app-vaultsecret
          key: S3_ACCESS_KEY_ID
        secretAccessKey:
          name: ejbca-app-vaultsecret
          key: S3_SECRET_ACCESS_KEY
```

Is the app secret supposed to be recreated at some point ?

**Comment by benweet** [comment]
I've got it recreated once I removed the `recovery` section in the YAML (after the restore completed) :

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ejbca-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: ejbca
      owner: dbuser
  #   recovery:
  #     source: ejbca-postgres
  #     recoveryTarget:
  #       targetTime: "2023-04-21 15:31:00+00:00"
  # externalClusters:
  #   - name: ejbca-postgres
  #     barmanObjectStore:
  #       destinationPath: s3://ejbca/pg-backup
  #       endpointURL: http://ejbca-minio:9000
  #       s3Credentials:
  #         accessKeyId:
  #           name: ejbca-app-vaultsecret
  #           key: S3_ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: ejbca-app-vaultsecret
  #           key: S3_SECRET_ACCESS_KEY
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://ejbca/pg-backup1
      endpointURL: http://ejbca-minio:9000
      serverName: ejbca-postgres
      s3Credentials:
        accessKeyId:
          name: ejbca-app-vaultsecret
          key: S3_ACCESS_KEY_ID
        secretAccessKey:
          name: ejbca-app-vaultsecret
          key: S3_SECRET_ACCESS_KEY
```

Everything's fine after that 😄
