### DISCUSSION TITLE
gcp cloudsql primary -> cnpg read-replicas, possible?

### DISCUSSION THREAD

**Discussion by miran248** [cloudnative-pg/cloudnative-pg#6167] [Q&A]
Hey,

I have followed the [steps in this tutorial](https://cloud.google.com/sql/docs/postgres/replication/configure-external-replica) and no matter what it would always fail with the same error
```
pgbasebackup {"level":"info","ts":"2024-11-26T10:35:32.733858357Z","logger":"pg_basebackup","msg":"pg_basebackup: error: could not send replication command \"CREATE_REPLICATION_SLOT \"pg_basebackup_3623\" TEMPORARY PHYSICAL RESERVE_WAL\": ERROR:  must be superuser or cloudsqlreplica to use replication slots","pipe":"stderr","logging_pod":"cnpg-1-pgbasebackup"}
```
I added a new user both using sql and via gcp console, granted it a bunch of permissions, tried assigning it different roles (including `cloudsqlsuperuser` or `cloudsqlreplica`), restarted cloudsql db multiple times and i'd always get the exact same error! It's as if it was trying to connect to a different db instance, except gcp console logs were saying otherwise..

Crd (pg_basebackup + replica, both cloudsql and cnpg were pg14!)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: external-cluster-secret
  namespace: staging
stringData:
  # username: postgres or some other username
  # password: password
  username: cnpg
  password: cnpg-password
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-user-secret
  namespace: staging
stringData:
  username: user
  password: user-password
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: staging
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  instances: 1
  storage:
    size: 100Gi
    resizeInUseVolumes: true
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  bootstrap:
    pg_basebackup:
      source: gcp
      database: postgres or some other database
      owner: postgres or some other database
      secret:
        name: cnpg-user-secret
  replica:
    enabled: true
    source: gcp
  externalClusters:
    - name: gcp
      connectionParameters:
        host: private or public ip
        # user: postgres
        # user: cloudsqlreplica requires additional ip entries in pg_hba.conf, which isn't available
        user: cnpg
        dbname: postgres or some other database
      password:
        name: external-cluster-secret
        key: password
  postgresql:
    parameters:
      # these match the cloudsql settings
      max_connections: "10"
      max_replication_slots: "10"
      max_worker_processes: "8"
      max_wal_senders: "10"
    shared_preload_libraries:
      - pglogical
```

Then i followed [this tutorial](https://www.gabrielebartolini.it/articles/2024/03/cloudnativepg-recipe-5-how-to-migrate-your-postgresql-database-in-kubernetes-with-~0-downtime-from-anywhere) and while i saw no errors i ended up with an empty database (even though it seemed like it was doing something).

Crd (initdb + pubsub)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: external-cluster-secret
  namespace: staging
stringData:
  # username: postgres or some other username
  # password: password
  username: cnpg
  password: cnpg-password
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-user-secret
  namespace: staging
stringData:
  username: user
  password: user-password
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: staging
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  instances: 1
  storage:
    size: 100Gi
    resizeInUseVolumes: true
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: postgres or some other database
      owner: postgres or some other database
      secret:
        name: cnpg-user-secret
      import:
        source:
          externalCluster: gcp
        type: microservice
        databases:
          - database
        schemaOnly: true
  externalClusters:
    - name: gcp
      connectionParameters:
        host: private or public ip
        # user: postgres
        user: cnpg
        dbname: postgres or some other database
      password:
        name: external-cluster-secret
        key: password
  postgresql:
    parameters:
      max_connections: "10"
      max_replication_slots: "10"
      max_worker_processes: "8"
      max_wal_senders: "10"
    shared_preload_libraries:
      - pglogical
```

Any ideas?

(used helm chart `https://cloudnative-pg.io/charts/cloudnative-pg#0.22.1`)

Thanks!
Miran
