### DISCUSSION TITLE
TLS with CertManager and Public Authority (Let'sEncrypt)

### DISCUSSION THREAD

**Discussion by casualmatt** [cloudnative-pg/cloudnative-pg#6624] [Q&A]
Hi everyone,

I’m new to using CloudNativePG, and I’ve successfully set up the operator and a database cluster—it was surprisingly straightforward!

However, I’m currently stuck. I understand that I can’t use an NGINX ingress to add TLS to the connection since the PostgreSQL protocol requires TLS to be integrated directly. When I generate a TLS certificate using Cert-Manager with Let’s Encrypt or ZeroSSL, I only receive the key and the certificate (CRT), but not a CA certificate.

I haven’t found any specific or even general resources online that address setups without a CA certificate.

Does anyone have suggestions? (If I manage to resolve this, I’d like to contribute the solution to the public documentation. Are pull requests open to everyone, or can only maintainers contribute?)

**Comment by garry-t** [comment]
I've been trying it already 3d day. 
So what I tried manually make ca.crt , i took intermediate certificate from the provided cert by traefik and download issuer certificate from letsencrypt, but it doesn't work, means cnpg seems like applied cert because they are ok, but when connection to primary via public trusted dns, bad handshake . I dont know what is the reason of it..

**Comment by coutantal** [comment]
Hi guys,
I found a way to enable TLS with cloudnative-pg and a let's encrypt certmanager-generated certificate.

First create a Certificate resource with cert-manager :
(Note that we're tweaking the secret creation to add cnpg.io/reload label in order to regularly reload postgres instance for cert renewals)
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres
  namespace: my-namespace
spec:
  dnsNames:
  - my-postgres.johndoe.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: my-postgres-tls
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
  - digital signature
  - key encipherment
```

Once cert-manager has done his job you should have a ready Certificate with your related TLS secret : 
```bash
$ kubectl get secrets -n my-namespace
NAME                           TYPE                       DATA   AGE
my-postgres-tls                kubernetes.io/tls          2      6m
```

It seems that there is no solution to automatically store let's encrypt root certificate in your cluster from cert-manager, so you can use : 
```bash
$ kubectl create -n my-namespace secret generic my-postgres-tls-ca --from-file=ca.crt=<(curl -sL "https://letsencrypt.org/certs/isrgrootx1.pem")
```
```bash
$ kubectl get secrets -n my-namespace
NAME                           TYPE                       DATA   AGE
my-postgres-tls                kubernetes.io/tls          2      8m
my-postgres-tls-ca             Opaque                     1      2m
```

Then finally create your cluster and reference your secrets : 
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
  namespace: my-namespace
spec:
  instances: 1
  certificates:
    serverCASecret: my-postgres-tls-ca
    serverTLSSecret: my-postgres-tls
  storage:
    storageClass: my-storage-class
    size: 5Gi
```

```bash
$ kubectl describe clusters.postgresql.cnpg.io my-postgres -n my-namespace
```
You can check the cluster status : 
```bash
Status:
[...]
  Certificates:
    Client CA Secret:  my-postgres-ca
    Expirations:
      My - Postgres - Ca:           2025-12-12 12:50:22 +0000 UTC
      My - Postgres - Replication:  2025-12-12 12:50:22 +0000 UTC
      My - Postgres - Tls:          2025-11-15 07:24:24 +0000 UTC
      My - Postgres - Tls - Ca:     2035-06-04 11:04:38 +0000 UTC
[...]
    Server CA Secret:             my-postgres-tls-ca
    Server TLS Secret:            my-postgres-tls
```

The only drawback is if the root certificate is replaced or renewed, but I think cloudnative-pg will detect and alert incompatibility with the new certificate. To be tested.
