### DISCUSSION TITLE
Database never starts up after initialization

### DISCUSSION THREAD

**Discussion by m00nwtchr** [cloudnative-pg/cloudnative-pg#6746] [Q&A]
Currently just trying to start a simple single instance database.
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  storage:
    size: 1Gi
 ```
 
 Initdb logs: [cluster-example-1-initdb-4f29n.log](https://github.com/user-attachments/files/18628919/cluster-example-1-initdb-4f29n.log)

Cluster logs: [cluster-example-1.log](https://github.com/user-attachments/files/18628922/cluster-example-1.log)

The state of the cluster pod is Running, but with failed probes.
