### DISCUSSION TITLE
NetworkPolicy End to end - Operator to postgresql cluster (Calico CNI)

### DISCUSSION THREAD

**Discussion by bhagatdharmendra** [cloudnative-pg/cloudnative-pg#7051] [Q&A]
The cloudnative-pg operator has been deployed on cnpg-system namespace and the postgresql cluster on "cloudnative-pg", but no pods are appearing. I can see that the CNPG status says it cannot reach the Operator, indicating that the network policy has not been set up correctly. Currently, we have a policy that denies all ingress into all namespaces, but allows egress. 

It would be really helpful if we can get the network policy which we can place and use it on fly. Thank you in advance for help.  

operator info
```bash
 kubectl get pods -n cnpg-system --show-labels 
NAME                                       READY   STATUS    RESTARTS   AGE   LABELS
barman-cloud-7dbbf8994b-gdjmw              1/1     Running   0          4d    app=barman-cloud,pod-template-hash=7dbbf8994b
cloudnative-pg-operator-57b8c64969-jz58d   1/1     Running   0          4d    app.kubernetes.io/instance=cloudnative-pg-operator,app.kubernetes.io/name=cloudnative-pg,pod-template-hash=57b8c64969

```
Postgresql Cluster Info
```bash
kubectl get pods --show-labels -n cloudnative-pg 
NAME                             READY   STATUS      RESTARTS   AGE   LABELS
cluster-example-1                1/1     Running     0          16m   cnpg.io/cluster=cluster-example,cnpg.io/instanceName=cluster-example-1,cnpg.io/instanceRole=primary,cnpg.io/podRole=instance,role=primary
cluster-example-1-initdb-9n2vx   0/1     Completed   0          18m   batch.kubernetes.io/controller-uid=5f86b399-c349-4754-aecf-87232479d4e6,batch.kubernetes.io/job-name=cluster-example-1-initdb,cnpg.i
```
Cnpg-status
```bash
kubectl cnpg status cluster-example                                                                                                                                                                    1 ↵
Cluster Summary
Name                 cloudnative-pg/cluster-example
System ID:           7477565715853627414
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:17.2
Primary instance:    cluster-example-1
Primary start time:  2025-03-03 12:54:09 +0000 UTC (uptime 19m38s)
Status:              Instance Status Extraction Error: HTTP communication issue Communication issue detected: The operator was unable to receive the status from all the ready instances. This may be due to network restrictions such as NetworkPolicy and/or any other network plugin setting. Please verify your network configuration.
Instances:           3
Ready instances:     1
Size:                78M
Current Write LSN:   0/4000000 (Timeline: 1 - WAL File: 000000010000000000000004)

Continuous Backup status
Not configured

Streaming Replication status
Not available yet

Instances status
Name               Current LSN  Replication role  Status  QoS         Manager Version  Node
----               -----------  ----------------  ------  ---         ---------------  ----
cluster-example-1  0/4000000    Primary           OK      BestEffort  1.25.0           worker04

```

Now Current applied Policy

```

#1 Deny All 
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: deplu
  name: default-deny-cnpg-system
  namespace: cnpg-system
spec:
  ingress:
  - action: Allow
    source:
      namespaceSelector: kubernetes.io/metadata.name == 'cnpg-system'
  selector: all()
  types:
  - Ingress

#2 
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: deploy
  name: cloudnative-pg-allow-admission-webhooks
  namespace: cnpg-system
spec:
  ingress:
  - action: Allow
    protocol: TCP
    source:
      nets:
      - 192.168.0.0/24 ## Complete Cluster Range
  selector: app.kubernetes.io/instance == 'cloudnative-pg-operator'
  types:
  - Ingress

# 3
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: foundation
  name: allow-cnpg-status
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 8000
      - 5432
      selector: has(cnpg.io/cluster)
    protocol: TCP
    source:
      nets:
      - 192.168.0.0/24
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in
    {"kube-system", "calico-system", "calico-apiserver"}
  order: 1
  types:
  - Ingress
 
```
