### DISCUSSION TITLE
Additional managed services with a custom service port

### DISCUSSION THREAD

**Discussion by Hazmi35** [cloudnative-pg/cloudnative-pg#7058] [Q&A]
Hi, I'm trying to add additional services for the PostgreSQL cluster via managed.services in ClusterSpec. I want to customize the LoadBalancer port but it seems that cnpg didn't correctly set the service port?

This is how I write my ManagedServices spec, but the result creates a postgresql-rw-pub with port 5432 instead of 38474

```yaml
#(rest of code)
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "postgresql-rw-pub"
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-resource-group: some-resource-group
                service.beta.kubernetes.io/azure-pip-name: some-public-ipv4
            spec:
              ports:
                - name: postgres
                  port: 38474
                  targetPort: 5432
                  protocol: TCP
              type: LoadBalancer
#(rest of code)
```

Result
```
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)           AGE
postgresql-pool     LoadBalancer   172.19.228.246   [redacted]      38475:30300/TCP   2d20h
postgresql-r        ClusterIP      172.19.216.110   <none>          5432/TCP          3d1h
postgresql-ro       ClusterIP      172.19.175.2     <none>          5432/TCP          3d1h
postgresql-rw       ClusterIP      172.22.190.2     <none>          5432/TCP          3d1h
postgresql-rw-pub   LoadBalancer   172.16.72.184    [redacted]      5432:32351/TCP    48m
```

As you can see postgresql-rw-pub service port is 5432 rather than 38474
