### DISCUSSION TITLE
Managing extensions guaranteeing immutability

### DISCUSSION THREAD

**Discussion by gbartolini** [cloudnative-pg/cloudnative-pg#7073] [Ideas]
This thread serves as a follow-up to the article I wrote titled ["The Immutable Future of PostgreSQL Extensions in Kubernetes with CloudNativePG"](https://www.gabrielebartolini.it/articles/2025/03/the-immutable-future-of-postgresql-extensions-in-kubernetes-with-cloudnativepg/). 

The purpose of this discussion is to promote collaborative thinking on how to develop a feature in CloudNativePG that makes use of `extension_control_path` in PostgreSQL and image volumes in Kubernetes.

We should also consider image catalogs to provide a way to distribute extensions.

**Comment by gbartolini** [comment]
The pilot in #6546 only caters for the following configuration:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-with-extensions
spec:
  instances: 1
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector-18-testing:latest
  storage:
    storageClass: standard
    size: 1Gi
```

There are a couple of open questions:

- how do we address the possibility of hosting two versions of the same extension in a system? do we want to do it?
- how do we integrate extensions with image catalogs?

**Reply by mnencia** [reply]
What are the specific scenarios where having multiple versions of an extension is necessary or beneficial?

**Reply by gbartolini** [reply]
I've observed this pattern in VMs with Postgres clusters that host multiple databases. For instance, one database might be using PostGIS 3.4, while another is on 3.5.

I believe we should strongly advocate for using a microservices database approach. What are your thoughts?

**Reply by mnencia** [reply]
I believe that the microservice database approach is superior, and we should continue to advocate for its adoption, as we already do. Additionally, I think that the PostGIS-like approach is feasible only because they have different shared object names for different versions. This practice is not common among most extensions, and it may be more of an issue for PostgreSQL to address rather than the operator. From the operator's perspective, the name provided for the extension is simply a unique symbolic identifier used for the extension; it does not have a direct link to the extension's internal name. Thus, it is the user's responsibility to choose a compatible list of extensions.

**Comment by gbartolini** [comment]
Extensions can also be part of an image catalog. For example, it could look like this:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:16.8
      extensions:
        - name: pgvector
          image: ghcr.io/cloudnative-pg/extensions/pgvector-16:0.8.0-1
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:17.4
      extensions:
        - name: pgvector
          image: ghcr.io/cloudnative-pg/extensions/pgvector-17:0.8.0-1
```

**Reply by gbartolini** [reply]
How can we integrate image catalogs into a cluster definition? For instance, if the `image` stanza for an extension in the cluster is empty, but the cluster depends on a catalog and the extension name matches one in the catalog, we can use the image specified in that catalog directly. Here’s an example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-with-extensions
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 17
  postgresql:
    extensions:
      - name: pgvector
  storage:
    storageClass: standard
    size: 1Gi
```
