### DISCUSSION TITLE
Support for IPV6 in dual stack?

### DISCUSSION THREAD

**Discussion by jackson-chris** [cloudnative-pg/cloudnative-pg#7116] [Q&A]
Is it possible to have the postgres cluster setup to use IPV6 addresses on a dual stack configured k8s cluster? I researched the documentation and looked through open issues but I didn't see any reference. All I was able to find is how to configure the cloudnative pg operator itself for dual stack resulting in the `cnpg-webhook-service` using an IPV6 address.

**Comment by sxd** [comment]
Hello @jackson-chris 

Yes, indeed this could be possible, will require a couple of tweaks not so complicated, but this hasn't been requested by the community in a long time, the idea was something that we had a long long time ago, but since no one in the community has ever requested we thought it wasn't needed.

Even if it can be done, it will require some work on the tests and people that want to test and help, because there's two things to test, dual stack and only ipv6/ipv4 implementations on this, and how it behaves in an upgrade or something like that.

If the community is willing to help on testing PRs and also help on create the proper E2E tests for these will be awesome, we can create a couple of Issues/PRs for these, but again, this will require a lot of help from the community.

Regards!

**Reply by jackson-chris** [reply]
Indeed the testing will be tricky as you would need to test the following matrix:

- DualStack, Ordering I believe matters, as it will dictate the value assigned to `spec.podIP`:
    - IPv4IPv6
    - IPv6IPv4
- SingleStackIPv4
- SingleStackIPv6

**Comment by jackson-chris** [comment]
Background for this question/request is related to the US government mandate detailing in this [memo](https://www.whitehouse.gov/wp-content/uploads/2020/11/M-21-07.pdf):

> The Office of Management and Budget (OMB) has mandated that 80% of IP-enabled assets be IPv6-only by the end of fiscal year 2025.

**Comment by der-eismann** [comment]
Any updates here? I can see that the DB is listening on an IPv6 interface, however the k8s service is only SingleStack IPv6.

**Comment by AW-CBNG** [comment]
Bumping this also, @sxd. We'd like to set this behaviour in the `kind: Cluster` CR (or wherever most appropriate)

For example:
```YAML
Kind: Cluster
...
    template:
      services:
        ipFamilies:
          - IPv6
        ipFamilyPolicy: SingleStack
...
```

Using OpenShift.

Thank you.

**Comment by kainz** [comment]
The only current way to do this is to define additional managed services within a cluster and specify the desired IP stack setup in those service templates.  I use a `managed` stanza in my cluster definition similar to the following:

```yaml
    managed:
      services:
        ## disable the default services
        disabledDefaultServices: ["ro", "r"]
        additional:
          - selectorType: rw
            serviceTemplate:
              metadata:
                name: "db-dbname-ds-rw"
              spec:
                type: ClusterIP
                ipFamilyPolicy: RequireDualStack
          - selectorType: r
            serviceTemplate:
              metadata:
                name: "db-dbname-ds-r"
              spec:
                type: ClusterIP
                ipFamilyPolicy: RequireDualStack
          - selectorType: ro
            serviceTemplate:
              metadata:
                name: "db-dbname-ds-ro"
              spec:
                type: ClusterIP
                ipFamilyPolicy: RequireDualStack
``` 


Assuming, for example, that you have proper DualStack support running on whichever nodes your cluster gets scheduled to (aka those Nodes have and know about and assign IPv4+IPv6 PodCIDRs), and ipv6 routing works however you do for your substrate (I use cilium-bgp in conjunction with frr BGP routing core for dumb/external nodes), a cluster with the above provisioned setup would be accessible via the ipv4 and ipv6 advertised addresses allocated on each of the `db-dbname-ds-WHATEVER` services.  CNPG as of v1.28.1 does not allow disabling the default `rw` service.

**Comment by cagataygurturk** [comment]
Hi everyone, https://github.com/cloudnative-pg/cloudnative-pg/pull/10425 resolves this. Appreciate your upvotes for the PR.

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-dualstack
spec:
  instances: 3

  managed:
    services:
      # This template is applied to all services (rw, ro, r) as a defaults
      # layer. Per-service values in additional managed services take precedence.
      serviceTemplate:
        spec:
          ipFamilyPolicy: RequireDualStack
          ipFamilies:
            - IPv4
            - IPv6

  storage:
    size: 1Gi
```
