### DISCUSSION TITLE
I got a cluster up and running, how should I test the Disaster Recovery?

### DISCUSSION THREAD

**Discussion by Sleepful** [cloudnative-pg/cloudnative-pg#7418] [Q&A]
The cluster works fine, the `/base` and `/wals` archiving is shown in S3, verifying that backups are working fine. How do I destroy and recover the cluster to make sure that it works smoothly?

I tried using `kubectl cnpg destroy cluster` but the cluster did not recover from this, as shown by `kubectl cnpg status cluster`. This comment says that there is no way to resume from this:
https://github.com/cloudnative-pg/cloudnative-pg/issues/5542#issuecomment-2507613134

So.... how should I instruct CNPG to destroy a cluster and let it attempt a recovery?

**Comment by dosubot** [comment]
Hello @Sleepful! I'm [Dosu](https://dosu.dev), here to help you tackle bugs, answer questions, and navigate your way to becoming a contributor. I'll be around while you wait for a human maintainer. How can I assist you today?


To instruct CloudNativePG to destroy a cluster and attempt a recovery from a backup stored in S3, you should create a `values.yaml` file with the following configuration:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  [...]

  superuserSecret:
    name: superuser-secret

  bootstrap:
    recovery:
      source: clusterBackup

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://your-s3-bucket-name/
        s3Credentials:
          accessKeyId:
            name: recovery-object-store-secret
            key: access_key_id
          secretAccessKey:
            name: recovery-object-store-secret
            key: secret_access_key
        wal:
          maxParallel: 8
```

Ensure that you use the same PostgreSQL version and configuration as the original cluster. The recovery process is not performed "in-place" on an existing cluster; instead, it bootstraps a new cluster using the data from the backup. The operator orchestrates the recovery using `barman-cloud-restore` for the base backup and `barman-cloud-wal-restore` for WAL files. You can speed up the WAL restore phase by setting the `maxParallel` option. Once the recovery is complete, the new primary instance will start as usual, and the remaining instances will join the cluster as replicas. If desired, you can include a `backup` section in the manifest to start archiving WALs and taking backups after recovery <sup>[[1]](https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/docs/Recovery.md)</sup><sup>[[2]](https://cloudnative-pg.io/documentation/1.19/backup_recovery)</sup><sup>[[3]](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/recovery.md)</sup>.



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=reply-with-mention&utm_term=cloudnative-pg%2Fcloudnative-pg).*

---

Docs are dead. Just use [Dosu](https://dosu.dev?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-tagline&utm_term=cloudnative-pg%2Fcloudnative-pg).

[![Leave Feedback](https://img.shields.io/badge/Leave%20Feedback-555555?style=flat)](https://app.dosu.dev/response-feedback?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-feedback&utm_term=cloudnative-pg%2Fcloudnative-pg&message_id=85297f44-0583-4e5c-8d1b-a7018dd02abd) [![Ask Dosu about cloudnative-pg](https://img.shields.io/badge/Ask%20Dosu%20about%20cloudnative--pg-2f7b3f?style=flat&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iODYiIGhlaWdodD0iODkiIHZpZXdCb3g9IjAgMCA4NiA4OSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4yOTIzNiAxMi43OTI4TDE3Ljc1OTMgNi42ODE4OFY3Mi41NjY3TDUuMjkyMzYgODQuMDYxOFYxMi43OTI4WiIgZmlsbD0iI0I0QkI5MSIvPjxwYXRoIGQ9Ik0xOC4yNTc1IDczLjExOTZMNTkuMTMyOSA3Mi43NDhMNTEuNzAxMSA4Mi40MDk1TDI5LjAzMzggODYuMjkxTDYuMjM5NjIgODUuMTU1NEwxOC4yNTc1IDczLjExOTZaIiBmaWxsPSIjNzc4NTYxIi8%2BPHBhdGggZD0iTTE3LjQ5MTYgMy43MzYzM0wzLjU4NTU3IDEyLjcwOTlWODMuNTc5MkMzLjU4NTU3IDg0Ljc1NDIgNC45ODU2MyA4NS4zNjUyIDUuODQ3MDUgODQuNTY2TDE5LjYyOTYgNzEuNzgwMSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjQyODQ0IiBzdHJva2UtbGluZWNhcD0icm91bmQiLz48bWFzayBpZD0iZG9zdS1kLWN1dG91dCIgZmlsbD0id2hpdGUiPjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNNDAuNzA0IDAuNTE4MDY2SDE3LjA0MzlWNzYuMjIyMUg0MC43MDRINDIuNTgwNUg0Ny44MDEzQzY4LjcwNjQgNzYuMjIyMSA4NS42NTMzIDU5LjI3NTIgODUuNjUzMyAzOC4zNzAxQzg1LjY1MzMgMTcuNDY1IDY4LjcwNjMgMC41MTgwNjYgNDcuODAxMyAwLjUxODA2Nkg0Mi41ODA1SDQwLjcwNFoiLz48L21hc2s%2BPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MC43MDQgMC41MTgwNjZIMTcuMDQzOVY3Ni4yMjIxSDQwLjcwNEg0Mi41ODA1SDQ3LjgwMTNDNjguNzA2NCA3Ni4yMjIxIDg1LjY1MzMgNTkuMjc1MiA4NS42NTMzIDM4LjM3MDFDODUuNjUzMyAxNy40NjUgNjguNzA2MyAwLjUxODA2NiA0Ny44MDEzIDAuNTE4MDY2SDQyLjU4MDVINDAuNzA0WiIgZmlsbD0iI0YzRjZGMSIvPjxwYXRoIGQ9Ik0xNy4wNDM5IDAuNTE4MDY2Vi02LjU3OTE5SDkuOTQ2NjlWMC41MTgwNjZIMTcuMDQzOVpNMTcuMDQzOSA3Ni4yMjIxSDkuOTQ2NjlWODMuMzE5NEgxNy4wNDM5Vjc2LjIyMjFaTTE3LjA0MzkgNy42MTUzMkg0MC43MDRWLTYuNTc5MTlIMTcuMDQzOVY3LjYxNTMyWk0yNC4xNDEyIDc2LjIyMjFWMC41MTgwNjZIOS45NDY2OVY3Ni4yMjIxSDI0LjE0MTJaTTQwLjcwNCA2OS4xMjQ5SDE3LjA0MzlWODMuMzE5NEg0MC43MDRWNjkuMTI0OVpNNDIuNTgwNSA2OS4xMjQ5SDQwLjcwNFY4My4zMTk0SDQyLjU4MDVWNjkuMTI0OVpNNDcuODAxMyA2OS4xMjQ5SDQyLjU4MDVWODMuMzE5NEg0Ny44MDEzVjY5LjEyNDlaTTc4LjU1NiAzOC4zNzAxQzc4LjU1NiA1NS4zNTU1IDY0Ljc4NjcgNjkuMTI0OSA0Ny44MDEzIDY5LjEyNDlWODMuMzE5NEM3Mi42MjYxIDgzLjMxOTQgOTIuNzUwNSA2My4xOTQ5IDkyLjc1MDUgMzguMzcwMUg3OC41NTZaTTQ3LjgwMTMgNy42MTUzMkM2NC43ODY2IDcuNjE1MzIgNzguNTU2IDIxLjM4NDcgNzguNTU2IDM4LjM3MDFIOTIuNzUwNUM5Mi43NTA1IDEzLjU0NTMgNzIuNjI2IC02LjU3OTE5IDQ3LjgwMTMgLTYuNTc5MTlWNy42MTUzMlpNNDIuNTgwNSA3LjYxNTMySDQ3LjgwMTNWLTYuNTc5MTlINDIuNTgwNVY3LjYxNTMyWk00MC43MDQgNy42MTUzMkg0Mi41ODA1Vi02LjU3OTE5SDQwLjcwNFY3LjYxNTMyWiIgZmlsbD0iYmxhY2siIG1hc2s9InVybCgjZG9zdS1kLWN1dG91dCkiLz48cGF0aCBkPSJNNjguOTIxNSAzNi4wMTM1QzY4LjkyMTUgMzYuMDEzNSA2NS43MzY5IDQ5LjQ3MzggNTEuNDIzMSA0OS40NzM4QzM3LjEwOTMgNDkuNDczOCAzMi41Nzg3IDM3LjM1OTYgMzIuNTc4NyAzNi4wMTM1IiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjcuNjkxNjEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjxwYXRoIGQ9Ik0wLjM0ODYzMyA4NS40OTQ2QzAuMzQ4NjMzIDg1LjQ5NDYgMjkuNDg1NiA4NS44MzA5IDM0LjgwOSA4NS42OThDNDQuODMzNyA4NS40NDc3IDUxLjI4NzIgODQuNDAyIDU3LjUyNjkgNzguOTcyNEM2Mi44MTI5IDc0LjM3MjcgNzUuMTM0MiA1OS42ODM2IDc1LjEzNDIgNTkuNjgzNiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjE2NDgyIi8%2BPC9zdmc%2B)](https://github.dosu.com/cloudnative-pg/cloudnative-pg?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-ask-repo&utm_term=cloudnative-pg%2Fcloudnative-pg) [![Share Dosu with your team](https://img.shields.io/badge/Share%20Dosu%20with%20your%20team-1f6feb?style=flat)](https://app.dosu.dev/signup?referrer=openSource&source=github-footer&utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-share-team&utm_term=cloudnative-pg%2Fcloudnative-pg)

**Reply by Sleepful** [reply]
This is not helpful and misses the point

**Comment by thomascjohnson** [comment]
I was testing this by applying a manifest like this:

cluster-example-with-backup.yaml
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-with-backup
spec:
  instances: 1

  storage:
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://backups
      endpointURL: http://object-storage-service:9000
      s3Credentials:
        accessKeyId:
          name: object-storage
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: object-storage
          key: ACCESS_SECRET_KEY
```

```
kubectl apply -f cluster-example-with-backup.yaml
```

I'd let it run and run a backup:

```
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  cluster:
    name: cluster-example-with-backup
```

Then once the base and wals directories were populated, I'd delete the cluster:

```
kubectl delete -f cluster-example-with-backup.yaml
```

Then I'd update the manifest:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-with-backup
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      source: cluster-example-with-backup

  externalClusters:
    - name: cluster-example-with-backup
      barmanObjectStore:
        destinationPath: s3://backups
        endpointURL: http://object-storage-service:9000
        s3Credentials:
          accessKeyId:
            name: object-storage
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: object-storage
            key: ACCESS_SECRET_KEY
```

This worked, but I find this process awkward because now I would have to use a different name for the backups going forward, or remove the backup entry like I did in the second manifest. In other words, the manifest is now stateful. I see that it would be difficult to do something else, though.
