### DISCUSSION TITLE
fixed service hostname to connect to the cluster

### DISCUSSION THREAD

**Discussion by brpaz** [cloudnative-pg/cloudnative-pg#7438] [Q&A]
Hello.

Let´s say I want to create a new cluster from an existing cluster  or backup in order for example to update to a major postgres version.  If I hardcode the hostname in my applications, Ex: `my-cluster.cnpg-system.svc.cluster.local` and now the new cluster is `my-cluster-2.cnpg-system.svc.cluster.local`   this means I would need to update all the applications to point to the new host.

Is there a way to have a "fixed" hostname?

What I did was to create some kind of proxy service that my applications connects to:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-main-primary
  namespace: cnpg-system
spec:
  selector:
    cnpg.io/cluster: main-v2
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
```

So if the cluster name changes, I just need to update the selector.

Is this a good practice? or there is a more "native" way of handling this? Can a connection pooler, be used for this as well?

Thank you.
