### DISCUSSION TITLE
Improve migration guide to new container images from active cluster

### DISCUSSION THREAD

**Discussion by enguidanos-soluciones-web** [cloudnative-pg/cloudnative-pg#7542] [Q&A]
Hi,

Currently i have this production CNPG Cluster, deployed as 3 nodes with PodAntiAffinity:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: xxxxxxxxxxxx
  namespace: xxxxxxxxxxxx
spec:
  instances: 3
  startDelay: 300
  stopDelay: 300
  imageName: custom-image-xxxxxxxxxxxx
  imagePullSecrets:
    - name: elastic-container-registry-puller-credential
  storage:
    storageClass: longhorn
    size: 10Gi
  walStorage:
    storageClass: longhorn
    size: 10Gi
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      checkpoint_completion_target: "0.9"
      default_statistics_target: "100"
      effective_cache_size: "1536MB"
      effective_io_concurrency: "200"
      huge_pages: "off"
      maintenance_work_mem: "128MB"
      max_connections: "100"
      max_wal_size: "4GB"
      min_wal_size: "1GB"
      random_page_cost: "1.1"
      shared_buffers: "512MB"
      wal_buffers: "16MB"
      work_mem: "1310kB"
    pg_hba:
      - xxxxxxxxxxxx
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  superuserSecret:
    name: xxxxxxxxxxxx
  bootstrap:
    initdb:
      database: application
      owner: application
      secret:
        name: xxxxxxxxxxxx
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://xxxxxxxxxxxx
      endpointURL: https://s3.xxxxxxxxxxxx.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: s3-xxxxxxxxxxxx-bucket-writer
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-xxxxxxxxxxxx-bucket-writer
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 1
  resources:
    requests:
      memory: 2Gi
      cpu: "1"
    limits:
      memory: 2Gi
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: "true"
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

```

Also, there is a custom image for pgvector and potential other extensions:

```dockerfile
FROM postgres:17.4 AS local
COPY extensions.sh .
RUN /extensions.sh

FROM ghcr.io/cloudnative-pg/postgresql:17.4-bookworm AS cnpg
USER root
COPY extensions.sh .
RUN /extensions.sh
USER 26
```

```bash
#!/bin/bash

set -xe

# requirements
apt-get update
apt-get install -y build-essential make gcc pkg-config clang postgresql-server-dev-17 libssl-dev

# extension: pgvector
apt-get install -y --no-install-recommends postgresql-17-pgvector

# cleanup
apt-get remove -y build-essential make gcc pkg-config clang postgresql-server-dev-17 libssl-dev
rm -fr /tmp/*
rm -fr /var/lib/apt/lists/*
apt-get autoremove -y
```

I want to prepare the migration for the new image build process but i see this notes:

<img width="864" alt="Screenshot 2025-05-10 at 11 34 04" src="https://github.com/user-attachments/assets/a657c1de-b899-4fc2-90c5-9f3779122da3" />

And the problem is.... ¿i need to recreate a cluster and fill with data from a physical backup because i need to change the image build process? ¿where i have to change to the `[Barman Cloud Plugin](https://github.com/cloudnative-pg/plugin-barman-cloud) as a replacement for the native Barman Cloud` for standard images?

Thanks,
