### DISCUSSION TITLE
Is there a way to extend field to be updated in pod using gatekeeper?

### DISCUSSION THREAD

**Discussion by gnetanel** [cloudnative-pg/cloudnative-pg#7869] [Q&A]
I would like to add a sidecar container to my cluster pods; I have noticed that this is not supported and there are actualy issues with feature request on that. 

Instead, I tried to achieve same goal using gatekeeper by injecting the sidcard into the pod, however once trying to do that, I got an error log in operator that only subset of fields can be modified.
I wonder if there is a way to extend the list of field to be modified or maybe some other approach which allow me to inject the sidecar into the pods.
Adding the gatekeeper configuration for reference and the error that I got

Thanks in advance!

```

apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: inject-sideload-container
spec:
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchLabels:
        cnpg.io/cluster: database-cluster
    namespaces:
      - ncms
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  location: "spec.containers[name:sideload]"
  parameters:
    assign:
      value:
        name: sideload
        image: bcmt-registry:5000/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep infinity"]
```

Error:
{
    "level": "error",
    "ts": "2025-06-22T07:48:46.689960981-04:00",
    "msg": "Reconciler error",
    "controller": "cluster",
    "controllerGroup": "postgresql.cnpg.io",
    "controllerKind": "Cluster",
    "Cluster": {
        "name": "database-cluster",
        "namespace": "ncms"
    },
    "namespace": "ncms",
    "name": "database-cluster",
    "reconcileID": "7b32c6f9-4a21-45ae-ab69-eeb8f6a0bdbc",
    "error": "cannot updated metadata on pods: Pod \"database-cluster-1\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n  core.PodSpec{\n  \tVolumes:        {{Name: \"pgdata\", VolumeSource: {PersistentVolumeClaim: &{ClaimName: \"database-cluster-1\"}}}, {Name: \"scratch-data\", VolumeSource: {EmptyDir: &{}}}, {Name: \"shm\", VolumeSource: {EmptyDir: &{Medium: \"Memory\"}}}, {Name: \"kube-api-access-fkk29\", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: \"token\"}}, {ConfigMap: &{LocalObjectReference: {Name: \"kube-root-ca.crt\"}, Items: {{Key: \"ca.crt\", Path: \"ca.crt\"}}}}, {DownwardAPI: &{Items: {{Path: \"namespace\", FieldRef: &{APIVersion: \"v1\", FieldPath: \"metadata.namespace\"}}}}}}, DefaultMode: &420}}}},\n  \tInitContainers: {{Name: \"bootstrap-controller\", Image: \"bcmt-registry:5000/cloudnative-pg/cloudnative-pg:1.26.0@sha256:d\"..., Command: {\"/manager\", \"bootstrap\", \"/controller/manager\", \"--log-level=info\"}, Env: {{Name: \"TZ\", Value: \"Canada/Eastern\"}}, ...}},\n  \tContainers: []core.Container{\n  \t\t{Name: \"postgres\", Image: \"bcmt-registry:5000/cloudnative-pg/postgresql:16@sha256:51fdf0d55\"..., Command: {\"/controller/manager\", \"instance\", \"run\", \"--status-port-tls\", ...}, Ports: {{Name: \"postgresql\", ContainerPort: 5432, Protocol: \"TCP\"}, {Name: \"metrics\", ContainerPort: 9187, Protocol: \"TCP\"}, {Name: \"status\", ContainerPort: 8000, Protocol: \"TCP\"}}, ...},\n  \t\t{\n  \t\t\t... // 9 identical fields\n  \t\t\tResizePolicy:  nil,\n  \t\t\tRestartPolicy: nil,\n- \t\t\tVolumeMounts: []core.VolumeMount{\n- \t\t\t\t{\n- \t\t\t\t\tName:      \"kube-api-access-fkk29\",\n- \t\t\t\t\tReadOnly:  true,\n- \t\t\t\t\tMountPath: \"/var/run/secrets/kubernetes.io/serviceaccount\",\n- \t\t\t\t},\n- \t\t\t},\n+ \t\t\tVolumeMounts:  nil,\n  \t\t\tVolumeDevices: nil,\n  \t\t\tLivenessProbe: nil,\n  \t\t\t... // 3 identical fields\n  \t\t\tTerminationMessagePath:   \"/dev/termination-log\",\n  \t\t\tTerminationMessagePolicy: \"File\",\n- \t\t\tImagePullPolicy:          \"Always\",\n+ \t\t\tImagePullPolicy:          \"IfNotPresent\",\n  \t\t\tSecurityContext:          nil,\n  \t\t\tStdin:                    false,\n  \t\t\t... // 2 identical fields\n  \t\t},\n  \t},\n  \tEphemeralContainers: nil,\n  \tRestartPolicy:       \"Always\",\n  \t... // 29 identical fields\n  }\n",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"
}
