### DISCUSSION TITLE
multiple accesses to same WAL file during Switchover

### DISCUSSION THREAD

**Discussion by legrandlegrand** [cloudnative-pg/cloudnative-pg#7883] [Q&A]
Hello,
analyzing switchover duration with this S3 configuration

```
  backup:
    barmanObjectStore:
      serverName: pg-demo-im-5
      destinationPath: s3://d4i/
      endpointURL: http://minio.minio-operator.svc.cluster.local
      s3Credentials:
        accessKeyId:
          name: pg-demo-backup-credentails
          key: ACCESS_KEY
        secretAccessKey:
          name: pg-demo-backup-credentails
          key: SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 3
      data:
        compression: gzip
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "7d"
```

I noticed access to the same WAL File multiple times:
```
{"level":"info","ts":"2025-06-24T09:41:35.175921604Z","logger":"wal-restore","msg":"WAL file not found in the recovery object store","logging_pod":"pg-demo-im-2","walName":"00000009.history","options":["--endpoint-url","http://minio.minio-operator.svc.cluster.local","--cloud-provider","aws-s3","s3://d4i/","pg-demo-im-5"],"startTime":"2025-06-24T09:41:34.668373828Z","endTime":"2025-06-24T09:41:35.175869216Z","elapsedWalTime":0.507495398}
{"level":"info","ts":"2025-06-24T09:41:36.09858991Z","logger":"wal-restore","msg":"WAL file not found in the recovery object store","logging_pod":"pg-demo-im-2","walName":"000000080000000000000013","options":["--endpoint-url","http://minio.minio-operator.svc.cluster.local","--cloud-provider","aws-s3","s3://d4i/","pg-demo-im-5"],"startTime":"2025-06-24T09:41:35.305817446Z","endTime":"2025-06-24T09:41:36.0985678Z","elapsedWalTime":0.792750319}
{"level":"info","ts":"2025-06-24T09:41:36.99446749Z","logger":"wal-restore","msg":"WAL file not found in the recovery object store","logging_pod":"pg-demo-im-2","walName":"000000080000000000000013","options":["--endpoint-url","http://minio.minio-operator.svc.cluster.local","--cloud-provider","aws-s3","s3://d4i/","pg-demo-im-5"],"startTime":"2025-06-24T09:41:36.231445573Z","endTime":"2025-06-24T09:41:36.994446356Z","elapsedWalTime":0.763000789}
{"level":"info","ts":"2025-06-24T09:41:37.633759735Z","logger":"wal-restore","msg":"WAL file not found in the recovery object store","logging_pod":"pg-demo-im-2","walName":"00000009.history","options":["--endpoint-url","http://minio.minio-operator.svc.cluster.local","--cloud-provider","aws-s3","s3://d4i/","pg-demo-im-5"],"startTime":"2025-06-24T09:41:37.129354562Z","endTime":"2025-06-24T09:41:37.633727302Z","elapsedWalTime":0.504372758}
{"level":"info","ts":"2025-06-24T09:41:38.30848079Z","logger":"wal-restore","msg":"Restored WAL file","logging_pod":"pg-demo-im-2","walName":"00000008.history","startTime":"2025-06-24T09:41:37.823421922Z","endTime":"2025-06-24T09:41:38.308458167Z","elapsedWalTime":0.485036256}
{"level":"info","ts":"2025-06-24T09:41:38.308637347Z","logger":"wal-restore","msg":"WAL restore command completed (parallel)","logging_pod":"pg-demo-im-2","walName":"00000008.history","maxParallel":3,"successfulWalRestore":1,"failedWalRestore":2,"endOfWALStream":false,"startTime":"2025-06-24T09:41:37.819336269Z","downloadStartTime":"2025-06-24T09:41:37.823398883Z","downloadTotalTime":0.485234046,"totalTime":0.489296702}
```

Look at 
"walName":"00000009.history"
"walName":"000000080000000000000013"

Is that expected ?
Regards
PAscal
