### DISCUSSION TITLE
Cannot extract Pod status - Failed upgrade to 1.17.1 - Helm Chart 0.15.1

### DISCUSSION THREAD

**Discussion by onedr0p** [cloudnative-pg/cloudnative-pg#830] [General]
I went to upgrade to the 0.15.1 helm chart and noticed that the postgres-3 pod is stuck in a non-ready state.

```
❯ k get po | rg postgres
postgres-1                                                        1/1     Running     2 (2d16h ago)    5d20h
postgres-2                                                        1/1     Running     2 (2d16h ago)    5d20h
postgres-3                                                        0/1     Running     0                7m17s
postgres-cloudnative-pg-68699f8fd5-5tcbw                          1/1     Running     0                116s
```

## Operator Logs

```
{"level":"info","ts":1665150369.7360933,"msg":"Cannot extract Pod status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","cluster":{"name":"postgres","namespace":"default"},"namespace":"default","name":"postgres","reconcileID":"6fb1a239-558b-4fe2-bbcf-67fca04fbdf7","uuid":"654c488f-4646-11ed-8526-0eceb761ea56","name":"postgres-3","error":"error status code: 500, body: failed to connect to `host=/controller/run user=postgres database=postgres`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))\n"}
```

## postgres-3 Logs

```
{"level":"info","ts":1665150506.8953855,"logger":"postgres","msg":"record","logging_pod":"postgres-3","record":{"log_time":"2022-10-07 13:48:26.895 UTC","user_name":"postgres","database_name":"postgres","process_id":"12008","connection_from":"[local]","session_id":"63402e2a.2ee8","session_line_num":"1","session_start_time":"2022-10-07 13:48:26 UTC","transaction_id":"0","error_severity":"FATAL","sql_state_code":"57P03","message":"the database system is starting up","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":1665150506.895522,"msg":"Instance status probe failing","logging_pod":"postgres-3","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))"}
```

## System Information

k3s 1.24.6
Flux 0.35.0

## Helm Configuration

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    crds:
      create: false
    config:
      data:
        INHERITED_ANNOTATIONS: kyverno.io/ignore
```

## Cluster configuration

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.default.svc.cluster.local:9000/
      serverName: postgres-v1
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
```
