### DISCUSSION TITLE
GKE Credentials for backups

### DISCUSSION THREAD

**Discussion by Smana** [cloudnative-pg/cloudnative-pg#833] [Q&A]
Hey everyone,

I'm currently testing cnpg operator on a GKE (Google Cloud) environment.
I'd like to store the backups in GCS and I followed [this doc](https://cloudnative-pg.io/documentation/1.17/backup_recovery/#google-cloud-storage)

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
[...]
spec:
  backup:
    barmanObjectStore:
      destinationPath: "gs://<destination path here>"
      googleCredentials:
        gkeEnvironment: true
```

But honestly I don't understand how the permissions are given to the pod to write backups into GCS.
It is indeed mentioned

> This method will require carefully defined permissions for cluster and pods, which have to be defined by a cluster administrator.

Currently with the default installation I have I get a permission error:

```console
{"level":"info","ts":1665218642.5000658,"logger":"barman-cloud-wal-archive","msg":"2022-10-08 08:44:02,499 [272] ERROR: Barman cloud WAL archiver exception: 403 POST https://storage.googleapis.com/storage/v1/b?project=myproject&prettyPrint=false: Access denied.","pipe":"stderr","logging_pod":"instance-1"} 
```

What did I miss please?

Regards,
Smana

**Comment by Smana** [comment]
Otherwise I'll use the json credentials file alternative. I just wanted to understand If there was another method :)

**Comment by Smana** [comment]
This is probably what I'm looking for [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). I'll test that and confirm.
If so that'd be cool to have a pointer in the CNPG doc. Don't you think?

**Reply by Smana** [reply]
Well I'm not sure I can add an annotation to the service account loaded by the `Cluster`'s pods.
According to this [doc](https://cloudnative-pg.io/documentation/1.17/labels_annotations/) if I add it at the cluster definition level, it should be propagated to all underlying resources.
Unfortunately, it doesn't seem to work as expected.

here is my cluster's metadata

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster          
metadata:                         
  annotations:          
    iam.gke.io/gcp-service-account: ....gserviceaccount.com               
  labels:
```

And it's not propagated to the serviceaccount.
Still digging....
