### DISCUSSION TITLE
Cannot access replicated cluster by pod IP

### DISCUSSION THREAD

**Discussion by netthier** [cloudnative-pg/cloudnative-pg#862] [Q&A] [answered]
I have a database cluster configured like this:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: some-ns
spec:
  instances: 1
  bootstrap:
    recovery:
      source: db
  replica:
    enabled: true
    source: db
  externalClusters:
    - name: db
      barmanObjectStore:
        destinationPath: "s3://some-bucket"
        endpointURL: "https://s3.eu-central-1.wasabisys.com"
        s3Credentials:
          accessKeyId:
            name: db-secret
            key: WSBI_ACCESS_KEY
          secretAccessKey:
            name: db-secret
            key: WSBI_SECRET_KEY
  storage:
    size: 100Gi
```
The cluster deploys and correctly downloads the base backup and WALs.
Executing `psql` in the pod works and shows all tables.
However, when attempting to access the cluster using the pod IP or through the service, the connection times out.
Running `PGPASSWORD=hunter2 psql -h db-r -p 5432 -d some_db -U some_user` in the same pod fails with a timeout, though the IP resolves correctly. (user/password replaced for obvious reasons)
`pg_isready` reports `/controller/run:5432 - accepting connections` despite that.
This also applies to any attempts at accessing the cluster from another pod.

My goal with this Cluster is to have a read-only replica of a certain production database running in a different cluster to develop against.
