### DISCUSSION TITLE
Failing to import a database with plpgsql functions

### DISCUSSION THREAD

**Discussion by scvalex** [cloudnative-pg/cloudnative-pg#969] [General]
TL;DR I'm trying to bootstrap import a database with `plpgsql` functions, but it fails with `pg_restore: error: could not execute query: ERROR:  language "plpgsql" does not exist`.  I'm probably not the first person to try this, so what's the trick to getting this to work?

Details:

I'm trying to convert an old PostgreSQL pod to cloudnative-pg.  I'm using the microservice import:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-data
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  storage:
    storageClass: "openebs-zfspv-lazy"
    size: 100Gi
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - dosare
        source:
          externalCluster: old-cluster
  externalClusters:
    - name: old-cluster
      connectionParameters:
        host: postgres
        user: dosare
        dbname: dosare
      password:
        name: dosare-config
        key: pg-password
```

This fails during the `pg_restore` with:

```
...
"level":"info","ts":1667911904.2648947,"logger":"pg_dump","msg":"pg_dump: dumping contents of table \"public.dosare\"","pipe":"stderr","logging_pod":"pg-data-1"}
{"level":"info","ts":1667911996.6173406,"msg":"dropping extensions from the target (empty) database","logging_pod":"pg-data-1"}
{"level":"info","ts":1667911996.6208682,"msg":"dropping extension from target database","logging_pod":"pg-data-1","extName":"plpgsql"}
{"level":"info","ts":1667911996.6550565,"msg":"temporarily granting superuser permission to owner user","logging_pod":"pg-data-1","owner":"app"}
{"level":"info","ts":1667911996.6687803,"msg":"executing database importing section","logging_pod":"pg-data-1","databaseName":"dosare","section":"pre-data"}
{"level":"info","ts":1667911996.6688378,"msg":"Running pg_restore","logging_pod":"pg-data-1","cmd":"pg_restore","options":["-U","postgres","--no-owner","--no-privileges","--role=app","-d","app","--section","pre-data","/var/lib/postgresql/data/pgdata/dumps/dosare.dump"]}
{"level":"info","ts":1667911996.7049005,"logger":"pg_restore","msg":"pg_restore: while PROCESSING TOC:","pipe":"stderr","logging_pod":"pg-data-1"}
{"level":"info","ts":1667911996.7049184,"logger":"pg_restore","msg":"pg_restore: from TOC entry 214; 1255 16391 FUNCTION diesel_manage_updated_at(regclass) dosare","pipe":"stderr","logging_pod":"pg-data-1"}
{"level":"info","ts":1667911996.7049224,"logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  language \"plpgsql\" does not exist","pipe":"stderr","logging_pod":"pg-data-1"}
...
```

I tried to solve this a `postInitTemplateSQL`, but that doesn't seem to help:

```
      postInitTemplateSQL:
        - CREATE OR REPLACE LANGUAGE plpgsql;
```

I think what's going on is that the restore is dropping all the extensions, including `plpgsql` in https://github.com/cloudnative-pg/cloudnative-pg/blob/67285747a43754017e0a1fa16deafd00371aa1b7/pkg/management/postgres/logicalimport/database.go#L299

The comment there implies that `pg_restore` will recreate the extension, but that doesn't seem to be happening.  For reference, I also don't ever remember having to enable `plpgsql`; I always thought it was enabled by default.

Is there some way to tell cloudnative-pg to not drop extensions, or is there some other hook where I can add the extension during restore?
