### ISSUE TITLE
Too many bootstrap types specified error

### ISSUE THREAD

**Issue by jgillich** [cloudnative-pg/cloudnative-pg#1006]
I have a controller that writes a Cluster object with the following bootstrap config:

```go
Bootstrap: &cnpgv1.BootstrapConfiguration{
	Recovery: &cnpgv1.BootstrapRecovery{
		Source: "pool1-cnpg",
	},
},
```

This is what I get when I marshal to yaml:
```
bootstrap:
  initdb: null
  recovery:
    backup: null
    source: pool1-cnpg
    recoverytarget: null
    database: ""
    owner: ""
    secret: null
  pgbasebackup: null
```

But when I try to apply this, I get 

```
admission webhook \"vcluster.kb.io\" denied the request: Cluster.cluster.cnpg.io \"pool1-cnpg\" is invalid: spec.bootstrap: Invalid value: \"\": Too many bootstrap types specified
```

Using v1.18

Can someone tell me what I'm doing wrong? I have no clue what's happening. I looked at the validator code and it looks fine to me
