### ISSUE TITLE
Read backup credentials from any namespace

### ISSUE THREAD

**Issue by cod-r** [cloudnative-pg/cloudnative-pg#1048]
In my org the developers create their own cnpg Clusters in their own namespace. Right now for every cluster created we need to also create a Secret containing the s3 credentials for backups. 
### Proposal
Read backup credentials from a different namespace than the one where the `Cluster` resource is created.

We (the admins) create a single Secret in a namespace not accessible by the developers, and they can just reference the secret from that namespace without having access to it.

Example:
```yaml
  backup:
    barmanObjectStore:
      s3Credentials:
        namespace: admin-only    # set the isolated namespace here
        accessKeyId:
          name: do-s3-creds
          key: ACCESS_KEY
        secretAccessKey:
          name: do-s3-creds
          key: SECRET_KEY
```
