### ISSUE TITLE
Customize labels and annotations for the service account

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#1083]
Based on the use case triggered in #756, we could solve the issue on a more general case - rather than having to document it. This would allow us to customize workload identities in public cloud providers such as EKS, AKS, and GKE.

We could add a new section in the cluster's `spec` to enable definition of custom labels and annotations for the service account that controls the cluster. This enables us to associate the service account to an IAM role or a workload identity. For example:

In Azure:

```
...
  serviceAccount:
    labels:
      azure.workload.identity/use: true
    annotations:
      azure.workload.identity/client-id: XXXXXXXXXXXX
```

or, in EKS:

```
...
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
```

or, in GKE:

```
...
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: GSA_NAME@GSA_PROJECT.iam.gserviceaccount.com
```

Please update the documentation accordingly, especially for the backup part.
