### ISSUE TITLE
Introduce environment variable definition for each workload in a cluster

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#1090]
Add the `.spec.env` section to introduce support for definition of environment variables for any workload that runs within the specified cluster:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  storage:
    size: 1Gi

  env:
  # Requested in #492
  - name: TZ
    value: Europe/Rome
  # Requested in #807
  - name: HTTP_PROXY
    value: http://someproxy:8080
  - name: HTTPS_PROXY
    value: http://someproxy:8080
  # This is blocked by the webhook
  - name: PGDATA
    value: /var/lib/postgresql/data/pgdata
```

The webhook should block any attempt to define a variable that starts with PG (see https://www.postgresql.org/docs/current/libpq-envars.html).

Changing the content of the `env` section inevitably triggers a rolling update (documentation needs to be updated to cover this case too).

Such environment definition is inherited by all the workloads that are initiated in a cluster's lifecycle, including initialization jobs, and auxiliary commands such as WAL archiver or backup process.
