### ISSUE TITLE
Tablespaces, including temporary

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#11]
Add declarative support for tablespace, including temporary ones. This improves vertical scalability in conjunction with declarative partitioning supported by Postgres, as well as for indexes.

**Comment by adminnz** [comment]
Maybe allowing more direct control over the volumes in the Cluster CRD?

You could declare the volumes & their mounts (effectively using the existing k8s PersistentVolumeSpec).
Then reference them with tablespaces. 

Something like:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-with-tablespaces
spec:
  instances: 3

  volumes:
  - name: data_slow 
    storageClassName: standard
    capacity: 
       storage: 10Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /mnt/data_slow
  - name: data_fast
    storageClassName: premium
    capacity: 
       storage: 5Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /mnt/data_fast
 
  tablespaces:
    tblspace_fast:
       volume: data_fast
    tblspace_slow:
       volume: data_slow
```
