### ISSUE TITLE
WAL volume is resized without a user request

### ISSUE THREAD

**Issue by lmocofan** [cloudnative-pg/cloudnative-pg#1190]
The operator automatically resizes the WAL volume on a new cluster (in the end it matches data volume size).

  storage:
    storageClass: ebs-gp3
    size: 16Gi
  walStorage:
    storageClass: ebs-gp3
    size: 8Gi

**Comment by mirakladp** [comment]
Hello ,

We have the same problem in AWS EKS cluster.

```
  instances: 2

  bootstrap:
    initdb:
      database: amaumo_db
      owner: amaumo
      secret:
        name: db-user

  storage:
    storageClass: standard-ssd
    size: 2Gi
  walStorage:
    storageClass: standard-ssd
    size: 1Gi
```

During the `initdb` phase the volumes are correct but after, the walStorage takes the same value than the main storage volume:

Init phase:
```
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cnpg-amaumo-cluster-v1-1       Bound    pvc-dd57c357-f50e-4919-8e97-06606c455824   2Gi        RWO            standard-ssd   39s
cnpg-amaumo-cluster-v1-1-wal   Bound    pvc-6c2ccbce-9017-4fa5-8841-c3e416c8f479   1Gi        RWO            standard-ssd   39s

```

After the init:
```
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cnpg-amaumo-cluster-v1-1       Bound    pvc-dd57c357-f50e-4919-8e97-xxxxxxxxxxxx   2Gi        RWO            standard-ssd   12m
cnpg-amaumo-cluster-v1-1-wal   Bound    pvc-6c2ccbce-9017-4fa5-8841-xxxxxxxxxxxx   2Gi        RWO            standard-ssd   12m
cnpg-amaumo-cluster-v1-2       Bound    pvc-426837bd-a526-4cfe-95e0-xxxxxxxxxxxx   2Gi        RWO            standard-ssd   3m22s
cnpg-amaumo-cluster-v1-2-wal   Bound    pvc-34696862-22d5-4172-8d23-xxxxxxxxxxxx   2Gi        RWO            standard-ssd   3m22s
```
