### ISSUE TITLE
Catalog of PostgreSQL images

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#12]
From a usability standpoint, it would be great if had to only specify the major version of PostgreSQL in an image (e.g. quay.io/enterprisedb/postgresql:14) and let the operator figure out which image to pull down and when to update the operands.

Every time a new set of images is built in the postgres-containers project, update a JSON file that contains the metadata of the container images, including the major version (14, 13, …), the full version (e.g. 14.2), the tag and the digest.

This is still a stub of idea. We need further analysis.

**Comment by gbartolini** [comment]
A proposal is to add a new CRD called `PostgresImageCatalog`, like in the following example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: PostgresImageCatalog
metadata:
  name: postgresql
spec:
  baseName: …
  versions:
   - major: “15”
      fullVersion: “15.1”
      imageID: xxxx
      tag: 15.1-2-debian
     architectures? … registryURL?
```

We should shop around and look for well defined and possibly standard ways to define image metadata (for example goharbor?).

The idea is that CloudNativePG ships with a predefined catalog that is updated with each release of CloudNativePG.

The catalog could be used in the `Cluster` definition as follows:

``` yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageCatalog:
    name: postgresql
    major: 15
```
