### ISSUE TITLE
Add volume projection template

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#1259]
# The problem

It is impossible to mount custom files inside the Postgres pods, which impacts the possibility of using several Postgres features and extensions that require additional data files.

# The proposed solution

Introduce a [projected volume](https://kubernetes.io/docs/concepts/storage/projected-volumes/) template that allows the user to mount arbitrary data under the `/projected` directory.

The `.spec.projectedVolumeTemplate` field contains a `corev1.ProjectedVolumeSource` object that is always mounted on the `/projected` directory inside the Postgres pods (either an Instance or an initialization Job)

# Example

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  projectedVolumeTemplate:
    sources:
      - secret:
          name: mysecret
          items:
            - key: username
              # resulting path: /projected/my-group/my-username
              path: my-group/my-username
```
