### ISSUE TITLE
No target backup found

### ISSUE THREAD

**Issue by danotrampus** [cloudnative-pg/cloudnative-pg#1313]
Hi,

I'm trying to replicate what the doc says in [Replica Cluster](https://cloudnative-pg.io/documentation/1.16/replica_cluster/), but when i try to create the replica cluster on a second provider the recovery process gives me the following error:
```
$ kubectl logs -n starten-29-dev odoo-db-1-full-recovery-s85kw
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":1673244415.202184,"msg":"Recovering from external cluster","logging_pod":"odoo-db-1","sourceName":"odoo-db"}
{"level":"error","ts":1673244415.7991278,"msg":"Error while restoring a backup","logging_pod":"odoo-db-1","error":"no target backup found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:84\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:59\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250"}
```
When in fact there are multiple backups already store on my S3 backup store:
![image](https://user-images.githubusercontent.com/11494867/211251902-3a3d62fd-8f0f-419f-9d58-419fa46efd33.png)

**¿What am i doing wrong?**

### Additional Information

Kubernetes version: 1.24.8
CloudNativePG Operation version: 1.18.1

Manifest of primary cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1048kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
  storage:
    storageClass: do-block-storage
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://backups/
      endpointURL: https://starten.us-southeast-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          name: odoo-db-backup-secret
          key: BACKUP_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: odoo-db-backup-secret
          key: BACKUP_S3_ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
  monitoring:
    enablePodMonitor: true
```

Manifest of backup on primary cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cluster-backup
spec:
  cluster:
    name: odoo-db
```

Manifest of replica cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1048kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
  storage:
    storageClass: linode-block-storage
    size: 1Gi
  bootstrap:
    recovery:
      source: odoo-db
  replica:
    enabled: true
    source: odoo-db
  externalClusters:
  - name: odoo-db
    barmanObjectStore:
      destinationPath: s3://backups/
      endpointURL: https://starten.us-southeast-1.linodeobjects.com
      serverName: odoo-db
      s3Credentials:
        accessKeyId:
          name: odoo-db-backup-secret
          key: RESTORE_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: odoo-db-backup-secret
          key: RESTORE_S3_ACCESS_SECRET_KEY
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
  monitoring:
    enablePodMonitor: true
```

Thx.

**Comment by maaft** [comment]
Got the exact same issue. Are the docs maybe lacking?

**Comment by danotrampus** [comment]
After several hours of debbuging i manage to make it work.

 Manifest of primary cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1048kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
  storage:
    storageClass: do-block-storage
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://starten/
      endpointURL: https://us-southeast-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          name: odoo-db-backup-secret
          key: BACKUP_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: odoo-db-backup-secret
          key: BACKUP_S3_ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
  monitoring:
    enablePodMonitor: true
```

Manifest of backup on primary cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cluster-backup
spec:
  cluster:
    name: odoo-db
```

Manifest of replica cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1048kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
  storage:
    storageClass: linode-block-storage
    size: 1Gi
  bootstrap:
    recovery:
      source: odoo-db
  replica:
    enabled: true
    source: odoo-db
  externalClusters:
  - name: odoo-db
    barmanObjectStore:
      destinationPath: s3://starten/
      endpointURL: https://us-southeast-1.linodeobjects.com
      serverName: odoo-db
      s3Credentials:
        accessKeyId:
          name: odoo-db-backup-secret
          key: RESTORE_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: odoo-db-backup-secret
          key: RESTORE_S3_ACCESS_SECRET_KEY
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
  monitoring:
    enablePodMonitor: true
```

The main thing to notice is that you have to point your `endpointUrl` to the base url of your provider WITHOUT your bucket name and put your bucket name in `destinationPath`. Example:
 
Wrong:
```
destinationPath: s3://some_folder_name/
endpointURL: https://BUCKET_NAME.us-southeast-1.linodeobjects.com
```

Right:
```
destinationPath: s3://BUCKET_NAME/
endpointURL: https://us-southeast-1.linodeobjects.com
```

Sorry for the trouble. I hope this explanation helps the next one.
