### ISSUE TITLE
External cluster password secret ignored in bootstrap with pg_dump import

### ISSUE THREAD

**Issue by sbidoul** [cloudnative-pg/cloudnative-pg#1346]
When importing from an external cluster using the pg_dump/microservice method, it seems the external cluster password is ignored when provided as a secret reference. This works fine when the password is passed in connectionParameters.

This config works:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-app
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-10
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      import:
        type: microservice
        databases:
          - app
        source:
          externalCluster: external-postgres
  externalClusters:
    - name: external-postgres
      connectionParameters:
        host: external-postgres.namespace.svc
        user: postgres
        dbname: postgres
        password: "*************"
```

while this one does not seem to work

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-app
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6-10
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      import:
        type: microservice
        databases:
          - app
        source:
          externalCluster: external-postgres
  externalClusters:
    - name: external-postgres
      connectionParameters:
        host: external-postgres.namespace.svc
        user: postgres
        dbname: postgres
      password:
        name: external-postgres-secret
        key: password
```

I have tripled checked that the `external-postgres-secret` exists as well as the `password` key in it.
