### ISSUE TITLE
Postgres cannot get out of recovery mode on restore

### ISSUE THREAD

**Issue by dspeck1** [cloudnative-pg/cloudnative-pg#1361]
We are restoring a postgres cluster that crashed.  When doing a restore with this config.

```
  bootstrap:
    recovery:
      source: usdf-butler
      recoveryTarget:
        backupID: 20221210T000000
        targetTime: "2023-01-22 16:50:00.00000+00"

  externalClusters:
    - name: usdf-butler
      barmanObjectStore:
        destinationPath: s3://s3-name-removed
        endpointURL: http://url-removed:9000
        s3Credentials:
          accessKeyId:
            name: s3-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: s3-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
```

We get this error below after the backup is restored and the WAL playback.    The max_connection setting was changed from 500 to 1000 around a month ago.  We have tried setting this value to either 500 or 1000 in the cnpg database configuration.  We also tried deleting the restore pod, but the restore pod can never work change the recovery mode to false.  It appears that maybe the recovery pod does not respect CNPG cluster settings?  We currently can't get the system out of recovery mode even though the data restored.
```
 server after making the necessary configuration changes.","context":"WAL redo at 22B/D00000D0 for XLOG/PARAMETER_CHANGE: max_connections=1000 max_worker_processes=32 max_wal_senders=10 max_prepared_xacts=0 max_locks_per_xact=64 wal_level=logical wal_log_hints=on track_commit_timestamp=off","backend_type":"startup","query_id":"0"}} server after making the necessary configuration changes.","context":"WAL redo at 22B/D00000D0 for XLOG/PARAMETER_CHANGE: max_connections=1000 max_worker_processes=32 max_wal_senders=10 max_prepared_xacts=0 max_locks_per_xact=64 wal_level=logical wal_log_hints=on track_commit_timestamp=off","backend_type":"startup","query_id":"0"}}
```
