### ISSUE TITLE
Error while bootstrapping data directory

### ISSUE THREAD

**Issue by Sapp00** [cloudnative-pg/cloudnative-pg#1373]
Hi there,
when deploying a cluster, I receive this error all the time and cannot sucessfully create one. 

Cloudnative-PG is installed using the current helm chart:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 1.18.1
    releaseName: cnpg
    namespace: postgres
```

Full log (cluster-example-1-initdb-<uid>):
```
Defaulted container "initdb" out of: initdb, bootstrap-controller (init)
{"level":"info","ts":1675094246.6801445,"msg":"Creating new data directory","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"info","ts":1675094247.1110559,"logger":"initdb","msg":"The files belonging to this database system will be owned by user \"postgres\".
This user must also own the server process.

The database cluster will be initialized with this locale configuration:
  provider:    libc
  LC_COLLATE:  C
  LC_CTYPE:    C
  LC_MESSAGES: en_US.utf8
  LC_MONETARY: en_US.utf8
  LC_NUMERIC:  en_US.utf8
  LC_TIME:     en_US.utf8
The default text search configuration will be set to \"english\".

Data page checksums are disabled.

creating directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":1675094247.1112525,"logger":"initdb","msg":"Bus error
child process exited with exit code 135
initdb: removing data directory \"/var/lib/postgresql/data/pgdata\"
","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":1675094247.1113946,"msg":"Error while bootstrapping data directory","logging_pod":"cluster-example-1","error":"error while creating the PostgreSQL instance: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error
	pkg/management/log/log.go:127
github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error
	pkg/management/log/log.go:165
github.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand
	internal/cmd/manager/instance/initdb/cmd.go:146
github.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2
	internal/cmd/manager/instance/initdb/cmd.go:103
github.com/spf13/cobra.(*Command).execute
	pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	cmd/manager/main.go:64
runtime.main
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250"}
Error: error while creating the PostgreSQL instance: exit status 1
```

The cluster:
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
    storageClass: "mayastor-2"
```

Storage Class:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-2
parameters:
  repl: '2'
  protocol: 'nvmf'
  ioTimeout: '60'
  local: 'true'
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
```

Thank you and best regards
