### ISSUE TITLE
Allow `initdb` and `recovery` options together in bootstrap config

### ISSUE THREAD

**Issue by rustygreen** [cloudnative-pg/cloudnative-pg#1424]
I am trying to define the initdb database/owner as well as the recovery together in the `bootstrap` section, but I get the error: **`invalid: spec.bootstrap: Invalid value: "": Too many bootstrap types specified`**.

```yaml
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
    recovery:
      source: postgres-backup
```

I'm confused why this is not valid? When the cluster is first created (and there is no backup available yet) I want it to create with the specified database and owner. If I rebuild the cluster and the backup exists then I would expect it to restore from that backup (ignoring the initdb config).

Am I looking at this wrong? I don't want it to be a 2-step process (first define initdb and then remove it and define the recovery section after the cluster is created the first time) - that makes the gitops workflow much less repeatable. My setup uses FluxCD and I need the entire cluster definition to work as-is the first time (with or without an available backup).
