### ISSUE TITLE
Pods should set Ephemeral storage limit 

### ISSUE THREAD

**Issue by yonglian** [cloudnative-pg/cloudnative-pg#1548]
As discussed with EDB team during an interlock call between EDB and IBM,  hosted by Prasa U,  we agreed to open this ticket to track this request.  

Even though EDB pods are not using ephemeral storage today and no plan to use it down the row, to be safe and avoid any potential trouble down the road,  EDB team will look at adding Ephemeral limit setting  with very minimal value (such as 10MB or less). 

Some certification requirements in Cloud pak for data depend on such settings to pass (instead of documenting with some exceptions)

**Comment by yonglian** [comment]
I have no permission to add anything else like labels, etc. Please help to add and correct as needed. Thanks

**Comment by nitinpatil-edb** [comment]
Hello Team,

Is there any update on this JIRA ? 

Customer is looking for an update and they raised follow-up ticket on the support portal 96641.

**Comment by sxd** [comment]
Hi @yonglian 

when you mean " Ephemeral limit" which limit you mean? there's more than one

Regards

**Comment by sxd** [comment]
Hi @yonglian 

I'm following this Kubernetes page https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage so I can see two different ways to limit

Kind regards!

**Comment by yonglian** [comment]
hi @sxd  

you link has a good example as shown below:

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi
```

so ff you are using the pod or container setting,  via the following:
```
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
```

if your pod is using `emptyDir` as part of the definition,  then you should also add `sizeLimit` to have the limit setting (see last 3 roles in the sample above). 

I assume those are the ways you are referring to.  If I misunderstood, let me know.

**Comment by yonglian** [comment]
Here  are more details / instructions given to other CPD services on this topic. 

<img width="903" alt="image" src="https://github.com/cloudnative-pg/cloudnative-pg/assets/28273173/faaaed9b-8987-4a4b-8af4-91e0578cb857">

```
apiVersion: v1
kind: Pod
metadata:
name: ephemeral-storage-pod-example
spec:
containers:
- name: ui
image: "cp.stg.icr.io/cp/my-example-frontend-ui:latest"
volumeMounts:
- mountPath: /etc/config
name: config-vol
resources:
requests:
cpu: "0.5"
memory: "100Mi"
ephemeral-storage: "1Gi"
limits:
cpu: "1"
memory: "200Mi"
ephemeral-storage: "5Gi"
- name: nginx
image: "cp.stg.icr.io/cp/sample-panamax-nginx:latest"
volumeMounts:
- mountPath: /cache
name: cache-volume
resources:
requests:
ephemeral-storage: "2Mi"
volumes:
- name: cache-volume
emptyDir:
sizeLimit: "6Mi"
- name: config-vol
configMap:
name: ephemeral-storage-configmap
items:
- key: jsonString
path: data
```

>In the example above, both containers in the Pod require ephemeral storage, but they require a different amount. The total amount of ephemeral storage requested at the time the Pod is created is 1Gi + 2Mi and the total amount of ephemeral storage the Pod is allowed to use is 5Gi + 6Mi.

>Additionally, note that the ephemeral limit is specified differently for the containers - the top container is using a ConfigMap and specifying the ephemeral storage limit in its resources.limits while the second container is using emptyDir for its local storage and specifies the ephemeral storage limit using the emptyDir.sizeLimit property in the volumes section.

>The kubelet is managing the emptyDir as a resource, so if the containers in the Pod exceed the allocated ephemeral storage limit, the Pod will be evicted from the Node.

**Comment by jlong49** [comment]
Hey @yonglian,

Could you clarify specifically what you would like? Is it just defaults? We already have setting the ephemeral-storage available via the `resource` part of our cluster spec. For instance, you could set it in the following way:

```
spec:
   instances: 3
   resources:
     limits:
       ephemeral-storage: 1Gi

   storage:
     size: 1Gi
```
