### ISSUE TITLE
Allow Specifying Additional PodMonitor Labels

### ISSUE THREAD

**Issue by aphistic** [cloudnative-pg/cloudnative-pg#1562]
Hi!

I'd like the ability to provide additional labels that are added to a `Cluster`'s `PodMonitor` when it's created.

In my cluster, I'm using the Prometheus Operator to set up scraping, and the `Prometheus` instance is set up with specific `PodMonitor` or `ServiceMonitor` labels to specify which Prometheus instance should scrape it.

I had some thoughts about something like:
```
monitoring:
  podMonitor:
    enabled: true
    additionalLabels:
      someLabel: withValue
```

But that would duplicate the existing `enablePodMonitor` value, so I thought I'd create this and see what you all think!

**Comment by itay-grudev** [comment]
I have a similar situation. In my case, I need to specify the prometheus release name in the `PodMonitor` labels it it won't get scraped. My case requires the following:

My case is:

```yaml
monitoring:
  podMonitor:
    enabled: true
    labels:
      release: prometheus
```

P.S. I suggest calling it just `labels` as opposed to as that's what most charts use.
