### ISSUE TITLE
Better support for sidecar containers in batch jobs (aka Linkerd support)

### ISSUE THREAD

**Issue by Otterpohl** [cloudnative-pg/cloudnative-pg#1678]
CloudNativePG uses Kubernetes jobs for various operator actions, initialising databases, joining to a cluster etc.

However, when used in conjunction with Linkerd, Kubernetes jobs do not terminate as the injected sidecar running the Linkerd Proxy runs indefinitely. For details: https://tech.ingrid.com/on-linkerd-and-kubernetes-jobs

Although there are a few options, the most reasonable way forward is to introduce support for the `/shutdown` endpoint of the [Linkerd Proxy](https://linkerd.io/2.12/tasks/graceful-shutdown/#graceful-shutdown-of-job-and-cronjob-resources)

As discussed with @leonardoce, I will take a look at implementing a solution similiar to that of `istio`'s `/quitquitquit` as implemented in cloudnative-pg [here](https://github.com/cloudnative-pg/cloudnative-pg/pull/967)

**Comment by 99hops** [comment]
@sxd @Otterpohl I just got into this issue today and I belive it's still/again happening the `-join` Jobs don't terminate with the linkerd-proxy remaining the only active container.. 

I am using the latest helms on both cnpg+linkerd and I played a lot with annotations without luck.
Can someone please revisit this? Here is slack link to thread https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1727335916419619


 ```
bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: old
```
Last lines of import-1 pod
```
{"level":"info","ts":"2024-09-26T11:26:28Z","msg":"Running initdb --sync-only","logging_pod":"postgresql-1-import","pgdata":"/var/lib/postgresql/data/pgdata"}

{"level":"info","ts":"2024-09-26T11:26:28Z","logger":"initdb","msg":"syncing data to disk ... ok\n","pipe":"stdout","logging_pod":"postgresql-1-import"} 
```

At this point import routine is stuck forever waiting for the pod to be manually killed.

Please advice :cat:

**Comment by sxd** [comment]
@99hops this should be fixed a linkerd level just like istio already did, look for options here https://linkerd.io/2-edge/tasks/graceful-shutdown/#native-sidecar basically if they don't obey the shutdown endpoint there's nothing we can do about it

**Comment by 99hops** [comment]
Found solution here https://github.com/linkerd/linkerd2/discussions/13105

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      config.linkerd.io/proxy-admin-shutdown: enabled
```
