### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by tim-brand** [cloudnative-pg/cloudnative-pg#1689]
I've successfully created a cluster and migrated my existing data into it. It works fine.
Now I want to setup the backup, and there I've run into an issue.
I've configured a Minio endpoint, which is in my local network.
The error I got is:
```
ERROR: Barman cloud WAL archive check exception: maximum recursion depth exceeded while calling a Python object
```

The complete log:
```json
{"level":"info","ts":"2023-03-11T22:18:10Z","logger":"postgres","msg":"record","logging_pod":"dsmr-reader-2","record":{"log_time":"2023-03-11 22:18:10.989 UTC","process_id":"40873","connection_from":"10.244.0.135:34668","session_id":"640cfe22.9fa9","session_line_num":"1","session_start_time":"2023-03-11 22:18:10 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"XX000","message":"could not accept SSL connection: Success","backend_type":"not initialized","query_id":"0"}}
{"level":"info","ts":"2023-03-11T22:18:32Z","logger":"postgres","msg":"record","logging_pod":"dsmr-reader-2","record":{"log_time":"2023-03-11 22:18:32.370 UTC","process_id":"25","session_id":"640b3ed2.19","session_line_num":"95","session_start_time":"2023-03-10 14:29:38 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint starting: time","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2023-03-11T22:18:42Z","logger":"wal-archive","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"dsmr-reader-2"}
{"level":"info","ts":"2023-03-11T22:18:45Z","logger":"postgres","msg":"record","logging_pod":"dsmr-reader-2","record":{"log_time":"2023-03-11 22:18:45.766 UTC","process_id":"25","session_id":"640b3ed2.19","session_line_num":"96","session_start_time":"2023-03-10 14:29:38 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint complete: wrote 105 buffers (0.6%); 0 WAL file(s) added, 0 removed, 1 recycled; write=11.739 s, sync=1.206 s, total=13.397 s; sync files=47, longest=0.180 s, average=0.026 s; distance=16464 kB, estimate=29830 kB","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2023-03-11T22:18:47Z","logger":"barman-cloud-check-wal-archive","msg":"2023-03-11 22:18:47,651 [40894] ERROR: Barman cloud WAL archive check exception: maximum recursion depth exceeded while calling a Python object","pipe":"stderr","logging_pod":"dsmr-reader-2"}
{"level":"error","ts":"2023-03-11T22:18:48Z","logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"dsmr-reader-2","currentPrimary":"dsmr-reader-2","targetPrimary":"dsmr-reader-2","options":["--endpoint-url","http://********","--cloud-provider","aws-s3","s3://backup/postgres","dsmr-reader"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:257\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:383\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:169\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-03-11T22:18:48Z","msg":"while barman-cloud-check-wal-archive","logging_pod":"dsmr-reader-2","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:384\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:169\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-03-11T22:18:48Z","logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"dsmr-reader-2","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:83\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/proc.go:250"}
{"level":"info","ts":"2023-03-11T22:18:48Z","logger":"postgres","msg":"record","logging_pod":"dsmr-reader-2","record":{"log_time":"2023-03-11 22:18:48.139 UTC","process_id":"38111","session_id":"640ceefa.94df","session_line_num":"113","session_start_time":"2023-03-11 21:13:30 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"archive command failed with exit code 1","detail":"The failed archive command was: /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/00000004000000000000007E","backend_type":"archiver","query_id":"0"}}
```

I wonder if anyone could help me with this.
If there are more details required, let me know, so I can provide them.

**Comment by fr6nco** [comment]
Hi, similar issue popped up for me, when trying to bootstrap a new cluster from a backup. Im using azure tho. Pasting my log output, hopefully it helps:

```
{"level":"info","ts":"2024-03-20T09:31:11Z","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"cloudnative-restore-cluster-1-full-recovery"}
{"level":"info","ts":"2024-03-20T09:31:28Z","logger":"barman-cloud-check-wal-archive","msg":"2024-03-20 09:31:28,544 [13] ERROR: Barman cloud WAL archive check exception: maximum recursion depth exceeded while calling a Python object","pipe":"stderr","logging_pod":"cloudnative-restore-cluster-1-full-recovery"}
{"level":"error","ts":"2024-03-20T09:31:28Z","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"cloudnative-restore-cluster-1-full-recovery","currentPrimary":"","targetPrimary":"cloudnative-restore-cluster-1","options":["--cloud-provider","azure-blob-storage","https://***********.blob.core.windows.net/cloudnative-pg/","cloudnative-restore-cluster"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:257\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*InitInfo).checkBackupDestination\n\tpkg/management/postgres/restore.go:868\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.InitInfo.Restore\n\tpkg/management/postgres/restore.go:236\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:87\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:267"}
{"level":"error","ts":"2024-03-20T09:31:28Z","msg":"Error while restoring a backup","logging_pod":"cloudnative-restore-cluster-1-full-recovery","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:89\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:267"}
```

This is the cluster definition:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
  generation: 1
  labels:
    app.kubernetes.io/instance: cloudnative-restore
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: cloudnative-pg
    argocd.argoproj.io/instance: cloudnative-restore
    helm.sh/chart: cluster-0.0.3
  name: cloudnative-restore-cluster
  namespace: madme-lab
spec:
  affinity:
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: AZURE_STORAGE_ACCOUNT
          name: cloudnative-restore-cluster-backup-azure-creds
        storageKey:
          key: AZURE_STORAGE_KEY
          name: cloudnative-restore-cluster-backup-azure-creds
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: 'https://*****.blob.core.windows.net/cloudnative-pg/'
      wal:
        compression: gzip
        encryption: AES256
    retentionPolicy: 30d
    target: prefer-standby
  bootstrap:
    recovery:
      backup:
        name: cloudnative-cluster-daily-backup-20240320000000
      database: app
      owner: app
  enableSuperuserAccess: true
  externalClusters:
    - barmanObjectStore:
        azureCredentials:
          storageAccount:
            key: AZURE_STORAGE_ACCOUNT
            name: cloudnative-restore-cluster-backup-azure-recovery-creds
          storageKey:
            key: AZURE_STORAGE_KEY
            name: cloudnative-restore-cluster-backup-azure-recovery-creds
        destinationPath: 'https://*****.blob.core.windows.net/cloudnative-pg/'
      name: objectStoreRecoveryCluster
  failoverDelay: 0
  imageName: 'ghcr.io/cloudnative-pg/postgresql:15.2'
  imagePullPolicy: IfNotPresent
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_connections: '300'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_worker_processes: '32'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    updateInterval: 30
  resources: {}
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 4Gi
    storageClass: az-standard
  switchoverDelay: 3600
  ```

Im running version:
    image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.1

on Kube:
1.27.5
