### ISSUE TITLE
Postgres container image timezone

### ISSUE THREAD

**Issue by altitude1326** [cloudnative-pg/cloudnative-pg#169]
Hi,

Is they a way to specify TZ environnement variable of containers to set correct timezone for me ? I don't find in documentation. Or another solution to specify timezone.
Thank you.

**Comment by gbartolini** [comment]
Do you mean the timezone in Postgres?

**Comment by altitude1326** [comment]
The problem is if i use sql function like `now()`, it will return container time (UTC), but i need GMT+2.

**Comment by gbartolini** [comment]
PostgreSQL has an extensive support for timezones. I suggest you look at the PostgreSQL documentation for details, in particular:

- [Date time data types](https://www.postgresql.org/docs/current/datatype-datetime.html)
- [Client connections config options](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE)

All you have to do is add this option to the Postgres cluster configuration, like in this example (pg-italy.yaml)

``` yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-italy
spec:
  instances: 1

  postgresql:
    parameters:
      timezone: "Europe/Rome"

  storage:
    size: 1Gi
```

Create the cluster and verify with:

``` console
$ k exec -ti pg-italy-1 -c postgres -- psql -x -c "SHOW timezone"
-[ RECORD 1 ]---------
TimeZone | Europe/Rome
```

I hope this helps.
