### ISSUE TITLE
Restore fails

### ISSUE THREAD

**Issue by sergioenterprisedb** [cloudnative-pg/cloudnative-pg#1809]
I can't restore backup from my object storage to my cluster-restore.

# Context
Operator version: 1.19.1
Description: using Minio to store my backup. I was working well some days ago.

# Error
```
k get pod -w
NAME                                    READY   STATUS    RESTARTS   AGE
cluster-example-1                       1/1     Running   0          2m
cluster-example-2                       1/1     Running   0          89s
cluster-example-3                       1/1     Running   0          2m6s
cluster-restore-1-full-recovery-52r7t   0/1     Error     0          19s
cluster-restore-1-full-recovery-6t4g2   0/1     Error     0          27s
cluster-restore-1-full-recovery-f924z   0/1     Error     0          23s
cluster-restore-1-full-recovery-pcqgw   0/1     Error     0          11s
cluster-restore-1-full-recovery-pql9n   0/1     Error     0          39s
cluster-restore-1-full-recovery-smfdf   0/1     Error     0          15s
cluster-restore-1-full-recovery-zf6nj   0/1     Error     0          31s
^Csergio.romera@laptop390-ma-us:~/Documents/GitHub/kubecon2022-demo
> k logs cluster-restore-1-full-recovery-zf6nj
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":"2023-03-24T15:12:57Z","msg":"PGData already exists, can't overwrite","logging_pod":"cluster-restore-1-full-recovery"}
```
# Cluster Config
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  #imagePullPolicy: Always
  minSyncReplicas: 1
  maxSyncReplicas: 1

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 1Gi

  backup:
    target: "prefer-standby"
    barmanObjectStore:
      destinationPath: "s3://cnp/"
      endpointURL: "http://192.168.1.25:9000"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY
      data:
        immediateCheckpoint: true
      #wal:
      #  compression: gzip
      #  maxParallel: 8
      #  encryption: AES256
    retentionPolicy: "1d"
```

# Backup file
```
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  cluster:
    name: cluster-example
```
# Restore file
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  #imagePullPolicy: Never

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      backup:
        name: backup-test
```
