### ISSUE TITLE
Operator automatically deletes any manually created podMonitor during cluster creation

### ISSUE THREAD

**Issue by m33li5** [cloudnative-pg/cloudnative-pg#1844]
During cluster creation, when `.spec.monitoring.enablePodMonitor: false` (the default value) the operator will delete any manually created podMonitor resource. Only after cluster creation has completed, can I create the podMonitor and the operator will not interfere.

The logic is at [controllers/cluster_create.go](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/controllers/cluster_create.go#L806-L814):
```
case !cluster.IsPodMonitorEnabled() && podMonitor != nil:
		contextLogger.Info("Deleting PodMonitor")
```
When deploying clusters, I would like to deploy all resources (secrets, podmonitors, poolers) at the same time and not implement some seperate delay logic for podMonitors to be only applied after the cluster creation has completed.

Maybe there is a way to distinguish between which podMonitor is managed by the operator and which one is managed by the user?

For example, a label the operator looks for to know this podMonitor is managed by it. Also, the opposite would work, a general label the user can apply to a resource which tells the operator "hands off".

**Comment by m33li5** [comment]
> Just to be clear, using a name for the podmonitor different from the default one is not an option? Or isn't that working?

Indeed, changing the podMonitor name is a viable workaround for this issue. I missed the fact the operator only looks for a podMonitor with the same name as the cluster. Even though I would prefer to name the resources of a single cluster the same way, it is not a hard blocker for me and I can use the workaround.

Thanks @phisco !

**Comment by rouke-broersma** [comment]
@phisco this behavior is still present and is not very transparent to the user, it is unexpected. I use gitops to manage my cluster and I only recently noticed that the podmonitor was constantly being reconciled. I don't think it's correct that cnpg tries to manage podmonitors (or any other resource for that matter) that it does not own.

**Comment by phisco** [comment]
Totally agree @rouke-broersma, reopening this. I would argue it's not the operator's job to manage these resources altogether actually, I'll propose deprecating this in the future, too much effort for something users can define on their own.

**Comment by phisco** [comment]
Totally agree, but let's open a dedicated issue for it, @sxd, I can do that by EOD.

**Comment by rouke-broersma** [comment]
I don't necessarily agree that it's not the operator's responsibility to manage these resources, because the operator is best suited to have the knowledge of how to interact with the resource. If you look at the different operator maturity levels it's expected that an operator manages nearly all operational tasks for the highest maturity level. 

But I understand that a tradeoff must be made between features and their cost. Managing this resource ourselves isn't that big of a deal so deprecating and removing is fine with me. 

And Prometheus is also not the only monitoring tool available for Kubernetes so deciding to support one over one of the others is also a choice this project may not want to make.

**Comment by jurim76** [comment]
The operator deletes my custom pooler's podmonitors, regardless the name.
I have the following parameter in my custom CR chart.
```yaml
  monitoring:
    enablePodMonitor: false
```
And I have the custom podmonitor templates for db and poolers pods.
Template for db podmonitor, where `instanceName` is a cluster name and the podmonitor name will be "users", for exampe (I guess it not duplicates the operator's default one)
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $instanceName }}
  labels:
    {{- include "core.labels" $ | nindent 4 }}
    {{- toYaml $.Values.exporter.labels | nindent 4 }}
    name: {{ $instanceName }}
spec:
*****
```

Template for pooler podmonitor, where `pooler.suffix` is "pgpool" `.` is "rw" or "ro" and the podmonitor name will be "users-rw-pgpool"
```yaml
{{- $poolerName := printf "%s-%s-%s" $instanceName . $.Values.pooler.suffix }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/poolerName: {{ $poolerName }}
    {{- toYaml $.Values.exporter.labels | nindent 4 }}
  name: {{ $poolerName }}
****
```

Helm creates both podmonitors for db pods and pooler pods, during the installation.
But operator deletes only the pooler's podmonitors after some time and does not touch the db podmonitors.
