### ISSUE TITLE
Restore from Cloudflare R2 not working, no target backup found

### ISSUE THREAD

**Issue by aleksasiriski** [cloudnative-pg/cloudnative-pg#1893]
Backups get uploaded without issues, but restore on a new cluster results in this error:
```json
Defaulted container "full-recovery" out of: full-recovery, bootstrap-controller (init)
{"level":"info","ts":"2023-04-09T18:50:40Z","msg":"Recovering from external cluster","logging_pod":"cloudnative-pg-1-full-recovery","sourceName":"cloudnative-pg"}
{"level":"error","ts":"2023-04-09T18:50:41Z","msg":"Error while restoring a backup","logging_pod":"cloudnative-pg-1-full-recovery","error":"no target backup found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:93\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.2/x64/src/runtime/proc.go:250"}
```

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: hcloud-volumes
    size: 10Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7-9
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
  affinity:
    enablePodAntiAffinity: true
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/server-type
            operator: In
            values:
            - ram
  backup:
    barmanObjectStore:
      destinationPath: s3://cloudnative-pg-backup
      endpointURL: https://mycloudflareid.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cloudflare-r2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cloudflare-r2-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: 7d
  bootstrap:
    recovery:
      source: cloudnative-pg
  externalClusters:
    - name: cloudnative-pg
      barmanObjectStore:
        destinationPath: s3://cloudnative-pg-backup
        endpointURL: https://mycloudflareid.r2.cloudflarestorage.com
        s3Credentials:
          accessKeyId:
            name: cloudflare-r2-credentials
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: cloudflare-r2-credentials
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip
          maxParallel: 8
```

![image](https://user-images.githubusercontent.com/31509435/230791579-5b898006-97d9-40dd-a93d-ed8dd46589b9.png)
