### ISSUE TITLE
Cluster create fails with exteral cluster

### ISSUE THREAD

**Issue by msijmons** [cloudnative-pg/cloudnative-pg#1921]
Hi All,

If a new cluster is created with a bootstrap section, See below:

```
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: cdo-cluster
  storage:
    size: 1Gi
  externalClusters:
    - name: cdo-cluster
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: external-cluster-example-rw
        user: postgres
        dbname: postgres
        sslmode: require
      password:
        name: cluster-example-superuser
        key: password
```
All roles are copied from the external cluster to the new cluster, except the roles postgres, streaming_replica, cnp_pooler_pgbouncer
All databases are exported with pg_dump from the external cluster and loaded with pg_restore into the new cluster.
This all according to the documentation.

But if the source databases contains objects  owned by streaming_replica or cnp_pooler_pgbouncer, those objects are included in the export.

If pgBouncer is used, the following function will be created and the following grants are applied in each database that is pooled by pgBouncer:

```
CREATE OR REPLACE FUNCTION user_search(uname TEXT)
  RETURNS TABLE (usename name, passwd text)
  LANGUAGE sql SECURITY DEFINER AS
  'SELECT usename, passwd FROM pg_shadow WHERE usename=$1;';

GRANT CONNECT ON DATABASE app TO cnpg_pooler_pgbouncer;

REVOKE ALL ON FUNCTION user_search(text)
  FROM public;

GRANT EXECUTE ON FUNCTION user_search(text)
  TO cnpg_pooler_pgbouncer;
```

Now the import fails in the newly created cluster, because postgres creates the function and tries to grant connect rights to the database to role cnp_pooler_pgbouncer  and grants execute rights on the function to the role cnp_pooler_pgbouncer.

So it works as designed a long as the roles streaming_replica and cnp_pooler_pgbouncer do not exists in the external (source) cluster, otherwise errors can and will occur.
