### ISSUE TITLE
Restore from Bucket Store Not working.

### ISSUE THREAD

**Issue by scoutinho-randori** [cloudnative-pg/cloudnative-pg#1929]
```
  bootstrap:
    recovery:
      source: postgres
      recoveryTarget:
        backupID: 20230312T000000
        targetLSN: 1A814/F7FBAB00
        # targetTime: "2023-03-12 05:07:24.678995+00:00"
        # targetLSN: 1BA79/215C3528
        # exclusive: false
        # targetImmediate: true
  enableSuperuserAccess: true
  externalClusters:
    - barmanObjectStore:
        destinationPath: 'gs://edb-backups-xxxxxx-platform-vxxxxiper/gen0'
        googleCredentials:
          gkeEnvironment: true
        wal:
          compression: snappy
          maxParallel: 8
      name: postgres
```

Have the following bootstrap, recovery and externalCluster. The primary gets setup fine but then the `recovery_target_time` attribute never gets written to the custom.conf file. I logged in while the wal restore is happening and noticed that the custom.conf does not have that parameter.  So the recovery keeps going on.
