### ISSUE TITLE
deployment strategy for pgbouncer

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#1982]
to replace the default value  

```
strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
```
