### ISSUE TITLE
adjusting image of pgbouncer, postgresql and operator itself

### ISSUE THREAD

**Issue by r0b1ndot** [cloudnative-pg/cloudnative-pg#2017]
Hey,
i tried to adjust the used images in my cluster deployment like the following:

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-mycluster
spec:
  postgresql:
  imageName: myrepo.tld/loudnative-pg/postgresql:latest
  imagePullSecrets:
    - name: mysecret
  pgbouncer:
  imageName: myrepo.tld/cloudnative-pg/pgbouncer:latest
  imagePullSecrets:
    - name: mysecret
    
```

i still get: spec.pgbouncer.imageName: field not declared in schema

how to configure it properly? and how to change the image of the operator itself without having a generic values.yaml?
the image to be changed is also: ghcr.io/cloudnative-pg/cloudnative-pg:XX
the deployment like this is currently done by a cluster.yml file.
i mirrored it locally to an local repo-server and wanted to use them but also in the clusterspec i see no way in changing the operator image:

https://cloudnative-pg.io/documentation/1.20/api_reference/#clusterspec
