### ISSUE TITLE
section:pre-data, exit status 1

### ISSUE THREAD

**Issue by Evolt0** [cloudnative-pg/cloudnative-pg#2027]
import Postgres databases with monolith but `error while executing pg_restore, section:pre-data, exit status 1`

```
cloudnative-pg:15
postgresql:11
```

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgsql-cluster
spec:
  instances: 1
  superuserSecret:
    name: pgsql-cluster-superuser
  imageName: ghcr.io/cloudnative-pg/postgresql:11
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: machine-pg
  externalClusters:
    - name: machine-pg
      connectionParameters:
        host: x.x.x.x
        user: postgres
        dbname: postgres
        sslmode: disable
      password:
        name: machine-pg-superuser
        key: password
```
