### ISSUE TITLE
When removing resource limits the pods are not restarted automatically

### ISSUE THREAD

**Issue by ngoeddel-openi** [cloudnative-pg/cloudnative-pg#2037]
For load tests we decided to remove the resource limits of our Postgres cluster to avoid CPU throttling and therefore changed the Cluster resource:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
...
spec:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
...
```
Before it also had a resource limit defined for CPU and memory.

Although the specification changed the CloudNativePG operator did not changed the cluster state and restarted the Pods. I had to manually do that with the `kubectl-cnpg restart <clustername>` command.

## Versions
Operator: ghcr.io/cloudnative-pg/cloudnative-pg:1.18.1
Postgres: ghcr.io/cloudnative-pg/postgresql:15.1
