### ISSUE TITLE
failed to call webhook: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by winston0410** [cloudnative-pg/cloudnative-pg#2143]
I encountered this error when I tried to apply a `Cluster` manifest through `argocd`.

```sh
postgresql.cnpg.io            Cluster                         staging-medusa       medusa-cluster                                      OutOfSync  Missing        Internal error occurred: failed calling webhook "mcluster.kb.io": failed to call webhook: Post "https://cnpg-webhook-service.pg.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": x509: certificate signed by unknown authority
```

Which seems like the cert of the webhook endpoint is self-signed and not respected. I tried to exec the call in a random pod with `curl` to confirm that:

```sh
$ curl https://cnpg-webhook-service.pg.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

My question is, is it possible to replace the cert for the webhook, or is this misconfiguration on my end?

My config:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pg

helmCharts:
  - name: cloudnative-pg
    includeCRDs: true
    releaseName: cloudnative-pg
    namespace: pg
    version: 0.18.0
    repo: https://cloudnative-pg.io/charts/
    valuesInline:
      image:
        pullPolicy: Always
```
