### ISSUE TITLE
Feature Request: support extraVolumes and extraVolumeMounts

### ISSUE THREAD

**Issue by Alegrowin** [cloudnative-pg/cloudnative-pg#2312]
It would be great to allow adding extra volumes and volumes mounts.

A use case would be to support dynamic secrets using [Secret Provider Classes](https://developer.hashicorp.com/vault/docs/platform/k8s/csi#using-secret-provider-classes)

The ability to mount additional volumes and mounts would allow to dynamically create secrets using Secret Provider Class when the pod is created.

Something similar to

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1

  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: postgres
  
  extraVolumeMounts:
    - name: vault-postgres-secrets
      mountPath: "/mnt/secrets-store"
  extraVolumes:
    - name: vault-postgres-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: vault-postgres-secrets
```

Thanks!
