### ISSUE TITLE
Pooler init containers do not inherit resource limits

### ISSUE THREAD

**Issue by achanda** [cloudnative-pg/cloudnative-pg#2327]
Hello, I am running CloudnativePG in a K8S cluster that blocks resources without resource limits. Here is my pooler config

```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: mytestcluster-ro
  namespace: cnpg-clusters
spec:
  cluster:
    name: mytestcluster
  instances: 3
  type: ro
  template:
    spec:
      containers:
      - image: ghcr.io/cloudnative-pg/pgbouncer:1.19.1
        name: pgbouncer
        resources:
          limits:
            cpu: "1"
            memory: "1G"
          requests:
            cpu: "1"
            memory: "1G"
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
```

I see the following in operator logs

```
{"level":"info","ts":"2023-06-19T19:34:11Z","msg":"Creating deployment","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler","Pooler":{"name":"mytestcluster-ro","namespace":"cnpg-clusters"},"namespace":"cnpg-clusters","name":"mytestcluster-ro","reconcileID":"a30def4c-674d-4d94-b338-18f156de6904","uuid":"444a15b9-0ed8-11ee-be3d-be1be5c54b21"}
{"level":"error","ts":"2023-06-19T19:34:11Z","msg":"Reconciler error","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler","Pooler":{"name":"mytestcluster-ro","namespace":"cnpg-clusters"},"namespace":"cnpg-clusters","name":"mytestcluster-ro","reconcileID":"a30def4c-674d-4d94-b338-18f156de6904","error":"admission webhook \"admission-control-webhook-v1-deployments.foobar.com\" denied the request: missing resource.limits for: bootstrap-controller","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

From the error it seems that the init container is trying to run without any resource limits. It should inherit the pooler's resource limits.
