### ISSUE TITLE
Deleting a cluster should also cleanup up barman resources.

### ISSUE THREAD

**Issue by rohank2002** [cloudnative-pg/cloudnative-pg#2328]
When a cluster is created and is backed up using the backup CRD. The cluster gets backed up. Once the cluster is deleted, the backup stored in barman cloud is not cleaned up.

Manifests:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: default
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://<bucket_name>
      s3Credentials:
        inheritFromIAMRole: true
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: <aws-role>
```

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  cluster:
    name: cluster-example
```
Once the above cluster is deleted, the files are not cleaned-up in s3. Can this be a feature flag? An annotation on the cluster CRD, or a property?
