### ISSUE TITLE
Clean install fails to start replicas

### ISSUE THREAD

**Issue by AJK74** [cloudnative-pg/cloudnative-pg#2353]
Hi,

**problem**
new 3 node cluster starts primary which seems fine and can query with psql - but no replica pods get created.

**environment**
 - a bare metal cluster (ubuntu hosts) running kubernetes v1.26
 - cluster is in namespace ext
 - controller is installed in cnpg-system using the helm chart
 - cluster doesn't have a csi / automated pv provisioning so pvs are created manually
 - only the pv from the first host gets claimed

**cluster configuration**
```yaml
  apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: pg
  spec:
    instances: 3
    imageName: ghcr.io/cloudnative-pg/postgresql:15.3
 
    # Persistent storage configuration
    storage:
      size: 50Gi
      pvcTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: local-storage
        volumeMode: Filesystem
  
    affinity:
      enablePodAntiAffinity: true 
      topologyKey: kubernetes.io/hostname 
      podAntiAffinityType: preferred
```

**when cluster comes up we have the following**
```bash
NAME                       READY   STATUS      RESTARTS   AGE
pod/pg-1                   1/1     Running     0          31m
pod/pg-1-initdb--1-86nhj   0/1     Completed   0          137m
pod/ubuntu                 1/1     Running     0          14h

NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/pg-r    ClusterIP   10.102.181.81    <none>        5432/TCP   137m
service/pg-ro   ClusterIP   10.99.140.141    <none>        5432/TCP   137m
service/pg-rw   ClusterIP   10.104.104.214   <none>        5432/TCP   137m

NAME                    COMPLETIONS   DURATION   AGE
job.batch/pg-1-initdb   1/1           41s        137m
```

**controller logs show**
```json
{"level":"info","ts":"2023-06-24T11:29:51Z","msg":"Cannot extract Pod status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"fc802273-9673-4094-89a2-a2868762260c","uuid":"6e026de8-1282-11ee-bd18-8e70f882700f","name":"pg-1","error":"Get \"http://192.168.18.253:8000/pg/status\": dial tcp 192.168.18.253:8000: i/o timeout"}
{"level":"info","ts":"2023-06-24T11:29:51Z","msg":"Failed to extract instance status from ready instances. Attempting to requeue...","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"fc802273-9673-4094-89a2-a2868762260c","uuid":"6e026de8-1282-11ee-bd18-8e70f882700f"}
{"level":"info","ts":"2023-06-24T11:30:03Z","msg":"Cannot extract Pod status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"7ca102e3-14f8-4daf-8e29-47301e855bc2","uuid":"75354488-1282-11ee-bd18-8e70f882700f","name":"pg-1","error":"Get \"http://192.168.18.253:8000/pg/status\": dial tcp 192.168.18.253:8000: i/o timeout"}
{"level":"info","ts":"2023-06-24T11:30:03Z","msg":"Failed to extract instance status from ready instances. Attempting to requeue...","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"7ca102e3-14f8-4daf-8e29-47301e855bc2","uuid":"75354488-1282-11ee-bd18-8e70f882700f"}
{"level":"info","ts":"2023-06-24T11:30:15Z","msg":"Cannot extract Pod status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"0215cbf1-f55c-4d44-bd09-9893055394ef","uuid":"7c61f7d9-1282-11ee-bd18-8e70f882700f","name":"pg-1","error":"Get \"http://192.168.18.253:8000/pg/status\": dial tcp 192.168.18.253:8000: i/o timeout"}
{"level":"info","ts":"2023-06-24T11:30:15Z","msg":"Failed to extract instance status from ready instances. Attempting to requeue...","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg","namespace":"ext"},"namespace":"ext","name":"pg","reconcileID":"0215cbf1-f55c-4d44-bd09-9893055394ef","uuid":"7c61f7d9-1282-11ee-bd18-8e70f882700f"}
```
**investigation**

have created a bare pod in the cnpg-system namespace to test the call being made using curl

```bash
curl 'http://192.168.18.253:8000/pg/status'
{"currentLsn":"0/6000000","systemID":"7248177365388468245","isPrimary":true,"replayPaused":false,"pendingRestart":false,"pendingRestartForDecrease":false,"isWalReceiverActive":false,"node":"","pod":{"metadata":{"name":"pg-1","creationTimestamp":null},"spec":{"containers":null},"status":{}},"isPgRewindRunning":false,"totalInstanceSize":"29 MB","mightBeUnavailable":false,"lastArchivedWAL":"000000010000000000000005","lastArchivedWALTime":"2023-06-24T11:05:23.61393Z","lastFailedWALTime":"-infinity","isArchivingWAL":true,"currentWAL":"000000010000000000000005","timeLineID":1,"isPodReady":false,"executableHash":"76ceae159df15258568e3c48687e90c35aecda372e23e4ab1ef2a7eb6a2fe950","isInstanceManagerUpgrading":false,"instanceManagerVersion":"1.20.1","instanceArch":"amd64"}
```

Looks like maybe the controller can't get past not getting the status from the first pod? and is stuck retrying every 10s or so, but as far as i can tell the call it is trying to use should succeed.

Any pointers on where to look next?

Thanks
