### ISSUE TITLE
Cannot create an externalCluster of type monolith when source cluster has a pooler defined

### ISSUE THREAD

**Issue by isdinAghmir** [cloudnative-pg/cloudnative-pg#2369]
Hello, 

I am referring to issue: #1921. which is closed now with no resolution.

With this following manifest which creates a Cluster from an External of type monolith.
The source cluster has a pooler configured and is configured with cnpg version 1.20.1 operator.
The External Cluster is also configured with cnpg 1.20.1 operator.

Tested with cnpg 1.20.0 -> same issue. 

Tested scenarios: 

  - Create the source cluster without a pooler
    - External cluster creation success

  - Create the source cluster with a pooler
    - External cluster fails

 - Specify the cnpg_pooler user in the spec.managed.role section
   - Error, role name is reserved by operator.

Relevant Logs: 
```
{"level":"info","ts":"2023-06-27T09:35:50Z","msg":"found a role that needs to be skipped","logging_pod":"externalcluster01-1-import","rolesToSkip":["postgres","streaming_replica","cnpg_pooler_pgbouncer","app"],"role":{"oid":"16540","rolname":"cnpg_pooler_pgbouncer","rolinherit":true,"rolcanlogin":true,"rolconnlimit":-1}}
{"level":"info","ts":"2023-06-27T09:35:50Z","msg":"found a role that needs to be skipped","logging_pod":"externalcluster01-1-import","rolesToSkip":["postgres","streaming_replica","cnpg_pooler_pgbouncer","app"],"role":{"oid":"16544","rolname":"streaming_replica","rolinherit":true,"rolcanlogin":true,"rolreplication":true,"rolconnlimit":-1,"rolcomment":"Special user for streaming replication created by CloudNativePG"}}
{"level":"info","ts":"2023-06-27T09:35:50Z","logger":"postgres","msg":"record","logging_pod":"externalcluster01-1-import","record":{"log_time":"2023-06-27 09:35:50.648 UTC","user_name":"postgres","database_name":"application","process_id":"56","connection_from":"[local]","session_id":"649aad76.38","session_line_num":"1","command_tag":"GRANT","session_start_time":"2023-06-27 09:35:50 UTC","virtual_transaction_id":"4/48","transaction_id":"759","error_severity":"ERROR","sql_state_code":"42704","message":"role \"cnpg_pooler_pgbouncer\" does not exist","query":"REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;\nGRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;\n\n\n","application_name":"cnpg-instance-manager","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2023-06-27T09:35:50Z","logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  role \"cnpg_pooler_pgbouncer\" does not exist","pipe":"stderr","logging_pod":"externalcluster01-1-import"}
{"level":"info","ts":"2023-06-27T09:35:50Z","logger":"pg_restore","msg":"GRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;","pipe":"stderr","logging_pod":"externalcluster01-1-import"}
```

external cluster manifest:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: externalcluster01
  namespace: postgres-external01
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3

  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: pg-cluster01

  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 trust 
    shared_preload_libraries: 
      - 'pgaudit'
    parameters:
      shared_buffers: "512MB"
      max_connections: "300"
      effective_cache_size: "1536MB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "4"
      effective_io_concurrency: "2"
      work_mem: "1310kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  storage:
    size: 10Gi


  externalClusters:
    - name: pg-cluster01
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: pg-cluster01-rw.postgres
        user: postgres
        dbname: postgres
      # password:
      #   name: devteam-secret
      #   key: password   
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-external01-rw
  namespace: postgres-external01
spec:
  cluster:
    name: externalcluster01
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
      server_lifetime: "3600"
      server_idle_timeout: "3600"      
``` 

Do you have an Idea on how to fix this please? 

thank you
