### ISSUE TITLE
How to pass .sql file to init the DB ?

### ISSUE THREAD

**Issue by Ryder05** [cloudnative-pg/cloudnative-pg#242]
I am using a shell script to download a .sql using wget/curl file and then  exucting the command `kubectl exec -i $PG_POD_NAME -- bash -c "export PGPASSWORD=${PASSWORD} && psql -v ON_ERROR_STOP=1 -U ${DB_USER} -d ${DB} -h localhost" < ./import-postgres.sql` to intilize the postgres DB.
Since i am migrating to Helm, I don't want to run shell scripts anymore so i am wondering if there is a way to run .sql file.
I know i can do this by using postInitApplicationSQL option but it wouldn't be a good choice since the .sqll file contains more than 1000 line.

**Comment by Anhui-tqhuang** [comment]
seems to support something like
```yaml
postInitApplicationSQLRefs:
  secretRefs: []
  configmapRefs:
  - name: configmapName1
    key: file.sql
  - name: configmapName2
    key: file.sql
```
