### ISSUE TITLE
S3 Backup size indefinitely growing

### ISSUE THREAD

**Issue by GioPat** [cloudnative-pg/cloudnative-pg#2429]
**Background**
Kubernetes server version: EKS 1.25.10
Cloudnative-pg version:
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/9217515/8ff98a25-dd51-46cb-8fc6-8fc3368f26a9)

The following manifest is deployed:
```yaml
apiVersion: v1
data:
  password: *****************************************
  username: *****************************************
kind: Secret
metadata:
  name: app-superuser-secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
data:
  ACCESS_KEY_ID: *****************************************
  ACCESS_SECRET_KEY: *****************************************
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-prod
spec:
  description: "app Production database"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  instances: 1

  postgresql:
    pg_hba:
      - "host all all all md5"

  superuserSecret:
    name: app-superuser-secret

  storage:
    size: 300Gi

  backup:
    barmanObjectStore:
      destinationPath: "s3://dest-bucket/db_bak/"
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"

  resources:
    requests:
      memory: "12Gi"
      cpu: "3"
    limits:
      memory: "12Gi"
      cpu: "3"
```
The disk space used in the container is the following (running `df -h` inside the container) is barely 28 GB as you see in the following screen:
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/9217515/679a1753-ebf4-4f97-a8e9-67f6f09f6580)

**Issue**
The bucket size is inexorably increasing as you can see from this screen (done over 2 months of monitoring):
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/9217515/623d5429-281c-4561-a39e-eb5f880c8c05)

Even though the retention period is set to 30d the S3 bucket is unexpectedly increasing and has arrived to more than 3TB

Do you have any suggestion to avoid this issue and how to save some space by not losing the ability to restore the database?

Thanks.
