### ISSUE TITLE
Wrong interpretation of cluster.spec.postgresql.parameters

### ISSUE THREAD

**Issue by Brice187** [cloudnative-pg/cloudnative-pg#2471]
# System
Kubernetes: v1.27.3+k3s1
Operator v1.20.1
PG Image: ghcr/cloudnative-pg/postgresql:15.3

# Issue
 I defined the following cluster:

```
...
  postgresql:
    parameters:
      effective_cache_size: "512MB"
      maintenance_work_mem: "128MB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "6"
      shared_buffers: "1GB"
      work_mem: "256MB"
...
```
This **effective_cache_size** and **maintenance_work_mem** were not recognized:

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/2021699/389f72b3-33d6-4708-92bd-c5f5db807074)

# workaround

Had to define the size in bytes

```
...
  postgresql:
    parameters:
      effective_cache_size: "536870912" # 2^29 KB = 512MB
      maintenance_work_mem: "134217728" # 2^27 KB = 128MB
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "6"
      shared_buffers: "1GB"
      work_mem: "256MB"
...
```

# expected solution

Please check if the parameters are set correctly by the operator so we can use standard postgres-config notation. Thank you
