### ISSUE TITLE
EDB On demand backup is getting failed.

### ISSUE THREAD

**Issue by oberai07** [cloudnative-pg/cloudnative-pg#2472]
Hi Team,

We are trying to integrate OpenStack Swift s3 storage with open-source cloudnative-pg for Kubernetes.  We have a Primary Postgres cluster running with barmanobjectstore to store backups and we are able to integrate the storage with the Primary Postgres cluster successfully but our DB on-demand backups are failing with exit code 4. There are no such error logs about failure in Postgres operator and k8s events. 

Could you please let me know what is wrong with the below configuration?  Because without logs it is getting difficult to debug this specific issue.

```
ubuntu@kma001:~$ cat edb-primary-cluster.yaml 
# Please find below the backup related section only, this is not the full manifest code.

backup:
    barmanObjectStore:
      destinationPath: s3://wal-edb-backups/pgdb-backup/
      endpointURL: http://<openstack-proxy-server-ip>:8080/
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: false
        jobs: 2

```

```
ubuntu@kma001:~$ kubectl get backups
NAME                 AGE     CLUSTER               PHASE    ERROR
edb-primary-backup   5h41m   edb-primary-cluster   failed   exit status 4

```
```
ubuntu@kma001:~$ kubectl describe backup edb-primary-backup
Status:
  Backup Name:       backup-1689842553
  Destination Path:  s3://wal-edb-backups/pgdb-backup/
  Endpoint URL:      http://<openstack-proxy-server-ip>:8080/
  Error:             exit status 4
  Instance ID:
    Container ID:  docker://0a277c264f0e10b2c13741425493ae82a633bfc8f7d530b62933509afe5252e1
    Pod Name:      edb-primary-cluster-2
  Phase:           failed
  s3Credentials:
    Access Key Id:
      Key:                  ACCESS_KEY_ID
      Name:                 aws-creds
    Inherit From IAM Role:  false
    Secret Access Key:
      Key:      ACCESS_SECRET_KEY
      Name:     aws-creds
  Server Name:  edb-primary-cluster
Events:         <none>
```
```
ubuntu@kma001:~$ cat edb-primary-backup.yaml 
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: edb-primary-backup
spec:
  cluster:
    name: edb-primary-cluster


```
