### ISSUE TITLE
"Pooler not automatically configured, manual configuration required" issue popping up on all poolers

### ISSUE THREAD

**Issue by btxbtx** [cloudnative-pg/cloudnative-pg#2479]
I am seeing this issue pop up for all of my poolers, despite having what I believe to be correctly configured poolers.  According to the [docs](https://cloudnative-pg.io/documentation/1.15/connection_pooling/) all I need is for the pooler to set `cluster.name` to be that of the cluster, and to not let its own name conflict.

The image I'm using is: `ghcr.io/cloudnative-pg/cloudnative-pg:1.20.0`

Here is a sample message from the operator logs:
```
{"level":"info","ts":"2023-07-21T10:22:04Z","msg":"pooler not automatically configured, manual configuration required","cluster":"cnpg-cluster","pooler":"cnpg-pooler"}
```

The pooler configuration:

```
---
# Source: cnpg-pooler/templates/pooler.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cnpg-pooler
  namespace: "database"
  labels:
    app.kubernetes.io/name: cnpg-pooler
    helm.sh/chart: cnpg-pooler-0.1.0
    app.kubernetes.io/instance: pooler
    app.kubernetes.io/managed-by: Helm
spec:
  cluster:
    name: cnpg-cluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      null
```

The cluster config:

```
---
# Source: cnpg-cluster/templates/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: "database"
  labels:
    app.kubernetes.io/name: cnpg-cluster
    helm.sh/chart: cnpg-cluster-0.1.2
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: Helm
spec:
  instances: 2

  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: superuser-creds

  managed:
    roles:
      - name: readonly
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: readonly-creds
        inRoles:
          - pg_read_all_data

  storage:
    size: 1Gi
```

Am I missing something?

**Comment by quercus-carsten** [comment]
Same problem here. Nothing really different from the config of OP. Noticed it since I first tried pooler in 1.19.X and I still see these messages in operator logs with v1.20.1

**Comment by quercus-carsten** [comment]
Hm, I haven't noticed any issues with the resulting pooler(s) so far. 

Pooler config:
```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: myapp-pg-pooler-rw
spec:
  cluster:
    name: myapp-postgresql
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  monitoring:
    enablePodMonitor: true
```
        
Resulting object:

```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  annotations:
[...]
  labels:
[...]
  name: myapp-pg-pooler-rw
  namespace: myapp
[...]
spec:
  cluster:
    name: myapp-postgresql
  instances: 2
  monitoring:
    enablePodMonitor: true
  pgbouncer:
    parameters:
      default_pool_size: "10"
      max_client_conn: "1000"
    paused: false
    poolMode: transaction
  type: rw
status:
  instances: 2
```

resulting pgbouncer.ini
  /controller/configs/pgbouncer.ini

```
[databases]
* = host=myapp-postgresql-rw

[pgbouncer]
pool_mode = transaction
auth_user = cnpg_pooler_pgbouncer
auth_query = SELECT usename, passwd FROM user_search($1)

admin_users = pgbouncer
auth_hba_file = /controller/configs/pg_hba.conf
auth_type = hba
client_tls_ca_file = /controller/configs/client-ca/ca.crt
client_tls_cert_file = /controller/configs/server-tls/tls.crt
client_tls_key_file = /controller/configs/server-tls/tls.key
client_tls_sslmode = prefer
default_pool_size = 10
ignore_startup_parameters = extra_float_digits,options
listen_addr = *
listen_port = 5432
log_stats = 0
max_client_conn = 1000
server_tls_ca_file = /controller/configs/server-tls/ca.crt
server_tls_cert_file = /controller/configs/authUser/tls.crt
server_tls_key_file = /controller/configs/authUser/tls.key
server_tls_sslmode = verify-ca
unix_socket_dir = /controller/run
```

From what I can see, all my specifics have been applied - so, looks fine to me.



I just looked up where this message is being generated:
https://github.com/cloudnative-pg/cloudnative-pg/blob/c4a369fff121f4060db9c53df99bae73292b2caf/controllers/cluster_status.go#L423-L425

"slices" should contain "pgbouncerPoolerIntegrations.Secrets" and "pooler.Name" otherwise we get this message.

And here:
https://github.com/cloudnative-pg/cloudnative-pg/blob/c4a369fff121f4060db9c53df99bae73292b2caf/controllers/cluster_status.go#L420

data is beeing assembled in preparation for some checks.

One of the two attributes is missing I guess? I dont't know what "Secrets" should contain. But if its the certificates for the pooler - it should use the certificates of the cluster as far as I know ... then this works fine for me too.

Maybe someone with deeper knowledge can shed some light on this :)
