### ISSUE TITLE
Connection Pooling: Bouncer service name not present in TLS certificate, leading to connection error

### ISSUE THREAD

**Issue by agtogna** [cloudnative-pg/cloudnative-pg#2490]
Hello, if we create a cluster and a pooler, the bouncer service name does not get added to the server's certificate AltNames; since the bouncer uses the server's certificate, the TLS connection from an application to the bouncer gets dropped since it's not verifiable:
- `code": "ERR_TLS_CERT_ALTNAME_INVALID"[...]`
- `Hostname/IP does not match certificate's altnames: Host: pg-bouncer. is not in the cert's altnames:[...]`

I had to manually add the service's DNS name to the PG Cluster's resource:
```
spec:
  certificates:
    serverAltDNSNames:
    - pg-bouncer
    - pg-bouncer.namespace
    - pg-bouncer.namespace.svc
```
so the bouncer's service would be verifiable.

Shouldn't it be managed by the Operator itself, at least for the Pooler's service Alt Names?
