### ISSUE TITLE
PostInitApplicationSQLRefs

### ISSUE THREAD

**Issue by Anhui-tqhuang** [cloudnative-pg/cloudnative-pg#250]
It might be good to involve a way to read sql files from configmap or secrets to init db
```yaml
postInitApplicationSQLRefs:
  secretRefs: []
  configmapRefs:
  - name: configmapName1
    key: file.sql
  - name: configmapName2
    key: file.sql
```
related:
- https://github.com/cloudnative-pg/cloudnative-pg/issues/242

the implementation to these references is:
- secrets -> configmaps
- inside secrets or configmaps, the order is same as the order of each array
