### ISSUE TITLE
Proposal: Rename cluster label to cnpg_cluster

### ISSUE THREAD

**Issue by sjentzsch** [cloudnative-pg/cloudnative-pg#2501]
I would like to discuss a breaking change on observability. Our problem (and I will argue in a moment why it would not only affect us): Metrics from cnpg expose the `cluster` label (for example `cnpg_collector_up` ), and the [Grafana dashboard](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/monitoring/grafana-dashboard.json) builds upon that. However, the `cluster` label is a commonly-used general label often referring to the Kubernetes cluster the data originates from, and used by many as an external label when pushing metrics etc.. Those two concept cannot co-exist, and we decided to relabel the cnpg `cluster` label to `app_cluster`, but then we of course cannot use your upstream dashboard anymore (might also affect alerts at some point in time). My point is, with the current naming, the support for multi-cluster scenarios is quite restricted, and I am afraid we are not the only ones running cnpg in multi-cluster scenarios. My proposal is to rename the `cluster` label to `cnpg_cluster`, knowing that it will break existing alerts & dashboards for users. What do you think?

Feel free to also add to the Slack Thread: https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1690284881972749

**Comment by gbartolini** [comment]
I am concerned about the introduction of this breaking change. Can we do something like what we did for the log field names?

https://github.com/cloudnative-pg/cloudnative-pg/commit/936b930eaca7d0c85d571a7eac3fc6f401105551

And then get the plugin to control that in the generate command as part of the options for the deployment of the operator. See:

https://github.com/cloudnative-pg/cloudnative-pg/commit/91efc27e1a514ea1f4e0d003f3296dd611a304a5

Any comments?

That way we won't be breaking existing installations, but give the possibility for users to change the mapping in the installation and update their dashboard. In a few releases we can change the default.

**Comment by phisco** [comment]
I'd suggest adding both for a while, there should be no issue in doing so and the cluster label would be overridden if needed. We can even make the label to use a parameter in the dashboard, to ease the transition.

**Comment by gbartolini** [comment]
Hi Philippe,

> I'd suggest adding both for a while, there should be no issue in doing so and the cluster label would be overridden if needed. We can even make the label to use a parameter in the dashboard, to ease the transition.

I am probably missing something here. But wouldn't that mean that the exporter everytime sends the information twice?

**Comment by phisco** [comment]
@gbartolini Nono, labels are just additional metadata for each metrics.
```
cnpg_collector_up{cluster="cluster-example"} 1
```
Should be reported as:
```
cnpg_collector_up{cluster="cluster-example" cnpg_cluster="cluster-example"} 1
```

Because "cluster" in multi cluster monitoring systems can be used by other tools to show which Kubernetes cluster the metric is coming from, and therefore can overwrite the one we set.

**Comment by gbartolini** [comment]
oh ... and then we change the dashboard immediately and communicate the change. Got it. Thanks

**Comment by phisco** [comment]
> @phisco I am not sure what you mean by

I meant that we could add another parameter to the dashboard to let people choose which label they want to use, cluster or cnpg_cluster.

However, I was assuming it would have been overwritten, if that's not the case I don't see any other way than changing it, updating the dashboard and clearly stating the breaking change in the next minor release.

**Comment by itay-grudev** [comment]
@phisco I am more worried about automatic alerts that would break, not that worried for the dashboard.

**Comment by onedr0p** [comment]
I think if the change is communicated clearly in an upcoming release, and then actually changed in the next version after that people should have enough heads up that this is changing. I honestly can't imagine anyone upgrading cnpg without reading the changelogs, giving people enough warning a head of time is ample enough IMO

**Comment by phisco** [comment]
@onedr0p, https://github.com/cloudnative-pg/cloudnative-pg/pull/3075 was just merged, as per the comment [here](https://github.com/cloudnative-pg/cloudnative-pg/pull/3075#issuecomment-1793802677) this is not a complete fix as the real issue is with the grafana dashboard lacking the ability to change the label being used, but using that and manually fixing the label being used by the dashboard you should still be able to have everything working. Changing the label by default could mean user's custom alerts are not going to trigger, so we should do that with extreme care and we couldn't come up with a safe migration path for it.

**Comment by onedr0p** [comment]
> Changing the label by default could mean user's custom alerts are not going to trigger, so we should do that with extreme care and we couldn't come up with a safe migration path for it.

I saw that mentioned earlier which is why I suggested to give people a heads up this will change in a future release, and then change it in a release sometime after that.  Communication is key here... basically keep mentioning this change will happen on every release until it happens:

> [!IMPORTANT]
> Breaking changes to the prometheus metrics will be happening in v1.x.x, this will affect alerts. Please read here for more information.

If you all don't want to change this label at all maybe it's worth it to support two grafana dashboards one additional one with the cnpg_cluster label in this repo?

**Comment by onedr0p** [comment]
I tried to setup those relabelings but it's not coming thru, the cluster label just appears to be dropped instead...

## Prom Query

```
cnpg_backends_max_tx_duration_seconds{application_name="cnpg_metrics_exporter", container="postgres", datname="app", endpoint="metrics", instance="10.42.1.245:9187", job="database/postgres16", namespace="database", pod="postgres16-3", state="active", usename="postgres"}
```

## Cluster config

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
...
  monitoring:
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - { sourceLabels: ["cluster"], targetLabel: cnpg_cluster, action: replace }
      - { regex: cluster, action: labeldrop }
...
```

## Prom rendered config

I am seeing it applied in prometheus but the label is not being changed...

```yaml
- job_name: podMonitor/database/postgres16/0
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    separator: ;
    regex: (Failed|Succeeded)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster, __meta_kubernetes_pod_labelpresent_cnpg_io_cluster]
    separator: ;
    regex: (postgres16);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: database/postgres16
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: metrics
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [cluster]
    separator: ;
    regex: (.*)
    target_label: cnpg_cluster
    replacement: $1
    action: replace
  - separator: ;
    regex: cluster
    replacement: $1
    action: labeldrop
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - database
```

Not sure what to do here, anyone have any ideas?

**Comment by ThomasADavis** [comment]
According to some docs..  (we're using victoriametrics/vmagent here), if your adding 'cluster' to all your metrics as a global label, prometheus is supposed to rename the metric label from 'cluster' to 'exported_cluster', and then add your over-riding cluster label..

ie, in a grafana explorer, look for cnpg_collector_up, and see if you have an 'exported_cluster' label (which in our case, we do have..)

This should not be considered a long term solution..  it's just how a current Prometheus/VMagent handles conflicting labels.

**Comment by itay-grudev** [comment]
Would you consider calling the label: `cloudnative-pg.io/cluster-name` instead?

**Comment by dragoangel** [comment]
Hi @onedr0p , JFYI I managed to configure:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
spec:
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - action: replace
        sourceLabels:
          - cluster
        targetLabel: cnpg_cluster
      - action: labeldrop
        regex: cluster
```

and in Thanos I see properly:
```
{__name__="cnpg_collector_postgres_version", cluster="mycluster", cnpg_cluster="cloud-cluster", container="postgres", endpoint="metrics", environment="myenv", full="16.4", instance="10.2.177.35:9187", job="cloud-cluster/cloud-cluster", namespace="cloud-cluster", pod="cloud-cluster-2", tenant="mytenant"}
{__name__="cnpg_collector_postgres_version", cluster="mycluster", cnpg_cluster="cloud-cluster", container="postgres", endpoint="metrics", environment="myenv", full="16.4", instance="10.2.53.241:9187", job="cloud-cluster/cloud-cluster", namespace="cloud-cluster", pod="cloud-cluster-3", tenant="mytenant"}
{__name__="cnpg_collector_postgres_version", cluster="mycluster", cnpg_cluster="cloud-cluster", container="postgres", endpoint="metrics", environment="myenv", full="16.4", instance="10.2.58.115:9187", job="cloud-cluster/cloud-cluster", namespace="cloud-cluster", pod="cloud-cluster-1", tenant="mytenant"}
```

I think this is just workaround, and better not use `cluster` label at exporter and use `cnpg_cluster` label by default. Even with this workaround we or will have to deploy custom Grafana dashboard, or allow template existing one.

Also we do not need to statically set `cnpg_cluster` label in Prometheus alerts, it will be anyway populated from metrics we are querying in all cases except someone will use `sum` and would forget to add `by (cnpg_cluster)` 😊.

**Comment by dragoangel** [comment]
P.s. if speak about Grafana dashboards, I would split Operator metrics fully from Postgres metrics. It better to be separate dashboard.

Also `sum(kube_pod_status_ready{namespace="$operatorNamespace"} * on (pod) group_left( label_app_kubernetes_io_name ) kube_pod_labels{label_app_kubernetes_io_name=~"cloudnative-pg"})` isn't working. `kube_pod_labels` isn't exist in my setup.

**Comment by danielloader** [comment]
Well again that relies on your dashboard being installed via helm I guess.

If you aren't hosting grafana yourself you're more likely to import the json as is or import it via id on the dashboard marketplace (which has the cnpg dashboard published to it and where I found it)

**Comment by fcanovai** [comment]
I see that the `cluster` label is used only in for these two default metrics:
- `cnpg_collector_up`
- `cnpg_collector_postgres_version`

Then, the `cnpg_collector_up` metric is the base from which the dashboard extracts the namespace, cluster and instance variables. But we don't really need the `cluster` label there. We could change the dashboard to get the cluster variable not from the `cluster` or `cnpg_cluster` label, but from the `pod` one, moving from
```
/\bcnpg_cluster\b="(?<text>[^"]+)/g
```
to
```
/\bpod\b=\"(.*)-[1-9][0-9]*\"/g
```
It would still extract the same value, but won't require a label defined in the metric. People would be able to directly use the json. 

Then we could drop the `cluster` label in a future cnpg release, giving proper notification to the users. They could easily set relabelling if needed.

**Comment by dragoangel** [comment]
@fcanovai I think this is a bad idea, better to not loose cluster information, it easilly can become needed at any time.

**Comment by danielloader** [comment]
Yeah I'd keep a label for differentiating between CNPG clusters. Adding a cluster selector to every single panel sounds like the more difficult to square issue - just because if you run a single kubernetes cluster self hosted prometheus/grafana stack you may not have the config akin to above setup:

```
prometheusSpec:
  ## External labels to add to any time series or alerts when communicating with external systems
  ## Required by https://thanos.io/tip/components/sidecar.md/
  externalLabels:
    cluster: mycluster
    tenant: mytenant
    environment: myenv
```

So either you'd need to support single/multi cluster deployments and put the associated additional filter on each query on each dashboard chart, or you'd have to mandate in the documentation your prometheus setup _has_ to include a cluster value. 

Not an enviable decision but in a selfish personal perspective, I'd support anything that can support this federated metrics grafana dashboard to work - currently I'm having to suffix the cluster name to the CNPG cluster names in each environment just to be able to tell them apart in the dashboard.

**Comment by fcanovai** [comment]
I'd like to have a solution that works for Prometheus with and without `externalLabels` being defined.

Also, right now setting `cluster` in an external label would break the dashboard, since it will override the `cluster` label that `cnpg_collector_up` exports and the dashboard uses to find the instances.

By the way, that label was added exactly for this: having a working dropdown menu. If it was really important as a label it would have been added to all the default metrics, instead of just two of them. But we don't need it for that, we just need the pod name and the namespace to identify the existing clusters, and Prometheus gets those labels automatically. @danielloader : this works for multiple clusters in the same namespace. In the following example I have two clusters in the default namespace.
![cluster_query](https://github.com/user-attachments/assets/a327d767-6683-4852-a743-de8cf14789cf)

This would give us a chance to have an updated dashboard with the following variables:

1. namespace (from label)
2. cnpg_cluster (regexp)
3. instance (label again)

Now, we want to add a k8s `cluster` to this set of identifiers, to support multicluster metrics collection. We can write in the documentation that multicluster Prometheus setups have to define an `externalLabels` `cluster` label. This will add the k8s cluster name, unless there is a `cluster` label already, according to the Prometheus doc. Which is annoying because that label exists for `cnpg_collector_up` and `cnpg_collector_postgres_version`. I consider this a point in favour of removing the label. There is a [Thanos sidecar issue](https://github.com/thanos-io/thanos/issues/1579) about it always overriding the value, and I've seen it happening in my test, but I'm not convinced we should rely on it.

In a single k8s cluster scenario, instead, I don't think we should force users to define `externalLabels`. In this case, most of the metrics won't have the `cluster` label, but it will exist for `cnpg_collector_up` and `cnpg_collector_postgres_version`. If we add to the dashboard the logic to filter on what we believe a k8s cluster, the label would break the logic. Again, I'd remove the `cluster` label from there.

Removing the label, however, could break some logic for customers that have their own dashboards, or use that label in some ways. We could rename the to `cnpg_cluster` for a while and document how to relabel it to `cluster` if needed.
Then we could do one of the following:
* Add an info metric with value 1 and informational labels, telling people that they can find the value there, if needed
* Add the `cnpg_cluster` label to all the extracted metrics, if we want to associate the metric directly to the CNPG cluster

I'd go with the first and leave the second approach to the future if it comes up as needed.

So, in a single k8s cluster scenario where `cluster` is not set in the `externalLabels`, Grafana would not find `cluster` in the metrics, will evaluate that as empty string and would be able to match `cluster=''`, getting all the metrics for which cluster is not set.

We would need to support the new `cluster` variable  as a predicate in all the queries of the dashboard. Maybe it would be possible to template (jsonnet?) the dashboard to allow users to define their own predicates and build the dashboard, in case `cluster` cannot be used or it is not enough to correctly identify where the metrics are coming from.

So, the steps for me:
* make the dashboard (CNPG) `cluster` label agnostic
* drop/rename/move the (CNPG) `cluster` label. Inform users and document alternatives.
* add the (k8s) `cluster` label support in the dashboard

**Comment by dragoangel** [comment]
Hi @fcanovai, I not get why we need to rely on `cluster` label, sorry.

Multicluster can be easy out of this, main reason it to not get label conflicts I assume. 

If users have multiply clusters and global view - they would name their `cnpg_clusters` in uniq way across different clusters, so they will not mix together - this will be enough.

> Add an info metric with value 1 and informational labels, telling people that they can find the value there, if needed

> I'd go with the first and leave the second approach to the future if it comes up as needed.

I don't think it is good idea, to get `cnpg_cluster` from such metric - it will require group_left queries in both Grafana dashboard and Prom alert, they always so bad in maintaining... Such solution can be accepted if there would be tongs of labels on tons of metrics, but this not the case. Also group_left in wrong queries results in many-to-many correlation errors, and problem of this errors that they not always instantly visible...

**Comment by fcanovai** [comment]
> Hi @fcanovai, I not get why we need to rely on cluster label, sorry.

We don't. My idea was adding support for k8s clusters inside the dashboard. It would make sense to me to have a variable there, so we can select just the cnpg clusters in a single, user-specified k8s cluster. Right now there is no way to clearly identify the source of the metrics beside namespace and instance, since most of the metrics don't export anything else.

> Multicluster can be easy out of this, main reason from my view here - not get label cluster conflicts and solution just move to cnpg_cluster.
> If users have multiply clusters and global view - they would name their cnpg_cluster in uniq way across different clusters, so they will not mix together - this will be enough.

This is not 100% transparent. It requires a (minimal, alright) amount of housekeeping user-side. It would be a quick win, but it doesn't generalise the dashboard.

> I don't think it is good idea, to get cnpg_cluster from such metric - it will require group_left queries in both Grafana dashboard and Prom alert, they always so bad in maintaining... Such solution can be accepted if there would be tongs of labels on tons of metrics, but this not the case. Also group_left in badly written queries (which why they hard to maintain) results in many-to-many correlation errors, and problem of this errors that they not always instantly visible - in someone's setup they will appears and in another is not, or they will appears only when pods will be recreated, etc...

I'm not sure I understand your position here. What we currently have doesn't seem different: two metrics are the only ones exporting `cluster`. E.g.: a snippet of the `/metrics` endpoint

```
[...]
# HELP cnpg_collector_sync_replicas Number of requested synchronous replicas (synchronous_standby_names)
# TYPE cnpg_collector_sync_replicas gauge
cnpg_collector_sync_replicas{value="expected"} 0
cnpg_collector_sync_replicas{value="max"} 0
cnpg_collector_sync_replicas{value="min"} 0
cnpg_collector_sync_replicas{value="observed"} 0
# HELP cnpg_collector_up 1 if PostgreSQL is up, 0 otherwise.
# TYPE cnpg_collector_up gauge
cnpg_collector_up{cluster="cluster-with-metrics"} 1
[...]
```

Unless the idea is adding the label to all metrics?

**Comment by dragoangel** [comment]
@fcanovai if you would see distributed topology you will also see the best practices for naming of the clusters :)

They must have different naming. This is my view and view that written in docs.

**Comment by danielloader** [comment]
Sure but what if you have multiple kubernetes environments that are stages like production, staging and test. I wouldn't want to link my clusters across kubernetes environments and it complicates referencing the databases if the object itself has different names in different kubernetes clusters.

**Comment by dragoangel** [comment]
> Sure but what if you have multiple kubernetes environments that are stages like production, staging and test. I wouldn't want to link my clusters across kubernetes environments and it complicates referencing the databases if the object itself has different names in different kubernetes clusters.

Usually when people have multiple environments for production and staging they have independent monitoring for them as well which is not connected between each other. Different environments should not be connected in any way. This is best practice always.

**Comment by danielloader** [comment]
Again while I agree that's the opposite of how Prometheus federation works and it's the opposite of how grafana cloud works. There's an expectation that you bring your kubernetes clusters to the same backend and switch clusters using dashboard variables.

https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/helm-chart-config/

Can't confirm for sure but Datadog and new relic also angle towards this model.

If I were hosting my own monitoring stack I'd agree with you because the monitoring stack would be isolated internally to the cluster and thus naturally cluster scoped, but are you confident this is how it will work with anyone who's using a SaaS observability solution?

**Comment by dragoangel** [comment]
Yes, there truly possible chances that monitoring could be done this way. But you can't filter by everything possible option, otherwise you will have force users to set this label even they not needed it. I by myself have environment label even when my monitoring stacks are not connected. But this should be noted in some obvious place (values comments?), with examples hot to put this labels statically on the pod monitor if users not have them by design

**Comment by maxpain** [comment]
Any updates on this?

**Comment by tsndqst** [comment]
@gbartolini can this be re-opened?  The "cluster" label that cnpg adds to metrics still conflicts with "cluster" labels that represent the k8s cluster where cnpg is running.

**Comment by itay-grudev** [comment]
I agree. It should be re-opened. I also think we did more damage by not addressing it sooner, just for the sake of backwards compatibility.

**Comment by maaft** [comment]
so, what is the path forward here? 

The CNPG Operator (helm chart) already supports adding of relabelConfigs:
```yaml
monitoring:
  # -- Specifies whether the monitoring should be enabled. Requires Prometheus Operator CRDs.
  podMonitorEnabled: false
  # -- Metrics relabel configurations to apply to samples before ingestion.
  podMonitorMetricRelabelings: []
  # -- Relabel configurations to apply to samples before scraping.
  podMonitorRelabelings: []
  # -- Additional labels for the podMonitor
  podMonitorAdditionalLabels: {}
``` 

What would speak against adding these options also to the [monitoring section](https://cloudnative-pg.io/documentation/1.15/api_reference/#MonitoringConfiguration) of ClusterSpec? 

Than you could configure it like this:

```yaml
podMonitorMetricRelabelings:
            - sourceLabels: [cluster]
              targetLabel: cnpg_cluster
              action: labelmap
              replacement: $1
            - action: labeldrop
              regex: cluster
```

and everyone can do as he pleases.

Grafana dashboard is a separate issue of course, but you could alwas copy the dashboard, change `cluster` to `cnpg_cluster` and deploy it yourself.

As a workaround I'll now do both:

1. disable podMonitor for my cluster and deploy my own version with correct relabeling
2. disable grafana dashboard and deploy my own that uses the correct new label
