### ISSUE TITLE
Data is backed up, but backup enters failed phase due to "can't extract backup id"

### ISSUE THREAD

**Issue by btxbtx** [cloudnative-pg/cloudnative-pg#2510]
As the title suggests, I am able to backup my data using a `Backup` or `ScheduledBackup`.   However, the backup is unable to extract a backup id which puts the backup in the failed phase.

Here's the backup schedule:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup
spec:
  schedule: "50 * * * *"
  backupOwnerReference: self
  cluster:
    name: my-cluster
```

The logs:

```js
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:07Z",
  "msg": "WAL archiving is working",
  "logging_pod": "my-cluster-2"
}
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:07Z",
  "msg": "Backup started",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2",
  "options": [
    "--user",
    "postgres",
    "--name",
    "backup-1690362727",
    "--endpoint-url",
    "<my s3 compatible storage>",
    "--cloud-provider",
    "aws-s3",
    "<my s3 destination>",
    "my-cluster"
  ]
}
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:29Z",
  "msg": "Backup completed",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2"
}
my-cluster-2 postgres {
  "level": "error",
  "ts": "2023-07-26T09:12:30Z",
  "logger": "barman",
  "msg": "Can't extract backup id",
  "logging_pod": "my-cluster-2",
  "command": "barman-cloud-backup-show",
  "options": [
    "--format",
    "json",
    "--endpoint-url",
    "<my s3 compatible storage>",
    "--cloud-provider",
    "aws-s3",
    "<my s3 destination>",
    "my-cluster",
    "backup-1690362727"
  ],
  "stdout": "",
  "stderr": "2023-07-26 09:12:30,354 [273] ERROR: Barman cloud backup show exception: Unknown backup 'backup-1690362727' for server 'my-cluster'\n",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.executeQueryCommand\n\tpkg/management/barman/backuplist.go:87\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.GetBackupByName\n\tpkg/management/barman/backuplist.go:140\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).getExecutedBackupInfo\n\tpkg/management/postgres/backup.go:383\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:352\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:267"
}
my-cluster-2 postgres {
  "level": "error",
  "ts": "2023-07-26T09:12:30Z",
  "msg": "Backup failed",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:271"
}
```

Happy to provide more config if it is helpful.

As an aside, when this problem is encountered using `ScheduledBackup`, it seems to cause the ScheduledBackup to run repeatedly rather than adhering to its schedule.

**Comment by mwienk** [comment]
I'm running into this issue as well, I'm on linode s3 storage, perhaps that might cause the issue somehow

**Comment by mwienk** [comment]
Fixed it with help from https://github.com/EnterpriseDB/barman/issues/835. Moving the bucket name from the endpoint url into the destinationpath fixes it (see https://github.com/cloudnative-pg/cloudnative-pg/pull/2630/files)

**Comment by mrclrchtr** [comment]
Thank you so much. I spent several hours on the problem. In my case it was the following combination:

Failing chart config:
```
backups:
  data:
    encryption: "" # Contabo does not support encryption
  wal:
    encryption: "" # Contabo does not support encryption
  endpointURL: "https://eu2.contabostorage.com/cnpg-cluster-backups-prod"
  s3:
    bucket: "cnpg-cluster-backups-prod"
```

Successful config:
```
backups:
  enabled: true
  data:
    encryption: "" # Contabo does not support encryption
  wal:
    encryption: "" # Contabo does not support encryption
  endpointURL: "https://eu2.contabostorage.com"
  destinationPath: "s3://cnpg-cluster-backups-prod/"
  s3:
    bucket: "cnpg-cluster-backups-prod"
```
