### ISSUE TITLE
Unable to create Cloudnative-pg continuous backups

### ISSUE THREAD

**Issue by perfectra1n** [cloudnative-pg/cloudnative-pg#2517]
Hi there,

(continuation of my comments on #1985)

I love Cloudnative-pg, and I'm willing to fight hard to keep using it in my homelab cluster lol. I'm not able to create Continuous Backups of my cluster (named `main-cluster`). My Operator was installed via the Helm Chart, and then I created my cluster. I have a Minio instance created (API URL `s3.domain.com`) an S3 bucket (`cloudnative-pg-backups`), and a user (`backup-user1`). This is all contained in the `databases` namespace.

I essentially see two different kinds of errors.

1. Unable to fetch the Secret
```json
{"level":"info","ts":"2023-07-28T14:56:37Z","msg":"backup credentials don't yet have access permissions. Will retry reconciliation loop","logging_pod":"main-cluster-4"}
{"level":"error","ts":"2023-07-28T15:41:09Z","logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"main-cluster-1","currentPrimary":"main-cluster-1","targetPrimary":"main-cluster-1","options":["--cloud-provider","aws-s3","s3://cloudnative-pg-backups","main-cluster"],"exitCode":-1,"error":"exit status 4","stacktrace":"stacktrace..."}
```

2. 403 HTTP error when calling the HeadBucket operation
```json
{"level":"info","ts":"2023-07-28T03:53:30Z","logger":"barman-cloud-check-wal-archive","msg":"2023-07-28 03:53:30,429 [31408] ERROR: Barman cloud WAL archive check exception: An error occurred (403) when calling the HeadBucket operation: Forbidden","pipe":"stderr","logging_pod":"main-cluster-1"}
{"level":"error","ts":"2023-07-28T03:53:30Z","logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"main-cluster-1","currentPrimary":"main-cluster-1","targetPrimary":"main-cluster-1","options":["--cloud-provider","aws-s3","s3://cloudnative-pg-backups/main-cluster/","main-cluster"],"exitCode":-1,"error":"exit status 4","stacktrace":"stacktrace..."}
{"level":"error","ts":"2023-07-28T03:53:30Z","msg":"while barman-cloud-check-wal-archive","logging_pod":"main-cluster-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"stacktrace..."}
{"level":"error","ts":"2023-07-28T03:53:30Z","logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"main-cluster-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"stacktrace..."}
```

Following are the resources that were created:

Operator's Helm Release
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-config-or-state-change.discord: ""
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: '0.18.2'
    helm:
      releaseName: cnpg-database-release
      values: |
        create:
          crds: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: databases
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 
```

Cluster
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
  labels:
    name: main-cluster
    usecase: databases
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-8
  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB

  storage:
    size: 30Gi
    storageClass: local-path

  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnative-pg-backups"
      endpointUrl: "https://s3.domain.com"
      serverName: "main-cluster"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: aws-creds
          key: MINIO_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 8
      data:
        compression: gzip    
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: main-cluster
  namespace: databases
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: main-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: main-cluster-cnpg-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.11.0.5
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: main-cluster
    role: primary
```

Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: databases
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "8VPlstring123cZ"
  MINIO_SECRET_KEY: "rEIFTjbstring1234Nli9Wn6aVWiB23kz"
```

I am applying the Secret via `k apply -f aws-creds.yaml`.
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/2390633/1f7454fb-2afa-4991-8d6b-d673ddbe8fdb)

I have validated that the ServiceAccount *can* get `secrets/aws-creds` from the `databases` namespace:
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/2390633/87385bcb-9a3d-4cfe-bd47-b3c94b9d4574)

The cluster appears healthy as well:
```
[32mCluster Summary[0m
Name:               main-cluster
Namespace:          databases
System ID:          7260600562685251612
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:14.8-8
Primary instance:   main-cluster-1
Status:             [32mCluster in healthy state[0m 
Instances:          [32m3[0m
Ready instances:    [32m3[0m
Current Write LSN:  0/27000060 (Timeline: 1 - WAL File: 000000010000000000000027)

[32mCertificates Status[0m
Certificate Name          Expiration Date                Days Left Until Expiration
----------------          ---------------                --------------------------
main-cluster-ca           2023-10-25 20:33:14 +0000 UTC  89.15
main-cluster-replication  2023-10-25 20:33:14 +0000 UTC  89.15
main-cluster-server       2023-10-25 20:33:14 +0000 UTC  89.15

[32mContinuous Backup status[0m
First Point of Recoverability:  Not Available
Working WAL archiving:          [31mFailing[0m
WALs waiting to be archived:    1
Last Archived WAL:              000000010000000000000025   @   2023-07-28T14:56:22.894764Z
Last Failed WAL:                000000010000000000000026   @   2023-07-28T16:59:46.422078Z

[32mStreaming Replication status[0m
Name            Sent LSN    Write LSN   Flush LSN   Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority
----            --------    ---------   ---------   ----------  ---------  ---------  ----------  -----      ----------  -------------
main-cluster-4  0/27000060  0/27000060  0/27000060  0/27000060  00:00:00   00:00:00   00:00:00    streaming  async       0
main-cluster-5  0/27000060  0/27000060  0/27000060  0/27000060  00:00:00   00:00:00   00:00:00    streaming  async       0

[32mUnmanaged Replication Slot Status[0m
No unmanaged replication slots found

[32mInstances status[0m
Name            Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----            -------------  -----------  ----------------  ------  ---         ---------------  ----
main-cluster-1  72 MB          0/27000060   Primary           OK      BestEffort  1.20.2           newworkernode2
main-cluster-4  72 MB          0/27000060   Standby (async)   OK      BestEffort  1.20.2           newworkernode1
main-cluster-5  72 MB          0/27000060   Standby (async)   OK      BestEffort  1.20.2           newworkernode1
```

I'm not exactly sure where I'm going wrong, why the permissions are (possibly) messed up, or why the ServiceAccount can't read the Secret. Any direction would be hugely appreciated. Where am I going wrong?
