### ISSUE TITLE
Barman DB restore is getting failed for Replica clusters

### ISSUE THREAD

**Issue by oberai07** [cloudnative-pg/cloudnative-pg#2524]
Hi Team 
We are trying to integrate OpenStack Swift s3 storage with open-source cloudnative-pg for Kubernetes. We have a Primary Postgres cluster running with barmanobjectstore to store backups. We can integrate the Swift S3 storage with the Primary Postgres cluster and create on-demand backups successfully. But, when we try to restore the backups from S3 storage for Replica clusters, it throws the below error.
`ERROR: Barman cloud restore exception: not a gzip file","pipe":"stderr","logging_pod":"edb-primary-cluster-1-full-recovery"}
`
We can see backups are available in the S3 bucket in gzip format.  How can we fix this issue? It looks like the backup gzip file is corrupted but why?

I am using the below Postgis and operator images for configuration:
Postgis: ghcr.io/cloudnative-pg/postgis:11-3.3-64
Operator: ghcr.io/cloudnative-pg/cloudnative-pg:1.20.0

**Comment by phisco** [comment]
@oberai07, sharing the Cluster configuration for both the source and replica cluster would definitely be helpful.

**Comment by oberai07** [comment]
@phisco Thanks for the reply. PFB manifests of Primary and Replica Postgres Clusters.


**Primary Postgres Cluster**

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edb-primary-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgis:11-3.3-64
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.36.147.0/24 md5
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-app-user
  superuserSecret:
    name: cluster-superuser
  storage:
    size: 2Gi
    storageClass: local-edb-pgsql
  backup:
    barmanObjectStore:
      destinationPath: s3://edb-backups/
      endpointURL: http://10.32.121.140:8080/
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: false
        jobs: 2

```
**Replica Cluster**

**apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edb-primary-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgis:11-3.3-64
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.36.147.0/24 md5
  storage:
    size: 2Gi
    storageClass: local-edb-pgsql
  bootstrap:
    recovery:
      source: edb-primary-cluster
  replica:
    enabled: true
    source: edb-primary-cluster
  superuserSecret:
    name: cluster-superuser
  externalClusters:
  - name: edb-primary-cluster
    barmanObjectStore:
      destinationPath: "s3://edb-backups/"
      endpointURL: "http://10.32.121.140:8080"
      s3Credentials:
        accessKeyId:
          name: aws-creds          
          key: ACCESS_KEY_ID  
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY**

**Comment by phisco** [comment]
What about adding the following configuration to the new cluster's external cluster?
```
      wal:
        compression: gzip
      data:
        compression: gzip

```
