### ISSUE TITLE
[Feature Request] Support the scale sub-resource for Clusters

### ISSUE THREAD

**Issue by fullykubed** [cloudnative-pg/cloudnative-pg#2574]
We would like to utilize the vertical pod autoscaler to automatically scale the PG pods in the Cluster. The VPA can support managing pods of custom resources as long as they implement the scale sub-resource. It would be great to have that for the Cluster CRD.

## Example VPA Manifest

```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  creationTimestamp: "2023-08-11T19:53:06Z"
  generation: 2
  name: primary-api-pg
  namespace: primary-api
  resourceVersion: "5833222"
  uid: 307a843d-9891-4a0c-8a4c-b6c05827697e
spec:
  targetRef:
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    name: primary-api-pg
  updatePolicy:
    updateMode: Auto
```

## Current Error
```
Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef postgresql.cnpg.io/v1 / Cluster / primary-api-pg, last error Resource primary-api/primary-api-pg has an empty selector for scale sub-resource
```

**Comment by jclangst** [comment]
More info on the implementation spec [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource).

**Comment by phisco** [comment]
Good point! Looks like the only thing we are missing is the `scaleselector`

**Comment by devthejo** [comment]
Need this also. Can I propose a PR ?

**Comment by devthejo** [comment]
Here is my workaround:
- disable cnpg webhooks, here are the values passed to the official cnpg chart
```yaml
webhook:
    mutating:
      create: false
    validating:
      create: false
````

- add a kyverno rule to mutate the cluster crd and the clusters
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cnpg-cluster-scale-selector
spec:
  background: true
  generateExisting: true
  mutateExistingOnPolicyUpdate: true
  useServerSideApply: true
  rules:
    - name: add-spec-selector-to-crd
      match:
        resources:
          kinds:
            - CustomResourceDefinition
          names:
            - clusters.postgresql.cnpg.io
      mutate:
        targets:
          - apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            name: clusters.postgresql.cnpg.io
        patchStrategicMerge:
          spec:
            versions:
              - (name): v1
                schema:
                  openAPIV3Schema:
                    type: object
                    served: true
                    storage: true
                    properties:
                      spec:
                        properties:
                          selector: 
                            type: string
                subresources:
                  scale:
                    labelSelectorPath: .spec.selector
                    specReplicasPath: .spec.instances
                    statusReplicasPath: .status.instances
    - name: add-spec-selector-to-clusters
      match:
        resources:
          kinds:
            - postgresql.cnpg.io/v1/Cluster
      mutate:
        targets:
          - apiVersion: postgresql.cnpg.io/v1
            kind: Cluster
        patchStrategicMerge:
          spec:
            selector: "cnpg.io/cluster={{ request.object.metadata.name }}"
```

and my vpa:
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    name: my-pg-cluster
  updatePolicy:
    updateMode: "Off"
```

and I can see the provided recommendations from the vpa

tada !!!

**Comment by devthejo** [comment]
I finally had problem caused by this issue: https://github.com/cloudnative-pg/cloudnative-pg/issues/3753 so I reactived webhook and removed a part using the following manual patch
and after upgraded cnpg to latest version the kyverno policy part that update the crd didn't work anymore, so
here is my tricky solution for now

```sh
kubectl -n cnpg patch crd clusters.postgresql.cnpg.io --type json --patch-file patches/cluster-crd.patch.yaml
kubectl patch mutatingwebhookconfiguration cnpg-mutating-webhook-configuration --type=json  --patch-file patches/webhook.patch.yaml
```

`patches/cluster-crd.patch.yaml`:

```json
[
  {
    "op": "add",
    "path": "/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/selector",
    "value": { "type": "string" },
  },
  {
    "op": "add",
    "path": "/spec/versions/0/subresources/scale/labelSelectorPath",
    "value": ".spec.selector",
  },
]
```

`patches/webhook.patch.yaml`:

```json
[{ "op": "remove", "path": "/webhooks/1" }]
```

and in argocd applicationset set.templatate.spec:
```yaml
ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jsonPointers:
            - /webhooks
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/selector
            - /spec/versions/0/subresources/scale/labelSelectorPath
````

and the new kyverno policy:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cnpg-cluster-scale-selector
spec:
  background: true
  generateExisting: true
  mutateExistingOnPolicyUpdate: true
  useServerSideApply: true
  rules:
    - name: add-spec-selector-to-clusters
      match:
        resources:
          kinds:
            - postgresql.cnpg.io/v1/Cluster
      mutate:
        targets:
          - apiVersion: postgresql.cnpg.io/v1
            kind: Cluster
        patchStrategicMerge:
          spec:
            selector: "cnpg.io/cluster={{`{{ request.object.metadata.name }}`}}"
```
