### ISSUE TITLE
Misleading documentation regarding Azure Blob Storage backups

### ISSUE THREAD

**Issue by netthier** [cloudnative-pg/cloudnative-pg#2576]
The docs on backing up into Azure Blob Storage currently say the following:
> Given the previous secret, the provided credentials can be injected inside the cluster configuration:
 ```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
[...]
spec:
  backup:
    barmanObjectStore:
      destinationPath: "<destination path here>"
      azureCredentials:
        connectionString:
          name: azure-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: azure-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: azure-creds
          key: AZURE_STORAGE_SAS_TOKEN
```
(https://cloudnative-pg.io/documentation/1.18/backup_recovery/#azure-blob-storage)
The first part of the docs correctly mentions that only specific combinations of these values are required.
However, specifying more than the required values actually makes cloudnative-pg reject the resource with an error like
`when connection string is not specified, one and only one of storage key and storage SAS token is allowed` or similar.
This should either be explicitly specified or the example changed such that specifying all 4 parameters isn't presented as a valid configuration.
