### ISSUE TITLE
For creating postgres cluster, why is the cpu limit required to be added ?

### ISSUE THREAD

**Issue by ditpoo** [cloudnative-pg/cloudnative-pg#2586]
In the cluster resource, why is it required to add cpu limits 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
...
spec:
  resources:
    limits:
      memory: 1Gi
      cpu: 1
...
```
As mentioned here https://www.howtogeek.com/devops/should-you-set-kubernetes-cpu-limits/ , it should be not mandatory to set the cpu limits, so why is it so with the operator ?
