### ISSUE TITLE
Feature request: set labels/annotations on generated services

### ISSUE THREAD

**Issue by rvos-73** [cloudnative-pg/cloudnative-pg#2610]
Current: cannot set custom labels or annotations on the generated k8s service objects

Want: ability to specify custom labels/annotations on service objects. 
Being able to do something like this would be great:
```
service-r:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: <hostname>
        metallb.universe.tf/address-pool: <pool>
```

Motivation: We want some services to be picked up by metallb. For this, we need to be able to set a custom label to a specific services ( e.g. the -r service). Currently, it seems we can only add the annotation with some post deployment. This is not ideal.
