### ISSUE TITLE
Allow to define custom namespace for PodMonitor

### ISSUE THREAD

**Issue by jurim76** [cloudnative-pg/cloudnative-pg#2613]
In our company we are using monitoring namespace for prometheus `probeNamespaceSelector`, that means prometheus monitors this namespace only.
cnpg operator doesn't allow to specify different namespace for podmonitor and creates podmonitor in current namespace only.
It's a good idea to add custom namespace support for podmonitor kind, allow to setup monitoring in more flexible way, imho.

**Comment by cloudymax** [comment]
We are seeing the same issue, we have an existing installation of the kube-prometheus-stack that monitoring the 'monitoring' namespace. Following the monitoring examples leads to "No data" in all dashboards. We'd prefer not to have to run 2 full prometheus and grafana stacks to use this operator fully.

**Comment by joekrill** [comment]
Being able to add additional labels would be ideal, too. For `kube-prometheus-stack` you need a `release` label that matches the name of the helm release in order for prometheus to pick up the monitor. 

On the other hand, it was super simply to just set `enablePodMonitor: false` and create one manually, too, which I'm fairly certain has the same exact effect, i.e.:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  labels:
    release: prometheus-stack 
  namespace: whatever-you-want
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
  podMetricsEndpoints:
    - port: metrics

```
