### ISSUE TITLE
Using Operator with Pooler - role "cnpg_pooler_pgbouncer" does not exist

### ISSUE THREAD

**Issue by MarkCupitt** [cloudnative-pg/cloudnative-pg#263]
I have a pretty vanilla operator and pooler setup, experimenting with them, using pgadmin4 via the pooler service to access, letting the operator create the secrets

Pgadmin4 gets a timeout when logging in with the following logs being generated

Database Pod Logs

```
# {"level":"info","ts":1655279411.679227,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:50:11.679 UTC","pid":"16","level":"WARNING","msg":"server login failed: FATAL role \"cnpg_pooler_pgbouncer\" does not exist"}}
```

Pooler Pod Logs
```
# {"level":"info","ts":1655279457.3416626,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:50:57.341 UTC","pid":"16","level":"LOG","msg":"S-0x253bbb0: postgres/cnpg_pooler_pgbouncer@10.152.183.182:5432 new connection to server (fr
# {"level":"info","ts":1655279457.3450568,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:50:57.344 UTC","pid":"16","level":"LOG","msg":"S-0x253bbb0: postgres/cnpg_pooler_pgbouncer@10.152.183.182:5432 SSL established: TLSv1.3/TLS
# {"level":"info","ts":1655279457.346074,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:50:57.346 UTC","pid":"16","level":"WARNING","msg":"server login failed: FATAL role \"cnpg_pooler_pgbouncer\" does not exist"}}
# {"level":"info","ts":1655279457.3461196,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:50:57.346 UTC","pid":"16","level":"LOG","msg":"S-0x253bbb0: postgres/cnpg_pooler_pgbouncer@10.152.183.182:5432 closing because: login faile
# {"level":"info","ts":1655279471.6721904,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:51:11.672 UTC","pid":"16","level":"LOG","msg":"C-0x252b3b0: postgres/(nouser)@192.168.1.242:1794 closing because: query_wait_timeout (age=1
# {"level":"info","ts":1655279471.6722536,"msg":"record","pipe":"stderr","record":{"timestamp":"2022-06-15 07:51:11.672 UTC","pid":"16","level":"WARNING","msg":"C-0x252b3b0: postgres/(nouser)@192.168.1.242:1794 pooler error: query_wait_timeout"}}
```

Database Yaml

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: $DB_CLUSTER_NAME-database
  namespace: $POSTGRES_NAMESPACE
spec:
  instances: $postgres_number_of_instances
  imageName: ghcr.io/cloudnative-pg/postgresql:14.3
  startDelay: 0
  stopDelay: 0
  primaryUpdateStrategy: unsupervised

#  superuserSecret:
#    name: $DB_CLUSTER_NAME.superuser
 
  # Parameters and pg_hba configuration will be append
  # to the default ones to make the cluster work
  # https://github.com/cloudnative-pg/cloudnative-pg/blob/main/
  postgresql:
    parameters:
      max_worker_processes: "60"
      shared_buffers: "1GB"
      auto_explain.log_min_duration: '10s'
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    
    pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret $DB_CLUSTER_NAME.app.user
      # - host all all all md5
      - host all all all scram-sha-256 # (or md5 for PostgreSQL

  bootstrap:
    initdb:
      database: bonanza
      owner: $POSTGRES_APP_USER
#      secret:
#        name: $DB_CLUSTER_NAME.app.user
      dataChecksums: true
      encoding: 'UTF8'
 
  resources:
    requests:
      cpu: "$postgres_request_cpu"
      memory: "$postgres_request_memory"
    limits:
      cpu: "$postgres_limits_cpu"
      memory: "$postgres_limits_memory"
    
  affinity:
    enablePodAntiAffinity: false #unrestricted affinity
    topologyKey: kubernetes.io/hostname #defaul value
    podAntiAffinityType: preferred #default value

  storage:
    size: $POSTGRES_DB_SIZE
#    storageClass: $PostgresStorageClass

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: $DB_CLUSTER_NAME.pooler.rw
  namespace: $POSTGRES_NAMESPACE
spec:
  cluster:
    name: $DB_CLUSTER_NAME-database
  instances: 2
  type: "rw"
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
---

**Comment by phisco** [comment]
hello, I tried reproducing the issue, but I didn't manage to. Here the stripped down configuration i've tried:
```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  postgresql:
    pg_hba:
      - host all all all scram-sha-256 # (or md5 for PostgreSQL

  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: bonanza
      owner: bonanza
      dataChecksums: true
      encoding: 'UTF8'
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler
spec:
  cluster:
    name: cluster-example
  instances: 2
  type: "rw"
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
```

tested the conneciton by getting the pasword from the cluster-example-superuser secret, decoded and tried accessing through the pooler from one of the cluster's instances itself: `kubectl exec -ti  cluster-example-2 -- psql 'host=pooler user=postgres  dbname=postgres'` and inserting the password.
