### ISSUE TITLE
Request: Add connection URI to the basic-auth secrets

### ISSUE THREAD

**Issue by 02JanDal** [cloudnative-pg/cloudnative-pg#2632]
A lot of applications that use PostgreSQL take a connection URI containing the connection parameters (https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6).

It would be great if CNPG could add such a URI to the `basic-auth` secrets, next to the username, password and pgpass file. That way, applications that want to be given such a URI could be configured with just an environment variable and `secretKeyRef`, rather than the current way of either manually constructing the URI or using variable expansions like:

```yaml
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: db-app
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: db-app
                key: password
          - name: DATABASE_URI
            value: postgresql://$(PGUSER):$(PGPASSWORD)@db-r/app
```

Instead, I'd want just:

```yaml
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: db-app
                key: uri
```

It's certainly not the end of the world, but feels like a relatively small change for a decent improvement in DX.
