### ISSUE TITLE
S3 backup: Invalid endpoint with environment variable usage

### ISSUE THREAD

**Issue by nlamirault** [cloudnative-pg/cloudnative-pg#2648]
I setup my backup like that:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "authentik.labels" (index .Subcharts "authentik") | nindent 4 }}
  name: {{ .Values.cloudnativepg.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ... 
  envFrom:
  - secretRef:
      name: authentik-cloudflare-credentials
  ...
  backup:
    barmanObjectStore:
      destinationPath: s3://{{ .Values.cloudnativepg.backup.s3.bucket }}
      endpointURL: "${AWS_ENDPOINT_URL}"
      s3Credentials:
        accessKeyId:
          name: authentik-cloudflare-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-cloudflare-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        maxParallel: 8
```

in the cluster pod, i've got the environment variable set:

```
nobody@authentik-1:/$ env|grep AWS
AWS_ENDPOINT_URL=https://xxxxxxx.r2.cloudflarestorage.com
```

But backup logs says it is invalid:

```
{"level":"error","ts":"2023-08-30T16:11:51Z","msg":"while barman-cloud-check-wal-archive","logging_pod":"authentik-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:384\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:169\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-08-30T16:11:51Z","logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"authentik-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:83\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/proc.go:250"}
{"level":"info","ts":"2023-08-30T16:11:51Z","logger":"postgres","msg":"record","logging_pod":"authentik-1","record":{"log_time":"2023-08-30 16:11:51.194 UTC","process_id":"28","session_id":"64ef6585.1c","session_line_num":"65","session_start_time":"2023-08-30 15:51:33 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"archive command failed with exit code 1","detail":"The failed archive command was: /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/000000010000000000000001","backend_type":"archiver","query_id":"0"}}
{"level":"info","ts":"2023-08-30T16:11:53Z","logger":"wal-archive","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"authentik-1"}
{"level":"info","ts":"2023-08-30T16:11:56Z","logger":"barman-cloud-check-wal-archive","msg":"2023-08-30 16:11:56,897 [971] ERROR: Barman cloud WAL archive check exception: Invalid endpoint: ${AWS_ENDPOINT_URL}","pipe":"stderr","logging_pod":"authentik-1"}
{"level":"error","ts":"2023-08-30T16:11:57Z","logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"authentik-1","currentPrimary":"authentik-1","targetPrimary":"authentik-1","options":["--endpoint-url","${AWS_ENDPOINT_URL}","--cloud-provider","aws-s3","s3://portefaix-homelab-authentik","authentik"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:257\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:383\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:169\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/proc.go:250"}
```

**Comment by MichaluxPL** [comment]
Where do You set this AWS_ENDPOINT_URL variable ?
Log shows that operator cannot resolve it to an address.
If You try to do it in the cluster's manifest, than I'm affraid it won't work that way.

**Comment by nlamirault** [comment]
@MichaluxPL the environment variable comes from the `envFrom` field and set into the corresponding secret. So it's actually present in the pod `cluster` but not in the pod operator.
I can set that variable into the Operator pod, but with that, i've got only one possible endpoint ...
do you think it could possible to add a variable into the `s3credentials` ?
like that:

```yaml
     s3Credentials:
        accessKeyId:
          name: authentik-cloudflare-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-cloudflare-credentials
          key: ACCESS_SECRET_KEY
       endpointUrl:
          name: authentik-cloudflare-credentials
          key: ENDPOINT_URL
```
