### ISSUE TITLE
Missing documentation on how to enable pg extensions

### ISSUE THREAD

**Issue by smitpatelx** [cloudnative-pg/cloudnative-pg#2660]
# What's the problem:
- Recently, I was trying to use `uuid-soop` extension and after 2 days of trying I finally found the solution. So I decided to share this here, so other users can find the solution without wasting their time.

# How to solve it?
- Using `bootstrap.initdb`. [Docs](https://cloudnative-pg.io/documentation/1.17/bootstrap/#the-bootstrap-section)
- Here is working example:
```yaml
bootstrap:
  initdb:
    database: your-db-name
    owner: your-db-user
    secret:
      name: your-db-secret
    postInitTemplateSQL:
      - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      - CREATE EXTENSION IF NOT EXISTS <extension-name>;
```

# What problems I face:
- So first I created my own image with the init script which didn't work here for some reason.
- Then I tried to put the `CREATE EXTENSION` script under `postInitSQL`.
- Problem here is, command under **postInitSQL** section, run before database is created, so uuid extension is not available in that newly created database.
- To solve it, I replaced `postInitSQL` with `postInitTemplateSQL`.

# Todo:
- I would like to contribute to docs and add this information.
- Let me know, if I can contribute to docs.

Cheers 🎉
