### ISSUE TITLE
Operator waits for jobs it didn't create

### ISSUE THREAD

**Issue by jarom-pdk** [cloudnative-pg/cloudnative-pg#2662]
The `initdb` job was never created due to an error in a cluster definition that wasn't rejected by the admission webhook (#2661). Instead the process errored out early due to being unable to create a job based on the invalid configuration. Using the YAML below with CNPG 1.20.2 resulted in no pod being created due to the invalid specification in the YAML but CNPG is waiting for the pod to become available and to initialize the DB though there are no jobs for such scheduled.

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-issue-resources
spec:
  description: "Fails to Create Pod for Cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1

  storage:
    storageClass: standard
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 75m
      memory: 128Mi
```

This appears to be the relevant item from the operator logs:
```
cnpg-cloudnative-pg-7dd9bf9949-r9694 manager {"level":"error","ts":"2023-08-31T22:15:27Z","msg":"Unable to create job","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-issue-resources","namespace":"test"},"namespace":"test","name":"cnpg-issue-resources","reconcileID":"ac13adfc-1c0e-4914-b3d5-e3bece9b4871","uuid":"e3769c8b-484b-11ee-a5f3-72d6aa6f68c1","job":{"namespace":"test","name":"cnpg-issue-resources-1-initdb"},"error":"Job.batch \"cnpg-issue-resources-1-initdb\" is invalid: [spec.template.spec.containers[0].resources.requests: Invalid value: \"256Mi\": must be less than or equal to memory limit, spec.template.spec.initContainers[0].resources.requests: Invalid value: \"256Mi\": must be less than or equal to memory limit]","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).createPrimaryInstance\n\tcontrollers/cluster_create.go:1004\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).ReconcilePods\n\tcontrollers/cluster_controller.go:645\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).reconcileResources\n\tcontrollers/cluster_controller.go:499\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).reconcile\n\tcontrollers/cluster_controller.go:335\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).Reconcile\n\tcontrollers/cluster_controller.go:145\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
```
