### ISSUE TITLE
Boostrapping multi-terrabyte cluster too slow with pg_dump

### ISSUE THREAD

**Issue by rochecompaan** [cloudnative-pg/cloudnative-pg#2677]
I set up a temporary Postgres deployment to bootstrap a new cluster according to #2638. The total size of the database is 6.2 terabytes. After roughly one day, only 300 GB was restored. For comparison, the wal-g restore took about 6 hours, and this was only possible because I could increase the concurrency to 100. For CPNG, the spec doesn't currently allow increasing the number of pg_dump jobs, e.g., `pg_dump -j njobs`. 

I suspect that even increasing the number of pg_dump jobs won't help me to restore a  database this size in a reasonable time (hours instead of days), but I would be happy to try if such an option becomes available.

I used an unorthodox workaround that might be useful to someone else trying to bootstrap a new cluster from a big database:
1. Create a temporary Postgres deployment using the base backup restored using wal-g.
2. Create a single instance CNPG cluster with node affinity set to the same node as the temp Postgres instance.
3. Use [imperative hibernation](https://cloudnative-pg.io/documentation/1.20/kubectl-plugin/#cluster-hibernation) to hibernate the CNPG cluster.
4. Move the base, global, and all the pg_* dirs from the Postgres persistent volume to the CNPG instance persistent volume and fix file permissions. Keep all the config files as is. I moved the files directly on the node filesystem while not in use by any pods.
5. Switch hibernation off on the CNPG cluster to start the cluster up and scale to 3 instances. 

It would be great if the docs could address bootstrapping a new cluster from a physical backup in the future, but allowing one to increase the number of pg_dump jobs would already be a big help.

**Comment by rochecompaan** [comment]
@gbartolini, thanks for your feedback!

Yes, WAL-G is a physical backup tool, just like Barman, but let me clarify how pg_dump comes into play.

I only used WAL-G to set up a temporary Postgres instance running inside the Kubernetes cluster. I created a Kubernetes Job to use WAL-G to restore to a persistent volume. Once the job was completed, I mounted the persistent volume inside the Postgres instance. At this point I had a running instance that one can use to bootstrap a new CNPG cluster using `externalClusters` as documented here: https://cloudnative-pg.io/documentation/1.20/database_import/#the-microservice-type
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-microservice
spec:
  instances: 3

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - angus
        source:
          externalCluster: cluster-pg96
        #postImportApplicationSQL:
        #- |
        #  INSERT YOUR SQL QUERIES HERE
  storage:
    size: 1Gi
  externalClusters:
    - name: cluster-pg96
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: pg96.local
        user: postgres
        dbname: postgres
      password:
        name: cluster-pg96-superuser
        key: password
```

As per the docs:
* export of the selected database (in initdb.import.databases) using pg_dump -Fc
* import of the database using pg_restore --no-acl --no-owner into the initdb.database

So, I'm referring to how the operator uses pg_dump to bootstrap the cluster, not my direct use. I had a look at the options used, and it doesn't support running multiple processes: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/management/postgres/logicalimport/database.go#L102

I'm heading over to read your article next. I just wanted to clarify my use of pg_dump first.
