### ISSUE TITLE
How can we force to use single storage location to save the acrhived WAL files for Primary and Replica Postgresql CLusters after failover?

### ISSUE THREAD

**Issue by oberai07** [cloudnative-pg/cloudnative-pg#2678]
We have Replica clusters and Primary Postgres Cluster deployed in our environment and we want to use a single storage location i.e. same barmanObjectStore configuration for all Postgres clusters deployed on different Kubernetes clusters. 
In earlier operator versions it was possible to use the same barmanObjectStore configuration but with Postgres operator version 1.20, the Replica cluster is throwing the below error. We need the same barmanObjectStore configuration on Primary Postgres and Replica clusters to perform Postgres Clusters failover operations between multiple k8s clusters deployed on different regions so that replication would never break between the Primary Postgres Cluster and the Replica Cluster.

`ERROR: WAL archive check failed for server recoveredCluster : Expected empty archive`

After the failover or promotion of the Replica cluster to a Primary Postgres Cluster, we would recreate the Replica cluster on another Kubernetes cluster by deleting the Primary Postgres Cluster.  Doing this we would always have the  Primary and Replica Clusters setup deployed and running on different Kubernetes clusters.

**Comment by oberai07** [comment]
PFB Replica Cluster Manifest:

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edb-primary-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgis:11-3.3-68
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      archive_timeout: '120'
    pg_hba:
      - host all all 10.36.0.0/24 md5
  storage:
    size: 2Gi
    storageClass: local-edb-pgsql
  bootstrap:
    recovery:
      source: edb-primary-cluster
  replica:
    enabled: true
    source: edb-primary-cluster
  superuserSecret:
    name: cluster-superuser
  externalClusters:
  - name: edb-primary-cluster
    barmanObjectStore:
      destinationPath: "s3://pgdata-backup"
      endpointURL: "http://<IP>:8080"
      s3Credentials:
        accessKeyId:
          name: aws-creds          
          key: ACCESS_KEY_ID  
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        immediateCheckpoint: true
  backup:
    barmanObjectStore:
              destinationPath: "s3://pgdata-backup"
              endpointURL: "http://<IP>:8080"
              serverName: "recoveredCluster"
              s3Credentials:
                accessKeyId:
                  name: aws-creds
                  key: ACCESS_KEY_ID
                secretAccessKey:
                  name: aws-creds
                  key: ACCESS_SECRET_KEY
              wal:
                compression: gzip
              data:
                compression: gzip
                immediateCheckpoint: true
                jobs: 2

```

**Comment by gbartolini** [comment]
@oberai07 could this be related to #2730?

**Comment by oberai07** [comment]
> @oberai07 could this be related to #2730?

Not sure. If it would skip checking the WAL archives already stored in the S3 storage bucket (i.e. skip checking the empty archive for the replica cluster declared in the backup section) then, it may be able to fix this issue.

**Comment by gbartolini** [comment]
Yes, it should.

**Comment by gbartolini** [comment]
I have been able to test that the feature is now working thanks to the aforementioned fix, with the following example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-skipping-wal-archive-check
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
# ...
```

I am closing this ticket. Feel free to reopen in the future if the issue is not fixed.
