### ISSUE TITLE
Allow Creation of Multiple Databases

### ISSUE THREAD

**Issue by MarkCupitt** [cloudnative-pg/cloudnative-pg#269]
The current bootstrap: initdb allows for the creation of a single database with its associated user/owner, for example:

```
  bootstrap:
    initdb:
      database: bonanza
      owner: $POSTGRES_APP_USER
      secret:
        name: $DB_CLUSTER_NAME.app.user
      dataChecksums: true
      encoding: 'UTF8'
```

We have a K8's application that uses several databases and we would like to create them all at once in this manner if at all possible

```
  bootstrap:
    initdb:
      - database: db1
        owner: user1
        secret:
          name: app.user1
        dataChecksums: true
        encoding: 'UTF8'
      - database: db2
        owner: user2
        secret:
          name: app.user2
        dataChecksums: false
        encoding: 'LATIN1'
```
