### ISSUE TITLE
Wrong condition `ClusterIsReady` during single replica restart

### ISSUE THREAD

**Issue by ianstanton** [cloudnative-pg/cloudnative-pg#2809]
When restarting a _single_ replica `Cluster`, the pod does not restart and we never see the `ConditionClusterReady` condition flip to `False`. We only see:
```
  conditions:
  - lastTransitionTime: "2023-09-15T18:00:21Z"
    message: Cluster is Ready
    reason: ClusterIsReady
    status: "True"
    type: Ready
```

We are not able to connect with `psql` during this restart time, but `ConditionClusterReady` is True. This condition should be `False` until the restart is complete and we're able to connect again.

**_Note_** - This is not the case with a 3-replica `Cluster`, where we observe two of the replicas roll restart, and see this expected condition:
```
  conditions:
  - lastTransitionTime: "2023-09-15T18:07:40Z"
    message: Cluster Is Not Ready
    reason: ClusterIsNotReady
    status: "False"
    type: Ready
```

I spoke with @litaocdl and we noticed `status.phase` is prematurely set back to `Cluster in healthy state` before the restart is complete:
```
> k -n cnpg get cluster -o custom-columns='type:.status.conditions[0].type,value:.status.conditions[0].status,STATUS_PHASE:.status.phase,REASON:.status.phaseReason' -w
type    value   STATUS_PHASE               REASON
Ready   True    Cluster in healthy state   <none>
Ready   True    Cluster in healthy state   <none>
Ready   False   Primary instance is being restarted in-place   cluster has been explicitly restarted via annotation
Ready   False   Primary instance is being restarted in-place   cluster has been explicitly restarted via annotation
Ready   True    Cluster in healthy state                       <none>
Ready   True    Cluster in healthy state                       <none>
Ready   True    Cluster in healthy state                       Primary instance restarted in-place
Ready   True    Cluster in healthy state                       <none>
```

Link to video and discussion here: https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1694806264280799?thread_ts=1694804358.894749&cid=C03AX0J5P29
