### ISSUE TITLE
Unable to modify pg_ident.conf

### ISSUE THREAD

**Issue by jniclas** [cloudnative-pg/cloudnative-pg#2832]
Hey,

it is possible to modify the pg_hba in the Cluster yaml, but I saw no option todo the same with pg_ident.conf. Is there another way of modifing this file?

Best regards
Niclas

**Comment by gbartolini** [comment]
What's your goal?

**Comment by jniclas** [comment]
I would like to use cloudNativePG with supabase, so I made their postgres image compatible with cloudNativePG with a custom image that builds on top of their image, but the pg_ident.conf and pg_hba.conf get overwritten by the cloudNativePG operator.  I need settings that match https://github.com/supabase/postgres/blob/develop/ansible/files/postgresql_config/pg_hba.conf.j2

**Comment by jniclas** [comment]
I was able to run the supabase postgres image with cloud native by doing

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "supabase.db.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: "supabase/postgres:15.1.1.26"
  imagePullPolicy: IfNotPresent
  postgresUID: 101
  postgresGID: 102
  ...
```

The actual issue was the postgres user id and group.
pg_hba and pg_ident are fine and work with supabase postgres image.
I updated my readme [README.md](https://github.com/jniclas/supabase-cloudnativedb/blob/main/README.md)
