### ISSUE TITLE
Review default values for `startDelay`, `stopDelay` and `switchoverDelay`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2833]
The current default values for `startDelay`, `stopDelay` and `switchoverDelay` are respectively `30`, `30` and `40000000`.

I believe it is time to review them, especially `startDelay` (which controls the liveness probe) which is by default too low. Although we explain that this needs to be set properly [here](https://cloudnative-pg.io/documentation/current/instance_manager/), I have barely seen that value being redefined.

SwitchoverDelay was conservatively set to a very high level in order not to break existing installations (at EDB time), but it basically emulates an infinite time for switchover - leaving the cluster hanging if there are open connections.

I am proposing new default values as follows:

- `startDelay: 3600`: we give Postgres up to 1 hour to recover from crash recovery or standby re-alignment situations
- `stopDelay: 1800`: we give Postgres up to 15 minutes to shutdown gracefully (smart) before we execute fast shutdown - we should introduce an option that controls the threshold between smart and fast (currently 50%)
- `switchoverDelay: 3600`: we give Postgres up to 1 hour to complete the fast shutdown

Thoughts?

**Comment by gbartolini** [comment]
This could also be related to #1964. BTW we should at least remove the sentence in the docs that says:

> For now, the operator doesn't configure a startupProbe on the Pods, since startup probes have been introduced only in Kubernetes 1.17.

**Comment by gbartolini** [comment]
Currently, this is how we set readiness and liveness probes:

```
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: <startDelay>
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

One option could be to fix `initialDelaySeconds` to `1` in the liveness probe, and start using a `startupProbe` as in the following example:

```
    startupProbe:
      failureThreshold: <FAILURE_THRESHOLD>
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

Where <FAILURE_THRESHOLD> is <startDelay> / periodSeconds (default set to 10 seconds, which becomes the minimal value for `startDelay`).

I know that - as Armando was saying in #1964 - there's no real benefit, but IMHO it is a more correct way of using what Kubernetes provides.

Please refer to this: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
