### ISSUE TITLE
Defer volume snapshot backup start at cluster startup

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2935]
Look at the following example:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: angus
spec:

  instances: 3

  storage:
    storageClass: ebs-sc
    size: 1Gi

  backup:
    volumeSnapshot:
      className: csi-aws-vsc
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: angus
spec:
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  cluster:
    name: angus
  immediate: true
  method: volumeSnapshot
```

The issue here is that the primary is immediately fenced once it is created and before replicas are cloned. We should detect this and if an immediate scheduled backup requiring cold backups on volume snapshot is requested, we should defer it.
