### ISSUE TITLE
Monitoring queries are cluttering the logs of replica clusters

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#294]
The monitoring queries we propose in our documentation (https://cloudnative-pg.io/documentation/1.15.1/samples/cnpg-basic-monitoring.yaml) are using pg_current_wal_lsn which is a function that is executable only in primary servers, and we don’t restrict this particular query to be executed just in those:

```
    pg_stat_replication:
      query: |
       SELECT usename
         , COALESCE(application_name, '') AS application_name
         , COALESCE(client_addr::text, '') AS client_addr
         , EXTRACT(EPOCH FROM backend_start) AS backend_start
         , COALESCE(pg_catalog.age(backend_xmin), 0) AS backend_xmin_age
         , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), sent_lsn) AS sent_diff_bytes
         , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), write_lsn) AS write_diff_bytes
         , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), flush_lsn) AS flush_diff_bytes
         , COALESCE(pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), replay_lsn),0) AS replay_diff_bytes
         , COALESCE((EXTRACT(EPOCH FROM write_lag)),0)::float AS write_lag_seconds
         , COALESCE((EXTRACT(EPOCH FROM flush_lag)),0)::float AS flush_lag_seconds
         , COALESCE((EXTRACT(EPOCH FROM replay_lag)),0)::float AS replay_lag_seconds
       FROM pg_catalog.pg_stat_replication
      metrics:
        - usename:
            usage: "LABEL"
            description: "Name of the replication user"
        - application_name:
            usage: "LABEL"
            description: "Name of the application"
        - client_addr:
            usage: "LABEL"
            description: "Client IP address"
        - backend_start:
            usage: "COUNTER"
            description: "Time when this process was started"
        - backend_xmin_age:
            usage: "COUNTER"
            description: "The age of this standby's xmin horizon"
        - sent_diff_bytes:
            usage: "GAUGE"
            description: "Difference in bytes from the last write-ahead log location sent on this connection"
        - write_diff_bytes:
            usage: "GAUGE"
            description: "Difference in bytes from the last write-ahead log location written to disk by this standby server"
        - flush_diff_bytes:
            usage: "GAUGE"
            description: "Difference in bytes from the last write-ahead log location flushed to disk by this standby server"
        - replay_diff_bytes:
            usage: "GAUGE"
            description: "Difference in bytes from the last write-ahead log location replayed into the database on this standby server"
        - write_lag_seconds:
            usage: "GAUGE"
            description: "Time elapsed between flushing recent WAL locally and receiving notification that this standby server has written it"
        - flush_lag_seconds:
            usage: "GAUGE"
            description: "Time elapsed between flushing recent WAL locally and receiving notification that this standby server has written and flushed it"
        - replay_lag_seconds:
            usage: "GAUGE"
            description: "Time elapsed between flushing recent WAL locally and receiving notification that this standby server has written, flushed and applied it"

    pg_statio_user_tables:
      target_databases:
        - "*"
      query: |
        SELECT
          current_database() datname
          , schemaname
          , relname
          , heap_blks_read
          , heap_blks_hit
          , idx_blks_read
          , idx_blks_hit
          , toast_blks_read
          , toast_blks_hit
          , tidx_blks_read
          , tidx_blks_hit
        FROM pg_catalog.pg_statio_user_tables
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of current database"
        - schemaname:
            usage: "LABEL"
            description: "Name of the schema that this table is in"
        - relname:
            usage: "LABEL"
            description: "Name of this table"
        - heap_blks_read:
            usage: "COUNTER"
            description: "Number of disk blocks read from this table"
        - heap_blks_hit:
            usage: "COUNTER"
            description: "Number of buffer hits in this table"
        - idx_blks_read:
            usage: "COUNTER"
            description: "Number of disk blocks read from all indexes on this table"
        - idx_blks_hit:
            usage: "COUNTER"
            description: "Number of buffer hits in all indexes on this table"
        - toast_blks_read:
            usage: "COUNTER"
            description: "Number of disk blocks read from this table's TOAST table (if any)"
        - toast_blks_hit:
            usage: "COUNTER"
            description: "Number of buffer hits in this table's TOAST table (if any)"
        - tidx_blks_read:
            usage: "COUNTER"
            description: "Number of disk blocks read from this table's TOAST table indexes (if any)"
        - tidx_blks_hit:
            usage: "COUNTER"
            description: "Number of buffer hits in this table's TOAST table indexes (if any)"
 
```

This doesn’t result in any error normally because the clusters we use to test this configuration with are plain clusters, with a primary server. In this case, even when this query is executed on replicas, pg_stat_replication will be empty and no error will be raised.

This isn’t true on replica clusters, where the primary server is a designated primary. In this case, the following will happen:

```
❯ k exec -ti cluster-replica-tls-1 -- psql
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
psql (13.7)
Type "help" for help.

postgres=# SELECT usename
postgres-#   , COALESCE(application_name, '') AS application_name
postgres-#   , COALESCE(client_addr::text, '') AS client_addr
postgres-#   , EXTRACT(EPOCH FROM backend_start) AS backend_start
postgres-#   , COALESCE(pg_catalog.age(backend_xmin), 0) AS backend_xmin_age
postgres-#   , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), sent_lsn) AS sent_diff_bytes
postgres-#   , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), write_lsn) AS write_diff_bytes
postgres-#   , pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), flush_lsn) AS flush_diff_bytes
postgres-#   , COALESCE(pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), replay_lsn),0) AS replay_diff_bytes
postgres-#   , COALESCE((EXTRACT(EPOCH FROM write_lag)),0)::float AS write_lag_seconds
postgres-#   , COALESCE((EXTRACT(EPOCH FROM flush_lag)),0)::float AS flush_lag_seconds
postgres-#   , COALESCE((EXTRACT(EPOCH FROM replay_lag)),0)::float AS replay_lag_seconds
postgres-# FROM pg_catalog.pg_stat_replication
postgres-# 
postgres-# ;
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
postgres=# select * from pg_stat_replication;
 pid | usesysid |      usename      |   application_name    | client_addr | client_hostname | client_port |         backend_start         | backend_xmin |   state   | sent_lsn  | write_lsn | flush_lsn | replay_lsn | write_l
ag | flush_lag | replay_lag | sync_priority | sync_state |          reply_time           
-----+----------+-------------------+-----------------------+-------------+-----------------+-------------+-------------------------------+--------------+-----------+-----------+-----------+-----------+------------+--------
---+-----------+------------+---------------+------------+-------------------------------
 191 |    16386 | streaming_replica | cluster-replica-tls-2 | 10.244.0.39 |                 |       33142 | 2022-06-07 09:00:53.63102+00  |              | streaming | 0/A000060 | 0/A000060 | 0/A000060 | 0/A000060  |        
   |           |            |             0 | async      | 2022-06-07 09:06:30.820141+00
 294 |    16386 | streaming_replica | cluster-replica-tls-3 | 10.244.0.42 |                 |       60586 | 2022-06-07 09:01:02.580052+00 |              | streaming | 0/A000060 | 0/A000060 | 0/A000060 | 0/A000060  |        
   |           |            |             0 | async      | 2022-06-07 09:06:30.821507+00
(2 rows)
 
```

This is issue isn’t causing any major problems beside cluttering the logs, and perhaps to solve it we could just add a primary: true in our example.

Acceptance Criteria

Logs on standby do not contain anything about monitoring at the INFO level during normal operation when metrics are scraped from Prometheus.

issue originally opened by @leonardoce
