### ISSUE TITLE
Use a map in the backup status of volume snapshots

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2963]
Currently, snapshots are defined as a list:

```
  snapshotBackupStatus:
    snapshots:
    - large-20231002092908
    - large-20231002092908-wal
```

However, when in the future we will be managing tablespaces, this might generate toil that could have been avoided if we had put some structure here, for example by identifying PGDATA and WAL volumes:

```
  snapshotBackupStatus:
    snapshots:
      storage: large-20231002092908
      walStorage: large-20231002092908-wal
      tablespaces:
        TBS_NAME: VOLUME_SNAPSHOT_NAME
```

**Comment by mnencia** [comment]
To avoid repeating the word `snapshot` too many times, I would prefer to use this structure:

```
  snapshotBackupStatus:
    components:
      data: large-20231002092908
      wal: large-20231002092908-wal
      tablespaces:
        TBS_NAME: VOLUME_SNAPSHOT_NAME
```

Also, the storage word is misleading here, so I removed it.

What do you think?

**Comment by gbartolini** [comment]
What about `parts` or `items`then?

**Comment by mnencia** [comment]
I like `parts`

```
  snapshotBackupStatus:
    parts:
      data: large-20231002092908
      wal: large-20231002092908-wal
      tablespaces:
        TBS_NAME: VOLUME_SNAPSHOT_NAME
```

Should I go ahead with this design?
