### ISSUE TITLE
Cannot connect to the DB cluster via any credentials

### ISSUE THREAD

**Issue by kasvith** [cloudnative-pg/cloudnative-pg#3023]
Hi,

Im trying to create a HA cluster with following config with `pg_bouncer`
It appears that i cant access the db via either `pg_bouncer` or `direct` connection to any instance

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
  namespace: prod
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXMK # postgres
  password: cG9zdGdyZXMK # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-secret
  namespace: prod
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: ZGItdXNlcgo= # db-user
  password: NWVVKjBBe1VUM2M2Cg== # 5eU*0A{UT3c6
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-runner-db
  namespace: prod
spec:
  description: "PG Runner DB for Prod"
  # Choose your PostGres Database Version
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  # Number of Replicas
  instances: 3
  startDelay: 300
  stopDelay: 300
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 300
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: "10s"
    pg_hba:
      # - hostssl app all all cert
      - host app app all password
  logLevel: debug
  storage:
    storageClass: ebs-sc
    size: 5Gi
  walStorage:
    storageClass: ebs-sc
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb: # Deploying a new cluster
      database: data
      owner: db-user
      secret:
        name: db-user-secret

  managed:
    roles:
      - name: db-user
        ensure: present
        superuser: true
        createdb: true
        login: true
        passwordSecret:
          name: db-user-secret

  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: prod-pg-runner-pooler-rw
  namespace: prod
spec:
  cluster:
    name: pg-runner-db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "15"
```

The error im getting
```bash
root@psql-client:/# psql -h pg-runner-db-rw -U postgres -d data
Password for user postgres:
psql: error: connection to server at "pg-runner-db-rw" (10.100.164.44), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "pg-runner-db-rw" (10.100.164.44), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```

Related discussion:
https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1696750251890289

**Comment by litaocdl** [comment]
if we did not specific the enableSuperuserAccess in cluster yaml file, it will generated as false

```
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
````
