### ISSUE TITLE
`cannot reconcile database configurations: ... ERROR: cannot drop extension pg_stat_statements` after microservice import

### ISSUE THREAD

**Issue by NiklasRosenstein** [cloudnative-pg/cloudnative-pg#3033]
I'm initializing a `Cluster` from another live Postgres database using the `microservice` import type. The database uses the `pg_stat_statement` extension.

```
original=# \dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+------------------------------------------------------------------------
 pg_stat_statements | 1.10    | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
(3 rows)
```

After import, the new cluster has the same extensions enabled (as expected):

```
app=# \dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+------------------------------------------------------------------------
 pg_stat_statements | 1.10    | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
```

But I get the below error log line in the cluster Pod and don't understand why CloudNative PG even wants to drop the extension in the first place.

```json
{
    "level": "error",
    "ts": "2023-10-09T20:55:20Z",
    "msg": "Reconciler error",
    "controller": "cluster",
    "controllerGroup": "postgresql.cnpg.io",
    "controllerKind": "Cluster",
    "Cluster": {
        "name": "newcluster",
        "namespace": "default"
    },
    "namespace": "default",
    "name": "newcluster",
    "reconcileID": "541d846a-c742-4edc-b7bb-30a51a240f70",
    "error": "cannot reconcile database configurations: got errors while reconciling databases: [could not reconcile extensions for database app: ERROR: cannot drop extension pg_stat_statements because other objects depend on it (SQLSTATE 2BP01)]",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
}
```

<details><summary>Cluster manifest</summary>

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    meta.helm.sh/release-name: newcluster
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-10-09T20:46:52Z"
  generation: 1
  labels:
    app: raw
    app.kubernetes.io/managed-by: Helm
    chart: raw-v0.2.5
    heritage: Helm
    release: newcluster
  name: newcluster
  namespace: default
spec:
  affinity:
    podAntiAffinityType: preferred
    topologyKey: ""
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups
      endpointURL: https://ams1.vultrobjects.com
      s3Credentials:
        accessKeyId:
          key: AWS_ACCESS_KEY_ID
          name: newcluster-backup-s3-credentials
        inheritFromIAMRole: false
        secretAccessKey:
          key: AWS_SECRET_ACCESS_KEY
          name: newcluster-backup-s3-credentials
      serverName: newcluster
      wal:
        compression: gzip
    target: prefer-standby
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      import:
        databases:
        - original
        schemaOnly: false
        source:
          externalCluster: live
        type: microservice
      localeCType: C
      localeCollate: C
      owner: app
  enableSuperuserAccess: true
  externalClusters:
  - connectionParameters:
      dbname: original
      host: postgres.postgres.svc.cluster.local
      port: "5432"
      user: main
    name: live
    password:
      key: password
      name: newcluster-import-db-password
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  instances: 1
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_buffers: 128MB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    size: 8Gi
  switchoverDelay: 40000000
```

</details>
