### ISSUE TITLE
support AffinityConfiguration for each instance

### ISSUE THREAD

**Issue by Anhui-tqhuang** [cloudnative-pg/cloudnative-pg#309]
i think it might be better to define `AffinityConfiguration` for each instance of one cnpg cluster, instead of using the same one, it would provide more flexibility to manage the distribution of cnpg cluster. 

```yaml
instances:
- instance: 1
  affinityConfiguration: {}
- instance: 2
  affinityConfiguration: {}
- ...
```
