### ISSUE TITLE
Error creating cluster

### ISSUE THREAD

**Issue by sergioenterprisedb** [cloudnative-pg/cloudnative-pg#3104]
Error in field 'Primary start time' during the creation of a new cluster with 1.21.0 operator. This error appears in red the first seconds of the creation of the cluster. This error is not locking the creation of the cluster:
```
Cluster Summary
Primary server is initializing
Name:                cluster-example
Namespace:           default
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:14.2
Primary instance:     (switching to cluster-example-1)
Primary start time:  error: parsing time "" as "2006-01-02T15:04:05.000000Z07:00": cannot parse "" as "2006"
Status:              Setting up primary Creating primary instance cluster-example-1
Instances:           3
Ready instances:     0

Certificates Status
Certificate Name             Expiration Date                Days Left Until Expiration
----------------             ---------------                --------------------------
cluster-example-ca           2024-01-11 16:56:16 +0000 UTC  90.00
cluster-example-replication  2024-01-11 16:56:16 +0000 UTC  90.00
cluster-example-server       2024-01-11 16:56:16 +0000 UTC  90.00

Continuous Backup status
Not configured

Streaming Replication status
Primary instance not found

Unmanaged Replication Slot Status
No unmanaged replication slots found

Instances status
Name  Database Size  Current LSN  Replication role  Status  QoS  Manager Version  Node
----  -------------  -----------  ----------------  ------  ---  ---------------  ----
```
This is my yaml:
```
apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-example-superuser
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.2
  #imagePullPolicy: Never

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true
    #updateInterval: 300

  minSyncReplicas: 1
  maxSyncReplicas: 1

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
```
