### ISSUE TITLE
[Feature]: Allow exposing a pooler resource externally using a loadbalancer

### ISSUE THREAD

**Issue by achanda** [cloudnative-pg/cloudnative-pg#3141]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

In our use-case, CNPG runs in a specific K8S cluster while apps might be on a different K8S cluster. Hence, it is necessary to expose the pooler service externally using a service type `LoadBalancer`. Other people might have a similar use-case and will benefit from having this built into CNPG.

### Describe the solution you'd like

I am proposing that the `Pooler` resource be modified to specify a flag that denotes if the pooler should be exposed. Also, add a new field `loadBalancerSourceRanges` that is then used to create the pooler service.

```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-example-rw
spec:
  cluster:
    name: cluster-example
  instances: 1
  type: rw
  external: true
  loadBalancerSourceRanges:
  - 192.168.122.0/24
  - 0.0.0.0/32
  pgbouncer:
    poolMode: transaction
```

### Describe alternatives you've considered

So far we created a new service of type loadbalancer to expose the pooler externally. While this works fine, this introduces complexity in managing the deployment with two services, one managed by CNPG and one not managed by CNPG. It will be nice to have everything in the same umbrella.

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
