### ISSUE TITLE
[Bug]: cnpg gets upset if a mutating admission controller changes the image to a pull-through proxy

### ISSUE THREAD

**Issue by danielluke** [cloudnative-pg/cloudnative-pg#3231]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

dluke@geeklair.net

### Version

1.21.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

I recently installed habor + imageswap-webhook to use a pull-through caching proxy for images from ghcr.io wherever applicable.

This works just fine for my configured pooler (it runs a pgbouncer image pulled from my local cache). My cnpg 2-node Cluster kept trying to recover one of the nodes because it didn't think the version of the image was correct.

I was able to work around it by specifying an imageName that references my local proxy in my Cluster definition.  This works, but means I have to remember to modify the cluster definition if I ever turn this all off (instead of just removing the mutating webhook or disabling it from the namespace my cluster is running in).

I haven't looked through the code yet, but I suspect something is parsing the image name, which ideally wouldn't.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: foodb
  namespace: foo
spec:
  imageName: harbor.k8s.geeklair.net/ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      wal:
        compression: bzip2
      data:
        compression: bzip2
      endpointCA:
        name:
        key: 
      destinationPath: "s3://cnpgbackups"
      endpointURL: "http://minio.lintilla-minio"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
```

### Relevant log output

```shell
sorry, I didn't save this, I can recreate it pretty easily if that would be desirable, though.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nepoxx** [comment]
There's very little information here, what was happening, what does
 > cnpg gets upset
 
 or
 
 > My cnpg 2-node Cluster kept trying to recover one of the nodes because it didn't think the version of the image was correct.
 
 mean concretely? 
 
 I'm also using a mutating webhook to use harbor as a pull-through cache, so I'm interested in this.

**Comment by danielluke** [comment]
Did you try it? cnpg thinks the version of the image pulled through harbor is not correct and terminates the pod (which then happens over and over).

**Comment by Nepoxx** [comment]
This information is important to provide:
```
  phase: Primary instance is being restarted without a switchover
  phaseReason: 'the instance is using an old image: harbor.mydomain/ghcr/cloudnative-pg/postgresql:16.0
    -> ghcr.io/cloudnative-pg/postgresql:16.0'
```

**Comment by danielluke** [comment]
How about better - the problem is here: https://github.com/cloudnative-pg/cloudnative-pg/blob/faec6d7097b72900e12d88c1e30982e4e11b3c54/controllers/cluster_upgrade.go#L419 cnpg expects pgCurrentImageName == targetImageName (which means you can't use a mutating webhook to change the image name)

**Comment by darkweaver87** [comment]
:+1: on this issue. I'm currently using [k8s-image-swapper](https://github.com/estahn/k8s-image-swapper) and I(m facing the same problem.
It's a good production practice to have container images cached locally.
What do you think about checking the sha256 of the image instead ? Actually the name doesn't mean the image is the same :-)

**Comment by paulfantom** [comment]
FWIW I can also confirm the same is happening when using cloudnative-pg along with [kuik](https://github.com/enix/kube-image-keeper)

**Comment by zifeo** [comment]
Kuik users (likely same applies to similar systems) can bypass that by prefixing their manifest with localhost:7439 both on the operator (required by the init-container) and the clusters. However I would be curious to hear what is the recommended way to deal with that from the maintainers.

**Comment by DreamingRaven** [comment]
I am facing this same issue, is there not a way to get CNPG to either accept a proxy, or ignore the image name, and stick only to the image tag for any such validation?

```json
{
    "level": "info",
    "ts": "2025-07-27T19:49:30.906900316Z",
    "msg": "Pod rollout required",
    "controller": "cluster",
    "controllerGroup": "postgresql.cnpg.io",
    "controllerKind": "Cluster",
    "Cluster": {
        "name": "psql",
        "namespace": "keycloak"
    },
    "namespace": "keycloak",
    "name": "psql",
    "reconcileID": "2de2a316-56e1-45b4-a69f-1cd8cc7e9c74",
    "podName": "psql-1",
    "reason": "the instance is using a different image: harbor.org.example/ghcr.io/cloudnative-pg/postgresql:17.5 -> ghcr.io/cloudnative-pg/postgresql:17.5"
}
```

I guess the easiest way to work around this is to set the image name to the cache out the gate.

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql
spec:
  imageName: harbor.dorg.example/ghcr.io/cloudnative-pg/postgresql:17.5 # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imagePullSecrets:
  - name: image-pull-secret
```

EDIT: 

As I have no found out, you cant even do that as the bootstrap image is also checked:
```yaml
{
    "level": "info",
    "ts": "2025-07-27T20:02:47.053809419Z",
    "msg": "Pod rollout required",
    "controller": "cluster",
    "controllerGroup": "postgresql.cnpg.io",
    "controllerKind": "Cluster",
    "Cluster": {
        "name": "psql",
        "namespace": "keycloak"
    },
    "namespace": "keycloak",
    "name": "psql",
    "reconcileID": "e6b2c7fa-2d94-4090-9e11-e30b01a38cc2",
    "podName": "psql-1",
    "reason": "the instance is using an old bootstrap container image: harbor.org.example/ghcr.io/cloudnative-pg/cloudnative-pg:1.26.1 -> ghcr.io/cloudnative-pg/cloudnative-pg:1.26.1"
}
```
