### ISSUE TITLE
[Feature]: Cluster without default user

### ISSUE THREAD

**Issue by baurmatt** [cloudnative-pg/cloudnative-pg#3242]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We use the new declarative role management to create an admin user:

```
...
  managed:
    roles:
    - connectionLimit: -1
      createdb: true
      createrole: true
      ensure: present
      inherit: true
      login: true
      name: admin
      passwordSecret:
        name: cnpg-admin-secret
```

The user of the DB is supposed to handle user/db creation them self hence the default app user/db created by bootstrap.initdb isn't needed.

### Describe the solution you'd like

We like to see an option where none of the bootstrap options (initdb/pg_basebackup/recovery) is used e.g. by configuring `bootstrap: false`.

### Describe alternatives you've considered

I've checked, but couldn't find any option to disable the `app` db/user creation.

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
