### ISSUE TITLE
[Bug]: Clients cannot authenticate to cluster using Operator Managed or Certmanager based TLS certificates after following examples in the documentation

### ISSUE THREAD

**Issue by cloudymax** [cloudnative-pg/cloudnative-pg#3301]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

emax@cloudydev.net

### Version

1.21.0

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm:
- 0.19.1
- 0.19.0
- 0.18.2

### What happened?

# Issue overview

Hey Team, We're in the process of setting up a proof-of-concept deployment of CNPG Operator to replace our current Bitanmi postgres deployments.
The two key features we need for this to be a success are TLS certificate authentication and the ability to deploy via a declarative workflow using ArgoCD.

When using the built-in TLS certificates via the `kubectl cnpg` command TLS authentication does not succeed and failsover to password auth.

Since CNPG Operator supports CertManager though, this shouldn't be the end of the road as we already deploy Certmanager to handle our Ingress TLS.

Using the examples:
- https://cloudnative-pg.io/documentation/1.21/ssl_connections/
- https://cloudnative-pg.io/documentation/1.21/samples/cluster-example-cert-manager.yaml

We are able to create a test cluster and certificates using CertManager, however we are unable to successfully authenticate a client to the database using any combination of the generated secrets/certificates. Certificate auth always fails when enforced, or falls back to password if allowed.

## Reproduction

- Install helm

  ```bash
  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  chmod 700 get_helm.sh
  ./get_helm.sh
  ```

- Download the k3s installer

  ```bash
  curl -sfL https://get.k3s.io > k3s-install.sh
  ```

- install k3s

  ```bash
  bash k3s-install.sh --disable=traefik
  ```

- Wait for node to be ready

  ```bash
  sudo k3s kubectl get node
  NAME   STATUS   ROLES                  AGE   VERSION
  vm0    Ready    control-plane,master   1m   v1.27.4+k3s1
  ```

- Make an accessible version of the kubeconfig

  ```bash
  mkdir -p ~/.config/kube

  sudo cp /etc/rancher/k3s/k3s.yaml ~/.config/kube/config

  sudo chown $USER:$USER ~/.config/kube/config

  export KUBECONFIG=~/.config/kube/config

  ```

- Install CNPG Operator

  ```bash
  helm repo add cnpg https://cloudnative-pg.github.io/charts
  helm upgrade --install cnpg \
    --namespace cnpg-system \
    --create-namespace \
    cnpg/cloudnative-pg \
    --version 0.19.0
  ```

### Operator Managed

- Create test cluster

```yaml
kubectl apply -f - <<EOF
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  storage:
    size: 1Gi
EOF
```

- Create a client certificate

```bash
kubectl cnpg certificate cluster-app \
  --cnpg-cluster cluster-example \
  --cnpg-user app
```

- deploy the test app

```yaml
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
        - image: ghcr.io/cloudnative-pg/webtest:1.6.0
          name: cert-test
          volumeMounts:
            - name: secret-volume-root-ca
              mountPath: /etc/secrets/ca
            - name: secret-volume-app
              mountPath: /etc/secrets/app
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: >
                sslkey=/etc/secrets/app/tls.key
                sslcert=/etc/secrets/app/tls.crt
                sslrootcert=/etc/secrets/ca/ca.crt
                host=cluster-example-rw.default.svc
                dbname=app
                user=app
                sslmode=verify-full
            - name: SQL_QUERY
              value: SELECT 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /tx
      volumes:
        - name: secret-volume-root-ca
          secret:
            secretName: cluster-example-ca
            defaultMode: 0600
        - name: secret-volume-app
          secret:
            secretName: cluster-app
            defaultMode: 0600
EOF
```

- Check pod logs

```bash
│ SQL query: "SELECT 1"                                                                        │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:08:48.603 10.42.0.1 /tx - 500 - 18ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:08:49.603 10.42.0.1 /tx - 500 - 16ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:08:58.008 10.42.0.1 /tx - 500 - 16ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:09:08.009 10.42.0.1 /tx - 500 - 16ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:09:18.008 10.42.0.1 /tx - 500 - 16ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:09:28.008 10.42.0.1 /tx - 500 - 16ms                                      │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:09:38.008 10.42.0.1 /tx - 500 - 16ms
```

### Client Managed

- install CertManager

  ```bash
  helm repo add jetstack https://charts.jetstack.io
  helm repo update

  kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.crds.yaml

  helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.13.2
  ```

- Create Example Cluster

  ```yaml
  kubectl apply -f https://cloudnative-pg.io/documentation/1.21/samples/cluster-example-cert-manager.yaml
  ```

- List Secrets

  ```bash
  NAME                      TYPE                       DATA   AGE
  server-ca-key-pair        kubernetes.io/tls          3      5m19s
  client-ca-key-pair        kubernetes.io/tls          3      5m19s
  my-postgres-server-cert   Opaque                     3      5m20s
  my-postgres-client-cert   Opaque                     3      5m20s
  cluster-example-app       kubernetes.io/basic-auth   9      5m15s
  ```

- Validate certificates

  ```bash
  kubectl get secret my-postgres-client-cert\
    -o jsonpath="{.data['tls\.crt']}" \
    | base64 -d | openssl x509 -text -noout \
    | head -n 11

  Certificate:
      Data:
          Version: 3 (0x2)
          Serial Number:
              18:44:01:16:97:03:8e:cf:d1:df:37:d5:95:6c:1a:d8
          Signature Algorithm: ecdsa-with-SHA256
          Issuer: CN = my-selfsigned-client-ca
          Validity
              Not Before: Nov  5 06:50:37 2023 GMT
              Not After : Feb  3 06:50:37 2024 GMT
          Subject: CN = streaming_replica
  ```

  ```bash
  kubectl get secret client-ca-key-pair\
    -o jsonpath="{.data['tls\.crt']}" \
    | base64 -d | openssl x509 -text -noout \
    | head -n 11

  Certificate:
      Data:
          Version: 3 (0x2)
          Serial Number:
              2c:e0:df:13:a3:f2:86:cc:4c:cc:73:75:14:10:fa:c3
          Signature Algorithm: ecdsa-with-SHA256
          Issuer: CN = my-selfsigned-client-ca
          Validity
              Not Before: Nov  5 06:50:32 2023 GMT
              Not After : Feb  3 06:50:32 2024 GMT
          Subject: CN = my-selfsigned-client-ca
  ```

- Create example app using the `client-ca-key-pair` and `my-postgres-client-cert`

  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webtest
    template:
      metadata:
        labels:
          app: webtest
      spec:
        containers:
          - image: ghcr.io/cloudnative-pg/webtest:1.6.0
            name: cert-test
            volumeMounts:
              - name: secret-volume-root-ca
                mountPath: /etc/secrets/ca
              - name: secret-volume-app
                mountPath: /etc/secrets/app
            ports:
              - containerPort: 8080
            env:
              - name: DATABASE_URL
                value: >
                  sslkey=/etc/secrets/app/tls.key
                  sslcert=/etc/secrets/app/tls.crt
                  sslrootcert=/etc/secrets/ca/ca.crt
                  host=cluster-example-rw.default.svc
                  dbname=app
                  user=app
                  sslmode=verify-full
              - name: SQL_QUERY
                value: SELECT 1
            readinessProbe:
              httpGet:
                port: 8080
                path: /tx
        volumes:
          - name: secret-volume-root-ca
            secret:
              secretName: client-ca-key-pair
              defaultMode: 0600
          - name: secret-volume-app
            secret:
              secretName: my-postgres-client-cert
              defaultMode: 0600
  ```

- Attach to pod and see that SSL verification has failed:

  ```bash
  Database URL: "sslkey=/etc/secrets/app/tls.key sslcert=/etc/secrets/app/tls.crt sslrootcert=
  "
  SQL query: "SELECT 1"
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:01:05.158 10.42.0.1 /tx - 500 - 4ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:01:06.172 10.42.0.1 /tx - 500 - 14ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:01:09.765 10.42.0.1 /tx - 500 - 14ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:01:19.766 10.42.0.1 /tx - 500 - 14ms
  ```

- try again using only the `my-postgres-client-cert`

  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webtest
    template:
      metadata:
        labels:
          app: webtest
      spec:
        containers:
          - image: ghcr.io/cloudnative-pg/webtest:1.6.0
            name: cert-test
            volumeMounts:
              - name: secret-volume-app
                mountPath: /etc/secrets/app
            ports:
              - containerPort: 8080
            env:
              - name: DATABASE_URL
                value: >
                  sslkey=/etc/secrets/app/tls.key
                  sslcert=/etc/secrets/app/tls.crt
                  sslrootcert=/etc/secrets/app/ca.crt
                  host=cluster-example-rw.default.svc
                  dbname=app
                  user=app
                  sslmode=verify-full
              - name: SQL_QUERY
                value: SELECT 1
            readinessProbe:
              httpGet:
                port: 8080
                path: /tx
        volumes:
          - name: secret-volume-app
            secret:
              secretName: my-postgres-client-cert
              defaultMode: 0600
  ```

- Attach to pod, see that verification has failed

  ```bash
  Database URL: "sslkey=/etc/secrets/app/tls.key sslcert=/etc/secrets/app/tls.crt sslrootcert=
  "
  SQL query: "SELECT 1"
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:04:37.867 10.42.0.1 /tx - 500 - 19ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:04:38.863 10.42.0.1 /tx - 500 - 14ms
  ```

- Try again, using the `client-ca-key-pair`

  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webtest
    template:
      metadata:
        labels:
          app: webtest
      spec:
        containers:
          - image: ghcr.io/cloudnative-pg/webtest:1.6.0
            name: cert-test
            volumeMounts:
              - name: secret-volume-app
                mountPath: /etc/secrets/app
            ports:
              - containerPort: 8080
            env:
              - name: DATABASE_URL
                value: >
                  sslkey=/etc/secrets/app/tls.key
                  sslcert=/etc/secrets/app/tls.crt
                  sslrootcert=/etc/secrets/app/ca.crt
                  host=cluster-example-rw.default.svc
                  dbname=app
                  user=app
                  sslmode=verify-full
              - name: SQL_QUERY
                value: SELECT 1
            readinessProbe:
              httpGet:
                port: 8080
                path: /tx
        volumes:
          - name: secret-volume-app
            secret:
              secretName: client-ca-key-pair
              defaultMode: 0600
  ```

- attach to pod, see verification has failed

  ```bash
  SQL query: "SELECT 1"
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:06:19.180 10.42.0.1 /tx - 500 - 15ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:06:20.181 10.42.0.1 /tx - 500 - 15ms
  SSL error: certificate verify failed

  Sun Nov 05 2023 07:06:28.231 10.42.0.1 /tx - 500 - 14ms
  ```

### Cluster resource

```shell
Name:         cluster-example
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-11-05T06:50:32Z
  Generation:          1
  Resource Version:    53632
  UID:                 1ae0e8ac-00c4-46fb-be71-38b8a3958a71
Spec:
  Affinity:
    Pod Anti Affinity Type:  preferred
  Bootstrap:
    Initdb:
      Database:        app
      Encoding:        UTF8
      Locale C Type:   C
      Locale Collate:  C
      Owner:           app
  Certificates:
    Client CA Secret:        my-postgres-client-cert
    Replication TLS Secret:  my-postgres-client-cert
    Server CA Secret:        my-postgres-server-cert
    Server TLS Secret:       my-postgres-server-cert
  Enable Superuser Access:   false
  Failover Delay:            0
  Image Name:                ghcr.io/cloudnative-pg/postgresql:16.0
  Instances:                 3
  Log Level:                 info
  Max Sync Replicas:         0
  Min Sync Replicas:         0
  Monitoring:
    Custom Queries Config Map:
      Key:                    queries
      Name:                   cnpg-default-monitoring
    Disable Default Queries:  false
    Enable Pod Monitor:       false
  Postgres GID:               26
  Postgres UID:               26
  Postgresql:
    Parameters:
      archive_mode:                on
      archive_timeout:             5min
      dynamic_shared_memory_type:  posix
      log_destination:             csvlog
      log_directory:               /controller/log
      log_filename:                postgres
      log_rotation_age:            0
      log_rotation_size:           0
      log_truncate_on_rotation:    false
      logging_collector:           on
      max_parallel_workers:        32
      max_replication_slots:       32
      max_worker_processes:        32
      shared_memory_type:          mmap
      shared_preload_libraries:
      wal_keep_size:               512MB
      wal_receiver_timeout:        5s
      wal_sender_timeout:          5s
    Sync Replica Election Constraint:
      Enabled:              false
  Primary Update Method:    restart
  Primary Update Strategy:  unsupervised
  Replication Slots:
    High Availability:
      Enabled:        true
      Slot Prefix:    _cnpg_
    Update Interval:  30
  Resources:
  Smart Shutdown Timeout:  180
  Start Delay:             3600
  Stop Delay:              1800
  Storage:
    Resize In Use Volumes:  true
    Size:                   1Gi
  Switchover Delay:         3600
Status:
  Certificates:
    Client CA Secret:  my-postgres-client-cert
    Expirations:
      My - Postgres - Client - Cert:  2024-02-03 06:50:37 +0000 UTC
      My - Postgres - Server - Cert:  2024-02-03 06:50:37 +0000 UTC
    Replication TLS Secret:           my-postgres-client-cert
    Server Alt DNS Names:
      cluster-example-rw
      cluster-example-rw.default
      cluster-example-rw.default.svc
      cluster-example-r
      cluster-example-r.default
      cluster-example-r.default.svc
      cluster-example-ro
      cluster-example-ro.default
      cluster-example-ro.default.svc
    Server CA Secret:             my-postgres-server-cert
    Server TLS Secret:            my-postgres-server-cert
  Cloud Native PG Commit Hash:    27f62cac
  Cloud Native PG Operator Hash:  4912e5eb808aca3bf134923625f2346d404a3c860cf24aca4266493846f8fc3b
  Conditions:
    Last Transition Time:  2023-11-05T06:51:49Z
    Message:               Cluster is Ready
    Reason:                ClusterIsReady
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-11-05T06:51:00Z
    Message:               Continuous archiving is working
    Reason:                ContinuousArchivingSuccess
    Status:                True
    Type:                  ContinuousArchiving
  Config Map Resource Version:
    Metrics:
      Cnpg - Default - Monitoring:  53286
  Current Primary:                  cluster-example-1
  Current Primary Timestamp:        2023-11-05T06:51:00.543488Z
  Healthy PVC:
    cluster-example-1
    cluster-example-2
    cluster-example-3
  Instance Names:
    cluster-example-1
    cluster-example-2
    cluster-example-3
  Instances:  3
  Instances Reported State:
    cluster-example-1:
      Is Primary:    true
      Time Line ID:  1
    cluster-example-2:
      Is Primary:    false
      Time Line ID:  1
    cluster-example-3:
      Is Primary:    false
      Time Line ID:  1
  Instances Status:
    Healthy:
      cluster-example-1
      cluster-example-2
      cluster-example-3
  Latest Generated Node:  3
  Managed Roles Status:
  Phase:  Cluster in healthy state
  Pooler Integrations:
    Pg Bouncer Integration:
  Pvc Count:        3
  Read Service:     cluster-example-r
  Ready Instances:  3
  Secrets Resource Version:
    Application Secret Version:  53257
    Client Ca Secret Version:    53254
    Replication Secret Version:  53254
    Server Ca Secret Version:    53247
    Server Secret Version:       53247
  Target Primary:                cluster-example-1
  Target Primary Timestamp:      2023-11-05T06:50:37.523387Z
  Timeline ID:                   1
  Topology:
    Instances:
      cluster-example-1:
      cluster-example-2:
      cluster-example-3:
    Nodes Used:              1
    Successfully Extracted:  true
  Write Service:             cluster-example-rw
Events:
  Type    Reason                       Age   From            Message
  ----    ------                       ----  ----            -------
  Normal  CreatingPodDisruptionBudget  38m   cloudnative-pg  Creating PodDisruptionBudget cluster-example-primary
  Normal  CreatingPodDisruptionBudget  38m   cloudnative-pg  Creating PodDisruptionBudget cluster-example
  Normal  CreatingServiceAccount       38m   cloudnative-pg  Creating ServiceAccount
  Normal  CreatingRole                 38m   cloudnative-pg  Creating Cluster Role
  Normal  CreatingInstance             38m   cloudnative-pg  Primary instance (initdb)
  Normal  CreatingInstance             38m   cloudnative-pg  Creating instance cluster-example-2
  Normal  CreatingInstance             37m   cloudnative-pg  Creating instance cluster-example-3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cloudymax** [comment]
Looks like the issue is with my own reading comprehension rather than CNPG 😅 

When reading about the `Operator Managed` certificates the docs tell us:

> Operator-managed mode
> By default, the operator generates a single CA and uses it for both client and server certificates, which are then managed and renewed automatically.

I failed to account for the fact then when using the Certmanager based workflow that 2 unique CA's are created instead of just 1.

When accounting for the above, the following configuration allows us to log in:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
        - image: ghcr.io/cloudnative-pg/webtest:1.6.0
          name: cert-test
          volumeMounts:
            - name: secret-volume-app
              mountPath: /etc/secrets/appcrt
            - name: secret-volume-root-ca
              mountPath: /etc/secrets/ca
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: >
                sslkey=/etc/secrets/app/tls.key
                sslcert=/etc/secrets/app/tls.crt
                sslrootcert=/etc/secrets/ca/ca.crt
                host=cluster-example-rw.default.svc
                dbname=app
                user=app
                sslmode=verify-full
            - name: SQL_QUERY
              value: SELECT 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /tx
      volumes:
        - name: secret-volume-app
          secret:
            secretName: my-postgres-client-cert
            defaultMode: 0600
        - name: secret-volume-root-ca
          secret:
            secretName: my-postgres-server-cert
            defaultMode: 0600
```

**Comment by cloudymax** [comment]
Tried again, but this time on Kind:

Create the cluster:

```bash
kind create cluster --name pg
Creating cluster "pg" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-pg"
You can now use your cluster with:

kubectl cluster-info --context kind-pg
```

Install the operator:

```bash
helm upgrade --install cnpg \
    --namespace cnpg-system \
    --create-namespace \
    cnpg/cloudnative-pg \
    --version 0.19.0
```

Create the postgres cluster:

```bash
kubectl apply -f - <<EOF
     apiVersion: postgresql.cnpg.io/v1
     kind: Cluster
     metadata:
       name: cluster-example
     spec:
       instances: 3
       storage:
         size: 1Gi
     EOF
```

Create the client cert:

```bash
kubectl cnpg certificate cluster-app \
      --cnpg-cluster cluster-example \
      --cnpg-user app
```

Create the test app:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
        - image: ghcr.io/cloudnative-pg/webtest:1.6.0
          name: cert-test
          volumeMounts:
            - name: secret-volume-root-ca
              mountPath: /etc/secrets/ca
            - name: secret-volume-app
              mountPath: /etc/secrets/app
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: >
                sslkey=/etc/secrets/app/tls.key
                sslcert=/etc/secrets/app/tls.crt
                sslrootcert=/etc/secrets/ca/ca.crt
                host=cluster-example-rw.default.svc
                dbname=app
                user=app
                sslmode=verify-full
            - name: SQL_QUERY
              value: SELECT 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /tx
      volumes:
        - name: secret-volume-root-ca
          secret:
            secretName: cluster-example-ca
            defaultMode: 0600
        - name: secret-volume-app
          secret:
            secretName: cluster-app
            defaultMode: 0600
```


- Check pod logs

```bash
﻿│ "                                                                                            │
│ SQL query: "SELECT 1"                                                                        │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:51:01.560 10.244.0.1 /tx - 500 - 16ms                                     │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:51:02.562 10.244.0.1 /tx - 500 - 17ms                                     │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:51:07.562 10.244.0.1 /tx - 500 - 17ms                                     │
│ fe_sendauth: no password supplied                                                            │
│                                                                                              │
│ Sun Nov 05 2023 10:51:17.561 10.244.0.1 /tx - 500 - 16ms
```

**Comment by phisco** [comment]
@cloudymax looks like you are missing the pg_hba configuration change in your last attempt though, no?

**Comment by cloudymax** [comment]
> @cloudymax looks like you are missing the pg_hba configuration change in your last attempt though, no?

Correct, I omitted the pg_hba conf file from the second test because I wanted to remove all customization in the hopes I could achieve the same results as described by the docs:

https://cloudnative-pg.io/documentation/current/ssl_connections/
<img width="486" alt="Screenshot 2023-11-05 at 12 10 57" src="https://github.com/cloudnative-pg/cloudnative-pg/assets/84841307/e1d67d88-4a57-45bd-85a2-67a88952798c">

According to the docs, the test app should be able to connect without the use of a password. In my tests the app will fail its readiness probe forever due to the missing password - is that no longer the case?

**Comment by phisco** [comment]
Yeah, I think the docs are wrong, we do configure it in our e2es: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/tests/e2e/fixtures/certificates/cluster-ssl-enabled.yaml.template

**Comment by cloudymax** [comment]
> Yeah, I think the docs are wrong, we do configure it in our e2es: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/tests/e2e/fixtures/certificates/cluster-ssl-enabled.yaml.template

Thanks for the link, I can confirm that when adding the line:

```yaml
    pg_hba:
      - hostssl all all all cert
```

To the cluster config will allow the `Operator Managed ` examples to complete as described int the docs.

However, the [Certmanager manifest](https://cloudnative-pg.io/documentation/current/samples/cluster-example-cert-manager.yaml) linked in the documents on [this page](https://cloudnative-pg.io/documentation/current/certificates/) still fails to authenticate the client.

```bash
│ SQL query: "SELECT 1"                                                                        │
│ FATAL:  certificate authentication failed for user "app"                                     │
│                                                                                              │
│ Sun Nov 05 2023 12:30:01.773 10.42.0.1 /tx - 500 - 23ms                                      │
│ FATAL:  certificate authentication failed for user "app"                                     │
│                                                                                              │
│ Sun Nov 05 2023 12:30:02.770 10.42.0.1 /tx - 500 - 19ms                                      │
│ FATAL:  certificate authentication failed for user "app"                                     │
│                                                                                              │
│ Sun Nov 05 2023 12:30:11.294 10.42.0.1 /tx - 500 - 15ms                                      │
│ FATAL:  certificate authentication failed for user "app"
```

The secrets created by the manifest are:

```console
server-ca-key-pair        kubernetes.io/tls          3      95s
client-ca-key-pair        kubernetes.io/tls          3      94s
my-postgres-server-cert   Opaque                     3      95s
my-postgres-client-cert   Opaque                     3      95s
cluster-example-app       kubernetes.io/basic-auth   9      85s
```

`server-ca-key-pair `, `client-ca-key-pair `,  `my-postgres-server-cert `, and `my-postgres-client-cert ` all contain a `tls.key`, `tls.cert` and `ca.crt`. So it is confusing as to which are required to authenticate.

- using the `tls.key` and `tls.crt` values of `my-postgres-server-cert `, and the `ca.crt` value of `my-postgres-client-cert ` with the test app results in  the error: 

    > certificate authentication failed for user "app"

- using the `tls.key` and `tls.crt` values of `client-ca-key-pair`, and the `ca.crt` value of `server-ca-key-pair` with the test app results in  the error: 

    > certificate authentication failed for user "app"

- using the `tls.key` and `tls.crt` and `ca.crt` of `my-postgres-client-cert ` results in the error: 

    > error: certificate verify failed

- using the `tls.key` and `tls.crt` and `ca.crt` of `client-ca-key-pair` results in the error: 

    > error: certificate verify failed


Is the certmanager manifest testing anywhere in your e2e's that I could take a peak at? In leiu, is there a way to declaratively create the client-certs from a a yaml manifest for the Operator Managed workflow?

**Comment by phisco** [comment]
You need to use `cluster-example-app` or ask certmanager for another client certificate for your specific client, `my-postgres-client-cert` is a client certificate used by instances for replication.

**Comment by jessebot** [comment]
Is there any declarative way, through your operator framework, to generate a TLS cert for an external user, say nextcloud, to use connect to the cluster securely? If not, would you be willing to take that as feature request?

Our infra is entirely managed by Argo CD, and stopping in the middle of a deployment to use the a krew plugin isn't something we can easily do.

**Comment by cloudymax** [comment]
> You need to use `cluster-example-app` or ask certmanager for another client certificate for your specific client, `my-postgres-client-cert` is a client certificate used by instances for replication.

Thanks for the clarification, I had made an incorrect assumption about the nature of the "client" cert.

The fix was to to as you suggested, create a "user" cert signed by the client CA:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-nextcloud-cert
  labels:
    cnpg.io/reload: ""
 ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-user-cert
spec:
  secretName: my-user-cert
  usages:
    - client auth
  commonName: myuser
  issuerRef:
    name: client-ca-issuer
    kind: Issuer
    group: cert-manager.io
```
