### ISSUE TITLE
[Feature]: Better support installation with kustomize

### ISSUE THREAD

**Issue by erikgb** [cloudnative-pg/cloudnative-pg#3400]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We use kustomize to provision everything in our clusters. While I can install cloudnative-pg with kustomize, some simple adjustments to the release automation could improve the experience. ☺️ 

Currently, we use the following kustomization:
````yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cloudnative-pg/cloudnative-pg//config/default?ref=v1.21.1
images:
  - name: controller
    newName: ghcr.io/cloudnative-pg/cloudnative-pg
    newTag: 1.21.1
````

And as you can see, the version is repeated twice. This allows us to use [Renovate to suggest upgrades](https://docs.renovatebot.com/modules/manager/kustomize/), but upgrading the remote resource tag and image tag becomes two separate upgrades - if Renovate isn't configured for this specifically.

### Describe the solution you'd like

It is apparent to me that the image in the `default` kustomize overlay is of no use to end-users, as the value is just `controller:latest`. I work with controllers myself, so I know kubebuilder scaffolds this by default, and it's very convenient it operator CI and when developing the operator. 😉 

What I would suggest, is to create a new kustomize overlay on top of `default`, where you set the correct release image tag on the commit that is tagged for the release. I am not sure if you understand what I mean, but [here is an example](https://github.com/statnett/image-scanner-operator/blob/main/kustomization.yaml) from an operator I work on.

If the `kustomization.yaml` is put in the root of the repository, this will allow me (and others) to install cloudnative-pg with just a simple kustomization:
````yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cloudnative-pg/cloudnative-pg?ref=v1.21.1
````

It seems like you already have some release automation that could do this, ref. https://github.com/cloudnative-pg/cloudnative-pg/commit/27f62cac9c882a10d78b52a14d49da5401730356 (tagged commit for the 1.21.1 release)

### Describe alternatives you've considered

It is possible to use the [release artifact yaml](https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.21.1/cnpg-1.21.1.yaml), but that is "just" and URL and nothing that Renovate understands by default.

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
