### ISSUE TITLE
[Bug]: postInitApplicationSQLRefs

### ISSUE THREAD

**Issue by hosseindehghanpoor** [cloudnative-pg/cloudnative-pg#3559]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

hossein.dehghanpoor@gmail.com

### Version

1.21.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

I have bunch of SQL queries which I need to use to initialize the database. 
if I copy and paste all scripts to the database cluster, no error happens, but if i use postInitApplicationSQLRefs, i get bunch of errors (either secretRefs or configMapRefs). 

is there any other ways that i can run my scripts after database cluster is initiated?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
The provided information is not enough to understand the issue. There are some limitations with post init scripts, as they are run as part of the init job (so the cluster is not fully up yet).

**Comment by hosseindehghanpoor** [comment]
thank you for reply
my init script files are about 4000 lines and i would be a mess here to upload. 
i just want to find another way to run these init files after cluster creation. if you have any solution it would be appreciated.

**Comment by kamikaze** [comment]
I have another problem - it doesn't get executed at all.

```yaml
  bootstrap:
    initdb:
      database: mydb
      owner: mydb
      secret:
        name: mydb-db-creds
      localeCollate: "en_US.UTF-8"
      localeCType: "en_US.UTF-8"
      import:
        type: microservice
        databases:
          - mydb_legacy
        source:
          externalCluster: legacy-mydb-db
      postInitApplicationSQLRefs:
        secretRefs:
          - name: post-init-sql
            key: post-init.sql
```
