### ISSUE TITLE
[Bug]: The job 'olm-bundle' is always failure 

### ISSUE THREAD

**Issue by YanniHu1996** [cloudnative-pg/cloudnative-pg#3562]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.21.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The 'olm-bundle' job consistently encounters failure due to the outdated Go version in use.

https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/7203033623/job/19622386794

the job olm-bundle misses the `setup-go` step

```yaml
name: Create OLM bundle and catalog
runs-on: ubuntu-22.04
permissions:
  contents: read
  packages: write
needs:
  - buildx
if: |
  (always() && !cancelled()) &&
  needs.buildx.result == 'success' &&
  needs.buildx.outputs.push == 'true'
steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      fetch-depth: 0
      ref: ${{ needs.buildx.outputs.commit }}
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    with:
      platforms: ${{ needs.buildx.outputs.platforms }}
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Login to ghcr.io
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
  - name: Create bundle
    env:
      IMAGE_NAME: ${{ needs.buildx.outputs.image_name }}
      CONTROLLER_IMG: ${{ needs.buildx.outputs.controller_img_ubi }}
      BUNDLE_IMG: ${{ needs.buildx.outputs.bundle_img }}
    run: |
      make olm-catalog
  - name: Archive the bundle manifests
    uses: actions/upload-artifact@v3
    with:
      name: bundle
      path: |
        bundle.Dockerfile
        bundle/
        cloudnative-pg-catalog.yaml
      retention-days: 7
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
