### ISSUE TITLE
[Bug]: barmanObjectStore S3 SSL connection error: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by r10r** [cloudnative-pg/cloudnative-pg#3617]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.21.1

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

I've configured the cluster with barmanObjectStore for S3 but I'm getting the error **CERTIFICATE_VERIFY_FAILED**  when barman is trying to connect to the S3 storage. The required CA certificate is present in the system cert store */etc/ssl/certs*.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycluster
spec:
  instances: 2
  storage:
   size: 50Gi
  backup:
    volumeSnapshot:
      className: mysnapclass
    barmanObjectStore:
      wal:
        compression: gzip
      endpointURL: https://s3.mycompany.de
      destinationPath: s3://cnpg-backups
      s3Credentials:
        accessKeyId:
          name: backup-secret
          key: accessKeyId
        secretAccessKey:
          name: backup-secret
          key: secretAccessKey
```

### Relevant log output

```shell
ERROR: Barman cloud WAL archive check exception: SSL validation failed for https://s3.mycompany.de/cnpg-backups [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)","pipe":"stderr","logging_pod":"mycluster-1"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r10r** [comment]
I've already discovered myself that this can be fixed by setting the environment variable **REQUESTS_CA_BUNDLE**.
This seems to be required for barman (or any other python application) which otherwise use their builtin certificate store.

```yaml
apiVersion: postgresql.cnpg.io/v1                                                                                                                
kind: Cluster                                                                                                                                    
metadata:                                                                                                                                        
  name: mycluster                                                                                                                   
spec:                                                                                                                                            
  # export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt                                                                                 
  # When barmanObjectStore (a python based tool) is used it is required to excplicitly set the                                                   
  # the cert store bundle for python.                                                                                                      
  env:                                                                                                                                           
    - name: REQUESTS_CA_BUNDLE                                                                                                                   
      value: /etc/ssl/certs/ca-certificates.crt 
```

Can we make this the default ?

**Comment by pierreblais** [comment]
Hi, I'm facing the same issue with:

- PostgreSQL: `imageName: ghcr.io/cloudnative-pg/postgresql:16.0`
- CNPG Operator Helm Chart: `0.19.1`
- CNPG Operator: `1.21.1`

First I have try to set `cluster.spec.barmanObjectStore.endpointCA`:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-db
spec:
    backup:
    barmanObjectStore:
      destinationPath: "s3://<BUCKET_NAME>"
      endpointURL: https://<ENDPOINT>
      endpointCA: # Seems doing nothing ?
        name: cnpg-s3-cred-password
        key: CA_CERT
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-cred-password
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-s3-cred-password
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: 30d
```

Then I try to set directly the env vars:
