### ISSUE TITLE
[Bug]: WATCH_NAMESPACE does not restrict the operator to specified namespaces

### ISSUE THREAD

**Issue by yuha0** [cloudnative-pg/cloudnative-pg#3649]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.0

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

The configuration option `WATCH_NAMESPACE` could not restrict the controller to specified namespaces. I set `WATCH_NAMESPACE=cnpg-system` but the controller still tried to list namespaced resources in all namespaces.

Per documentation and helm chat, it is an option provided to the users, which seem to imply the operator can operate within certain namespaces.

### Relevant log output

```shell
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Starting CloudNativePG Operator","version":"1.22.0","build":{"Version":"1.22.0","Commit":"86b9dc80","Date":"2023-12-21"}}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Listening for changes on all namespaces"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Loading configuration from ConfigMap","namespace":"cnpg-system","name":"cnpg-controller-manager-config"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Loading configuration from Secret","namespace":"cnpg-system","name":"cnpg-controller-manager-config"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Operator configuration loaded","configuration":{"webhookCertDir":"","watchNamespace":"cnpg-system","operatorNamespace":"cnpg-system","operatorPullSecretName":"cnpg-pull-secret","operatorImageName":"ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0","postgresImageName":"ghcr.io/cloudnative-pg/postgresql:16.1","inheritedAnnotations":null,"inheritedLabels":null,"monitoringQueriesConfigmap":"cnpg-default-monitoring","monitoringQueriesSecret":"","enableInstanceManagerInplaceUpdates":false,"enableAzurePVCUpdates":false,"enablePodDebugging":false,"createAnyService":false}}
...
{"level":"info","ts":"2023-12-29T06:50:07Z","logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
{"level":"info","ts":"2023-12-29T06:50:07Z","msg":"pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User \"system:serviceaccount:cnpg-system:cnpg-manager\" cannot list resource \"persistentvolumeclaims\" in API group \"\" at the cluster scope"}
{"level":"error","ts":"2023-12-29T06:50:07Z","msg":"pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User \"system:serviceaccount:cnpg-system:cnpg-manager\" cannot list resource \"persistentvolumeclaims\" in API group \"\" at the cluster scope","stacktrace":"k8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:147\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:292\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/backoff.go:227\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:290\nk8s.io/client-go/tools/cache.(*controller).Run.(*Group).StartWithChannel.func2\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/wait.go:55\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/wait.go:72"}
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YanniHu1996** [comment]
Hi @yuha0 , I am not able to reproduce this issue,  here is my  procedure

1. Deploy the operator with 1,22.0
```sh
kubectl apply -f \
  https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.22/releases/cnpg-1.22.0.yaml
```

2. edit deployment 

```sh
kubectl get deployments.apps cnpg-controller-manager -oyaml | yq .spec.template.spec.containers.0
```
```yaml
args:
  - controller
  - --leader-elect
  - --config-map-name=cnpg-controller-manager-config
  - --secret-name=cnpg-controller-manager-config
  - --webhook-port=9443
command:
  - /manager
env:
  - name: OPERATOR_IMAGE_NAME
    value: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
  - name: OPERATOR_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: MONITORING_QUERIES_CONFIGMAP
    value: cnpg-default-monitoring
  - name: WATCH_NAMESPACE
    value: cnpg-system
image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
imagePullPolicy: IfNotPresent
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /readyz
    port: 9443
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
name: manager
ports:
  - containerPort: 8080
    name: metrics
    protocol: TCP
  - containerPort: 9443
    name: webhook-server
    protocol: TCP
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /readyz
    port: 9443
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 10001
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
  - mountPath: /controller
    name: scratch-data
  - mountPath: /run/secrets/cnpg.io/webhook
    name: webhook-certificates
```

3. check the log 

```json
{
  "level": "info",
  "ts": "2024-01-02T07:35:29Z",
  "logger": "setup",
  "msg": "Starting CloudNativePG Operator",
  "version": "1.22.0",
  "build": {
    "Version": "1.22.0",
    "Commit": "86b9dc80",
    "Date": "2023-12-21"
  }
}
{
  "level": "info",
  "ts": "2024-01-02T07:35:29Z",
  "logger": "setup",
  "msg": "Listening for changes",
  "watchNamespaces": [
    "cnpg-system"
  ]
}
```

Anything I miss?
