### ISSUE TITLE
[Feature]: Allow configuration of EphemeralStorage.

### ISSUE THREAD

**Issue by jfyne** [cloudnative-pg/cloudnative-pg#3677]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

As mentioned in #317 Barman `.part` files fill the `scratch-data` ephemeral storage. A comment there says that it has been fixed, however in the certain environments, for example GKE Autopilot this still happens. We are unable to set the `ephemeralVolumesSizeLimit` high enough to allow a base backup to happen.

### Describe the solution you'd like

I would like the cluster spec to optionally allow the setting of `ephemeralStorage` which would allow users to configure how the `scratch-data` volume is configured. This would allow the use of [generic ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes). For example

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ephemeral-example
spec:
  instances: 3

  storage:
    size: 1Gi

  ephemeralStorage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
```

### Describe alternatives you've considered

I have considered the option of having a separate mount for Barman, or configuring barman to output into the walStorage volume. I don't think these are good options, allowing the use of generic ephemeral volumes feels like the best approach.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
