### ISSUE TITLE
[Feature]: Allow configuration of ReadOnlyRootFilesystem.

### ISSUE THREAD

**Issue by jfyne** [cloudnative-pg/cloudnative-pg#3718]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We are experiencing a crash in our production Postgres, the logs are not particularly revealing as to what is causing the crash. In order to investigate more we need the core dumps. As mentioned in the docs we have set the `cnpg.io/coredumpFilter` annotation:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-controller-manager-config
  namespace: cnpg-system
data:
  INHERITED_ANNOTATIONS: categories, cnpg.io/coredumpFilter
  INHERITED_LABELS: environment, workload, app
```

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/coredumpFilter: "0xFF"
...
```

The annotation is correctly applied to the pod but we are still not getting core dumps. The reason for this we believe is that we are running on a node (specifically GKE autopilot) where the `/proc/sys/kernel/core_pattern` is set to:

```
/core.%e.%p.%t
```

The leading slash in the pattern prevents the core dumps from being written into the current working directory of the process and instead to a place where the file-system is read only, as set by cnpg.

As we are running on GKE autopilot privileged containers are forbidden and we are unable to set the `core_pattern` variable using a DaemonSet or some other method.

### Describe the solution you'd like

I would like the cluster spec to include on option to explicitly set the `ReadOnlyRootFilesystem` value in the container security context to false. This can be documented suggesting very strongly that you should only do this if you understand the security implications, and have a reason for doing it.

### Describe alternatives you've considered

Given the locked down nature of the environment we are running in, I can't think of any other way to get a core dump to be written.

However if you were on a more permissive k8s cluster it would usually be possible to set the `/proc/sys/kernel/core_pattern` to a value without a leading slash.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
