### ISSUE TITLE
[Bug]: CNPG11/1.22.0 replica bootstrap - DB fails to start: "FATAL:  could not create lock file \"/var/run/postgresql/.s.PGSQL.5432.lock\": No such file or directory"

### ISSUE THREAD

**Issue by dit-darius** [cloudnative-pg/cloudnative-pg#3747]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

darius@digitalitteam.com

### Version

1.22.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

Helm

### What happened?

Also tried with 1.21.1.
See slack: https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1706316108348809

Hello. We're trying to replace PG:11 with CNPG:11 in our GKE k8s cluster. We're currently attempting to perform a live migration by spinning up a CNPG cluster and bootstrapping it as a replica to the running PG.
Problem is, the database pod `debezium-postgres-replica-1` fails with an error
`FATAL:  could not create lock file \"/var/run/postgresql/.s.PGSQL.5432.lock\": No such file or directory","pipe":"stderr"`
I tried to `while :; do kubectl -n db exec -it debezium-postgres-replica-1 -- ls -l /var/run/postgresql ; sleep .1; done` and I can confirm the path does not exist: `ls: cannot access '/var/run/postgresql': No such file or directory`.

I'm bootstrapping with this yaml (in replica mode)
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: debezium-postgres-replica
  namespace: db
  labels:
    purpose: testing
spec:
  imageName: europe-docker.pkg.dev/<client-registry>/postgresql-cnpg:11
  imagePullPolicy: Always
  bootstrap:
    pg_basebackup:
      source: debezium-postgres
  replica:
    enabled: true
    source: debezium-postgres
  externalClusters:
    - name: debezium-postgres
      connectionParameters:
        host: debezium-postgresql-primary.db.svc
        user: postgres
      password:
        name: db-replica-secret
        key: password
  instances: 1
  storage:
    storageClass: standard-rwo
    size: "50Gi"
  resources:
    requests:
      cpu: 100m
      memory: 500M
    limits:
      cpu: "1"
      memory: 700M
```

And it fails with

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/153668027/b8616804-705a-47b9-b198-5a8aba1ee50b)
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/153668027/07b7b2fd-fb7c-4559-b4e3-34cc16ba06ad)
[cnpg_operator.log](https://github.com/cloudnative-pg/cloudnative-pg/files/14089431/cnpg_operator.log)

If I try to bootstrap a new DB using the `initdb option, the DB starts up just fine.
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/153668027/df20770d-9ed5-44ac-a32f-a86569afa512)

Why is that so? What am I doing wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
