### ISSUE TITLE
[Bug]: retentionPolicy not applied on backblaze

### ISSUE THREAD

**Issue by Ulrar** [cloudnative-pg/cloudnative-pg#3824]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.1

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

Hi,

The retentionPolicy doesn't seem to apply to my scheduled backups, looking at my backblaze bucket I have base backups that are multiple months old even though the retention is set to 7d.

I'm using Talos 1.6 and k8s 1.29.1, but I've only recently upgraded to these, I have backups dating back to 1.28 that weren't deleted either so I don't think it's related.

Everything is applied through ArgoCD.

### Cluster resource

```shell
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-homeassistant
  namespace: homeassistant
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      timezone: "Europe/Dublin"
  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant_user
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"
  storage:
    size: 10Gi
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "s3://.../homeassistant/"
      endpointURL: "https://s3.eu-central-003.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: pg-barman-backblaze
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-barman-backblaze
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-homeassistant-backup-daily
spec:
  schedule: "0 30 1 * * *"
  backupOwnerReference: self
  cluster:
    name: cluster-homeassistant
```

### Relevant log output

```shell
I'm not sure what to look for here, the controller logs do show the backup running at the correct time but no mentions of deletions anywhere.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtackaberry** [comment]
I don't think this is backblaze-specific but just general to S3.  I'm seeing the same thing with Minio.  Neither WALs nor the full base backups are getting prunted.  My config is basically the same except that `retentionPolicy` is 30d and my scheduled backups are weekly.

**Comment by puppetmaster** [comment]
We have the same issue here, with Minio.

**Comment by puppetmaster** [comment]
> We have the same issue here, with Minio.

We thought we had the same problem but in fact not at all, the retention period is well applied.

For better comprehension, this is our use case, and what append for us : 

Simple cluster : 
```
backup:
  barmanObjectStore:
    destinationPath: s3://backup/postgres
    endpointURL: https://my-minio.svc.cluster.local
    s3Credentials:
      accessKeyId:
        key: CONSOLE_ACCESS_KEY
        name: minio-user
      secretAccessKey:
        key: CONSOLE_SECRET_KEY
        name: minio-user
    wal:
      compression: gzip
  retentionPolicy: 2d
  target: prefer-standby
```
Note the retention is 2 days and we run a full backup every day.

The backup will be removed when this appends :
-  The backup hits 3 days of age (more than 2 days)
- We scheduled a manual backup, and it was completed successfully.

So after careful reading of the documentation, our understanding of this issue is :
The backup must be older than the retention, and it will be removed after the next valid backup, for us on the third day.

**Comment by Ulrar** [comment]
Unfortunately that's not the case for me, I've got months of backups left over with a 7 day retention

**Comment by BongoEADGC6** [comment]
Same issue here with Minio and CNPG 1.22.1

I've set my retention to 14d and multiple backups for the last 2 months with them set to backup weekly.

**Comment by Ulrar** [comment]
Not stale, this is still a problem

**Comment by bo0tzz** [comment]
Backblaze buckets have a lifecycle setting that defaults to keeping all versions of a file, even if deleted. What do you have that set to? 

![Image](https://github.com/user-attachments/assets/fc885e2a-df84-4ca4-b787-dfad3a6306d3)

**Comment by Ulrar** [comment]
I had no idea this was a thing, I have it on the first one which indeed sounds like the issue.
For this to work right, should I select the second or fourth one ? It sounds like 4th might let cnpg add rules per object as expected ?

**Comment by bo0tzz** [comment]
I use the second one, under the assumption that CNPG isn't aware of these lifecycle rules but just makes standard delete calls for objects that are out of the retention period.

**Comment by davinkevin** [comment]
Backblaze seems to be a red hering, we have the exact same issue with minio 😇

**Comment by h3mmy** [comment]
This problem also exists with rook-ceph rgw. I have to manually cleanup old objects. Once it hits a limit, the instance starts failing

**Comment by Ulrar** [comment]
I'm still seeing the same issue after changing the settings, so I don't think that was it sadly

**Comment by alessandroros** [comment]
We have the same issue on minio, i have to delete files manually otherwise it won't.

**Comment by Ulrar** [comment]
Not stale

**Comment by 5h4k4r** [comment]
I have the same issue with MinIO, and I have to manually delete the backups. I'm using the new barmancloud plugin.

**Comment by Ulrar** [comment]
Not stale

**Comment by Ulrar** [comment]
Not stale

**Comment by a-Tell** [comment]
Could it be you have the same issue like I had?
https://github.com/cloudnative-pg/cloudnative-pg/issues/8599

It looks like you are also using the Barman-Plugin to back up, right? I also had the Error `Missing required header for this request: Content-Md5`.

My solution was to use either `plugin-barman-cloud:v0.4.1` - or better: `plugin-barman-cloud:v0.9.0`


And set these env-vars on the sidecar like this:
```
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore

...

spec:

  ...

  instanceSidecarConfiguration:
    env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required

  ...
```

**Comment by Ulrar** [comment]
Mh, I don't have an object store, not familiar with this.
That's what I have : 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-synapse
  namespace: synapse
spec:
  instances: 1
  enablePDB: false
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      timezone: "Europe/Dublin"
  bootstrap:
    initdb:
      database: synapse
      owner: synapse_user
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"
  storage:
    size: 10Gi
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "s3://.../"
      endpointURL: "https://s3.eu-central-003.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: pg-barman-backblaze
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-barman-backblaze
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-synapse-backup-daily
  namespace: synapse
spec:
  schedule: "0 30 1 * * *"
  backupOwnerReference: self
  cluster:
    name: cluster-synapse
```

What you're saying is there's a different way to set that up entirely, and that you've had success getting the retention policy to work with that other method ?
It looks like you're using AWS though, and I'm using backblaze so it may still differ in the end, but might be worth a try.
