### ISSUE TITLE
[Feature]: Add a way to prefer one replica to another in case of failover

### ISSUE THREAD

**Issue by pchovelon** [cloudnative-pg/cloudnative-pg#3971]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

It could be great if we can choose which replica will be prefered to become the new primary in case of a failover.

### Describe the solution you'd like

Add a label or a new spec (example : `primariesOrder` in ClusterSpec to indicate which replica is preferred.
It could be based on the name of the pod / instance. For example : 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-prod
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 3
  primariesOrder:
  - cluster-prod-1
  - cluster-prod-3
  - cluster-prod-2
  storage:
    size: 1G
```

1st failover : the new primary will be cluster-prod-3
cluster-prod-1 is recreated and became a replica
2st failover : the new primary will be cluster-prod-1 as it is the first one in the list

### Describe alternatives you've considered

None

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
