### ISSUE TITLE
s3-compatible storage forced to use AWS s3 path

### ISSUE THREAD

**Issue by ahgraber** [cloudnative-pg/cloudnative-pg#399]
I am trying to refer to a local minio instance within the cluster definition; however, specifying `destinationPath` as `s3://...` forces an AWS uri.

Cluster specification (trucated):

```yaml
  backup:
    barmanObjectStore:
      destinationPath: "s3://bucketname"
      endpointURL: "https://nas.mydomain.com:9000"
      s3Credentials:
        accessKeyId:
          name: s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-secret
          key: ACCESS_SECRET_KEY
        # region: us-east
```

Logs:

```json
{"level":"info","ts":1657506747.8125663,"logger":"wal-archive","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"cnpg-1"}
{
  level":"info",
  "ts":1657506753.449887,
  "logger":"barman-cloud-check-wal-archive",
  "msg":"2022-07-11 02:32:33,449 [145] ERROR: Can't connect to cloud provider: Could not connect to the endpoint URL: \"https://s3.us-east.amazonaws.com/cnpg\"",
  "pipe":"stderr",
  "logging_pod":"cnpg-1"
}
{
  "level":"error",
  "ts":1657506753.4828458,
  "logger":"wal-archive",
  "msg":"Error invoking barman-cloud-check-wal-archive",
  "logging_pod":"cnpg-1",
  "currentPrimary":"cnpg-1",
  "targetPrimary":"cnpg-1",
  "options":
    [
      "--endpoint-url",
      "https://nas.mydomain.com:9000",
      "--cloud-provider",
      "aws-s3",
      "s3://cnpg",
      "cnpg"
    ],
  "exitCode":-1,
  "error":"exit status 2",
  "stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:234\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:381\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"}
```

If I do not specify the `s3://` prefix for `destinationPath`, I get a different error:

```json
{"level":"info","ts":1657507208.411864,"logger":"wal-archive","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"cnpg-1"}
{
  "level":"info",
  "ts":1657507208.5482411,
  "logger":"barman-cloud-check-wal-archive",
  "msg":"2022-07-11 02:40:08,548 [141] ERROR: Barman cloud WAL archive check exception: Invalid s3 URL address: cnpg",
  "pipe":"stderr",
  "logging_pod":"cnpg-1"
}
{
  "level":"error",
  "ts":1657507208.5699892,
  "logger":"wal-archive",
  "msg":"Error invoking barman-cloud-check-wal-archive",
  "logging_pod":"cnpg-1",
  "currentPrimary":"cnpg-1",
  "targetPrimary":"cnpg-1",
  "options":
    [
      "--endpoint-url",
      "https://nas.mydomain.com:9000",
      "--cloud-provider",
      "aws-s3",
      "cnpg",
      "cnpg"
    ],
  "exitCode":-1,
  "error":"exit status 4",
  "stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:234\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.checkWalArchive\n\tinternal/cmd/manager/walarchive/cmd.go:381\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.run\n\tinternal/cmd/manager/walarchive/cmd.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255"
}
```

I have deployed the operator via helm chart, version 0.13.1

**Comment by ahgraber** [comment]
By upgrading to operator v0.14 and including region, the erroneous s3 url is resolved.  However, I am getting a different error now (I think because I am using https for the endpointURL):

```json
{"level":"info","ts":1657588331.347125,"logger":"barman-cloud-wal-archive","msg":"2022-07-12 01:12:11,346 [148] ERROR: Barman cloud WAL archiver exception: An error occurred (NotImplemented) when calling the PutObject operation: Server side encryption specified but KMS is not configured","pipe":"stderr","logging_pod":"cnpg-1"}
{"level":"error","ts":1657588331.3814707,"msg":"Error invoking barman-cloud-wal-archive","logging_pod":"cnpg-1","walName":"pg_wal/000000010000000000000001","currentPrimary":"cnpg-1","targetPrimary":"cnpg-1","options":["--gzip","-e","AES256","--endpoint-url","https://nas.mydomain.com:9000","--cloud-provider","aws-s3","s3://cnpg","cnpg","pg_wal/000000010000000000000001"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).Archive\n\tpkg/management/barman/archiver/archiver.go:173\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).ArchiveList.func1\n\tpkg/management/barman/archiver/archiver.go:118"}
{"level":"info","ts":1657588331.3815506,"logger":"wal-archive","msg":"Failed archiving WAL: PostgreSQL will retry","logging_pod":"cnpg-1","walName":"pg_wal/000000010000000000000001","startTime":1657588329.502264,"endTime":1657588331.3815458,"elapsedWalTime":1.879281724,"error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4"}
```

updated cluster definition:
```yaml
# ...
 backup:
    barmanObjectStore:
      destinationPath: "s3://bucketname"
      endpointURL: "https://nas.mydomain.com:9000"
      s3Credentials:
        accessKeyId:
          name: s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-secret
          key: ACCESS_SECRET_KEY
        region:
          name: s3-secret
          key: REGION
```
