### ISSUE TITLE
Cluster operations causing heavy control plane load

### ISSUE THREAD

**Issue by rust84** [cloudnative-pg/cloudnative-pg#407]
Hi, 

I have recently been exploring cnpg operator and am encountering issue where cluster operations, such as creating or replacing a node, are causing the the cpu usage of the control plane nodes to escalate until they fall over. 

Now full disclosure this is my homelab setup and the master nodes are Pi4 4GB with SSDs. The cluster is bootstrapped using Talos OS and worker nodes are Intel NUC with 32GB ram. Under normal operation the control plane nodes sit at around 20% CPU usage.

I run a number of different workloads including some complex operators like Rook Ceph which is providing the PVCs for postgres and I have not encountered this issue in the past year. My database side is quite small ~280MB. 

When the failure happens I am seeing the kube-api server consuming 100% cpu and a huge number of writes to etcd and associated IO with it.

I've added graphs below to illustrate.

node metrics:

![Screenshot 2022-07-10 125502](https://user-images.githubusercontent.com/23284108/178517626-331e2eb9-cc45-4be4-9602-95198e4a1c77.gif)

etcd graph:

![before](https://user-images.githubusercontent.com/23284108/178517640-272eae3d-9fed-4a34-adc5-ac591bf9beba.gif)

processes:

![F](https://user-images.githubusercontent.com/23284108/178517900-43a036c3-65a4-418e-9a49-04902c63e2c6.gif)

I have tried tuning the etcd election timeout to 5s and increasing the heartbeat interval without sucess. I am running k8s v1.24.2 and operator 1.6. I recently upgraded from K8s v1.23.8 and operator 1.5.1 and had the issue before and after. 

The last crash actually happened as I was rebooting the nodes one at a time to upgrade k8s (with the cluster in maintenance mode). The operator spawned a new node and started streaming the data and that is when the crash occurred. 

To recover I have to reboot all three control plane nodes at the same time and then quickly scale down the operator which is crashlooped at this point. I have included the log from this most recent incident below. I cannot see anything in the log to indicate the problem except for the timeouts communicating with the API.

I completely accept I am not running on production grade hardware but I still feel that the load put on the api/etcd is excessive. Is this a known issue? Are there any settings which I can tune this? 

I really like the operator and the backup features are really nice. So I am reluctant to scrap it and go back to Bitnami however in the current state I am afraid of leaving the cluster unattended in case it does a node replacement🙁 

Under normal conditions it is completely manageable

![Screenshot 2022-07-12 155455](https://user-images.githubusercontent.com/23284108/178520204-77a75d66-92a3-4db6-910e-a6ed86dfb402.gif)

K8s version: v1.24.2
OS: Talos 1.1
Operator version: 1.6

Cluster spec:

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-default
  namespace: database
spec:
  instances: 3

  storage:
    size: 50Gi

  superuserSecret:
    name: postgres-default-superuser

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      wal:
        compression: bzip2
      destinationPath: s3://postgres-default/
      endpointURL: "https://nas.${SECRET_DOMAIN}:9000"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
```

Log:

https://gist.github.com/rust84/c4d5a337a3491435345358cf2f5223c5
