### ISSUE TITLE
[Feature]: Add a new `ClientCertificate` resource type

### ISSUE THREAD

**Issue by sando38** [cloudnative-pg/cloudnative-pg#4100]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Using client certificate authentication requires to create client certificates with the `kubectl cnpg certificate` cmd - at least this is the only know method to me :)

The corresponding created secret can be mounted into a container for authentication to a respective cnpg cluster. 

The client certificates expire after 90 days, meaning the need to be renewed by:

1. deleting the old client cert secret
2. running `kubectl cnpg certificate` cmd again
3. restarting the corresponding container

### Describe the solution you'd like

It would be cool to have cnpg resource (CRD) which one could create and the cnpg operator would create a corresponding client-cert kubernetes secret, e.g. like this:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ClientCertificate
metadata:
  name: my-client-certificate
  namespace: default
  labels:
    k8s-sidecar/watch: "true"
  annotations:
    k8s-sidecar-target-directory: "certs"
spec:
  cluster: "cnpg-cluster"
  certificateDuration: "30d"
  user: "app"
  revokeOnRenewal: "true"
  secretName: "my-client-certificate"
```

As you can see I also would like to assign custom labels/annotations to the resource, so that I could e.g. `kiwigrid/k8s-sidecar` to dynamically inject an updated `secret` into a running container.

Maybe the operator could also revoke old client certificates when a new one has been created.

### Describe alternatives you've considered

I created a kubernetes `CronJob` for this task, but in my opinion such a task is better suited in the cnpg-operator:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-krew-plugin
  namespace: cloudnative-pg
data:
  download-krew.sh: |
    #!/bin/sh

    (
      set -x; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" -C /krew
    )

  install-krew.sh: |
    #!/bin/bash

    (
      set -x; OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      /krew/"${KREW}" install krew
    )
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-client-cert-cnpg-ejabberd-testing-01
  namespace: cloudnative-pg
data:
  create-client-cert.sh: |
    #!/bin/bash

    echo "> Install krew plugin ..."
    export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
    kubectl krew install cnpg

    echo "> Check if cnpg client secret exists, delete old ..."
    if [ "$(kubectl get secret $CNPG_CLUSTER_CLIENT_SECRET_NAME --namespace $CNPG_CLUSTER_NAMESPACE)" ]
    then kubectl delete secret $CNPG_CLUSTER_CLIENT_SECRET_NAME --namespace $CNPG_CLUSTER_NAMESPACE
    fi

    echo "> Create cnpg client secret for $CNPG_CLUSTER_USERNAME ..."
    kubectl cnpg certificate $CNPG_CLUSTER_CLIENT_SECRET_NAME \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      --cnpg-cluster $CNPG_CLUSTER_NAME \
      --cnpg-user $CNPG_CLUSTER_USERNAME

    echo "> Label and annotate secret for k8s-watcher ..."
    kubectl label secret $CNPG_CLUSTER_CLIENT_SECRET_NAME \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      "helm-ejabberd/testing=true"

    kubectl label secret $CNPG_CLUSTER_CLIENT_SECRET_NAME \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      "cnpg.io/reload="

    kubectl annotate secret $CNPG_CLUSTER_CLIENT_SECRET_NAME \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      "k8s-sidecar-target-directory=certs/cnpg-tls"

    echo "> Label and annotate $CNPG_CLUSTER_NAME-ca for k8s-watcher ..."
    kubectl label secret $CNPG_CLUSTER_NAME-ca \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      "helm-ejabberd/testing=true"

    kubectl annotate secret $CNPG_CLUSTER_NAME-ca \
      --namespace $CNPG_CLUSTER_NAMESPACE \
      "k8s-sidecar-target-directory=certs/cnpg-tls"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: client-cert-cnpg-ejabberd-testing-01
  namespace: cloudnative-pg
spec:
  schedule: '@weekly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: client-cert-cnpg-ejabberd-testing-01
        spec:
          restartPolicy: Never
          serviceAccountName: cloudnative-pg
          initContainers:
            - image: docker.io/curlimages/curl:8.6.0
              name: download-krew
              command: ["/bin/sh", "-c", "/script/download-krew.sh"]
              volumeMounts:
              - name: scripts-krew-plugin
                mountPath: /script/download-krew.sh
                subPath: download-krew.sh
                readOnly: true
              - name: tmpfs
                mountPath: /krew
                subPath: krew

          containers:
            - image: docker.io/bitnami/kubectl:1.29.1
              name: create-client-certs
              command:
                - "bin/bash"
                - "-c"
                - "/script/install-krew.sh && /script/create-client-cert.sh"
              env:
              - name: CNPG_CLUSTER_NAME
                value: "cnpg-ejabberd-testing-01"
              - name: CNPG_CLUSTER_NAMESPACE
                value: "ejabberd"
              - name: CNPG_CLUSTER_USERNAME
                value: "ejabberd"
              - name: CNPG_CLUSTER_CLIENT_SECRET_NAME
                value: "cnpg-ejabberd-testing-user"
              volumeMounts:
              - name: scripts-krew-plugin
                mountPath: /script/install-krew.sh
                subPath: install-krew.sh
                readOnly: true
              - name: create-cnpg-client-cert
                mountPath: /script/create-client-cert.sh
                subPath: create-client-cert.sh
                readOnly: true
              - name: tmpfs
                mountPath: /krew
                subPath: krew
              - name: tmpfs
                mountPath: /.krew
                subPath: krew-home

          volumes:
          - name: tmpfs
            emptyDir:
              defaultMode: 777

          - name: scripts-krew-plugin
            configMap:
              name: scripts-krew-plugin # part of cloudnative-pg kustomization
              defaultMode: 0755
              items:
              - key: download-krew.sh
                path: download-krew.sh
              - key: install-krew.sh
                path: install-krew.sh

          - name: create-cnpg-client-cert
            configMap:
              name: create-client-cert-cnpg-ejabberd-testing-01
              defaultMode: 0755
              items:
              - key: create-client-cert.sh
                path: create-client-cert.sh

---
apiVersion: batch/v1
kind: Job
metadata:
  name: client-cert-cnpg-ejabberd-testing-01
  namespace: cloudnative-pg
  labels:
    app: client-cert-cnpg-ejabberd-testing-01
spec:
  template:
    metadata:
      labels:
        app: client-cert-cnpg-ejabberd-testing-01
    spec:
      restartPolicy: Never
      serviceAccountName: cloudnative-pg
      initContainers:
        - name: download-krew
          image: docker.io/curlimages/curl:8.6.0
          command:
            - /bin/sh
            - '-c'
            - /script/download-krew.sh
          volumeMounts:
            - name: scripts-krew-plugin
              readOnly: true
              mountPath: /script/download-krew.sh
              subPath: download-krew.sh
            - name: tmpfs
              mountPath: /krew
              subPath: krew

      containers:
        - name: create-client-certs
          image: docker.io/bitnami/kubectl
          command:
            - bin/bash
            - '-c'
            - "/script/install-krew.sh && /script/create-client-cert.sh"
          env:
          - name: CNPG_CLUSTER_NAME
            value: "cnpg-ejabberd-testing-01"
          - name: CNPG_CLUSTER_NAMESPACE
            value: "ejabberd"
          - name: CNPG_CLUSTER_USERNAME
            value: "ejabberd"
          - name: CNPG_CLUSTER_CLIENT_SECRET_NAME
            value: "cnpg-ejabberd-testing-user"
          volumeMounts:
            - name: scripts-krew-plugin
              readOnly: true
              mountPath: /script/install-krew.sh
              subPath: install-krew.sh
            - name: create-cnpg-client-cert
              readOnly: true
              mountPath: /script/create-client-cert.sh
              subPath: create-client-cert.sh
            - name: tmpfs
              mountPath: /krew
              subPath: krew
            - name: tmpfs
              mountPath: /.krew
              subPath: krew-home

      volumes:
        - name: tmpfs
          emptyDir:
            defaultMode: 777

        - name: scripts-krew-plugin
          configMap:
            name: scripts-krew-plugin
            items:
              - key: download-krew.sh
                path: download-krew.sh
              - key: install-krew.sh
                path: install-krew.sh
            defaultMode: 0755

        - name: create-cnpg-client-cert
          configMap:
            name: create-client-cert-cnpg-ejabberd-testing-01
            items:
              - key: create-client-cert.sh
                path: create-client-cert.sh
            defaultMode: 0755
```

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No (but I am happy to test)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
