### ISSUE TITLE
[Feature]:  Use Workload Identity for Backup from GKE

### ISSUE THREAD

**Issue by movergan** [cloudnative-pg/cloudnative-pg#4142]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently for Google Bucket backup to work it is mandatory to provide a service account JSON key. It is considered legacy way and WorkLoad identity should be used instead. 
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity 

At the moment it fails if no credentials are provided:
```
{"level":"info","ts":"2024-03-18T22:05:44Z","logger":"barman-cloud-check-wal-archive","msg":"2024-03-18 22:05:44,562 [1245] ERROR: Barman cloud WAL archive check exception: ('File /controller/.application_credentials.json is not a valid json file.', JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))","pipe":"stderr","logging_pod":"psql-0-cluster-1"}
```

### Describe the solution you'd like

1. Add an option to use custom annotations for Kubernetes service accounts so it would be possible to add:

      iam.gke.io/gcp-service-account: postgres-sa@<project>.iam.gserviceaccount.com

2. "Teach" the backup mechanism when "google" is used, it should use native authentication mechanisms. 
More details here: https://cloud.google.com/docs/authentication/client-libraries  

### Describe alternatives you've considered

Use the service account JSON file created manually. 

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by movergan** [comment]
I have to add clarification here and close the issue. 
1. I was confused because I tried to create a "cluster" using the helm chart.  It is a 0.0.3 version and doesn't have all the power of raw manifest yet. 
2. In order to make WI work you should use "Cluster" manifest "as is" and add the following field to the configuration:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-0-cluster
  namespace: p01
  labels:
    helm.sh/chart: cluster-0.0.3
    app.kubernetes.io/name: cluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  imagePullPolicy: IfNotPresent
...
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: postgres-sa@<project>.iam.gserviceaccount.com
```
