### ISSUE TITLE
[Bug]: Error while bootstrapping data directory

### ISSUE THREAD

**Issue by dustinmoris** [cloudnative-pg/cloudnative-pg#4158]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

YAML manifest

### What happened?

Running the following manifest:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: plausible-postgres-credentials
  namespace: plausible
type: kubernetes.io/basic-auth
stringData:
  username: plausible
  password: redacted

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: plausible
spec:
  instances: 2
  imageName: postgres:14.11
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard-rwo
  enableSuperuserAccess: false
  superuserSecret:
    name: redacted
  bootstrap:
    initdb:
      database: plausible
      owner: plausible
      secret:
        name: plausible-postgres-credentials
  postgresql:
    parameters:
      timezone: "Europe/London"
```

results in this error:

```bash
pod/pg-cluster-1-initdb-dr2t8   0/1     Error      0              31s
pod/pg-cluster-1-initdb-mtcs8   0/1     Error      0              72s
```

with logs for the container:

```bash
Defaulted container "initdb" out of: initdb, bootstrap-controller (init)
{"level":"info","ts":"2024-03-25T10:31:57Z","msg":"Creating new data directory","logging_pod":"pg-cluster-1-initdb","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"info","ts":"2024-03-25T10:31:57Z","logger":"initdb","msg":"initdb: could not look up effective user ID 26: user does not exist\n","pipe":"stderr","logging_pod":"pg-cluster-1-initdb"}
{"level":"error","ts":"2024-03-25T10:31:57Z","msg":"Error while bootstrapping data directory","logging_pod":"pg-cluster-1-initdb","error":"error while creating the PostgreSQL instance: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:151\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2\n\tinternal/cmd/manager/instance/initdb/cmd.go:104\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:267"}
Error: error while creating the PostgreSQL instance: exit status 1
```

### Cluster resource

```shell
apiVersion: v1
kind: Secret
metadata:
  name: plausible-postgres-credentials
  namespace: plausible
type: kubernetes.io/basic-auth
stringData:
  username: plausible
  password: redacted

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: plausible
spec:
  instances: 2
  imageName: postgres:14.11
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard-rwo
  enableSuperuserAccess: false
  superuserSecret:
    name: redacted
  bootstrap:
    initdb:
      database: plausible
      owner: plausible
      secret:
        name: plausible-postgres-credentials
  postgresql:
    parameters:
      timezone: "Europe/London"
```

### Relevant log output

```shell
Defaulted container "initdb" out of: initdb, bootstrap-controller (init)
{"level":"info","ts":"2024-03-25T10:31:57Z","msg":"Creating new data directory","logging_pod":"pg-cluster-1-initdb","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"info","ts":"2024-03-25T10:31:57Z","logger":"initdb","msg":"initdb: could not look up effective user ID 26: user does not exist\n","pipe":"stderr","logging_pod":"pg-cluster-1-initdb"}
{"level":"error","ts":"2024-03-25T10:31:57Z","msg":"Error while bootstrapping data directory","logging_pod":"pg-cluster-1-initdb","error":"error while creating the PostgreSQL instance: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:151\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2\n\tinternal/cmd/manager/instance/initdb/cmd.go:104\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:267"}
Error: error while creating the PostgreSQL instance: exit status 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
