### ISSUE TITLE
[Bug]: retentionPolicy does not limit backups

### ISSUE THREAD

**Issue by kamikaze** [cloudnative-pg/cloudnative-pg#4170]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

kamikaze.is.waiting.you@gmail.com

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

For some reason base backups are not being dropped after retentionPolicy: 7d (another cluster for 2d as well). I have such "extra" base backups since 2024-03-18, today is 2024-03-26. Worked before correctly.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg16
  namespace: pg
spec:
  description: "PROD cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  startDelay: 300
  stopDelay: 300
  instances: 3
  storage:
    size: 20Gi
    resizeInUseVolumes: False
  minSyncReplicas: 1
  maxSyncReplicas: 1
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  superuserSecret:
    name: db-postgres-creds
  externalClusters:
    - name: prod-db-backup
      barmanObjectStore:
        destinationPath: "s3://prod-db-backup/"
        serverName: "pg-0"
        s3Credentials:
          accessKeyId:
            name: s3-backuper-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: s3-backuper-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
  bootstrap:
    initdb:
      database: db
      owner: owner
      secret:
        name: db-creds
      localeCollate: "en_US.UTF-8"
      localeCType: "en_US.UTF-8"
      postInitApplicationSQLRefs:
        secretRefs:
          - name: post-init-sql
            key: post-init.sql
  backup:
    barmanObjectStore:
      destinationPath: "s3://prod-db-backup/"
      serverName: "pg16-0"
      s3Credentials:
        accessKeyId:
          name: s3-backuper-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-backuper-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
        maxParallel: 8
      data:
        compression: bzip2
    retentionPolicy: 7d
  postgresql:
    parameters:
      work_mem: "32MB"
      shared_buffers: "1GB"
  resources:
    requests:
      memory: "1.3Gi"
      cpu: "0.5"
    limits:
      memory: "2.6Gi"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kamikaze** [comment]
Also I have a daily backup set

**Comment by davinkevin** [comment]
I have the same issue for more than ~2 months now, but not for all my clusters 🤷

**Comment by atimofeev** [comment]
Facing the same issue with cnpg `1.25.1` with this config:
```yaml
kind: Cluster
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        jobs: 2
      destinationPath: s3://***-postgresql-backup/
      endpointURL: ***
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: ***-postgresql-minio-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: ***-postgresql-minio-creds
      wal:
        compression: gzip
        maxParallel: 1
    retentionPolicy: 3d
    target: prefer-standby
---
kind: ScheduledBackup
spec:
  backupOwnerReference: self
  cluster:
    name: ***-postgresql-cluster
  immediate: true
  method: barmanObjectStore
  schedule: 0 0 0 * * *
```
Using self-hosted kubeadm-based k8s installation, with backups into self-hosted minio.

**Comment by kingfishx23** [comment]
are there update on this issue?

Mine's not working also. the WALs keeps increasing and Base Backups keep adding without limit
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  instances: 2
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised
  
  affinity:
    nodeSelector:
      type: backend

  postgresql:
    parameters:
      shared_buffers: 256MB
      work_mem: 16MB
      max_connections: "200"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: "10s"
      max_wal_size: "5GB"
    pg_hba:
      - host all all 10.244.0.0/16 md5

  backup:
    barmanObjectStore:
      serverName: "******"
      destinationPath: s3://******
      endpointURL: 'https://s3.eu-central-003.backblazeb2.com'
      s3Credentials:
        accessKeyId:
          name: ****
          key: accessKeyId
        secretAccessKey:
          name: ****
          key: secretAccessKey
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: '7d'

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
```
