### ISSUE TITLE
[Feature]: Allow specifying postgresql version manually

### ISSUE THREAD

**Issue by ThirVondukr** [cloudnative-pg/cloudnative-pg#4198]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Not all postgres images follow `tag:{version}...` convention (e.g. https://github.com/pgroonga/docker), perhaps you should be able to override that behavior in cluster configuration, for now I had to retag it in a personal repository.

### Describe the solution you'd like

Adding an explicit version to `Cluster` seems like an obvious solution:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: ...
spec:
  instances: 1
  imageName: doctorpy/pgroonga:16-3.1.9-debian
  postgresql:
    version: 16
  storage:
    size: 5Gi
```

### Describe alternatives you've considered

Adding something like a regex to extract version from image tag could be more flexible but is inherently error prone.

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
