### ISSUE TITLE
[Bug]: Incorrect calculation of cronjobs in scheduled backups

### ISSUE THREAD

**Issue by DeskPlant** [cloudnative-pg/cloudnative-pg#4202]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

patrik.zotj@gmail.com

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

YAML manifest

### What happened?

After creating a cluster, i tried attaching a scheduled backup resource to it using the yaml below.

```
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-test
spec:
  schedule: "0 1 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: test-db
```
The backups created by it are fine, the issue is the frequency of the backups does not match the given cron in the yaml file.
For examle if i give it a cronjob to backup every day at 1 am, even though it says the schedule is correct when i use kubectl describe, the backups are instead done every 1 hour. 

<img width="513" alt="image" src="https://github.com/cloudnative-pg/cloudnative-pg/assets/90926812/19a16033-9445-4202-a5d0-7eafd515098e">

<img width="160" alt="image" src="https://github.com/cloudnative-pg/cloudnative-pg/assets/90926812/5181fae4-92fc-4bae-b2d4-c94e2b5a1ce8">

I have tried this with other formats for example every 8 hours and that makes the backups occur every 8 minutes instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
