### ISSUE TITLE
[Feature]: introduce managed services

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4339]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

At the moment, CloudNativePG has a fixed number of services that are deployed with each Cluster:

- rw
- ro
- r

These services are all cluster IP.

There are use cases where:

- you don't want all the above services
- you want additional services with a different type (i.e., to expose the PostgreSQL service outside the Kubernetes cluster with a load balancer service)

### Describe the solution you'd like

We should improve the `Cluster` API with a new stanza called `managed.services`, providing capabilities like the ones shown below:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  storage:
    size: 1Gi
  managed:
    services:
      disabledDefaultServices: ['ro', 'r'] 
      additional:
      - type: rw
        serviceTemplate:
          metadata:
            name: cluster-example-lb-rw (REQUIRED)
          spec: (OPTIONAL)
            type: LoadBalancer
```

In the above example we disable the creation of the `cluster-example-ro` and `cluster-example-r` and we create an additional load balancer service.

### Describe alternatives you've considered

In this case we use the Kubernetes `corev1.Service` resource API. We could have managed it ourselves, but our phylosophy is to reuse K8s resources.

### Additional context

Feel free to limit this issue to either the `additional` stanza or the `disabledDefaultServices` implementation (which I fear might be more difficult to implement as it might introduce regressions).

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rewemkris** [comment]
This would be very useful. 
One point to mention is setting annotations in the serviceaccount template would also be very useful to give the oppurtunity f.e. Specify which loadbalancer network should be used through annotations

**Comment by anaskhantpl** [comment]
Hi, can you please update the docs that how to use that new feature.

**cluster.yaml:**

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  storage:
    size: "1Gi"
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
```
**O/P:**
```
root@k3d:/home/anas# kubectl get pod
NAME                                   READY   STATUS    RESTARTS   AGE
cnpg-cloudnative-pg-5c96f6fc67-68wz2   1/1     Running   0          23h
cluster-1                              1/1     Running   0          30m
cluster-2                              1/1     Running   0          29m
cluster-3                              1/1     Running   0          29m
```
### Custom SVC
**cluster-2-svc.yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: cluster-2
  labels:
    app: cluster
spec:
  type: ClusterIP 
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: cluster
```

**cluster-3-svc.yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: cluster-3
  labels:
    app: cluster
spec:
  type: ClusterIP 
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: cluster
```
**o/p:**
```
root@k3d:/home/anas# kubectl get svc
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP                                   PORT(S)                         AGE
kubernetes             ClusterIP      10.43.0.1       <none>                                        443/TCP                         15d
cnpg-webhook-service   ClusterIP      10.43.248.207   <none>                                        443/TCP                         23h
cluster-3              ClusterIP      10.43.55.127    <none>                                        5432/TCP                        32m
cluster-2              ClusterIP      10.43.170.112   <none>                                        5432/TCP                        32m
cluster-rw             ClusterIP      10.43.23.172    <none>                                        5432/TCP                        32m
```

I am using pgpool for loadbalancing, able to telnet `rw` service which generated by operator:
```
root@pgpool-6c4975696-jqpxn:/# telnet cluster-rw.default 5432
Trying 10.43.23.172...
Connected to cluster-rw.default.
Escape character is '^]'.
^CConnection closed by foreign host.

root@pgpool-6c4975696-jqpxn:/# telnet cluster-2.default 5432
Trying 10.43.170.112...
telnet: Unable to connect to remote host: Connection refused
```
everything is running on default namespace.
