### ISSUE TITLE
[Feature]: Give the possibility to automatically clean pgbench jobs - ttlSecondsAfterFinished option

### ISSUE THREAD

**Issue by pchovelon** [cloudnative-pg/cloudnative-pg#4374]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

pgbench jobs are not cleaned by default. It would be great to have to possibility to clean them automatically after a certain time.

### Describe the solution you'd like

The **ttlSecondsAfterFinished** option of a Kubernetes Job could be implemented. See [https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically]( https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically)

It could be configured in the YAML file, in a job or pgbench / section . For example for one hour TTL : 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: perf-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 1
  pgbench:
    ttlSecondsAfterFinished: '3600'
...
```

By default, we can keep it disabled.

### Describe alternatives you've considered

none 

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
