### ISSUE TITLE
[Bug]: The CustomResourceDefinition "poolers.postgresql.cnpg.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by remotejob** [cloudnative-pg/cloudnative-pg#4377]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

aleksander.mazurov@gmail.com

### Version

1.23.0

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

YAML manifest

### What happened?

I successfully install cnpg-1.21.3.yaml but all versions after have an error   
`The CustomResourceDefinition "poolers.postgresql.cnpg.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

Command:  
`k apply -f https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.22.3/cnpg-1.22.3.yaml`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by achanda** [comment]
@remotejob try a server side apply

```
k apply -f https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.22.3/cnpg-1.22.3.yaml --server-side
```

**Comment by remotejob** [comment]
Thanks. OK

As I understand I can't change the default PORT

   postgresql:
     parameters:
       port: "5431" 

`The Cluster "cluster-pg" is invalid: spec.postgresql.parameters.port: Invalid value: "5431": Can't set fixed configuration parameter`


## Anyway Result for install  was:  
namespace/cnpg-system serverside-applied
customresourcedefinition.apiextensions.k8s.io/backups.postgresql.cnpg.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/clusters.postgresql.cnpg.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/poolers.postgresql.cnpg.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/scheduledbackups.postgresql.cnpg.io serverside-applied
serviceaccount/cnpg-manager serverside-applied
clusterrole.rbac.authorization.k8s.io/cnpg-manager serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/cnpg-manager-rolebinding serverside-applied
configmap/cnpg-default-monitoring serverside-applied
service/cnpg-webhook-service serverside-applied
deployment.apps/cnpg-controller-manager serverside-applied
Apply failed with **3 conflicts**: conflicts with "kubectl-client-side-apply" using admissionregistration.k8s.io/v1:
- .webhooks[name="mbackup.cnpg.io"].rules
- .webhooks[name="mcluster.cnpg.io"].rules
- .webhooks[name="mscheduledbackup.cnpg.io"].rules
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts

### So my question: How resolve conflicts or I can continue without resolve ?

**Comment by christiaangoossens** [comment]
Can confirm this error happens, specifically through ArgoCD. Server-side apply applies it fine.

**Comment by graphenn** [comment]
It also happens at my environment, back to 1.22.1 is OK

Version
1.23.1

What version of Kubernetes are you using?
1.26.4

What is your Kubernetes environment?
Self-managed: kubekey created

How did you install the operator?
YAML manifest

**Comment by DevBey** [comment]
for argocd @christiaangoossens, enabling     - ServerSideApply=true works

**Comment by TecIntelli** [comment]
We can confirm this issue on a MicroK8s cluster, channel 1.29 (Kubernetes v1.29), with the provided cloudnative-pg addon, starting from cloudnative-pg version 1.22.2

`The CustomResourceDefinition "poolers.postgresql.cnpg.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

Cloudnative-pg versions 1.22.2, 1.22.3, 1.23.0 and 1.23.1 show the same behaviour. 

We modified the mentioned MicroK8s addon enable script manually (/var/snap/microk8s/common/addons/community/addons/cloudnative-pg/enable) by adding `--server-side` to line 42:
`apply_wait=$("${SNAP_DATA}"/bin/kubectl-cnpg install generate | $KUBECTL apply --server-side -f - > /dev/null)` and the addon installed without error.

However, do we need to change it to server side apply permanently or are there any ideas to fix this, to keep on client side apply?
[Comparison with Client-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/#comparison-with-client-side-apply)

**Comment by sxd** [comment]
Hello,

This was announced in the release 1.22.2 and it's on the release notes here: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/release_notes/v1.22.md#changes-2

Regards,

**Comment by Hevdin-twl** [comment]
The Same Issue on ArgoCD with various versions. I was able to run Argo app, by creating a custom  pooler.yaml with no annotations and with no pooler scheme. It's working but I guess should be correct way to fix it.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poolers.postgresql.cnpg.io
  # annotations removed here
spec:
  group: postgresql.cnpg.io
  names:
    plural: poolers
    singular: pooler
    kind: Pooler
    shortNames:
      - plr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # here should be pooler scheme
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
  webhookConversion: null
```

**Comment by chrismlee42** [comment]
> The Same Issue on ArgoCD with various versions. I was able to run Argo app, by creating a custom pooler.yaml with no annotations and with no pooler scheme. It's working but I guess should be correct way to fix it.
> 
> ```
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
>   name: poolers.postgresql.cnpg.io
>   # annotations removed here
> spec:
>   group: postgresql.cnpg.io
>   names:
>     plural: poolers
>     singular: pooler
>     kind: Pooler
>     shortNames:
>       - plr
>   scope: Namespaced
>   versions:
>     - name: v1
>       served: true
>       storage: true
>       schema:
>         openAPIV3Schema:
>           type: object
>           properties:
>             spec:
>               type: object
>               # here should be pooler scheme
>       subresources:
>         status: {}
>       additionalPrinterColumns:
>         - name: Age
>           type: date
>           jsonPath: .metadata.creationTimestamp
>   conversion:
>     strategy: None
>   webhookConversion: null
> ```

As noted a [couple](https://github.com/cloudnative-pg/cloudnative-pg/issues/4377#issuecomment-2081107268) of [times](https://github.com/cloudnative-pg/cloudnative-pg/issues/4377#issuecomment-2098803105) above, we can handle this in ArgoCD with the `-ServerSideApply=true` setting in the Application's `spec.syncPolicy.syncOptions`. Personally, I don't use the command line to create Applications, so all I can offer is my Application manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cnpg-system
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42-dev/cloudnative-pg-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
```
