### ISSUE TITLE
[Bug]: cnpg-controller-manager Pod in CrashLoopBackOff after upgrade to 1.23.1 on OpenShift 4.14

### ISSUE THREAD

**Issue by dakine1111** [cloudnative-pg/cloudnative-pg#4440]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.0

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Other

### How did you install the operator?

OLM

### What happened?

We are running the CloudNativePG operator from the certified-operators Hub on OpenShift 4.14
The Update approval was set to Automatic. The Operator was updated from cloudnative-pg.v1.22.2 (which runs fine) to cloudnative-pg.v1.23.1
With 1.23.1 the operator pod is in the state CrashLoopBackOff. This happens on 3 different OpenShift clusters.
There is a ClusterRole
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterimagecatalogs.postgresql.cnpg.io-v1-admin
rules:
  - verbs:
      - '*'
    apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusterimagecatalogs
```
After creating the following ClusterRoleBinding:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudnative-pg.v1.23.1-5d9489474d-bugfix
subjects:
  - kind: ServiceAccount
    name: cnpg-manager
    namespace: cloudnativepg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterimagecatalogs.postgresql.cnpg.io-v1-admin
```
the operator pod starts working again.
ClusterImageCatalog seems to be new in 1.23 and it looks like the rolebinding is missing here.

### Relevant log output

```shell
{"level":"error","ts":"2024-05-06T07:04:40Z","msg":"pkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1.ClusterImageCatalog: failed to list *v1.ClusterImageCatalog: clusterimagecatalogs.postgresql.cnpg.io is forbidden: User \"system:serviceaccount:cloudnativepg:cnpg-manager\" cannot list resource \"clusterimagecatalogs\" in API group \"postgresql.cnpg.io\" at the cluster scope","stacktrace":"k8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:147\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:292\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.29.4/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.29.4/pkg/util/wait/backoff.go:227\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:290\nk...
{"level":"info","ts":"2024-05-06T07:04:56Z","msg":"pkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: failed to list *v1.ClusterImageCatalog: clusterimagecatalogs.postgresql.cnpg.io is forbidden: User \"system:serviceaccount:cloudnativepg:cnpg-manager\" cannot list resource \"clusterimagecatalogs\" in API group \"postgresql.cnpg.io\" at the cluster scope"}
{"level":"error","ts":"2024-05-06T07:04:56Z","msg":"pkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1.ClusterImageCatalog: failed to list *v1.ClusterImageCatalog: clusterimagecatalogs.postgresql.cnpg.io is forbidden: User \"system:serviceaccount:cloudnativepg:cnpg-manager\" cannot list resource \"clusterimagecatalogs\" in API group \"postgresql.cnpg.io\" at the cluster scope","stacktrace":"k8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:147\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:292\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.29.4/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.29.4/pkg/util/wait/backoff.go:227\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tpkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:290\nk...
{"level":"info","ts":"2024-05-06T07:05:28Z","msg":"pkg/mod/k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: failed to list *v1.ClusterImageCatalog: clusterimagecatalogs.postgresql.cnpg.io is forbidden: User \"system:serviceaccount:cloudnativepg:cnpg-manager\" cannot list resource \"clusterimagecatalogs\" in API group \"postgresql.cnpg.io\" at the cluster scope"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
