### ISSUE TITLE
[Feature]: Add short names on crds

### ISSUE THREAD

**Issue by cnwaldron** [cloudnative-pg/cloudnative-pg#4627]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The crds are missing a shortname and if there's another CRD that exists with the same kind added after cnpg it becomes more challenging in k9s and kubectl to find the resource without the plugin. This becomes very common with the kind "Cluster". 

### Describe the solution you'd like

On the CRDS add the `shortNames:` section with some unique shortnames like:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: clusters.postgresql.cnpg.io
spec:
  group: postgresql.cnpg.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
    shortNames:
    - cnpgcluster  
  ```

### Describe alternatives you've considered

None, this was the easiest solution as it's supported in k8s. 

### Additional context

I've added the following to my clusters.postgresql.cnpg.io CRD in my cluster to check:
```yaml
shortNames:
- cnpgcluster
```
This allowed me to use cnpgcluster in k9s and kubectl to easily find my cnpg clusters. 

### Backport?

N/A

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
