### ISSUE TITLE
[Bug]: Wrong credentials in application secret after promoting a Replica Cluster

### ISSUE THREAD

**Issue by NiccoloFei** [cloudnative-pg/cloudnative-pg#4640]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.1

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Given a source Cluster `cluster-source` that specifies a non-default `user` and `database`:
```
metadata:
  name: cluster-source

bootstrap:
    initdb:
      database: mydb
      owner: myuser
```

And a Replica Cluster `cluster-replica`:
```
metadata:
  name: cluster-replica

bootstrap:
  recovery:
    source: cluster-source

replica:
  enabled: true
  source: cluster-source

externalClusters:
- name: cluster-source
  connectionParameters:
    host: cluster-source-rw.default.svc
    user: myuser
    dbname: mydb
  password:
    name: cluster-source-app
    key: password
```

Premise:
* The “-app” secret is not being generated for Replica Clusters, see [ShouldPgBaseBackupCreateApplicationSecret()](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/api/v1/cluster_types.go#L3052).
* Replica Clusters will skip the application database configuration, see https://cloudnative-pg.io/documentation/1.23/bootstrap/#configure-the-application-database (we are just creating a physical replica of the source cluster)

After promoting `cluster-replica` by setting `replica.enabled` to `false`, now that the cluster is not in replica mode anymore the operator will create a `cluster-replica-app` secret using the default value `app` as `owner` and `database`.

The result is an application secret `cluster-replica-app` which contains an user `app` and a database `app` that do not exist in our newly promoted Cluster.

Also, the operator will unsuccessfully try to reconcile the password for the `app` user, which will continuously fail:
```
{"level":"info","ts":"2024-05-22T15:25:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-replica-basicauth-1","record":{"log_time":"2024-05-22 15:25:38.639 UTC","user_name":"postgres","database_name":"postgres","process_id":"307","connection_from":"[local]","session_id":"664e0e72.133","session_line_num":"1","command_tag":"ALTER ROLE","session_start_time":"2024-05-22 15:25:38 UTC","virtual_transaction_id":"3/396","transaction_id":"0","error_severity":"ERROR","sql_state_code":"42704","message":"role \"app\" does not exist","query":"ALTER ROLE \"app\" WITH PASSWORD 'npWLS0TdGc9Ya9NQER29hlXN6dHq4wvKKeuYQXjJHjrBy8VnltJtx9FoMPnP9oaz'","application_name":"cnpg-instance-manager","backend_type":"client backend","query_id":"0"}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
