### ISSUE TITLE
LDAP search bind cluster seg faults if bindPassword is not specified

### ISSUE THREAD

**Issue by jlong49** [cloudnative-pg/cloudnative-pg#490]
```yaml
# This will segfault without my patch
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: search-bind-ldap-example
spec:
  instances: 1

  postgresql:
    ldap:
      server: 'openldap.default.svc.cluster.local'
      bindSearchAuth:
        bindDN: 'cn=admin,dc=example,dc=com'
        baseDN: 'ou=org,dc=example,dc=com'
  bootstrap:
    initdb:
      database: app
      owner: app

  monitoring:
    enablePodMonitor: true
  # Require 1Gi of space
  storage:
    size: 2Gi
```
