### ISSUE TITLE
[Chore]: restore the possibility to use PVCs as recovery source

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#5030]
### Description

The current API allows specifying the type of object to use as the recovery source. Previously, it was possible to enable recovery from a set of existing Persistent Volume Claims (PVCs). However, this functionality was lost when safety checks using snapshot metadata were introduced.

While snapshots provide comprehensive safety measures, the ability to recover from a set of PVCs remains valuable for troubleshooting and experimentation purposes. Although this method lacks the safety guarantees of snapshots, it can be a crucial tool in non-production environments.

### Proposal

I propose reinstating the ability to use PVCs as a recovery source. This approach will be explicitly unsupported in production and will require that the source PVCs are not actively used by a running PostgreSQL instance.

Restoring this functionality will enhance the flexibility and usability of the recovery process, especially in development and testing scenarios.

**Comment by redbaron** [comment]
I can across this feature by inspecting code, but couldn't find any mention of it in the docs? Is it an experiment CNPG is not committed to support going forward?

**Comment by Routhinator** [comment]
It seems to be there but the actual use of what is in the code seems to either not work or I've missed something: 

```yaml
      bootstrap:
        recovery:
          volumeSnapshots:
            storage:
              name: db-recovery
              kind: PersistentVolumeClaim
              apiGroup: v1
```

```
│ Error: cannot patch "nextcloud-db" with kind Cluster: admission webhook "vcluster.cnpg.io" denied the request: Cluster.cluster.cnpg.io "nextcloud-db" is invalid: spec.bootstrap.recovery.storage: Invalid value: v1.TypedLocalObjectReference{APIGroup:(*string)(0xc001291a00), Kind:"PersistentVolumeClaim", Name:"db-recovery"}: Only VolumeSnapshots and PersistentVolumeClaims are supported
```

**Comment by Routhinator** [comment]
Finally found what it will accept:

```yaml
      bootstrap:
        recovery:
          volumeSnapshots:
            storage:
              name: db-recovery
              kind: PersistentVolumeClaim
              apiGroup: ""
```
