### ISSUE TITLE
[Bug]: Small typo in the pgbench job definition

### ISSUE THREAD

**Issue by danielwestermann** [cloudnative-pg/cloudnative-pg#5039]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

daniel.westermann@dbi-services.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Hi,

not a big deal, but I guess there is typo here:

```
k8s@k8s1:~$ kubectl-cnpg pgbench my-pg-cluster --dry-run
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    pbBenchJob: my-pg-cluster
  name: my-pg-cluster-pgbench-499767
  namespace: default
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        pbBenchJob: my-pg-cluster
```

pbBenchJob -> pgBenchJob ?

Best regards
Daniel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
