### ISSUE TITLE
[Bug]: password authentication failed for user

### ISSUE THREAD

**Issue by droslean** [cloudnative-pg/cloudnative-pg#5072]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

droslean@gmail.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

Created the cluster. The instances are generating error:

```console
{"level":"info","ts":"2024-07-11T10:44:25Z","logger":"postgres","msg":"record","logging_pod":"nordes-postgres-1","record":{"log_time":"2024-07-11 10:44:25.267 UTC","user_name":"nordes","database_name":"nordes","process_id":"117234","connection_from":"10.244.1.79:55590","session_id":"668fb789.1c9f2","session_line_num":"1","command_tag":"authentication","session_start_time":"2024-07-11 10:44:25 UTC","virtual_transaction_id":"5/6556","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"nordes\"","detail":"Connection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
```

### Cluster resource

```shell
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: nordes-postgres
    namespace: nordes
  spec:
    postgresql:
      parameters:
        max_connections: "500"
    instances: 2
    bootstrap:
      initdb:
        database: nordes
        owner: nordes
    storage:
      size: 20Gi
    backup:
      volumeSnapshot:
        className: do-block-storage-snapshot-postgres-class
        labels:
          app: nordes
        online: true
      target: primary
      retentionPolicy: 10d
    monitoring:
      enablePodMonitor: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rc-networks** [comment]
Similar problem here.
Old DB deployed with [bitnamicharts/postgresql](https://github.com/bitnami/charts/tree/main/bitnami/postgresql).
Testing with CNPG:
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-microservice
  namespace: netbox
spec:
  instances: 2
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - netbox
        source:
          externalCluster: postgresql
  storage:
    size: 1Gi
  externalClusters:
    - name: postgresql
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: postgresql-hl.netbox
        user: netbox
        dbname: netbox
      password:
        name: pgpassword-secret
        key: PGPASSWORD
```

Provided the very same password as the OLD one but I am getting:
```
{"level":"info","ts":"2024-10-11T13:45:51Z","logger":"postgres","msg":"record","logging_pod":"cluster-microservice-1","record":{"log_time":"2024-10-11 13:45:51.443 UTC","user_name":"netbox","database_name":"netbox","process_id":"5039","connection_from":"172.25.39.79:52514","session_id":"67092c0f.13af","session_line_num":"1","command_tag":"authentication","session_start_time":"2024-10-11 13:45:51 UTC","virtual_transaction_id":"4/5979","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"netbox\"","detail":"Role \"netbox\" does not exist.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
```

Turning the application back to the OLD Postgres DB works.
Maybe I'm just missing something?
