### ISSUE TITLE
[Bug]: Certificated issued from cert-manager is not being mounted correctly

### ISSUE THREAD

**Issue by kndoni** [cloudnative-pg/cloudnative-pg#5098]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.2

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Self-managed: RKE

### How did you install the operator?

Helm

### What happened?

I have issued an certificate from cert-manager following the documentation steps described [here](https://cloudnative-pg.io/documentation/1.16/certificates/)

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres-server-cert
  namespace: postgresql-operator-test
spec:
  secretName: my-postgres-server-cert
  usages:
    - server auth
  commonName: cnpg-webhook-service.postgresql-operator-test.svc
  dnsNames:
    - cnpg-webhook-service
    - cnpg-webhook-service.postgresql-operator-test
    - cnpg-webhook-service.postgresql-operator-test.svc
    - cnpg-webhook-service.postgresql-operator-test.svc.cluster.local
  issuerRef:
    name: issuer
    kind: ClusterIssuer
    group: cert-manager.io
``` 

And then I have mounted it to the certificates: block section under clusters helm chart 
```
cluster:
  certificates:
     serverTLSSecret: my-postgres-server-cert
     serverCASecret: my-postgres-server-cert
``` 

The certificate is successfully issued because I can see it in the cluster events but again when I try to deploy the helm chart I notice that the cnpg-ca-secret and cnpg-webhook-cert objects are still automatically created by the operator and in the mutatingwebhookconfiguration in the caBundle I can see that still see that Issuer: OU = postgresql-operator-test, CN = cnpg-ca-secret certificate is being used.
Any ideas what might be wrong? 
I should also mention that istio mtls is being used in the cluster.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
