### ISSUE TITLE
[Bug]: self-healing not applied when using the Legacy Synchronous Replication

### ISSUE THREAD

**Issue by NiccoloFei** [cloudnative-pg/cloudnative-pg#5208]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

In the legacy Synchronous Replication method, when the `minSyncReplicas` value is higher than the currently available number of replicas, the operator is supposed to automatically disable Synchronous Replication by emptying `synchronous_standby_names` parameter.

In a scenario where the replica pods are being terminated, the self-healing is not applied because we aren’t properly marking as `notHealthy` the pods holding a `deletionTimestamp`.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-syncreplicas
spec:
  instances: 3

  minSyncReplicas: 1
  maxSyncReplicas: 1

  storage:
    size: 1G
```

### Relevant log output

```shell
instancesStatus:
      healthy:
      - cluster-example-syncreplicas-1
      - cluster-example-syncreplicas-2
      - cluster-example-syncreplicas-3
    phase: Waiting for the instances to become active
    phaseReason: Some instances are not yet active. Please wait.
    readyInstances: 1

This is an extract of the Cluster status. You can notice that all 3 instances are being marked as healthy in instancesStatus, even though we only have 1 readyInstance.

The status the pods is the following:

$ kubectl get pods -o wide
NAME                             READY   STATUS        RESTARTS      AGE   IP            NODE                              NOMINATED NODE   READINESS GATES
cluster-example-syncreplicas-1   1/1     Running       0             50m   10.244.2.5    pg-operator-e2e-v1-30-2-worker3   <none>           <none>
cluster-example-syncreplicas-2   1/1     Terminating   1 (49m ago)   50m   10.244.1.12   pg-operator-e2e-v1-30-2-worker2   <none>           <none>
cluster-example-syncreplicas-3   1/1     Terminating   0             50m   10.244.3.5    pg-operator-e2e-v1-30-2-worker    <none>           <none>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NiccoloFei** [comment]
Adding some steps to reproduce the issue:

1. Apply the following cluster
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-sample
  namespace: openshift-operators
spec:
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 1
  storage:
    size: 1Gi
```
2. Shutdown the workers holding pods `2` and `3` (if you are using Kind `docker stop pg-operator-e2e-v1-30-2-worker2 pg-operator-e2e-v1-30-2-worker3` for example).Make sure both the primary and the operator are scheduled on a worker node that will remain up and running.

3. Wait for pods `2` and `3` to end up in terminating state (this could take several minutes)

4. The status of the Cluster now should be similar to

```
instancesStatus:
      healthy:
      - cluster-sample-1
      - cluster-sample-2
      - cluster-sample-3
    phase: Waiting for the instances to become active
    phaseReason: Some instances are not yet active. Please wait.
    readyInstances: 1
```

5. `kubectl exec -it cluster-sample-1 -- psql -c 'show synchronous_standby_names'` should still contain all the replicas.
