### ISSUE TITLE
[Bug]: refusing to create the primary instance while the latest generated serial is not zero

### ISSUE THREAD

**Issue by rubenz91** [cloudnative-pg/cloudnative-pg#5235]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

mousetraphun@gmail.com

### Version

older in 1.23.x

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

While doing my initial deployment I notice that it always got stuck after completing the "cnpg-cluster-1-initdb", checking the logs of it I see that it start but then it got shutdown. From the operator all that I see is the error of the title of this issue.

### Cluster resource

```shell
Name:             cnpg-cluster-1-initdb-z9clj
Namespace:        cnpg-database
Priority:         0
Service Account:  cnpg-cluster
Node:             node2/192.168.88.202
Start Time:       Wed, 07 Aug 2024 00:42:16 +0000
Labels:           batch.kubernetes.io/controller-uid=afc0e4dd-5485-48d4-a468-c9e5859df8c4
                  batch.kubernetes.io/job-name=cnpg-cluster-1-initdb
                  cnpg.io/cluster=cnpg-cluster
                  cnpg.io/instanceName=cnpg-cluster-1
                  cnpg.io/jobRole=initdb
                  controller-uid=afc0e4dd-5485-48d4-a468-c9e5859df8c4
                  job-name=cnpg-cluster-1-initdb
Annotations:      cni.projectcalico.org/containerID: ada0bee1e7733875ba10ad29ace85779c3b39b9ce1d4ee19e65a63970d1e9e01
                  cni.projectcalico.org/podIP:
                  cni.projectcalico.org/podIPs:
Status:           Succeeded
SeccompProfile:   RuntimeDefault
IP:               172.168.104.3
IPs:
  IP:           172.168.104.3
Controlled By:  Job/cnpg-cluster-1-initdb
Init Containers:
  bootstrap-controller:
    Container ID:    containerd://6254af8b43c4c395038b9da674b484f79ee8b3667455639b03e633a691f406b8
    Image:           ghcr.io/cloudnative-pg/cloudnative-pg:1.23.3
    Image ID:        ghcr.io/cloudnative-pg/cloudnative-pg@sha256:09e65ad4891b4a45052d1334171d86e9ede1625c4cb04d372e3c8699cb4529ae
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      /manager
      bootstrap
      /controller/manager
      --log-level=info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 07 Aug 2024 00:42:16 +0000
      Finished:     Wed, 07 Aug 2024 00:42:16 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /controller from scratch-data (rw)
      /dev/shm from shm (rw)
      /etc/app-secret from app-secret (rw)
      /etc/superuser-secret from superuser-secret (rw)
      /run from scratch-data (rw)
      /var/lib/postgresql/data from pgdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nrtsn (ro)
Containers:
  initdb:
    Container ID:    containerd://ceb1c64fbb50448c0c436e09b1a2bbfcdf9e018d8406eafb0ac9264c1067ca2a
    Image:           ghcr.io/cloudnative-pg/postgresql:15.2
    Image ID:        ghcr.io/cloudnative-pg/postgresql@sha256:4c5c7266afcaffb736e6181d9bb71f05c67cba971afd9aab76207e6be312c546
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      /controller/manager
      instance
      init
      --initdb-flags
      --encoding=UTF8 --lc-collate=C --lc-ctype=C
      --app-db-name
      app
      --app-user
      app
      --log-level=info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 07 Aug 2024 00:43:37 +0000
      Finished:     Wed, 07 Aug 2024 00:43:38 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      PGDATA:        /var/lib/postgresql/data/pgdata
      POD_NAME:      cnpg-cluster-1-initdb
      NAMESPACE:     cnpg-database
      CLUSTER_NAME:  cnpg-cluster
      PGPORT:        5432
      PGHOST:        /controller/run
    Mounts:
      /controller from scratch-data (rw)
      /dev/shm from shm (rw)
      /etc/app-secret from app-secret (rw)
      /etc/superuser-secret from superuser-secret (rw)
      /run from scratch-data (rw)
      /var/lib/postgresql/data from pgdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nrtsn (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cnpg-cluster-1
    ReadOnly:   false
  scratch-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  shm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  superuser-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cnpg-cluster-superuser
    Optional:    false
  app-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cnpg-cluster-app
    Optional:    false
  kube-api-access-nrtsn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  26m   default-scheduler  Successfully assigned cnpg-database/cnpg-cluster-1-initdb-z9clj to node2
  Normal  Pulled     26m   kubelet            Container image "ghcr.io/cloudnative-pg/cloudnative-pg:1.23.3" already present on machine
  Normal  Created    26m   kubelet            Created container bootstrap-controller
  Normal  Started    26m   kubelet            Started container bootstrap-controller
  Normal  Pulling    26m   kubelet            Pulling image "ghcr.io/cloudnative-pg/postgresql:15.2"
  Normal  Pulled     25m   kubelet            Successfully pulled image "ghcr.io/cloudnative-pg/postgresql:15.2" in 1m19.068s (1m19.068s including waiting)
  Normal  Created    25m   kubelet            Created container initdb
  Normal  Started    25m   kubelet            Started container initdb
```

### Relevant log output

```shell
{"level":"info","ts":"2024-08-07T00:43:38Z","logger":"pg_ctl","msg":" done","pipe":"stdout","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","logger":"pg_ctl","msg":"server started","pipe":"stdout","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","msg":"Configuring new PostgreSQL instance","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","msg":"Executing post-init SQL instructions","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","msg":"Executing post-init template SQL instructions","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","msg":"executing Application instructions","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","logger":"pg_ctl","msg":"pg_ctl: server is running (PID: 33)\n/usr/lib/postgresql/15/bin/postgres \"-D\" \"/var/lib/postgresql/data/pgdata\" \"-c\" \"port=5432\" \"-c\" \"unix_socket_directories=/controller/run\" \"-c\" \"listen_addresses=127.0.0.1\"\n","pipe":"stdout","logging_pod":"cnpg-cluster-1-initdb"}
{"level":"info","ts":"2024-08-07T00:43:38Z","msg":"Shutting down instance","logging_pod":"cnpg-cluster-1-initdb","pgdata":"/var/lib/postgresql/data/pgdata","mode":"fast","timeout":null}
{"level":"info","ts":"2024-08-07T00:43:38Z","logger":"postgres","msg":"record","logging_pod":"cnpg-cluster-1-initdb","record":{"log_time":"2024-08-07 00:43:38.598 UTC","process_id":"33","session_id":"66b2c33a.21","session_line_num":"6","session_start_time":"2024-08-07 00:43:38 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received fast shutdown request","backend_type":"postmaster","query_id":"0"}}

{"level":"info","ts":"2024-08-07T01:13:40Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"746f21f2-6437-4faf-8a0d-9a39a5c242cf","latestGeneratedNode":1}
{"level":"info","ts":"2024-08-07T01:13:41Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"52019bfa-ed3d-4fb8-8c1e-a762bc5708d1","latestGeneratedNode":1}
{"level":"info","ts":"2024-08-07T01:13:42Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"60a1ceb5-794c-4192-9397-1b79319e933b","latestGeneratedNode":1}
{"level":"info","ts":"2024-08-07T01:13:43Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"dd832645-ac6e-4cc3-b9ba-3f3f78fc39d0","latestGeneratedNode":1}
{"level":"info","ts":"2024-08-07T01:13:44Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"61cb1bba-7c05-4ba2-82ba-a62885b66dd8","latestGeneratedNode":1}
{"level":"info","ts":"2024-08-07T01:13:45Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cnpg-cluster","namespace":"cnpg-database"},"namespace":"cnpg-database","name":"cnpg-cluster","reconcileID":"7309533e-31ec-4235-b1e2-e63ac8c9f5f6","latestGeneratedNode":1}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danpe** [comment]
I'm having the same issue here 😢

**Comment by kiemlicz** [comment]
facing this too, using following:  
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: postgres-0
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: postgres-1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: postgres-2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  affinity:
    enablePodAntiAffinity: true
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  instances: 1
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      huge_pages: "off"
  storage:
    resizeInUseVolumes: false
    size: 1Gi
    pvcTemplate:
      dataSource:
        apiGroup: v1
        name: postgres-0
        kind: PersistentVolumeClaim
```

**Comment by fm4991** [comment]
same here... after deleting all pods and pvcs of an existing cluster manually the operator doesn't spin up new ones.
k8s 1.29, cnpg operator helm install 0.18.2

**Comment by Lolliip0p** [comment]
I'm facing the same issue. Anyone here come up with a work around for this?

**Comment by nielsweistra** [comment]
Also have trhis same issue. InitJob starts but the cluster is not being (re)deployed. It only happens to a cluster that is being reployed with the same resources.

**Comment by marthydavid** [comment]
In our case deleting the cluster resource and re creating it solved the problem.
Bear in mind we used Retain storageclass for the PVs

**Comment by Lolliip0p** [comment]
Hi @marthydavid When deleting a postgres cluster with a Retain claim on PVs, does this result data lost when the cluster get recreated?

**Comment by marthydavid** [comment]
@Lolliip0p you are correct if you mark the storageclass retain the PV Claim will not be deleted from the volume so in this case the volume will be reused upon recreation of the clusters.postgresql.cnpg.io resource.
But you need to use this type of storageclass beforehand.

In the storageclass spec there's this field:
**reclaimPolicy: Retain**

Example: 
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  name: openebs-zfspv
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: data
  shared: "no"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

**Comment by PrivatePuffin** [comment]
I'm getting this quite often even when I completely remove the PVC, PV, Cluster-object and the complete helm chart of the affected application.

Seems to be quite related to latest releases of CNPG to be frank

**Comment by PrivatePuffin** [comment]
Well I now have to helm charts, that I completely nuke every trace off.
And yet every damn reinstall it ends up with this stupid error.

Its so bad and untraceable that I'm even rethinking my choice of going for CNPG to begin with.
I am lucky this wasn't a production cluster. But otherwise I would be royally screwed.

@sxd @mnencia 
Can this PLEASE be triaged. This is for sure not limited to people with remaining PVs or PVCs.

**Comment by livelace** [comment]
quick glance showed that cnpg [heavily relies](https://github.com/cloudnative-pg/cloudnative-pg/blob/ebe20200dee0bd8ed357ab459b6e5fdc30d12855/internal/controller/cluster_restore.go#L241) on [annotations](https://github.com/cloudnative-pg/cloudnative-pg/blob/ebe20200dee0bd8ed357ab459b6e5fdc30d12855/internal/controller/cluster_restore.go#L241) in its logic. 
i got the same err msg when i precreated pvc and cnpg cannot find appropritate annotation.
i let cnpg create pvc itself and cluster is running now.

**Comment by PrivatePuffin** [comment]
> quick glance showed that cnpg [heavily relies](https://github.com/cloudnative-pg/cloudnative-pg/blob/ebe20200dee0bd8ed357ab459b6e5fdc30d12855/internal/controller/cluster_restore.go#L241) on [annotations](https://cloudnative-pg.io/documentation/1.23/labels_annotations/) in its logic. i got the same err msg when i precreated pvc and cnpg cannot find appropritate annotation. i let cnpg create pvc itself and cluster is running now.

I have no PVC or PV, everything is 100% a clean slate, so it should be creating them.
This error shouldnt show if there is no PVC or PV afaik.

**Comment by livelace** [comment]
>I have no PVC or PV, everything is 100% a clean slate, so it should be creating them.
This error shouldnt show if there is no PVC or PV afaik.

probably, idk :) but code [shows](https://github.com/cloudnative-pg/cloudnative-pg/blob/ebe20200dee0bd8ed357ab459b6e5fdc30d12855/internal/controller/cluster_create.go#L1048) why it could happen. 

maybe some orphans objects are still existed. 
you can check it easily with something like this:
```shell
kubectl get pvc -A | grep cnpg.io 
```

**Comment by PrivatePuffin** [comment]
> > I have no PVC or PV, everything is 100% a clean slate, so it should be creating them.
> > This error shouldnt show if there is no PVC or PV afaik.
> 
> probably, idk :) but code [shows](https://github.com/cloudnative-pg/cloudnative-pg/blob/ebe20200dee0bd8ed357ab459b6e5fdc30d12855/internal/controller/cluster_create.go#L1048) why it could happen.
> 
> maybe some orphans objects are still existed. you can check it easily with something like this:
> 
> ```shell
> kubectl get pvc -A | grep cnpg.io 
> ```

When I say no objects exist, I mean it.
NONE.

Including their namespace.

**Comment by vacquah** [comment]
I have run into this issue as well - cant reinstall cnpg cluster. So there is no fix / workaround at the moment ?

**Comment by PrivatePuffin** [comment]
I found at least one case where this could be reproduced somewhat:
Cases where somehow the storageClass was invalid and it wasn't creating PVCs might, in some cases, not start as well with this error.

**Comment by vacquah** [comment]
> I found at least one case where this could be reproduced somewhat: Cases where somehow the storageClass was invalid and it wasn't creating PVCs might, in some cases, not start as well with this error.

@PrivatePuffin  Did you manage to get it to work? In my case, I am using Longhorn. I see the storage being provisioned on longhorn, then they are detached again after the initdb fails to provision. Worked perfectly before. But I decided to redo the cnpg install - uninstalled everything , including all storage items and namespaces. Ensured there was nothing left and rebooted the cluster. Still cant get it installed again. Always goes into an error loop during the provision of the first node in the cnpg cluster.

**Comment by PrivatePuffin** [comment]
@vacquah Can you give me the name of your storageClass?

**Comment by vacquah** [comment]
> [@vacquah](https://github.com/vacquah) Can you give me the name of your storageClass?

longhorn-postgres-storage

**Comment by vacquah** [comment]
Is there no solution to this? I still cant install.

**Comment by black-snow** [comment]
Same here, cordoned the nodes, deleted pods + pvcs, -> `refusing to create the primary instance while the latest generated serial is not zero`

Nuking the cluster as well helped.

**Comment by cgroschupp** [comment]
In my case, this happens when I manually delete the pvc/pv.
See also: https://github.com/cloudnative-pg/cloudnative-pg/blob/b3b6dbe7899d27dd65b42d4ecd89c9d0c3d780b0/internal/controller/cluster_create.go#L1063

If you really know what you are doing, you can override the lastGeneratedNode.
```sh
kubectl patch clusters.postgresql.cnpg.io mydb --type=merge --subresource status --patch 'status: {latestGeneratedNode: 0}'
```
Than the cluster comes back for me.

**Comment by PrivatePuffin** [comment]
> In my case, this happens when I manually delete the pvc/pv. See also:
> 
> [cloudnative-pg/internal/controller/cluster_create.go](https://github.com/cloudnative-pg/cloudnative-pg/blob/b3b6dbe7899d27dd65b42d4ecd89c9d0c3d780b0/internal/controller/cluster_create.go#L1063)
> 
> Line 1063 in [b3b6dbe](/cloudnative-pg/cloudnative-pg/commit/b3b6dbe7899d27dd65b42d4ecd89c9d0c3d780b0)
> 
>  contextLogger.Info("refusing to create the primary instance while the latest generated serial is not zero", 

I can confirm this, although I'm not sure why deleting and recreating the cluster resource wouldn't solve it.

> If you really know what you are doing, you can override the lastGeneratedNode.
> 
> kubectl patch clusters.postgresql.cnpg.io mydb --type=merge --subresource status --patch 'status: {latestGeneratedNode: 0}'
> Than the cluster comes back for me.

This is good shit!

**Comment by gbartolini** [comment]
I had totally missed this issue. We will look into it ASAP. Thanks.

**Comment by gbartolini** [comment]
> facing this too, using following:
> 
> ```
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: postgres-0
> spec:
>   capacity:
>     storage: 1Gi
>   accessModes:
>     - ReadWriteOnce
>   hostPath:
>     path: /mnt/postgres-data-0
> ---
> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: postgres-0
> spec:
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: ""
>   volumeName: postgres-0
>   resources:
>     requests:
>       storage: 1Gi
> ... <snipped>
> ```

Why do you create the storage before-hand instead of using dynamic provisioning?

**Comment by PrivatePuffin** [comment]
> Why do you create the storage before-hand instead of using dynamic provisioning?

Might be best to ignore this weird setup when bug tracing this.
As most of the other people affected here have the same issue without weird customizations.

**Comment by PrivatePuffin** [comment]
> I can see why creating storage before hand can make sense in some scenarios...

Can we please just **all** ignore this?
As it has absolutely zero to do with the issue.

Its rather annoying getting notifications for comments like these that have nothing really to do with the issue itself.

**Comment by aroundthfur** [comment]
Are there any updates on this issue?
We also see this while doing volume restores as a disaster recovery procedure. Our use case is to deploy a new cluster, hibernate, remove a new PV/PVC, load the PV/PVC from the backup, and re-enable the cluster (by un-hibernating).

As it stands now, it's not working and the workaround from @cgroschupp is not working for us.

**Comment by atanev** [comment]
we are also facing this issue with version `1.24.1` after deleting the PVC, scenario is identical with others. Reporting it as well hoping it will help with prioritization if knowing more are affected.

**Comment by jamesandariese** [comment]
I've run into this while restoring as well and the issue causing the orphaned PVCs to not be adopted by a new mydb-1 is because I had neglected to restore the labels and annotations along with the PVC.

If you're affected by this, you'll see in your cnpg controller logs that it can't find orphans: `no orphan PVCs found, skipping the restored cluster reconciliation`

```yaml
  annotations:
    cnpg.io/nodeSerial: "1"
    cnpg.io/operatorVersion: 1.24.0
    cnpg.io/pvcStatus: ready
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cnpg.io/cluster: mydb
    cnpg.io/instanceName: mydb-1
    cnpg.io/instanceRole: primary
    cnpg.io/pvcRole: PG_DATA
    role: primary
  name: mydb-1
  namespace: mydb
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: Cluster
    name: mydb
    uid: f1111111-111a-111f-111d-11111111111f
```

**Comment by fad3t** [comment]
I had a similar issue where the operator says it won't create the primary instance due to the generated serial not being 0.

In my case, this was due to a namespace storage quota which blocked the creation of the PVCs.
Unfortunately this information is not reported into the CNPG cluster status; I found it in the logs of the CNPG operator (besides a ton of other log messages). This might be something to improve?

Also, it seems the operator wasn't able to recover after the storage quota was increased; I had to patch the `latestGeneratedNode` value to 0 as described above to get it completely fixed.

**Comment by black-snow** [comment]
Running into this again.

**Comment by rosscdh** [comment]
yeah seems to be longhorn related.. 1.25.1 still completely unstartable.

**Comment by smiggiddy** [comment]
Fwiw, using Longhorn after applying the annotation and then patching it with the workaround above worked for me.
```
  annotations:
    cnpg.io/nodeSerial: "1"
    cnpg.io/operatorVersion: 1.24.0
    cnpg.io/pvcStatus: ready
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cnpg.io/cluster: mydb
    cnpg.io/instanceName: mydb-1
    cnpg.io/instanceRole: primary
    cnpg.io/pvcRole: PG_DATA
    role: primary
```
