### ISSUE TITLE
[Bug]: kubectl-cnpg v1.23.3 status command broken

### ISSUE THREAD

**Issue by HaveFun83** [cloudnative-pg/cloudnative-pg#5247]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.2

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

Since kubectl-cnpg plugin version 1.23.3 the status command can not extract the status from the postgres-pods

Cluster is running on cnpg v1.23.2
```
Cluster Summary
Name:                postgres-hedgedoc
Namespace:           hedgedoc
PostgreSQL Image:    cloudnative-pg/postgresql:14.8-6
Primary instance:    postgres-hedgedoc-4
Primary start time:  2024-06-18 14:04:24 +0000 UTC (uptime 1176h32m31s)
Status:              Cluster in healthy state 
Instances:           2
Ready instances:     2

Certificates Status
Certificate Name               Expiration Date                Days Left Until Expiration
----------------               ---------------                --------------------------
postgres-hedgedoc-ca           2024-08-17 00:10:20 +0000 UTC  10.40
postgres-hedgedoc-replication  2024-08-17 00:10:36 +0000 UTC  10.40
postgres-hedgedoc-server       2024-08-17 00:10:28 +0000 UTC  10.40

Continuous Backup status
First Point of Recoverability:  2024-07-27T02:01:06Z
No Primary instance found
Physical backups
Primary instance not found

Streaming Replication status
Primary instance not found

Unmanaged Replication Slot Status
No unmanaged replication slots found

Managed roles status
No roles managed

Tablespaces status
No managed tablespaces

Pod Disruption Budgets status
Name                       Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----                       ----     -------------  ---------------  -----------------------  -------------------
postgres-hedgedoc-primary  primary  1              1                1                        0

Instances status
Name                 Database Size  Current LSN  Replication role  Status              QoS         Manager Version  Node
----                 -------------  -----------  ----------------  ------              ---         ---------------  ----
postgres-hedgedoc-4  -              -            -                 ServiceUnavailable  Guaranteed  -                worker-2
postgres-hedgedoc-5  -              -            -                 ServiceUnavailable  Guaranteed  -                worker-1

Error(s) extracting status
-----------------------------------
the server is currently unable to handle the request (get pods http:postgres-hedgedoc-4:8000)
the server is currently unable to handle the request (get pods http:postgres-hedgedoc-5:8000)
```

With plugin version 1.23.2 everything is shown as expected.

We have the following networkpolicies in place which are derived from the cnpg-docs [example](https://cloudnative-pg.io/documentation/1.23/samples/networkpolicy-example.yaml)
```
Clusterwide deny all
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-management
  namespace: hedgedoc
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres-operator
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - port: status
      protocol: TCP
    - port: metrics
      protocol: TCP
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-hedgedoc
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-cluster
  namespace: hedgedoc
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: postgres-hedgedoc
    ports:
    - port: postgresql
      protocol: TCP
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-hedgedoc
  policyTypes:
  - Ingress
  ```
Maybe this PR broke the status requests https://github.com/cloudnative-pg/cloudnative-pg/pull/4974?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
@HaveFun83 Yes, now the status it's retrieved using a proxy so the user executing the command needs permissions to proxy the status port, otherwise, it will not be able to get the status

**Comment by HaveFun83** [comment]
i ran this as cluster-admin and got the error.
I also tried to allow all ingress connection from the kube-system namespace which also not worked.
It only works when i allow allow ingress traffic within the network-policy but this make no sense as this will open the connection from everywhere and we have to stay within our security and compliance rules

**Comment by achanda** [comment]
@sxd are the new permission requirements documented somewhere?

**Comment by sxd** [comment]
@achanda no that I remember only the PR that is there https://github.com/cloudnative-pg/cloudnative-pg/pull/4974

**Comment by sxd** [comment]
@HaveFun83 do you have news on this? adding permission fixed the issue? or it was a network issue ? can you elaborate a bit more here ?

**Comment by HaveFun83** [comment]
@sxd Thanks for your support. Don't know which permission i need to add to the cluster-admin user?  
Currently the status command only works when i allow all ingress traffic towards cluster pods, but this is not possible within our environment.

As workaround i downgrade the plugin to v1.23.2 which work as expected.
Any help or tips are greatly appreciated

I can try to reproduce this issue within an dev environment?

**Comment by sxd** [comment]
@HaveFun83 well, the ingress part will make sense since the new version doesn't use pod/exec to get into the pod land execute a command but instead proxy the port of the service to restrict the access only to that.
It will be very helpful if you can reproduce the issue so we can look into this reproduce and work in a fix.
On the other hand I'm going to create a ticket to handle the issue mentioned by @achanda that we don't have documentation for the permissions.

**Comment by HaveFun83** [comment]
As we use calico we implemented the following globalnetworkpolicy to allow the cnpg plugin proxy traffic to every cnpg cluster on the status port
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cnpg-status
spec:
  order: 1
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system", "calico-apiserver"}
  types:
    - Ingress
  ingress:
    - action: Allow
      destination:
        selector: has(cnpg.io/cluster)
        ports:
          - 8000
      protocol: TCP
      source:
        nets:
          - "<control-plane projectcalico.org/IPv4IPIPTunnelAddr>/32"
          ...

```
From our side this issue is resolved.

**Comment by till** [comment]
Had a look at this again this morning, hoping I had overseen something. But haven't found anything so far.

- as soon as I remove my own network policy (which includes the operator), the status command is working
- when I apply the [sample policy](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/networkpolicy-example.yaml), the command is broken

**Comment by HaveFun83** [comment]
@till can you show your network-policy? Which CNI do you use?

**Comment by till** [comment]
Using Calico, and the network policy is the sample in the repo:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: cluster-example # The label value must be the cluster name
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system # Namespace where the operator is deployed
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg # Matches the Operator pod
      ports:
        - port: 8000
        - port: 5432
```

I only changed the db instance name.
