### ISSUE TITLE
[Bug]: Switchover gets stuck in `Primary instance is being restarted in-place` for Postgres 12

### ISSUE THREAD

**Issue by YanniHu1996** [cloudnative-pg/cloudnative-pg#5268]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

This happens when doing a switchover in a replica cluster, 

After switchover manually by the following command
```sh
k cnpg promote cluster-replica-tls 2
```
The instance manager reconciling the new designated primary changes `primary_conninfo` in which `pending_restart` is true for Postgres 12. The cluster reconciliation detects the new designated primary is on the pending restart, it marks the cluster's phase as `Primary instance is being restarted in-place`  and waits for the instance manger to perform the restart . Unfortunately, the instance manager can only restart the real primary, the designated primary is skipped. Therefore, the cluster' phase is always in `Primary instance is being restarted in place` 

```sh
k exec po/cluster-replica-tls-2 -it -- psql -tAc 'select name from pg_settings where pending_restart;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
primary_conninfo
primary_slot_name
```

https://github.com/cloudnative-pg/cloudnative-pg/blob/5ab2763451a6c20bab6b89b234367fe1eacd0355/internal/management/controller/instance_controller.go#L309

### Cluster resource

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:12.19
  storage:
    size: 1Gi



apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-replica-tls
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:12.19
  bootstrap:
    pg_basebackup:
      source: cluster-example

  replica:
    primary: cluster-example
    source: cluster-example

  storage:
    size: 1Gi

  externalClusters:
  - name: cluster-example
    connectionParameters:
      host: cluster-example-rw.default.svc
      user: streaming_replica
      sslmode: verify-full
      dbname: postgres
    sslKey:
      name: cluster-example-replication
      key: tls.key
    sslCert:
      name: cluster-example-replication
      key: tls.crt
    sslRootCert:
      name: cluster-example-ca
      key: ca.crt
```

### Relevant log output

```shell
{"level":"info","ts":"2024-08-12T07:05:00Z","msg":"Restarting primary instance in-place","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-replica-tls","namespace":"default"},"namespace":"default","name":"cluster-replica-tls","reconcileID":"890b265e-9352-4e69-8975-6468db7834e8","primaryPod":"cluster-replica-tls-2","reason":"Postgres needs a restart to apply some configuration changes"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
