### ISSUE TITLE
Add missing pg_hba conf to ssl connection example

### ISSUE THREAD

**Issue by phisco** [cloudnative-pg/cloudnative-pg#527]
The example in the [docs](https://cloudnative-pg.io/documentation/1.16/ssl_connections/) is not working due to a missing pg_hba entry on the cluster enabling the user app to authenticate using certificates.
The following cluster is working:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  postgresql:
    pg_hba:
      - hostssl app all all cert

  storage:
    size: 1Gi
```
