### ISSUE TITLE
[Feature]: Add `--control-plane` option to plugin `install generate`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5270]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The `cnpg install generate` command provides some basic options to customise the default installation, such as replicas. We don't provide an easy way to patch the node selector and tolerations to deploy the operator in the control plane.

### Describe the solution you'd like

We should add an option `--control-plane` that adds to the deployment the following settings to the `Deployment`:

```yaml
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        value: NoSchedule          
```

### Describe alternatives you've considered

We can use helm or OLM for this purpose, but this option could provide a useful shortcut.

We could also enable specific options for the command, such as `--node-selector` (the initial scope of this ticket) and `--tolerations`, but it would complicate unnecessarily the user interface. If needed, these can be added in the future, but the imminent goal was to ensure that the operator is installed in a control plane node.

### Additional context

N/A

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
The patch does what I asked, but it is not sufficient to help me deploy the operator on the control plane - which is the driver for this option. My suggestion is to change the option into `--control-plane` to require proper affinity and tolerations to be deployed there, in particular:

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
```

Can you please make this change @armru? Thanks.
