### ISSUE TITLE
[Bug]: imagePullSecrets is not set in Pod spec for Pooler

### ISSUE THREAD

**Issue by PhantomPhreak** [cloudnative-pg/cloudnative-pg#5300]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

pavel.korchagin@nebius.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

We do have `PULL_SECRET_NAME` set in the [operator configuration](https://cloudnative-pg.io/documentation/1.22/operator_conf/) and expect it to be using for pulling images.
For cluster instances everything works fine, but Pooler's pod spec has no `imagePullSecrets` when poolers are deployed, causing inability to pull the image:

**Expected:**
```
  containers:
    - name: pgbouncer
      image: >-
        <image>
      command:
        - /controller/manager
        - pgbouncer
        - run
 ...
    seccompProfile:
      type: RuntimeDefault
  imagePullSecrets:
    - name: postgresql-pooler-ro-pull
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
...
```

**Actual:**
```
  containers:
    - name: pgbouncer
      image: >-
        <image>
      command:
        - /controller/manager
        - pgbouncer
        - run
 ...
    seccompProfile:
      type: RuntimeDefault
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
...
```

At that time, a `Secret` named `postgresql-pooler-ro-pull` are present in the Namespace, restarting Pooler's pod or Pooler's Deployment fixes the issue.

It looks like operator creating Pooler's Deployment before the pull-secret, so pods has no `imagePullSecrets` set.

### Relevant log output

```shell
{"level":"info","ts":"2024-08-15T13:53:49Z","msg":"Creating deployment","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler","Pooler":{"name":"postgresql-pooler-ro","namespace":"some-namespace"},"namespace":"some-namespace","name":"postgresql-pooler-ro","reconcileID":"b9cbb6b0-c695-447e-b0f6-c4ecfa08b2cc"}
{"level":"debug","ts":"2024-08-15T13:53:49Z","logger":"pooler_pull_secret","msg":"creating image pull secret for service account","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler","Pooler":{"name":"postgresql-pooler-ro","namespace":"some-namespace"},"namespace":"some-namespace","name":"postgresql-pooler-ro","reconcileID":"b9cbb6b0-c695-447e-b0f6-c4ecfa08b2cc","caller":"internal/controller/pooler_update.go:304"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
