### ISSUE TITLE
Please update documents for New Feature disabledDefaultServices implementation / managed services

### ISSUE THREAD

**Issue by anaskhantpl** [cloudnative-pg/cloudnative-pg#5381]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

anaskhan.tpl@outlook.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.3

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

I have disabled the default svc & using custom svc for my cluster.

**cluster.yaml:**

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  storage:
    size: "1Gi"
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
```
**O/P:**
```
root@k3d:/home/anas# kubectl get pod
NAME                                   READY   STATUS    RESTARTS   AGE
cnpg-cloudnative-pg-5c96f6fc67-68wz2   1/1     Running   0          23h
cluster-1                              1/1     Running   0          30m
cluster-2                              1/1     Running   0          29m
cluster-3                              1/1     Running   0          29m
```
### Custom SVC
**cluster-2-svc.yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: cluster-2
  labels:
    app: cluster
spec:
  type: ClusterIP 
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: cluster
```

**cluster-3-svc.yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: cluster-3
  labels:
    app: cluster
spec:
  type: ClusterIP 
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: cluster
```
**o/p:**
```
root@k3d:/home/anas# kubectl get svc
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP                                   PORT(S)                         AGE
kubernetes             ClusterIP      10.43.0.1       <none>                                        443/TCP                         15d
cnpg-webhook-service   ClusterIP      10.43.248.207   <none>                                        443/TCP                         23h
cluster-3              ClusterIP      10.43.55.127    <none>                                        5432/TCP                        32m
cluster-2              ClusterIP      10.43.170.112   <none>                                        5432/TCP                        32m
cluster-rw             ClusterIP      10.43.23.172    <none>                                        5432/TCP                        32m
```
I am using pgpool for loadbalancing, able to telnet `rw` service which generated by operator but others refusing:
```
root@pgpool-6c4975696-jqpxn:/# telnet cluster-rw.default 5432
Trying 10.43.23.172...
Connected to cluster-rw.default.
Escape character is '^]'.
^CConnection closed by foreign host.

root@pgpool-6c4975696-jqpxn:/# telnet cluster-2.default 5432
Trying 10.43.170.112...
telnet: Unable to connect to remote host: Connection refused
```
everything is running on default namespace. Is there any additional parameters do we need to pass with custom svc?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
