### ISSUE TITLE
[Bug]: Unable to recover backup data from s3 storage

### ISSUE THREAD

**Issue by odev-swe** [cloudnative-pg/cloudnative-pg#5434]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

odevswe@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Recently i deployed cnpg into my self hosted k3s cluster with the following values.yml
```
apiVersion: v1
data:
  password: b21zb21zMTIz
  username: b21z
  ACCESS_KEY_ID: xxxx
  ACCESS_SECRET_KEY: xxxx
  AWS_REGION: xxxx
kind: Secret
metadata:
  name: cnpg-cluster-app-user
  namespace: cnpg
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  # backup:
  #   barmanObjectStore:
  #     serverName: "cnpg-cluster"
  #     destinationPath: "s3://odev-pg"
  #     s3Credentials:
  #       accessKeyId:
  #         key: ACCESS_KEY_ID
  #         name: cnpg-cluster-app-user
  #       secretAccessKey:
  #         key: ACCESS_SECRET_KEY
  #         name: cnpg-cluster-app-user
  #     wal:
  #       compression: "bzip2"
  #       encryption: "AES256"
  #     data:
  #       compression: "bzip2"
  #       encryption: "AES256"
  #   retentionPolicy: "30d"
  #   target: "prefer-standby"

  externalClusters:
    - name: cluster-backup
      barmanObjectStore:
        serverName: "cnpg-cluster"
        destinationPath: "s3://odev-pg"
        wal:
          compression: "bzip2"
          encryption: "AES256"
        data:
          compression: "bzip2"
          encryption: "AES256"
        s3Credentials:
          region:
            key: AWS_REGION
            name: cnpg-cluster-app-user
          accessKeyId:
            key: ACCESS_KEY_ID
            name: cnpg-cluster-app-user
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: cnpg-cluster-app-user

  instances: 3
  storage:
    size: 1Gi

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      log_statement: all
      auto_explain.log_min_duration: '10s'

    pg_hba:
      - host all all 10.244.0.0/16 md5

  bootstrap:
    # initdb:
    #   database: oms-db
    #   owner: oms
    #   secret:
    #     name: cnpg-cluster-app-user
    recovery:
      source: cluster-backup
```

but unfortunely it unable to recover due to some error: "error":"no target backup found"

### Relevant log output

```shell
{"level":"info","ts":"2024-09-04T01:26:09Z","msg":"Recovering from external cluster","logging_pod":"cnpg-cluster-1-full-recovery","sourceName":"cluster-backup"}
{"level":"error","ts":"2024-09-04T01:26:10Z","msg":"Error while restoring a backup","logging_pod":"cnpg-cluster-1-full-recovery","error":"no target backup found","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:163\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:92\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:63\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvin319** [comment]
I'm observing a similar issue as well; the CNPG version is `1.23.3` in my case.

**Comment by odev-swe** [comment]
@alvin319 yup i was trying to figure whole day but still none of the solutions works yet...

**Comment by rubasace** [comment]
I faced the same issue today while getting my head around backups/recoveries. In my case, the issue was that the `externalClusters.name` was not matching the backup name  (the folder name on my S3 storage). Looking at your manifest, is there any chance the backup is called `cnpg-cluster` and by setting the `externalClusters.name` field to that it works?

I'm not sure if that's the expected value, I just came across this issue while troubleshooting and felt like leaving my findings here to try to help.

**Comment by alvin319** [comment]
@odev-swe, this issue is resolved for me because I need to run an ad-hoc / scheduled backup to generate the base files and recover the DB along with the WAL files. See [this](https://cloudnative-pg.io/documentation/1.16/backup_recovery/#on-demand-backups).

**Comment by 99hops** [comment]
I have the same problem on 1.24.1

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: boostrap-demo-cnpg
  namespace: uat
spec:
  instances: 3
  storage:
    storageClass: local-path
    size: 10Gi
  bootstrap:
    recovery:
     source: postgresql-uat01
  externalClusters:
    - name: postgresql-uat01
      barmanObjectStore:
        endpointURL: "http://minio.storage.svc"
        destinationPath: "s3://postgresql-uat/postgresql-uat01" #s3://bucket/last-server-name-to-restore
        s3Credentials:
          accessKeyId:
            name: cnpg-barman-s3
            key: CONSOLE_ACCESS_KEY
          secretAccessKey:
            name: cnpg-barman-s3
            key: CONSOLE_SECRET_KEY
        wal:
          maxParallel: 8
```
![Image](https://github.com/user-attachments/assets/c22efd1a-1772-4c97-a25c-dfba80452bb6)

**Comment by viallikavoo** [comment]
For anyone encountering this on Azure blob storage, you need to use the full path upto the container name under :
```
  externalClusters:
      - name: <blob-prefix-on-azure-storage>
        barmanObjectStore:
          destinationPath: https://${PG_PRIMARY_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/backups # This is the path of the storage account including container name
```
``

**Comment by davinkevin** [comment]
This logic with `extrnalclusters[].name` is over complicated. As an operator, I'd expect the configuration of the restore block to take the same input as the backup block. 

With it, no headeachs when we recover, we "just" have to copy/paste the block. 

Thank you to everyone in this thread for solutiosn and explanation.

**Comment by yz4322gly** [comment]
> I faced the same issue today while getting my head around backups/recoveries. In my case, the issue was that the `externalClusters.name` was not matching the backup name (the folder name on my S3 storage). Looking at your manifest, is there any chance the backup is called `cnpg-cluster` and by setting the `externalClusters.name` field to that it works?
> 
> I'm not sure if that's the expected value, I just came across this issue while troubleshooting and felt like leaving my findings here to try to help.

老哥,你这个方法好用,就是这个问题. 
  externalClusters:
    - name: pg-instance 要写成实际的文件夹的名称才可以

**Comment by NWBY** [comment]
@gbartolini apologies for tagging you directly. Is this something the team is aware of as the bot seems to have marked it as stale

**Comment by sashokbg** [comment]
Hello, I had the same issue and managed to find the solution - it was related to me providing bad "targetTime".

If you check the image below:

1) Is the name of the base backup that the operator created, it uses the timestamp when the backup has started
2) Is the content of the backup.info that confirms it
3) Is the timestamp when the backup has finished (it took 14 seconds in my case)

![Image](https://github.com/user-attachments/assets/3a7792b6-6ca7-44de-9dcc-41ee912a1b9a)

So the solution was to change my target time

from
  targetTime: "2025-05-01 22:11:**36**.00000+02:00" 

To

  targetTime: "2025-05-01 22:11:**47**.00000+02:00" 

The target time needs to be AFTER the backup has finished. It is kinda logical if you think about it of course.

**Comment by ERRDOX** [comment]
There is a statement in the doc which says  
 "Important
    By default, the `recovery` method strictly uses the `name` of the
    cluster in the `externalClusters` section as the name of the main folder
    of the backup data within the object store. This name is normally reserved
    for the name of the server. You can specify a different folder name
    using the `barmanObjectStore.serverName` property." 

you have to add your previous cluster to change the default "name" 
  externalClusters:

  - name: objectStoreRecoveryCluster
    barmanObjectStore:
      destinationPath: "s3://cnpg-cluster-production"
      endpointURL: "http://192.168.0.1:9000"
      serverName: cnpg-old # previous cluster name
      s3Credentials:
        accessKeyId:
          name: s3-postgres-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-postgres-backup
          key: SECRET_ACCESS_KEY

**Comment by ERRDOX** [comment]
## Regarding cluster recovery from object store

Based on the CloudNativePG documentation, there's an important note about recovery configuration:

> **Important**
> 
> By default, the recovery method strictly uses the `name` of the cluster in the `externalClusters` section as the name of the main folder of the backup data within the object store. This name is normally reserved for the name of the server. You can specify a different folder name using the `barmanObjectStore.serverName` property.

You need to add your previous cluster configuration to change the default "name". Here's an example:

```yaml
externalClusters:
  - name: objectStoreRecoveryCluster
    barmanObjectStore:
      destinationPath: "s3://cnpg-new"
      endpointURL: "http://192.168.0.1:9000"
      serverName: cnpg-old # previous cluster name
      s3Credentials:
        accessKeyId:
          name: s3-postgres-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-postgres-backup
          key: SECRET_ACCESS_KEY

**Comment by mwienk** [comment]
I got this error when I tried a recovery on a cluster that had image set to `ghcr.io/cloudnative-pg/postgresql:16.1` while the live version had `ghcr.io/cloudnative-pg/postgresql:17.0`. Setting the target version to 17.0 fixed it for me.

**Comment by NataliFilipova** [comment]
Hi Team,

I’m facing a critical issue that could have been disastrous if this had occurred in production. Fortunately, it happened in staging, but it's still alarming.

I cannot restore my old CNPG cluster from backup.

I’ve been trying for two days without success.

The cluster is only 1 month old.

It fails to detect the available backups from the object store.

kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: recoverytest4
  namespace: cnpg-tests
spec:
  instances: 3
  bootstrap:
    recovery:
      source: nameoftheoldcluster
      recoveryTarget:
        backupID: 20250501T193001      
  storage:
    size: 40Gi
  externalClusters:
    - name: nameoftheoldcluster
      barmanObjectStore:
        destinationPath: 's3://cnpg-tests-db-backups/'
        endpointCA:
          key: ca.crt
          name: truenas-ca
        endpointURL: 'https://truenas.dev.local:9000'
        s3Credentials:
          accessKeyId:
            key: ACCESS_KEY_ID
            name: truenas-s3-credentials
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: truenas-s3-credentials
        wal:
          maxParallel: 8

What I’ve Tried:
Creating a new cluster, my backup is in the same bucket. And it works, but my old doesn't. 
If anyone has encountered this issue or has ideas for recovery, I’d appreciate any input. This highlights a serious reliability concern in our disaster recovery process that we need to address urgently before this happens in production.

Thanks,
Natali

**Comment by NataliFilipova** [comment]
Hello,

The issue occurs when you're using ClusterImageCatalog and your target version is, for example, 17.5, while the default version in the operator is 17.2. This version mismatch causes a conflict. To avoid it, you need to specify ClusterImageCatalog in the restore YAML as well.

It would be helpful to include this in the documentation.

kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: recovery-test123
  namespace: nameofthenamespace
spec:
  **imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 17
    name: postgresql**
  instances: 3
  bootstrap:
    recovery:
      source: test
      recoveryTarget:
        backupID: 20250626T075315     
  storage:
    size: 40Gi
  externalClusters:
    - name: test
      barmanObjectStore:
        destinationPath: 's3://projectname/'
        endpointCA:
          key: ca.crt
          name: truenas-ca
        endpointURL: 'https://truenas.dev.local:9000'
        s3Credentials:
          accessKeyId:
            key: ACCESS_KEY_ID
            name: truenas-s3-credentials
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: truenas-s3-credentials
        wal:
          maxParallel: 8

**Comment by zdeneklapes** [comment]
Hello, I am using version 1.26.1, but I am unable to recover from a backup if I use targetTime; however, I can recover without using targetTime.

**Comment by sashokbg** [comment]
> Hello,
> 
> The issue occurs when you're using ClusterImageCatalog and your target version is, for example, 17.5, while the default version in the operator is 17.2. This version mismatch causes a conflict. To avoid it, you need to specify ClusterImageCatalog in the restore YAML as well.
> 
> It would be helpful to include this in the documentation.
> 
> kind: Cluster apiVersion: postgresql.cnpg.io/v1 metadata: name: recovery-test123 namespace: nameofthenamespace spec: **imageCatalogRef: apiGroup: postgresql.cnpg.io kind: ClusterImageCatalog major: 17 name: postgresql** instances: 3 bootstrap: recovery: source: test recoveryTarget: backupID: 20250626T075315 storage: size: 40Gi externalClusters: - name: test barmanObjectStore: destinationPath: 's3://projectname/' endpointCA: key: ca.crt name: truenas-ca endpointURL: 'https://truenas.dev.local:9000' s3Credentials: accessKeyId: key: ACCESS_KEY_ID name: truenas-s3-credentials secretAccessKey: key: ACCESS_SECRET_KEY name: truenas-s3-credentials wal: maxParallel: 8

This solved my issue. I had recently migrated my image catalog version to postgis, but my restore cluster was using   imageName: "ghcr.io/cloudnative-pg/postgresql:15.12". Images mismatch really did cause the problem !!

How did you even debug this issue ?

**Comment by NataliFilipova** [comment]
I had no other option—I had to restore the database.... trying for three days. It was fortunate that it happened in staging, because a week later the production went down and we had to restore it—we were lucky it happened in staging first.

I tried different approaches. At first, I thought it was something in the bucket...

**Comment by stblassitude** [comment]
For what it is worth, adding `serverName` did the trick for me, even though the name of the externalCluster was already set to my cluster name:

```yaml
  externalClusters:
    - name: netbox-pg
      barmanObjectStore:
        serverName: netbox-pg
        destinationPath: s3://cnpg-netbox
        endpointURL: http://minio-url-redacted:9000
...
```
