### ISSUE TITLE
Controller doesn't restore app secret when bootstrapping with password reset 

### ISSUE THREAD

**Issue by rlex** [cloudnative-pg/cloudnative-pg#545]
Hello! First of all, thanks for great product.
While evaluating it, i noticed followint (maybe bug, maybe expected?) behaviour: 

If you bootstrap postgres cluster from backup with following specified: 

```  
spec:
  bootstrap:
    recovery:
      source: outline-db
      database: app
      owner: app
      secret:
        name: reset-password
```
where secret named reset-password contains username and password, the secret with -app (which contains pgpass, username and password) is not getting recreated after cluster bootstrap. superuser, replication and etc are all here. 
Might be case with overriding superuser password too, but i hasn't checked it.
