### ISSUE TITLE
[Bug]: With monitoring I can't access specifics schemas with custom queries

### ISSUE THREAD

**Issue by albundy83** [cloudnative-pg/cloudnative-pg#5656]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

gregoire.bellon-gervais@docaposte.fr

### Version

1.24.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

Hello,

First, my cluster is a self-managed RKE2.

I have tried to add custom queries to collect tables, indexes and schema size.
I have added the following block to add my custom ConfigMap:
```yaml
...
spec:
  monitoring:
    customQueriesConfigMap:
      - key: easi-pg-queries
        name: easi-pg-queries
      - key: queries
        name: cnpg-default-monitoring
...
```

And the ConfigMap to add my custom queries:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: easi-pg-queries
  namespace: my-namespace
  labels:
    cnpg.io/reload: ''
data:
  easi-pg-queries: |
    easi_pg_tables:
      target_databases:
        - my-database
      query: |
        SELECT current_database() as datname, table_schema, table_name,
          pg_table_size(
            quote_ident(table_schema) || '.' || quote_ident(table_name)
          ),
          pg_indexes_size(
            quote_ident(table_schema) || '.' || quote_ident(table_name)
          )
        FROM information_schema.tables
        ORDER BY 4
      metrics:
        - datname:
            usage: 'LABEL'
            description: 'Name of the database'
        - table_schema:
            usage: 'LABEL'
            description: 'Name of the schema'
        - table_name:
            usage: 'LABEL'
            description: 'Name of the table'
        - pg_table_size:
            usage: 'GAUGE'
            description: 'Computes the disk space used by the specified table, excluding indexes (but including its TOAST table if any, free space map, and visibility map) in bytes'
        - pg_indexes_size:
            usage: 'GAUGE'
            description: 'Computes the total disk space used by indexes attached to the specified table in bytes'

    easi_pg_schemas:
      target_databases:
        - my-database
      query: |
        SELECT current_database() as datname, table_schema,
          sum(
            pg_total_relation_size(
              quote_ident(table_schema) || '.' || quote_ident(table_name)
            )
          )::bigint AS schema_size
        FROM information_schema.tables
        GROUP BY table_catalog, table_schema
        ORDER BY table_catalog, schema_size
      metrics:
        - datname:
            usage: 'LABEL'
            description: 'Name of the database'
        - table_schema:
            usage: 'LABEL'
            description: 'Name of the schema'
        - schema_size:
            usage: 'GAUGE'
            description: 'Size of the schema in bytes'
```
 
It works when I connect inside the Pod to the database using `postgres` user as defined in [doc](https://cloudnative-pg.io/documentation/1.24/monitoring/#monitoring-instances).

Here the output:
```bash
postgres@my-database-1:/$ psql -d my-database
psql (16.4 (Debian 16.4-1.pgdg110+1))
Type "help" for help.

my-database=# SELECT current_database() as datname, table_schema,
          sum(
            pg_total_relation_size(
              quote_ident(table_schema) || '.' || quote_ident(table_name)
            )
          )::bigint AS schema_size
        FROM information_schema.tables
        GROUP BY table_catalog, table_schema
        ORDER BY table_catalog, schema_size;
 datname |           table_schema            | schema_size 
---------+-----------------------------------+-------------
 my-database     | information_schema                |      253952
 my-database     | my-custom-schema-1                |     2531328
 my-database     | pg_catalog                        |    12591104
 my-database     | another-custom-schema-1           |    13811712
 my-database     | and-another-custom-schema-1       |    37052416
(5 rows)

my-database=# 
```

But my metrics in prometheus, I just have `information_schema` and `pg_catalog`.
Nothing related to my others schemas `my-custom-schema-1 `, `another-custom-schema-1` and `and-another-custom-schema-1`.
I have also checked using a direct curl call to `:9187/metrics` and it contains also contains just `information_schema` and `pg_catalog`.

Do you have an idea of what I have forgot ?

Thanks a lot for your help

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app: my-cluster
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: my-cluster
  name: my-cluster
  namespace: my-namespace
spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    barmanObjectStore:
      data:
        compression: snappy
        encryption: AES256
        jobs: 2
      destinationPath: s3://cloudnative-pg-my-cluster-dev
      endpointURL: https://oos.my-s3.outscale.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: cloudnative-pg-s3
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: cloudnative-pg-s3
      serverName: my-database
      wal:
        compression: snappy
        encryption: AES256
        maxParallel: 8
    retentionPolicy: 90d
  bootstrap:
    initdb:
      dataChecksums: true
      database: my-database
      encoding: UTF8
      import:
        databases:
          - my-database
        source:
          externalCluster: cluster-crunchy
        type: microservice
      localeCType: C
      localeCollate: C
      owner: my-cluster
  enableSuperuserAccess: false
  externalClusters:
    - connectionParameters:
        dbname: my-database
        host: my-cluster-primary.my-cluster-dev.svc
        user: my-cluster
      name: cluster-crunchy
      password:
        key: password
        name: my-cluster-pguser-my-cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 1
  monitoring:
    customQueriesConfigMap:
      - key: easi-pg-queries
        name: easi-pg-queries
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_worker_processes: '32'
      pgaudit.log: all, -misc
      pgaudit.log_catalog: 'off'
      pgaudit.log_parameter: 'on'
      pgaudit.log_relation: 'on'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: '2'
      ephemeral-storage: 1Gi
      memory: 8Gi
    requests:
      cpu: 100m
      ephemeral-storage: '0'
      memory: 128Mi
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2-retain-immediate
      volumeMode: Filesystem
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2-retain-immediate
      volumeMode: Filesystem
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by albundy83** [comment]
Is there a way to have DEBUG level log for monitoring ?
I'd like to understand why my others schemas are not displayed output.
Maybe also, I could provide you more logs that could help to fix this problem.

Thanks a lot :)

**Comment by albundy83** [comment]
Hello,
no one to help me ?
Maybe as I say in my previous post, some information to be able to enable debug ?

**Comment by linux-wizard** [comment]
@albundy83 I have the same issue. It seems to be due from a lack of permission for the `pg_monitor` role.
You can replicate this way:
- Connect as `postgres`
```sh
psql -U postgres mydb
```
- Test the query
```sql
SELECT current_database() as datname, table_schema,
          sum(
            pg_total_relation_size(
              quote_ident(table_schema) || '.' || quote_ident(table_name)
            )
          )::bigint AS schema_size
        FROM information_schema.tables
        GROUP BY table_catalog, table_schema
        ORDER BY table_catalog, schema_size;
```
- Now switch to the `pg_monitor` role
```sql
SET ROLE pg_monitor;
```
- Repeat the monitoring query --> tables are non longer listed
This may be related to https://github.com/prometheus-community/postgres_exporter/issues/1032

**Comment by linux-wizard** [comment]
@albundy83 Interestingly the following query work even when using `pg_monitor` role
```sql
SELECT current_database() AS datname, * 
  FROM (
  SELECT *, table_total_size_bytes-indexes_size_bytes-COALESCE(table_toast_size_bytes,0) AS table_size_bytes 
    FROM (
      SELECT nspname AS schemaname, relname AS tablename 
          , c.reltuples AS table_row_estimate
          , pg_total_relation_size(c.oid) AS table_total_size_bytes
          , pg_indexes_size(c.oid) AS indexes_size_bytes
          , COALESCE(pg_total_relation_size(reltoastrelid), 0) AS table_toast_size_bytes
      FROM pg_class c
      LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE relkind = 'r' ORDER BY table_total_size_bytes DESC
  ) a) a;
```

ref: https://www.sql-easy.com/learn/how-to-check-database-size-in-postgresql/

So I guess something is wrong when we pass the table name and it needs to be converted to an OID, while if we provide the OID directly, we have no issues

**Comment by albundy83** [comment]
Ah my hero :-), it has perfectly worked using your query:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: easi-pg-queries
  namespace: my-namespace
  labels:
    cnpg.io/reload: ''
data:
  easi-pg-queries: |
    easi_pg_tables:
      query: |
        SELECT current_database() AS datname, * 
        FROM (
        SELECT *, table_total_size_bytes-indexes_size_bytes-COALESCE(table_toast_size_bytes,0) AS table_size_bytes 
          FROM (
            SELECT nspname AS table_schema, relname AS table_name 
                , c.reltuples AS table_row_estimate
                , pg_total_relation_size(c.oid) AS table_total_size_bytes
                , pg_indexes_size(c.oid) AS indexes_size_bytes
                , COALESCE(pg_total_relation_size(reltoastrelid), 0) AS table_toast_size_bytes
            FROM pg_class c
            LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE relkind = 'r' ORDER BY table_total_size_bytes DESC
        ) a) a
      metrics:
        - datname:
            usage: 'LABEL'
            description: 'Name of the database'
        - table_schema:
            usage: 'LABEL'
            description: 'Name of the schema'
        - table_name:
            usage: 'LABEL'
            description: 'Name of the table'
        - table_row_estimate:
            usage: 'GAUGE'
            description: 'An estimate of the number of rows in the table'
        - table_total_size_bytes:
            usage: 'GAUGE'
            description: 'The total size of the table, including all associated components: the main table data, indexes, and TOAST (if applicable) in bytes'
        - indexes_size_bytes:
            usage: 'GAUGE'
            description: 'The total size of all indexes on the table in bytes'
        - table_toast_size_bytes:
            usage: 'GAUGE'
            description: 'The size of the TOAST table associated with the main table in bytes'
        - table_size_bytes:
            usage: 'GAUGE'
            description: 'The size of the table excluding indexes and TOAST data in bytes'
    easi_pg_schemas:
      query: |
        SELECT 
          current_database() AS datname,
          schemaname AS table_schema,
          SUM(table_total_size_bytes)::bigint AS schema_size
        FROM (
          SELECT 
            nspname AS schemaname, 
            relname AS tablename,
            pg_total_relation_size(c.oid) AS table_total_size_bytes
          FROM pg_class c
          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE relkind = 'r'
        ) a
        GROUP BY schemaname
        ORDER BY schema_size DESC;
      metrics:
        - datname:
            usage: 'LABEL'
            description: 'Name of the database'
        - table_schema:
            usage: 'LABEL'
            description: 'Name of the schema'
        - schema_size:
            usage: 'GAUGE'
            description: 'Size of the schema in bytes'
```
