### ISSUE TITLE
[Feature]: Add secret template for credentials secret

### ISSUE THREAD

**Issue by maxemann96** [cloudnative-pg/cloudnative-pg#5883]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

It's impossible to add specific labels and annotations to the generated `basic-auth` type secrets containing the credentials and connection information.

### Describe the solution you'd like

Something like `spec.secretTemplates.appUserSecret.annotations` (also this would introduce the possibility for other (future) secrets be specified here, like `superUserSecret`). would be sufficient.

### Describe alternatives you've considered

Alternative 1:
First workaround is to specify the annotations with the `inheritedMetadata` attribute from the Cluster spec. But this adds too much noise to any object related to this cluster. Also in my specific use case (allowing the secret to be replicated into another namespace) it is possibly leaking too much information into other workspaces. Since it is not possible to connect with the superuser password from the network, this is a threat, that IMHO is possible to accept.

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ...
spec:
  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: grafana
   ...
```

Alternative 2:
Use the possibility of the managed roles to create an additional role with also a self created secret. For example I now have a Grafana role.

### Additional context

The use case is replicating the postgres app user secret to another workspace by utilizing kubernetes-reflector). After writing the "Alternatives I considered" section, I realized, that for my specific use case, a Grafana role in Postgres (with also only read only access) would be more useful, but I opened the issue because I think this would be a useful addition in general for other use cases (database residing in other workspace than application for example).

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
