### ISSUE TITLE
[Bug]: Documentation still reports pod security policies

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5996]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The security page still reports pod security policies - which have been deprecated. See: https://cloudnative-pg.io/documentation/current/security/#pod-security-policies

We should change it into security contexts.

I exported the ones for the postgres container:

```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
