### ISSUE TITLE
[Bug]: status cmd still broken due to NetworkPolicy

### ISSUE THREAD

**Issue by till** [cloudnative-pg/cloudnative-pg#6025]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.4

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: k0s

### How did you install the operator?

Helm

### What happened?

follow up to: https://github.com/cloudnative-pg/cloudnative-pg/issues/5247

---

As soon as I apply the following NetworkPolicy, the status command does not report backup status, primary instance status, etc.. It seems like, the requests going through a proxy are not included in the policy and therefor blocked. I've been executing status using a root-level kubernetes account which is why I ruled out RBAC issues. As soon as I remove the network policy, it works.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: cluster-example # The label value must be the cluster name
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system # Namespace where the operator is deployed
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg # Matches the Operator pod
      ports:
        - port: 8000
        - port: 5432
```

### Cluster resource

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-catalog.yaml

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @till 

I think I was able to reproduce your issue, but can you show me the output of your status command?

Regards,

**Comment by disconn3ct** [comment]
Same issue here, hopefully with the same cause. Ingress netpol on the cluster NS causes the failure, with this removed it works fine:
```yaml
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cnpg-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: cloudnative-pg
    ports:
    - port: 8000
      protocol: TCP
    - port: 5432
      protocol: TCP
    - port: 9187
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: cnpg.io/cluster
      operator: Exists
```

`cnpg status` takes just under 5 minutes to return almost nothing. (#6068 makes debugging much harder)
```
Cluster Summary
Name                 namespace/cluster-psql
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:17.0
Primary instance:    cluster-psql-2
Primary start time:  2024-11-12 15:48:07 +0000 UTC (uptime 1h42m17s)
Status:              Cluster in healthy state 
Instances:           2
Ready instances:     2
Size:                618M

Continuous Backup status
First Point of Recoverability:  Not Available
No Primary instance found
Physical backups
Primary instance not found

Streaming Replication status
Primary instance not found

Instances status
Name              Current LSN  Replication role  Status  QoS                 Manager Version  Node
----              -----------  ----------------  ------  ---                 ---------------  ----
cluster-psql-2  -            -                 -       ServiceUnavailable  Burstable        -  worker-b
cluster-psql-3  -            -                 -       ServiceUnavailable  Burstable        -  worker-p

Error(s) extracting status
-----------------------------------
the server is currently unable to handle the request (get pods https:cluster-psql-2:8000)
the server is currently unable to handle the request (get pods https:cluster-psql-3:8000)
```

**Comment by till** [comment]
@sxd Is there anything else you need?

**Comment by sxd** [comment]
@till yes is enough, but I haven't had time which is the required policy to allow the subresources pods/proxy to be called and executed

**Comment by till** [comment]
@sxd I am not exactly familiar with the proxy part (yet), can you point me to where this happens? I'll try to investigate as well.

Btw, are you referring using the `kube-proxy` process that (usually) runs in `kube-system`? I guess then the policy would need to include something like `k8s-app=kube-proxy` and the `kube-system` namespace?

**Comment by till** [comment]
It took me a bit to get back to this, but I think I managed to make it work.

I created a 2 node cluster which is called `db-dec6-4` (in namespace `db-dec6-4`), and this is what the policy looks like like:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-dec6-4
  namespace: db-dec6-4
  generation: 1
  labels:
    app: db-dec6-4
    heritage: runway
    organization: till
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: db-dec6-4
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              organization: some-name
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
                  - cnpg-system
        - podSelector:
            matchLabels:
              cnpg.io/cluster: db-dec6-4
  policyTypes:
    - Ingress
```

Be nice if someone else could verify that. Then I am also happy to PR this with comments inline maybe.

The idea is the following:

1. allow requests from any namespace labeled `organization: some-name` (this is related to our setup, we tag namespaces of an org/team)
2. allow requests from namespace `kube-system` (this was needed to make the status command work)
3. from namespace `cnpg-system` (generally for the operator)
4. from any pod that belongs to the `db-dec6-4` cluster (this was needed in order to get it to run/boostrap completely)

(conditions are `OR` as far as I can tell)

For rule 4, if I didn't add it, it would basically timeout in init/bootstrap and was unable to go through the `-rw` service to complete the setup.

This is the output of the `kubectl-cnpg status` command:

```
Cluster Summary
Name                 db-dec6-4/db-dec6-4
System ID:           7445407285926371351
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:16.4-39-bookworm@sha256:d653f7ac4b2e95aa1559ff812a62a98965e2ccc88cc27551def41c18119404f2
Primary instance:    db-dec6-4-1
Primary start time:  2024-12-06 21:03:00 +0000 UTC (uptime 58s)
Status:              Cluster in healthy state 
Instances:           2
Ready instances:     2
Size:                94M
Current Write LSN:   0/404DE90 (Timeline: 1 - WAL File: 000000010000000000000004)

Continuous Backup status
First Point of Recoverability:  Not Available
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              000000010000000000000003.00000028.backup   @   2024-12-06T21:03:25.838189Z
Last Failed WAL:                -

Physical backups
Name  Phase  Started at  Total  Transferred  Progress  Tablespaces
----  -----  ----------  -----  -----------  --------  -----------

Streaming Replication status
Replication Slots Enabled
Name         Sent LSN   Write LSN  Flush LSN  Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority  Replication Slot
----         --------   ---------  ---------  ----------  ---------  ---------  ----------  -----      ----------  -------------  ----------------
db-dec6-4-2  0/404DE90  0/404DE90  0/404DE90  0/404DE90   00:00:00   00:00:00   00:00:00    streaming  async       0              active

Instances status
Name         Current LSN  Replication role  Status  QoS        Manager Version  Node
----         -----------  ----------------  ------  ---        ---------------  ----
db-dec6-4-1  0/404DE90    Primary           OK      Burstable  1.23.5           node-006.testing
db-dec6-4-2  0/404DE90    Standby (async)   OK      Burstable  1.23.5           node-004.testing
```

Guess I could add the ports into it, but honestly not yet sure what they all are. I'd still like a high-level diagram that shows what all runs in a pod, etc. and what is needed where.

**Comment by AntonFriberg** [comment]
I looked into this a bit since I had similar issues.

To get the cluster working correctly I needed the following NetworkPolicies

One for the `cnpg-system` namespace which is necessary for the cnpg clusters to be able to call the webhook on the controller on changes and to post metrics. 

```yaml
# Allow cnpg clusters to access operator
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {} # your desired labels here
    - ports:
        - port: 9443 # webhook-server
          protocol: TCP
        - port: 8080 # metrics
          protocol: TCP
  policyTypes:
    - Ingress
```

Second, for the `cnpg` cluster itself in whatever namespace you deploy the cluster into. This allows the controller to access necessary ports to be able to operate. Metrics on 9187, Kubernetes pod status on port 8000, and postgres interface itself on 5432. Here I also allow traffic from `kube-system` namespace.

```yaml
# Allow operator to access cnpg cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: <your-namespace-here>
spec:
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
                  - cnpg-system
      ports:
        - port: 9187 # metrics-manager
          protocol: TCP
        - port: 8000 # kubernetes status
          protocol: TCP
        - port: 5432 # postgres
          protocol: TCP
  policyTypes:
    - Ingress
```

All of the above allows full functionality of CloudNative-PG  but the `kubectl cnpg status` command still does not work for me at least. From my understanding `kubectl cnpg status` proxies network requests via the cluster to check status.

That is why we added `kube-system` to the namespaces that is allowed to reach our cnpg cluster pods. The proxied traffic should in my mind arrive from that namespace (the cluster I am testing in is using Cilium in this case). But, unfortunately it does not work.

I have not narrowed it down much but this works. I.e. *Allow all traffic from any source to the cnpg cluster*

``` yaml
# Allow operator to access cnpg cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: <your-namespace-here>
spec:
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress: {}
  policyTypes:
    - Ingress
```

But for some reason this does not work. I.e *Allow all traffic from any pod on any namespace*

```yaml
# Allow operator to access cnpg cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: <your-namespace-here>
spec:
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress
```

This is where my available skillset ends. I do not know how I can allow the `kubectl cnpg status` command without simply allowing all traffic since the traffic needed is somehow not originating from any pod in any namespace. At least not in my setup.

**Comment by AntonFriberg** [comment]
Ok, I got something that I think is good enough. I can keep full access but only for the status port (port 8000) and lock down the rest. So final working setup for me would be.

Allow access to cnpg operator from individual cnpg clusters

```yaml
# Allow cnpg clusters to access operator
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  ingress:
    - ports:
        - port: 9443 # webhook-server
          protocol: TCP
        - port: 8080 # metrics
          protocol: TCP
  policyTypes:
    - Ingress
```

Allow operator to reach cluster

```yaml
# Allow operator to reach cluster in our namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator-access
  namespace: <your-namespace-here>
spec:
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cnpg-system
      ports:
        - port: 9187 # metrics-manager
          protocol: TCP
        - port: 5432 # postgresql
          protocol: TCP
  policyTypes:
    - Ingress
```

And finally, allow operator and kubectl cnpg command access to cluster status.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-cluster-status
  namespace: <your-namespace-here>
spec:
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - ports:
        - port: 8000 # status
          protocol: TCP
  policyTypes:
    - Ingress
```

**Comment by sxd** [comment]
hello @till 

Can you test the solution proposed by  @AntonFriberg  ?

Regards!

**Comment by markmaker** [comment]
@AntonFriberg 's solution unfortunately does not work for me.

**Comment by till** [comment]
@sxd you can't test? I provided a solution as well, it does seem to work still for me.

**Comment by markmaker** [comment]
I'm on K3S with `cluster-cidr: 10.42.0.0/16` (default), and embedded network policy controller. 

This seems to work:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-cluster-status
  namespace:  <your-namespace-here>
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - from:
        - ipBlock:
            cidr: 10.42.0.0/16
      ports:
        - port: 8000
          protocol: TCP
...
```

The idea, and description how `kubectl proxy` apparently directly works from the cluster network, is from here:

https://github.com/projectcalico/canal/issues/127

Calico added some proprietary "GlobalNetworkPolicy" solution for that, but IMHO this should work with a standard Kubernetes NetworkPolicy and compliant network policy controller.

I guess needing to open it up like that is a security weakness to some extent? How bad is that?

Don't understand why the `cnpg` plugin needs to talk directly to the cluster instances, rather than just the operator. Shouldn't the operator be the boss and encapsulate all needed information and functionality?

_Mark

**Comment by makkes** [comment]
I dug a little deeper here and found out that my AKS cluster is using Konnectivity to proxy traffic for the API server so all traffic originates from one of the Konnectivity agent pods. Producing a NetworkPolicy rule to allow this is very simple then:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnpg-allow-konnectivity-proxy
  namespace: <db-cluster-namespace>
spec:
ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app: konnectivity-agent
          component: tunnel
```
