### ISSUE TITLE
[Bug]: Bootstrapping a new cluster using pg_basebackup from replica

### ISSUE THREAD

**Issue by maxpain** [cloudnative-pg/cloudnative-pg#6093]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

maxpain177@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

Bootstrapping using the `pg_basebackup` method doesn't work when using a `replica` IP instead of `primary` in the `externalClusters` section.
The `pg_basebackup` job successfully dumps the database but is stuck with the following logs:

```
specified neither \"primary_conninfo\" nor \"restore_command\"","hint":"The database server will regularly poll the pg_wal subdirectory to check for files placed there
```

`waiting for WAL to become available at 14B/3C002000`

There are no problems when bootstrapping from `primary`.

### Cluster resource

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fc-dev-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    pg_basebackup:
      source: fc-pg
      database: fastcup
      owner: fastcup
      secret:
        name: fc-dev-pg

  externalClusters:
    - name: fc-pg
      connectionParameters:
        # Production replica svc
        host: fc-pg-ro.fastcup
        user: streaming_replica
        sslmode: verify-full
      sslKey:
        name: fc-pg-replication
        key: tls.key
      sslCert:
        name: fc-pg-replication
        key: tls.crt
      sslRootCert:
        name: fc-pg-ca
        key: ca.crt

  storage:
    size: 1Ti
    storageClass: nvme-lvm-local

  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "16GB"
      effective_cache_size: "48GB"
      maintenance_work_mem: "2GB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "20971kB"
      huge_pages: "try"
      min_wal_size: "2GB"
      max_wal_size: "8GB"
      max_worker_processes: "16"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "16"
      max_parallel_maintenance_workers: "4"

      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      pg_stat_statements.track_utility: "true"
      pg_stat_statements.save: "false"
      track_io_timing: "on"
```

### Relevant log output

[pgbasebackup.log](https://github.com/user-attachments/files/17744632/pgbasebackup.log)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jsilvela** [comment]
You're not using the IP address as you comment, but the RO service

```
- name: fc-pg
      connectionParameters:
        # Production replica svc
        host: fc-pg-ro.fastcup
```

This worries me. The RO service is not a connection to one instance.
Then, while it is possible to run base backup on a replica, there are caveats.

https://www.postgresql.org/docs/current/app-pgbasebackup.html

```
Note that there are some limitations in taking a backup from a standby:

The backup history file is not created in the database cluster backed up.

pg_basebackup cannot force the standby to switch to a new WAL file at the end of backup. When you are using -X none, if write activity on the primary is low, pg_basebackup may need to wait a long time for the last WAL file required for the backup to be switched and archived. In this case, it may be useful to run pg_switch_wal on the primary in order to trigger an immediate WAL file switch.

If the standby is promoted to be primary during backup, the backup fails.

All WAL records required for the backup must contain sufficient full-page writes, which requires you to enable full_page_writes on the primary.
```
