### ISSUE TITLE
[Bug]: Operator deletes PodMonitor that it didn't create due to lack of owner reference check

### ISSUE THREAD

**Issue by ari-becker** [cloudnative-pg/cloudnative-pg#6109]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

YAML manifest

### What happened?

1. https://github.com/cloudnative-pg/cloudnative-pg/issues/6108 , decide to set `monitoring.enablePodMonitor: false`. In the same commit, create a `PodMonitor` to be applied manually, with the same name (i.e. the cluster name) and namespace.
2. Apply both changes simultaneously
3. Wonder why I don't have a `PodMonitor`
4. Go spelunking in the code: https://github.com/cloudnative-pg/cloudnative-pg/blob/3c2c3f695eafbf1a0db96954f1796ff37cbd0733/internal/controller/cluster_create.go#L959 gets a reference to the `PodMonitor` based on namespace and name only, *not* looking at the owner reference. Therefore https://github.com/cloudnative-pg/cloudnative-pg/blob/3c2c3f695eafbf1a0db96954f1796ff37cbd0733/internal/controller/cluster_create.go#L973 indeed finds the `PodMonitor` (that it doesn't have an owner reference on) and deletes it.

I worked around the issue by adding a short suffix to the `PodMonitor` name so that it wouldn't be deleted, but this isn't ideal because it changes the job label that Prometheus attaches to it.

### Cluster resource

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Jean-Daniel** [comment]
I'm also impacted by this issue.

Note that if you need to create your own PodMonitor but want to keep the same job label, you can override it using relabelings:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: clustername-suffix
spec:
  podMetricsEndpoints:
  - metricRelabelings:
    - replacement: clustername
      targetLabel: job
    port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: clustername

```
