### ISSUE TITLE
[Feature]: Support additional volume mounts

### ISSUE THREAD

**Issue by andyndang** [cloudnative-pg/cloudnative-pg#6149]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We have data stored in S3. We can mount S3 as an additional mount volume to the pod to bulk load data

### Describe the solution you'd like

Support additional volume mounts. Zalando's Postgres-operator supports this option 

### Describe alternatives you've considered

Add mount s3 as part of the container binary and run mount s3 as root

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nthtrung09it** [comment]
hey @andyndang @gbartolini how is it going? I want to mount some custom stuffs into /docker-entrypoint-initdb.d, like:

![Image](https://github.com/user-attachments/assets/58d7d049-ae0e-4286-901b-d62828bb2e32)

**Comment by nthtrung09it** [comment]
Basically, I want to execute an migrate.sh script in the **docker-entrypoint-initdb.d**.
But it seems that cloudnative-pg does not run it.

![Image](https://github.com/user-attachments/assets/9f9a409f-d70a-4d95-a04a-8525856cd67e)

**Comment by vishaltanawade** [comment]
Hi @gbartolini ,
is there any update on this , unlike other operators why CNPG does not support to execute all script automatically from folder docker-entrypoint-initdb.d.

**Comment by vishaltanawade** [comment]
not stale

**Comment by snkolev18** [comment]
Hi @andyndang 

You can try using the `podPatch` annotation

```yaml
metadata:
  annotations:
      cnpg.io/podPatch: |
            [
             {
                  "op": "add", "path": "/spec/volumes/-", "value": {
                    "name": "mount-name",
                    "persistentVolumeClaim": {
                        "claimName": "your-pvc"
                    }
                }
              },
              {
                "op": "add", "path": "/spec/containers/0/volumeMounts/-", "value": {
                  "name": "mount-name",
                  "mountPath": "<desired-path>"
                }
              }
            ]
```
