### ISSUE TITLE
[Bug]: barmanObjectStore backup fails with image version 17.2-2

### ISSUE THREAD

**Issue by pfaelzerchen** [cloudnative-pg/cloudnative-pg#6159]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

I tried to upgrade my current clusters from pg16 to pg17. Therefore, I deployed a new cluster definition that bootstraps from the old cluster. The new cluster is created fine and healthy:

```
kubectl cnpg status -n lldap lldap-db-17
Cluster Summary
Name                 lldap/lldap-db-17
System ID:           7440467538701451292
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:17.2-2
Primary instance:    lldap-db-17-1
Primary start time:  2024-11-23 13:34:39 +0000 UTC (uptime 4m5s)
Status:              Cluster in healthy state 
Instances:           3
Ready instances:     3
Size:                166M
Current Write LSN:   0/8005948 (Timeline: 1 - WAL File: 000000010000000000000008)

Continuous Backup status
First Point of Recoverability:  2024-11-23T13:37:56Z
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              000000010000000000000007.00001FD0.backup   @   2024-11-23T13:36:42.233917Z
Last Failed WAL:                -

Physical backups
Name  Phase  Started at  Total  Transferred  Progress  Tablespaces
----  -----  ----------  -----  -----------  --------  -----------

Streaming Replication status
Replication Slots Enabled
Name           Sent LSN   Write LSN  Flush LSN  Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority  Replication Slot
----           --------   ---------  ---------  ----------  ---------  ---------  ----------  -----      ----------  -------------  ----------------
lldap-db-17-2  0/8005948  0/8005948  0/8005948  0/8005948   00:00:00   00:00:00   00:00:00    streaming  async       0              active
lldap-db-17-3  0/8005948  0/8005948  0/8005948  0/8005948   00:00:00   00:00:00   00:00:00    streaming  async       0              active

Instances status
Name           Current LSN  Replication role  Status  QoS         Manager Version  Node
----           -----------  ----------------  ------  ---         ---------------  ----
lldap-db-17-1  0/8005948    Primary           OK      BestEffort  1.24.1           tick
lldap-db-17-2  0/8005948    Standby (async)   OK      BestEffort  1.24.1           trick
lldap-db-17-3  0/8005948    Standby (async)   OK      BestEffort  1.24.1           track
```

I then deployed a scheduled backup for both the volume snapshot and the barmanObjectstore:

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-db-backup-17
  namespace: lldap
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: lldap-db-17
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-db-cold-backup-17
  namespace: lldap
spec:
  schedule: "0 15 0 * * *"
  backupOwnerReference: self
  immediate: true
  method: volumeSnapshot
  cluster:
    name: lldap-db-17
```

But the barmanObjectStore fails:

```
NAME                                     AGE     CLUSTER       METHOD              PHASE       ERROR
lldap-db-backup-17-20241123133355        13m     lldap-db-17   barmanObjectStore   failed      parsing time "2024-11-23T13:36:00.398283+00:00" as "Mon Jan 2 15:04:05 2006": canno
t parse "2024-11-23T13:36:00.398283+00:00" as "Mon"
lldap-db-cold-backup-17-20241123133715   10m     lldap-db-17   volumeSnapshot      completed
```

`kubectl describe backup` reveals a completed before the failed state:

```yaml
$ kubectl -n lldap describe backup lldap-db-backup-17-20241123133355 
Name:         lldap-db-backup-17-20241123133355
Namespace:    lldap
Labels:       cnpg.io/cluster=lldap-db-17
              cnpg.io/immediateBackup=true
              cnpg.io/scheduled-backup=lldap-db-backup-17
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2024-11-23T13:33:55Z
  Generation:          1
  Owner References:
    API Version:     postgresql.cnpg.io/v1
    Controller:      true
    Kind:            ScheduledBackup
    Name:            lldap-db-backup-17
    UID:             dd069bcb-08d2-440f-9d60-cca54bc299ac
  Resource Version:  147767802
  UID:               2b7fb992-8963-430f-93f9-ff37f800fb8b
Spec:
  Cluster:
    Name:  lldap-db-17
  Method:  barmanObjectStore
Status:
  Backup Name:       backup-20241123133455
  Destination Path:  s3://cnpg-backup-lldap-17/
  Endpoint CA:
    Key:         ca.crt
    Name:        temp-selfsigned-ca
  Endpoint URL:  http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
  Error:         parsing time "2024-11-23T13:36:00.398283+00:00" as "Mon Jan 2 15:04:05 2006": cannot parse "2024-11-23T13:36:00.398283+00:00" as "Mon"
  Instance ID:
    Container ID:  containerd://843b64c70a856f5431fb44b8b389f9eda671c41ef16d325ea718615b74e14b69
    Pod Name:      lldap-db-17-1
  Method:          barmanObjectStore
  Phase:           failed
  s3Credentials:
    Access Key Id:
      Key:   AWS_ACCESS_KEY_ID
      Name:  cnpg-backup-17
    Secret Access Key:
      Key:      AWS_SECRET_ACCESS_KEY
      Name:     cnpg-backup-17
  Server Name:  lldap-db-17
  Stopped At:   2024-11-23T13:36:14Z
Events:
  Type     Reason         Age                From                   Message
  ----     ------         ----               ----                   -------
  Warning  FindingPod     15m (x2 over 15m)  cloudnative-pg-backup  Couldn't find target pod , will retry in 30 seconds
  Warning  BackupPending  15m                cloudnative-pg-backup  Backup target pod not ready: lldap-db-17-1
  Normal   Starting       14m (x4 over 15m)  cloudnative-pg-backup  Starting backup for cluster lldap-db-17
  Normal   Starting       13m                local-webserver        Backup started
  Normal   Completed      13m                local-webserver        Backup completed
  Normal   Failed         13m                local-webserver        Backup failed
```

The timestamp that could not be parsed is a recent timestamp when the error occurred.

The primary pod has a corresponding log entry. No further errors are logged in the primary or standby pods (postgres container).

I tested the same procedure with another database and got the same result - also with a current time stamp.

There were no services connected to the newly created pg17 cluster when the error appeared.

And another hint: I successfully migrated one cluster from pg16 to pg17 with the same procedure a day before. All I did in between was an update of the image catalog: 

* `16.5-1 -> 16.6-2`
* `17.1-1 -> 17.2-2`

So it may be a problem with the 17.2-2 image. I therefore tested an existing pg17 cluster after image upgrade from 17.1-1 to 17.2-2. It logs the same error. Before with version 17.1-1 a backup was successfully created.

### Cluster resource

```shell
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-db-17
  namespace: lldap
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  monitoring:
    enablePodMonitor: true

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  
  bootstrap:
    initdb:
      import:
        type: monolith #microservice
        databases:
          - lldap
        roles:
          - lldap
        source:
          externalCluster: lldap-db-16
      # database: lldap
      owner: lldap
      secret:
        name: postgres-user

  externalClusters:
    - name: lldap-db-16
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: lldap-db-rw.lldap.svc.cluster.local
        user: postgres
        dbname: postgres
      password:
        name: postgres-superuser
        key: password

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  storage:
    storageClass: ceph-block
    size: 5Gi

  backup:
    # Volume snapshot backups
    volumeSnapshot:
       className: ceph-block
       online: false
       snapshotOwnerReference: backup
    # WAL archive
    barmanObjectStore:
      serverName: lldap-db-17
      destinationPath: s3://cnpg-backup-lldap-17/
      endpointURL: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
      endpointCA:
        name: temp-selfsigned-ca
        key: ca.crt
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-17
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-17
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
        # encryption: AES256
        maxParallel: 8
      data:
        compression: bzip2
        # encryption: AES256
        # immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "60d"
```

### Relevant log output

```shell
{"level":"info","ts":"2024-11-23T13:36:14.340616841Z","msg":"Backup completed","backupName":"lldap-db-backup-17-20241123133355","backupNamespace":"lldap-db-backup-17-20241123133355","logging_pod":"lldap-db-17-1"}
{"level":"error","ts":"2024-11-23T13:36:14.764754833Z","msg":"Backup failed","backupName":"lldap-db-backup-17-20241123133355","backupNamespace":"lldap-db-backup-17-20241123133355","logging_pod":"lldap-db-17-1","error":"parsing time \"2024-11-23T13:36:00.398283+00:00\" as \"Mon Jan 2 15:04:05 2006\": cannot parse \"2024-11-23T13:36:00.398283+00:00\" as \"Mon\"","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:177"}
{"level":"info","ts":"2024-11-23T13:36:14.807927196Z","msg":"Applying backup retention policy","backupName":"lldap-db-backup-17-20241123133355","backupNamespace":"lldap-db-backup-17-20241123133355","logging_pod":"lldap-db-17-1","retentionPolicy":"60d"}
{"level":"error","ts":"2024-11-23T13:36:16.490513574Z","logger":"barman","msg":"Can't parse barman output","backupName":"lldap-db-backup-17-20241123133355","backupNamespace":"lldap","logging_pod":"lldap-db-17-1","command":"barman-cloud-backup-list","output":"{\"backups_list\": [{\"backup_label\": \"'START WAL LOCATION: 0/5000060 (file 000000010000000000000005)\\\\nCHECKPOINT LOCATION: 0/50000B8\\\\nBACKUP METHOD: streamed\\\\nBACKUP FROM: primary\\\\nSTART TIME: 2024-11-23 13:36:06 UTC\\\\nLABEL: Barman backup cloud 20241123T133600\\\\nSTART TIMELINE: 1\\\\n'\", \"backup_name\": \"backup-20241123133455\", \"begin_offset\": 96, \"begin_time\": \"2024-11-23T13:36:00.398283+00:00\", \"begin_wal\": \"000000010000000000000005\", \"begin_xlog\": \"0/5000060\", \"children_backup_ids\": null, \"cluster_size\": 39462555, \"compression\": null, \"config_file\": \"/var/lib/postgresql/data/pgdata/postgresql.conf\", \"copy_stats\": {\"total_time\": 13.607668, \"number_of_workers\": 2, \"analysis_time\": 0, \"analysis_time_per_item\": {\"data\": 0}, \"copy_time_per_item\": {\"data\": 3.06711}, \"serialized_copy_time_per_item\": {\"data\": 1.226201}, \"copy_time\": 3.06711, \"serialized_copy_time\": 1.226201}, \"data_checksums\": \"off\", \"deduplicated_size\": null, \"end_offset\": 270440, \"end_time\": \"2024-11-23T13:36:08.030878+00:00\", \"end_wal\": \"000000010000000000000005\", \"end_xlog\": \"0/5042068\", \"error\": null, \"hba_file\": \"/var/lib/postgresql/data/pgdata/pg_hba.conf\", \"ident_file\": \"/var/lib/postgresql/data/pgdata/pg_ident.conf\", \"included_files\": [\"/var/lib/postgresql/data/pgdata/custom.conf\", \"/var/lib/postgresql/data/pgdata/override.conf\"], \"mode\": null, \"parent_backup_id\": null, \"pgdata\": \"/var/lib/postgresql/data/pgdata\", \"server_name\": \"cloud\", \"size\": null, \"status\": \"DONE\", \"summarize_wal\": \"off\", \"systemid\": \"7440467538701451292\", \"tablespaces\": null, \"timeline\": 1, \"version\": 170002, \"xlog_segment_size\": 16777216, \"backup_id\": \"20241123T133600\"}]}\n","error":"parsing time \"2024-11-23T13:36:00.398283+00:00\" as \"Mon Jan 2 15:04:05 2006\": cannot parse \"2024-11-23T13:36:00.398283+00:00\" as \"Mon\"","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.GetBackupList\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:122\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).getBackupData\n\tpkg/management/postgres/backup.go:465\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).backupMaintenance\n\tpkg/management/postgres/backup.go:286\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:203"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
