### ISSUE TITLE
[Bug]: cluster metadata labels not set on pods

### ISSUE THREAD

**Issue by bjorns163** [cloudnative-pg/cloudnative-pg#6164]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When I use the operator to deploy a cluster, I set the metadata labels as described in the [documentation](https://cloudnative-pg.io/documentation/1.24/labels_annotations/) 

I added environment=production then create it with below config:

```
kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: cluster-sample
  namespace: test
  labels:
    environment: production
spec:
  instances: 3
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
```

When the cluster is created, I check if the labels are available on the pods, but the labels aren't there. 

```
oc get pods --show-labels
NAME               READY   STATUS    RESTARTS   AGE     LABELS
cluster-sample-1   1/1     Running   0          3m4s    cnpg.io/cluster=cluster-sample,cnpg.io/instanceName=cluster-sample-1,cnpg.io/instanceRole=primary,cnpg.io/podRole=instance,role=primary
cluster-sample-2   1/1     Running   0          2m30s   cnpg.io/cluster=cluster-sample,cnpg.io/instanceName=cluster-sample-2,cnpg.io/instanceRole=replica,cnpg.io/podRole=instance,role=replica
cluster-sample-3   1/1     Running   0          113s    cnpg.io/cluster=cluster-sample,cnpg.io/instanceName=cluster-sample-3,cnpg.io/instanceRole=replica,cnpg.io/podRole=instance,role=replica
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
