### ISSUE TITLE
[Feature]: Enable PITR from Backup object

### ISSUE THREAD

**Issue by mortenlj** [cloudnative-pg/cloudnative-pg#6173]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

If you attempt to configure recovery by combining a `Backup` object (method `volumeSnapshot`) with WAL archive in an object store, the PITR process fails. 
If you instead refer to the `volumeSnapshots` from the `Backup` object directly in the recovery stanzas, PITR works correctly.

Likewise, PITR from object store should also work fine (I haven't actually tested this).

It seems everything should be in place to perform PITR from a `Backup` object, regardless of method used to take the backup, as long as it is combined with a WAL archive in an object store.

### Describe the solution you'd like

Referring to a simple `Backup` object feels simpler and less error-prone than looking up the `volumeSnapshots`, making sure to combine the correct snapshots for storage/walStorage, and generally get the rest of the configuration correct.

```
  bootstrap:
    recovery:
      backup:
        name: backup-20241127004242
      recoveryTarget:
        targetTime: "2024-11-27T02:30:00"
      source: wal-archive
  externalClusters:
    - name: wal-archive
      barmanObjectStore:
        destinationPath: gs://wal-archive
        googleCredentials:
          gkeEnvironment: true
```

### Describe alternatives you've considered

It is possible to do PITR by using the volumeSnapshots directly, but that feels more complicated and error prone.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
