### ISSUE TITLE
[Bug]: "exec /manager: argument list too long" in  bootstrap-controller

### ISSUE THREAD

**Issue by maxcoolmakarov** [cloudnative-pg/cloudnative-pg#6234]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

maxim.i.makarov@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

Helm

### What happened?

I have a k8s managed cluster and a namespace with thousands of pods with different VENV. My cnpg worked fine for over a year and suddenly, newly created clusters or rebooted old ones start hanging in pending status due to sidecar container error.
Log:
` exec /manager: argument list too long`
Exactly same cluster manifest worked fine in other namespaces, so the problem relays to bash problem with large amount of VENVs in one namespace.

### Proposed solution:

Add an ability to set Pod parameter: `enableServiceLinks: false` to any created CNPG pod.

Current working solution is to use kyverno: 

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-service-links-for-database
spec:
  rules:
    - name: set-enable-service-links-false
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - <some namespace>
      mutate:
        patchesJson6902: |
          - op: replace
            path: /spec/enableServiceLinks
            value: false
```
and with `enableServiceLinks=false` clusters are able to start again 

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
