### ISSUE TITLE
'FATAL:  data directory "/var/lib/postgresql/data/pgdata" has invalid permissions' when bootstrapping cluster from backup

### ISSUE THREAD

**Issue by 9numbernine9** [cloudnative-pg/cloudnative-pg#625]
Hello! 👋 

I've recently started experiment with Cloudnative-pg (installed via Helm) in my homelab setup, a three-node K3S cluster running Kubernetes `v1.24.3+k3s1` and using Longhorn `1.3.1` as my CSI . After destroying a cluster, I'm attempting to restore the cluster from an S3 backup but I've noticed this message in the logs of the `full-recovery` container:
```
{"level":"info","ts":1660872541.8728054,"msg":"Starting up instance","logging_pod":"mycluster-1","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":1660872541.8913906,"logger":"pg_ctl","msg":"waiting for server to start....2022-08-19 01:29:01.891 UTC [33] FATAL:  data directory \"/var/lib/postgresql/data/pgdata\" has invalid permissions","pipe":"stdout","logging_pod":"mycluster-1"}
{"level":"info","ts":1660872541.8915691,"logger":"pg_ctl","msg":"2022-08-19 01:29:01.891 UTC [33] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).","pipe":"stdout","logging_pod":"mycluster-1"}
{"level":"info","ts":1660872541.9828606,"logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"mycluster-1"}
{"level":"info","ts":1660872541.9829462,"logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"mycluster-1"}mycluster
```
It seems that the permissions of the `/var/lib/postgresql/data/pgdata` directory aren't being set correctly for some reason? The `bootstrap-controller` initContainer seems to work fine:
```
{"level":"info","ts":1660872533.6525264,"msg":"Installing the manager executable","destination":"/controller/manager","version":"1.16.1","build":{"Version":"1.16.1","Commit":"14600bab","Date":"2022-08-12"}}
{"level":"info","ts":1660872534.7739167,"msg":"Setting 0755 permissions"}
{"level":"info","ts":1660872534.7739878,"msg":"Bootstrap completed"}
```
But then when the `full-recovery` container starts is when things go awry.

The YAML specs for my cluster are as follows:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycluster
  namespace: postgres
spec:
  bootstrap:
    recovery:
      source: mycluster
  externalClusters:
    - name: mycluster
      barmanObjectStore:
        data:
          compression: bzip2
          encryption: AES256
        destinationPath: s3://mycluster_backups
        endpointURL: https://url.to.m3.s3.storage.provider.com
        s3Credentials:
          accessKeyId:
            key: ACCESS_KEY_ID
            name: s3-credentials
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: s3-credentials
        wal:
          compression: bzip2
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
```
I'm really puzzled as to what's going wrong, though I admit that I am new to Cloudnative-pg and might be doing something wrong in my Cluster spec. 😄 If you can help me debug or understand this issue it would be greatly appreciated! I can provide any addiitonal information upon request.
