### ISSUE TITLE
[Bug]:  cnpg tatus hangs indefinitely if an instance is on a node that is  <NotReady>

### ISSUE THREAD

**Issue by sandroden** [cloudnative-pg/cloudnative-pg#6298]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

sandro.dentella@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Self-managed: RKE

### How did you install the operator?

Helm

### What happened?

# Command `cnpg status` hangs when a cluster node is NotReady

## Description
The `kubectl cnpg status` command hangs indefinitely when trying to get information about a PostgreSQL cluster that has instances on a NotReady node. This prevents operators from getting diagnostic information about the cluster status precisely when it might be most needed.

## Steps to Reproduce
1. Have a CNPG cluster with instances spread across multiple nodes (with node anti-affinity configured)
2. Make one of the nodes hosting a PostgreSQL instance NotReady (e.g., by stopping kubelet/rke2-agent)
3. Run `kubectl cnpg status <cluster-name>`
4. The command hangs indefinitely

## Current Behavior
The command hangs without providing any output or timeout, even though:
- The cluster status is available via `kubectl get cluster`
- Some instances are still healthy and accessible
- Other kubectl commands continue to work normally

## Expected Behavior
The command should either:
- Show partial information about the reachable instances
- Fail gracefully with a timeout and error message
- Show status with clear indication of which instances are unreachable

## Environment
- CloudNativePG version: 1.24
- Kubernetes version: 1.30.4
- kubectl-cnpg plugin version: 1.24.0

## Cluster Configuration
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-wikijs
  namespace: wikijs
spec:
  instances: 2
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    tolerations:
    - effect: NoSchedule
      key: app
      operator: Equal
      value: postgresql
    topologyKey: kubernetes.io/hostname
  # ... other relevant configs ...

status:
  instancesStatus:
    healthy:
    - pg-wikijs-1
  readyInstances: 1
  phase: Waiting for the instances to become active
  phaseReason: Some instances are not yet active. Please wait.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
