### ISSUE TITLE
PodDisruptionBudget is warning for primary instance

### ISSUE THREAD

**Issue by sathieu** [cloudnative-pg/cloudnative-pg#6307]
### Discussed in https://github.com/cloudnative-pg/cloudnative-pg/discussions/3865

<div type='discussions-op-text'>

<sup>Originally posted by **grahamboyle** February 23, 2024</sup>
Hi

I'm new to the K8s and Postgres world
I've created a database with 3 instances called pg-graham-dev3

Two pod disruption budgets get created by CNPG when I do this: 
pg-graham-dev3 and pg-graham-dev3-primary

pg-graham-dev3 is fine, min available is 1 and allowed disruptions is 1
pg-graham-dev3-primary is in warning , min available is 1 and allowed disruptions is 0

"Insufficient Pods" is the alert, I don't understand why its saying that where there are two replicas available.

Any advice on what's wrong?
```
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.22.1
  name: pg-graham-dev3-primary
  generation: 1
  namespace: cloudnativepg
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: pg-graham-dev3
      controller: true
  labels:
    cnpg.io/cluster: pg-graham-dev3
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: pg-graham-dev3
      role: primary
status:
  observedGeneration: 1
  disruptionsAllowed: 0
  currentHealthy: 1
  desiredHealthy: 1
  expectedPods: 1
  conditions:
    - type: DisruptionAllowed
      status: 'False'
      observedGeneration: 1
      lastTransitionTime: '2024-02-22T15:23:56Z'
      reason: InsufficientPods
      message: ''
```

</div>
