### ISSUE TITLE
[Feature]: Password-based authentication for pgbouncer clients

### ISSUE THREAD

**Issue by BalaMuralibi** [cloudnative-pg/cloudnative-pg#6318]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Hi,

I am creating initdb with auto generated password to use in client app airflow, according to documentation https://cloudnative-pg.io/documentation/1.22/connection_pooling/#authentication.

I have added steps described in above url mentioned in ```PostInitSQL``` , but pg cluster creation is failing with error ```airflow (initdb)``` is not available.

Can someone please advise , how to execute postInitSQL ? Executing Manually is not practical.
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster
  namespace: airflow
spec:
  instances: 3

  bootstrap:
    initdb:
      database: airflow
      owner: airflow
      #secret: airflow
      encoding: 'UTF8'
      postInitSQL:
        - CREATE ROLE cnpg_pooler_pgbouncer WITH LOGIN
        - GRANT CONNECT ON DATABASE airflow TO cnpg_pooler_pgbouncer
        - CREATE OR REPLACE FUNCTION public.user_search(uname TEXT)
            RETURNS TABLE (usename name, passwd text)
            LANGUAGE sql SECURITY DEFINER AS
            'SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1;'
        - REVOKE ALL ON FUNCTION public.user_search(text) FROM public
        - GRANT EXECUTE ON FUNCTION public.user_search(text) TO cnpg_pooler_pgbouncer

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 16
  storage:
    storageClass: standard
    size: 200Gi
  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:  
      - host all all samehost trust
      - local all all peer
      - host airflow airflow ip trust
      - hostssl airflow airflow ip password
  enableSuperuserAccess: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "1"

---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pgpooler
  namespace: airflow
spec:
  cluster:
    name: pgcluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  template:
    spec:
      containers:
      - name: pgbouncer
        image: cloudnative-pg/pgbouncer:1.22.1-14

```

### Describe the solution you'd like

My expectation is that cluster must create initDB first and execute PostinitSQL.

### Describe alternatives you've considered

na

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
