### ISSUE TITLE
[Bug]: The problem with backup in S3 (minio)

### ISSUE THREAD

**Issue by wildGecko** [cloudnative-pg/cloudnative-pg#6619]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

m.kuprienko@vl.team

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

Hello!
I have a k3s cluster. A PGSQL cluster and a mini cluster are running in the same namespace. I have set up a backup in the mini, but it does not work. In the logs of the instance from which the backup is made, these are the entries

```
{"level":"info","ts":"2025-01-17T13:00:00.421095535Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:01:00.443824867Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:02:00.466246417Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:03:00.488837823Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:04:00.511788423Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:05:00.533426109Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:06:00.554601143Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:07:00.575602324Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:08:00.597550552Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:09:00.619774588Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:09:00.619995346Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2","err":"wal-archive not working"}
{"level":"info","ts":"2025-01-17T13:10:00.279356691Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:11:00.300389141Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:12:00.322161444Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:13:00.34420666Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:14:00.369131926Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:15:00.391911954Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:16:00.415105072Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:17:00.436088902Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:18:00.45755317Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:19:00.479479168Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:19:00.479706886Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2","err":"wal-archive not working"}
{"level":"info","ts":"2025-01-17T13:20:00.273588307Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:21:00.294633385Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:22:00.316369374Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:23:00.337905339Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:24:00.360046485Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
{"level":"info","ts":"2025-01-17T13:25:00.381457123Z","msg":"WAL archiving is not working","logging_pod":"cloudnative-pgsql-replicated-cluster-2"}
```

Backup tasks have the `walArchivingFailing` status.

This is what the backup config looks like.

```
backups:
  enabled: true
  endpointURL: http://minio:9000
  s3:
    region: ""
    bucket: "backup-pgsql"
    path: "/v1"
    accessKey: "XXX"
    secretKey: "XXX"
  secret:
    create: true
    name: "s3-creds"
  scheduledBackups:
    - name: daily-backup
      schedule: "0 */10 * * * *"
```

This problem occurs on a clean installation.

My full config

```
version:
  postgresql: "12"

cluster:
  instances: 2
  storage:
    size: 10Gi
  walStorage:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  enablePDB: true
  enableSuperuserAccess: true
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    disableDefaultQueries: false
  postgresql:
    pg_ident:
      - local postgres greg
  initdb:
    database: cloud-db
    owner: greg
    secret:
      name: greg-sql

backups:
  enabled: true
  endpointURL: http://minio:9000
  s3:
    bucket: "backup-pgsql"
    path: "/"
    accessKey: "XXX"
    secretKey: "XXX"
  secret:
    create: true
    name: "s3-creds"
  scheduledBackups:
    - name: daily-backup
      schedule: "0 */10 * * * *"
```

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
