### ISSUE TITLE
[Bug]: Cluster import failing due to cnpg_pooler_pgbouncer Role

### ISSUE THREAD

**Issue by ahussainrc** [cloudnative-pg/cloudnative-pg#6654]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24 (latest patch)

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

**Issue Description**
I am creating a cnpg cluster using another cnpg cluster in bootstap > initdb > import.   
Import is failing on error: could not execute query: ERROR:  role \"cnpg_pooler_pgbouncer\" does not exist.
I know cnpg_pooler_pgbouncer Roles is not to be imported but if pooler is deployed in target cluster, import process should not fail 

**Steps to reproduce**

1. Decide a namespace
`MY_NS="cnpg-import-test"`
`echo $MY_NS`
 
2. Create Namespace
`kubectl create ns $MY_NS`
 
3. Create Admin Secret. This secret will be used by both source as well as target cluster. 
`kubectl apply -f createAdminSecret.yaml -n $MY_NS`
 
4. Create Source Cluster and Pooler
`kubectl apply -f createSourceClusternPooler.yaml -n $MY_NS`

5. Check source cluster and pooler
`kubectl get all -n $MY_NS`
 
7. Create target pooler and cluster using source cluster. `kubectl apply -f createTargetClusternPooler.yaml -n $MY_NS`

Import process will start and failed after some time.  Complete error is attached.

**createAdminSecret.yaml**
```
apiVersion: v1
data:
  password: c2VjcmV0 # secret
  username: cG9zdGdyZXM=  # postgres
kind: Secret
metadata:
  name: postgres-admin-user-secret
type: kubernetes.io/basic-auth
```

**createSourceClusternPooler.yaml**
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster-source
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-1
  instances: 1
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-cluster-app-secret
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-admin-user-secret
  storage:
    #storageClass: managed-nfs-storage
    size: 100Gi
---   
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cluster-source-pooler-rw
spec:
  cluster:
    name: postgres-cluster-source
  type: rw
  instances: 1
  template:
    metadata:
      labels:
        app: pooler
    spec:
      containers:
        - name: pgbouncer
          image: ghcr.io/cloudnative-pg/pgbouncer:1.22.1-14
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  serviceTemplate:
    spec:
      type: LoadBalancer
```

**createTargetClusternPooler.yaml**
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster-target
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-1
  instances: 1
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: source-cnpg-cluster
  externalClusters:
    - name: source-cnpg-cluster
      connectionParameters:
        host: postgres-cluster-source-rw
        user: postgres
        #sslmode: verify-full
        dbname: postgres
      password: 
        name: postgres-admin-user-secret
        key: password
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-admin-user-secret
  storage:
    #storageClass: managed-nfs-storage
    size: 100Gi
---   
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cluster-target-pooler-rw
spec:
  cluster:
    name: postgres-cluster-target
  type: rw
  instances: 1
  template:
    metadata:
      labels:
        app: pooler
    spec:
      containers:
        - name: pgbouncer
          image: ghcr.io/cloudnative-pg/pgbouncer:1.22.1-14
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  serviceTemplate:
    spec:
      type: LoadBalancer
```

### Cluster resource

```shell

```

### Relevant log output

```shell
{"level":"info","ts":"2025-01-24T10:06:10.339515384Z","logger":"pg_dump","msg":"pg_dump: saving encoding = UTF8","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.339613287Z","logger":"pg_dump","msg":"pg_dump: saving standard_conforming_strings = on","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.339863926Z","logger":"pg_dump","msg":"pg_dump: saving search_path = ","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.339936108Z","logger":"pg_dump","msg":"pg_dump: saving database definition","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.438904125Z","msg":"executing database importing section","logging_pod":"postgres-cluster-target-1-import","databaseName":"app","section":"pre-data"}
{"level":"info","ts":"2025-01-24T10:06:10.476891589Z","msg":"Running pg_restore","logging_pod":"postgres-cluster-target-1-import","cmd":"pg_restore","options":["-U","postgres","-d","host=/controller/run port=5432 user=postgres sslmode=disable application_name=cnpg-instance-manager dbname=app","--section","pre-data","/var/lib/postgresql/data/pgdata/dumps/app.dump"]}
{"level":"info","ts":"2025-01-24T10:06:10.830024178Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:10.829 UTC","user_name":"postgres","database_name":"app","process_id":"44","connection_from":"[local]","session_id":"67936612.2c","session_line_num":"1","command_tag":"GRANT","session_start_time":"2025-01-24 10:06:10 UTC","virtual_transaction_id":"3/34","transaction_id":"733","error_severity":"ERROR","sql_state_code":"42704","message":"role \"cnpg_pooler_pgbouncer\" does not exist","query":"REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;\nGRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;\n\n\n","application_name":"cnpg-instance-manager","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:10.830119294Z","logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  role \"cnpg_pooler_pgbouncer\" does not exist","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.830125666Z","logger":"pg_restore","msg":"Command was: REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.830141268Z","logger":"pg_restore","msg":"GRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.830153995Z","logger":"pg_restore","msg":"pg_restore: warning: errors ignored on restore: 1","pipe":"stderr","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.876217807Z","logger":"pg_ctl","msg":"pg_ctl: server is running (PID: 29)\n/usr/lib/postgresql/16/bin/postgres \"-D\" \"/var/lib/postgresql/data/pgdata\" \"-c\" \"port=5432\" \"-c\" \"unix_socket_directories=/controller/run\" \"-c\" \"listen_addresses=127.0.0.1\"\n","pipe":"stdout","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:10.876262185Z","msg":"Shutting down instance","logging_pod":"postgres-cluster-target-1-import","pgdata":"/var/lib/postgresql/data/pgdata","mode":"fast","timeout":null}
{"level":"info","ts":"2025-01-24T10:06:10.878328336Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:10.878 UTC","process_id":"29","session_id":"679365f3.1d","session_line_num":"6","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received fast shutdown request","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:10.934900871Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:10.934 UTC","process_id":"29","session_id":"679365f3.1d","session_line_num":"7","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"aborting any active transactions","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:10.957644275Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:10.957 UTC","process_id":"29","session_id":"679365f3.1d","session_line_num":"8","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"background worker \"logical replication launcher\" (PID 36) exited with exit code 1","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:11.065954155Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:11.065 UTC","process_id":"31","session_id":"679365f3.1f","session_line_num":"1","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"shutting down","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:11.11958448Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:11.119 UTC","process_id":"31","session_id":"679365f3.1f","session_line_num":"2","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint starting: shutdown immediate","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:14.778962416Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:14.778 UTC","process_id":"31","session_id":"679365f3.1f","session_line_num":"3","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint complete: wrote 931 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.492 s, sync=0.001 s, total=3.713 s; sync files=0, longest=0.000 s, average=0.000 s; distance=7388 kB, estimate=7388 kB; lsn=0/1C1CEB0, redo lsn=0/1C1CEB0","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:16.499183381Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-target-1-import","record":{"log_time":"2025-01-24 10:06:16.498 UTC","process_id":"29","session_id":"679365f3.1d","session_line_num":"9","session_start_time":"2025-01-24 10:05:39 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"database system is shut down","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-01-24T10:06:16.530322796Z","logger":"pg_ctl","msg":"waiting for server to shut down......... done","pipe":"stdout","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:16.530356328Z","logger":"pg_ctl","msg":"server stopped","pipe":"stdout","logging_pod":"postgres-cluster-target-1-import"}
{"level":"info","ts":"2025-01-24T10:06:16.530606775Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"postgres-cluster-target-1-import"}
{"level":"error","ts":"2025-01-24T10:06:16.530646703Z","msg":"Error while bootstrapping data directory","logging_pod":"postgres-cluster-target-1-import","error":"while executing logical import: error while executing pg_restore, section:pre-data, exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:160\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2\n\tinternal/cmd/manager/instance/initdb/cmd.go:109\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:68\nruntime.main\n\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/proc.go:272"}
Error: while executing logical import: error while executing pg_restore, section:pre-data, exit status 1
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ahussainrc** [comment]
This issue still exist in the latest version.

**Comment by ncgee** [comment]
Running into a similar problem here with version 1.26 of CloudNativePG, the `import` Pod logs the following after the last `pg_dump` line:

```
{"level":"info","ts":"2025-06-12T13:57:57.194682608Z","msg":"executing database importing section","logging_pod":"postgres-1-import","databaseName":"app","section":"pre-data"}
{"level":"info","ts":"2025-06-12T13:57:57.199599628Z","msg":"Running pg_restore","logging_pod":"postgres-1-import","cmd":"pg_restore","options":["-U","postgres","-d","host=/controller/run port=5432 user=postgres sslmode=disable application_name=cnpg-instance-manager dbname=app","--section","pre-data","/var/lib/postgresql/data/pgdata/dumps/app.dump"]}
{"level":"info","ts":"2025-06-12T13:57:57.257337068Z","logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  role \"cnpg_pooler_pgbouncer\" does not exist","pipe":"stderr","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.257379998Z","logger":"pg_restore","msg":"Command was: REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;","pipe":"stderr","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.257387289Z","logger":"pg_restore","msg":"GRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;","pipe":"stderr","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.257396729Z","logger":"pg_restore","msg":"pg_restore: warning: errors ignored on restore: 1","pipe":"stderr","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.257496418Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.256 UTC","user_name":"postgres","database_name":"app","process_id":"53","connection_from":"[local]","session_id":"684adce5.35","session_line_num":"1","command_tag":"GRANT","session_start_time":"2025-06-12 13:57:57 UTC","virtual_transaction_id":"3/40","transaction_id":"736","error_severity":"ERROR","sql_state_code":"42704","message":"role \"cnpg_pooler_pgbouncer\" does not exist","query":"REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;\nGRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;\n\n\n","application_name":"cnpg-instance-manager","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.261619838Z","logger":"pg_ctl","msg":"pg_ctl: server is running (PID: 32)\n/usr/lib/postgresql/16/bin/postgres \"-D\" \"/var/lib/postgresql/data/pgdata\" \"-c\" \"port=5432\" \"-c\" \"unix_socket_directories=/controller/run\" \"-c\" \"listen_addresses=127.0.0.1\"\n","pipe":"stdout","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.261674058Z","msg":"Shutting down instance","logging_pod":"postgres-1-import","pgdata":"/var/lib/postgresql/data/pgdata","mode":"fast","timeout":null,"pgCtlOptions":["-D","/var/lib/postgresql/data/pgdata","-m","fast","stop","-w"]}
{"level":"info","ts":"2025-06-12T13:57:57.264252769Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.264 UTC","process_id":"32","session_id":"684adce1.20","session_line_num":"6","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received fast shutdown request","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.264346389Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.264 UTC","process_id":"32","session_id":"684adce1.20","session_line_num":"7","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"aborting any active transactions","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.266891918Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.266 UTC","process_id":"32","session_id":"684adce1.20","session_line_num":"8","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"background worker \"logical replication launcher\" (PID 39) exited with exit code 1","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.267109839Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.266 UTC","process_id":"34","session_id":"684adce1.22","session_line_num":"1","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"shutting down","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.267339299Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.267 UTC","process_id":"34","session_id":"684adce1.22","session_line_num":"2","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint starting: shutdown immediate","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.279080119Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.278 UTC","process_id":"34","session_id":"684adce1.22","session_line_num":"3","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint complete: wrote 931 buffers (2.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.011 s, sync=0.001 s, total=0.012 s; sync files=0, longest=0.000 s, average=0.000 s; distance=7389 kB, estimate=7389 kB; lsn=0/1C1D4B8, redo lsn=0/1C1D4B8","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.288663279Z","logger":"postgres","msg":"record","logging_pod":"postgres-1-import","record":{"log_time":"2025-06-12 13:57:57.288 UTC","process_id":"32","session_id":"684adce1.20","session_line_num":"9","session_start_time":"2025-06-12 13:57:53 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"database system is shut down","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-06-12T13:57:57.364486909Z","logger":"pg_ctl","msg":"waiting for server to shut down.... done","pipe":"stdout","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.364537759Z","logger":"pg_ctl","msg":"server stopped","pipe":"stdout","logging_pod":"postgres-1-import"}
{"level":"info","ts":"2025-06-12T13:57:57.364722899Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"postgres-1-import"}
{"level":"error","ts":"2025-06-12T13:57:57.364787469Z","msg":"Error while bootstrapping data directory","logging_pod":"postgres-1-import","error":"while executing logical import: error while executing pg_restore, section:pre-data, exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:163\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2\n\tinternal/cmd/manager/instance/initdb/cmd.go:112\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071\nmain.main\n\tcmd/manager/main.go:71\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.3/x64/src/runtime/proc.go:283"}
Error: while executing logical import: error while executing pg_restore, section:pre-data, exit status 1
```

Using the monolith option, the configuration is as follows with the source cluster running PostgreSQL 15.10 and the target cluster PostgreSQL 16.9, both using the same configurations with the exception of the bootstrap section:

```
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - app
          - <redacted>
          - <redacted>
          - <redacted>
        roles:
          - app
          - <redacted>
          - <redacted>
          - <redacted>
        source:
          externalCluster: <prefix>-postgres
  externalClusters:
    - name: <prefix>-postgres
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: <prefix>-postgres-rw
        user: postgres
        dbname: postgres
        sslmode: require
      password:
        name: <prefix>-postgres-superuser
        key: password
```

The `app` database is empty, and the names of the databases and roles to import have been triple checked to make sure they match the source cluster. This error also occurs when the `app` database is omitted.

**Comment by ncgee** [comment]
Because the documentation said the `cnpg_pooler_pgbouncer` role is ignored I didn't think to try this before, but it seems to help to add

```
  bootstrap:
    initdb:
      import:
        pgDumpExtraOptions:
          - --no-privileges
```

This omits the `GRANT ALL ON FUNCTION` for the pgbouncer role which lets the import process complete. However, it also omits a `REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;`, and this also seems to be missing from subsequent `pg_dump`s on the new cluster. It's unclear to me whether this is a problem. Manually running the revoke against all databases restores it to `pg_dump` outputs as well.
