### ISSUE TITLE
Extend the API with the new fields for replication slots management

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#669]
Extend the API to support this:

``` yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  # Replication slots management configuration
  replicationSlots:

    # Replication slots for high availability configuration
    highAvailability:

      # This flag enables the usage of replication slots
      # for  purposes.
      # This can only be set at creation time.
      enabled: false

      # Prefix for replication slots managed by the operator for HA
      # (default `_cnpg_`).
      # This can only be set at creation time.
      slotPrefix: _cnpg_

    # Standby will update the status of the local replication slots
    # every `updateInterval` seconds.
    updateInterval: 300

  storage:
    size: 1Gi
```

The proposed API changes are meant to be merged in the `feature/haslots` branch.
