### ISSUE TITLE
[Feature]: bootstrap container in the DB pod should do init/join tasks instead of a separate job for ReadWriteOnce StorageClass

### ISSUE THREAD

**Issue by qdrddr** [cloudnative-pg/cloudnative-pg#6703]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I only have storage with the RedWriteOnce policy, meaning the PVC can be mounted to multiple pods/jobs ONLY if they reside on the same k8s node. My init/join jobs are created on separate nodes, creating unsolvable problems.

I believe relying on ReadWriteMany is not a correct approach for redistributing the PG cluster.

### Describe the solution you'd like

The bootstrap container in the DB pod will always be located with the DB instance, it is an ideal candidate to perform init/join tasks instead of separate job. Jobs should not mount volumes since they can run on another node.

### Describe alternatives you've considered

Trying to play with `nodeAffinity: requiredDuringSchedulingIgnoredDuringExecution` so the job would execute on the same node as the container to correctly bootstrap/init. Or you must have a ReadWriteMany storageClass...

### Additional context

Workaround idea: You can create an init container in the DB POD that would not mount any volumes untill the bootsrtap job is completed. In this case even the volume is attached to a Job on one node, the ReadWriteOnce volume will be detached and can be re-attached by the CSI to another node.

- k8s: v1.27
- cnpg operator v1.25 deployed [as manifests](https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/tags/v1.25.0/releases/cnpg-1.25.0.yaml)

eample of the deployed cluster manifest:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iam-cnpg
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 16.4-bullseye
spec:
  instances: 3
  description: "iam DB"
  imageName: "ghcr.io/cloudnative-pg/postgresql:16.4-bullseye"


  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: iam
      owner: iam
      secret:
        name: iam-cnpg-secret

  storage:
    storageClass: local-path
    size: 20Gi
  walStorage:
    storageClass: local-path
    size: 20Gi

  monitoring:
    enablePodMonitor: false

  nodeMaintenanceWindow:
    reusePVC: false
```

### Backport?

N/A

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
