### ISSUE TITLE
[Bug]: User database owner password is reset during rolling update (initdb)

### ISSUE THREAD

**Issue by Nils98Ar** [cloudnative-pg/cloudnative-pg#6762]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

arnold@aov.de

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

Helm

### What happened?

Is it expected that the password of the user `appuser` is reset to the value from the secret `appuser-initial-credentials` during a rolling update to a newer postgres minor version?

If so, is there any way to only define an **initial** password and to not reset it during updates?

### Cluster resource

```shell
kubectl get cluster -n postgres db-1  -o yaml | yq '.spec.bootstrap':

{
  "initdb": {
    "database": "appdb",
    "encoding": "UTF8",
    "localeCType": "C",
    "localeCollate": "C",
    "owner": "appuser",
    "postInitSQL": [
      "ALTER USER appuser WITH SUPERUSER"
    ],
    "secret": {
      "name": "appuser-initial-credentials"
    }
  }
}
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by pchovelon** [comment]
Can you give the YAML file ?

**Comment by mkris98** [comment]
@Nils98Ar you can try doing something like this to initialize an empty pgcluster without the app db.
Then you can create create the app users via a secret for example and grant the specific privileges you want
 
```
  bootstrap:
    initdb:
      localeCollate: 'en_US.utf8'
      localeCType: 'en_US.utf8'
      database: postgres
      owner: postgres
      secret:
        name: postgres-superuser-secret
      dataChecksums: true
      encoding: 'UTF8' #default
      postInitTemplateSQLRefs:
        secretRefs:
        - name: secret-init-roles
          key: create-initroles.sql
          
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser-secret
```

**Comment by Nils98Ar** [comment]
@pchovelon
> Can you give the YAML file ?

Do you need more than the bootstrap part?

```
kubectl get cluster -n postgres db-1  -o yaml | yq '.spec.bootstrap':
{
  "initdb": {
    "database": "appdb",
    "encoding": "UTF8",
    "localeCType": "C",
    "localeCollate": "C",
    "owner": "appuser",
    "postInitSQL": [
      "ALTER USER appuser WITH SUPERUSER"
    ],
    "secret": {
      "name": "appuser-initial-credentials"
    }
  }
}
```

@mkris98 Okay `postInitTemplateSQLRefs` could work. Or simply `postInitApplicationSQL`?

But if the user password is reset to the value from `initdb.secret` during upgrades, isn't the `postInitTemplateSQLRefs` and `initdb.postInitApplicationSQL` applied during updates again as well? Or only during the initial deployment?

**Comment by mkris98** [comment]
@Nils98Ar You can use postInitTemplateSQL f.e.

If you want to provision the application database with the user and you want to change the password for the user, then you can patch the password in the secret and trigger a reload of the configuration in the cluster.

Regarding postinitsql / postinitemplatesqls.
The sql commands will only execute once right after the creation of the pgcluster.

**Comment by Nils98Ar** [comment]
@mkris98

So `.spec.bootstrap.initdb.secret` is not usable for initial passwords as the password is always reset/reconfigured during rolling updates? The users of the DBs do not have access to Kubernetes and change the passwords via psql / pgAdmin in our case. So editing the secret is not an option for them.

If so we should probably switch to the postinitsql / postinitemplatesql approach. And the description of "secret" in the API reference should propably be improved ("initial credential")? https://cloudnative-pg.io/documentation/1.25/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapInitDB

**Comment by mkris98** [comment]
@Nils98Ar thats how kubernetes works, you have secrets to store sensitive information. If you dont specify the secret it gets created with a random password. If you specify the secret, you have to precreate it in the same namespace.

Please look up secrets and configmaps from the official kubernetes documentation. 

If you want to precreate users and set an initial password which can be changed by the users then I would suggest you create those inital users via the postinitsql section. 

Maybe you also want to have a look at secret management tools.

**Comment by Nils98Ar** [comment]
@mkris98 Yes I know how secrets and secret mgmt work but in this case we we only want to set the the password initially as the users have no access to K8s. We will switch to the postinitsql approach :)

I still think the [api reference](https://cloudnative-pg.io/documentation/1.25/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapInitDB) could be misinterpreted:
> Name of the secret containing the initial credentials for the owner of the user database.

**Comment by cowwoc** [comment]
Can one of the committers please confirm the expected behavior of `.spec.bootstrap.initdb.secret`? I see no indication in the documentation that it is run as part of a rolling update. It might make sense for this to be the case (e.g. after a major version update) but the documentation should explicitly spell this out.

**Comment by qbilon** [comment]
I have a similar issue regarding the password. 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: superfancydb
  namespace: test
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  managed:
    roles:      
      - name: hans
        login: true
        passwordSecret:
          name: hans-app      
      - name: juergen
        login: true
        passwordSecret:
          name: juergen-app      
  bootstrap:
    initdb:
      database: superfancydb
      owner: hans
      encoding: UTF8
```

At initial startup everything works great and the credentials from the `hans-app` are chosen. Now when i re-start my PC (leads to a restart of my local k3s). Sometimes the password in the secret `hans-app` (as intended) is chosen for the database role. But sometimes the one from `superfancydb-app` (the default secret one cnpg creates for the owner) is chosen, which leads to a SASL error in my app
