### ISSUE TITLE
[Bug]: Unable to backup to minio - SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jpabbuehl** [cloudnative-pg/cloudnative-pg#6875]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

I want to configure scheduled DB backup to minio s3 bucket, configured with self-signed certificate as described here https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager.html

I have confirmed that the self-signed cert-manager configuration is running as expected using a test pod mounted with secret ca.crt and running aws s3 cli command (see below)

However, I am not able to configure the backup properly.
Logs are pointing toward SSL error but I cannot sort out how to fix that after multiple attempts.

Thanks

JP
```
apiVersion: v1
kind: Pod
metadata:
  name: minio-test
  namespace: crawler-storage
spec:
  containers:
  - name: awscli
    image: amazon/aws-cli:latest
    command: ['sleep', '3600']
    env:
    - name: AWS_ACCESS_KEY_ID
      value: testtest
    - name: AWS_SECRET_ACCESS_KEY
      value: testtest
    - name: AWS_ENDPOINT_URL
      value: https://minio.crawler-storage.svc.cluster.local
    - name: AWS_CA_BUNDLE
      value: /etc/ssl/certs/ca.crt
    volumeMounts:
    - name: ca-cert-volume
      mountPath: /etc/ssl/certs/ca.crt
      subPath: ca.crt
      readOnly: true
  volumes:
  - name: ca-cert-volume
    secret:
      secretName: tenant-1-ca-tls
      items:
      - key: ca.crt
        path: ca.crt
```

```
kubectl exec -it minio-test -n crawler-storage -- aws s3 ls
2025-02-18 08:45:11 backup
2025-02-18 08:45:11 data
```

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crawler-db
  namespace: crawler-database
spec:
  description: "Database for crawler"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-3
  instances: 1
  startDelay: 30
  stopDelay: 30
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-auth
  logLevel: warning
  storage:
    size: 1Gi
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: false
  backup:
    barmanObjectStore:
      destinationPath: "s3://backup"
      endpointURL: "https://minio.crawler-storage.svc.cluster.local"
      s3Credentials:
        accessKeyId:
          name: cnpg-minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio-creds
          key: ACCESS_SECRET_KEY
      serverName: crawler-db
      endpointCA:
        name: tenant-1-ca-tls
        key: ca.crt
      wal:
        compression: gzip
      data:
        compression: gzip
      tags:
        retention: "30days"
    retentionPolicy: "30d"
```

### Relevant log output

```shell
{"level":"info","ts":"2025-02-19T00:03:52.906360941Z","logger":"barman-cloud-check-wal-archive","msg":"2025-02-19 00:03:52,905 [61] ERROR: Barman cloud WAL archive check exception: SSL validation failed for https://minio.crawler-storage.svc.cluster.local/backup [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)","pipe":"stderr","logging_pod":"crawler-db-1"}
{"level":"error","ts":"2025-02-19T00:03:53.032969254Z","logger":"wal-archive","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"crawler-db-1","options":["--endpoint-url","https://minio.crawler-storage.svc.cluster.local","--cloud-provider","aws-s3","s3://backup","crawler-db"],"exitCode":-1,"error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241219102532-2807bc88310d/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/walarchive.(*BarmanArchiver).CheckWalArchiveDestination\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20241218093921-134c7de4954a/pkg/walarchive/cmd.go:178\ngithub.com/cloudnative-pg/barman-cloud/pkg/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20241218093921-134c7de4954a/pkg/archiver/archiver.go:131\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.checkWalArchive\n\tpkg/management/postgres/archiver/archiver.go:320\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.internalRun\n\tpkg/management/postgres/archiver/archiver.go:191\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.Run\n\tpkg/management/postgres/archiver/archiver.go:139\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:62\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:68\nruntime.main\n\t/opt/hostedtoolcache/go/1.23.4/x64/src/runtime/proc.go:272"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
