### ISSUE TITLE
[Bug]: certificate alternative dns names have wrong domain

### ISSUE THREAD

**Issue by mrksngl** [cloudnative-pg/cloudnative-pg#6979]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

I just stumbled upon the certificates in the `status` of my `cluster`:
```yaml
status:
  certificates:
    serverAltDNSNames:
    - postgresql-rw
    - postgresql-rw.postgresql
    - postgresql-rw.postgresql.svc
    - postgresql-rw.postgresql.svc.cluster.local
    - postgresql-r
    - postgresql-r.postgresql
    - postgresql-r.postgresql.svc
    - postgresql-r.postgresql.svc.cluster.local
    - postgresql-ro
    - postgresql-ro.postgresql
    - postgresql-ro.postgresql.svc
    - postgresql-ro.postgresql.svc.cluster.local
```

The thing that made me wonder is: my kubernetes domain is not `cluster.local`.
So I went into the code and figured that function `GetClusterAltDNSNames` returns the dns names with `cluster.local` hard-coded.

I know that `cluster.local` is the default domain of kubernetes clusters, but can be altered to more or less anything.
So in my opinion, that should at least be configurable.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgresql
spec:
# irrelevant
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
