### ISSUE TITLE
[Bug]: Duplicated metrics collected when enabling both cluster and pooler pod monitors

### ISSUE THREAD

**Issue by Jean-Daniel** [cloudnative-pg/cloudnative-pg#7006]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

When creating a cluster with podMonitor enabled, the pod monitor are using the following pod selector:

```yaml
  selector:
    matchLabels:
      cnpg.io/cluster: analytics-pg17
```

This selector also matches other extra components like the pgbouncers that are deployed using a `Pooler` and can also specify their own pod monitors.

The cluster pod monitor should also include an extra label to limit its scope to the pods that are owned by the `Cluster` CRD.

For instance:

```yaml
  selector:
    matchLabels:
      cnpg.io/cluster: analytics-pg17
      cnpg.io/podRole: instance
```

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: analytics-pg17
spec:
  …
  monitoring:
    enablePodMonitor: true
  …
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
