### ISSUE TITLE
Cluster fails to ready on initdb.

### ISSUE THREAD

**Issue by shrinedogg** [cloudnative-pg/cloudnative-pg#714]
I'm unable to get a Cluster to ready on my baremetal k3s cluster with some basic options. The error I'm getting is:

`{"level":"error","ts":1662668796.8657594,"msg":"PostgreSQL process exited with errors","logging_pod":"cloudnative-pg-01-2","error":"signal: bus error (core dumped)","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/run/lifecycle.(*PostgresLifecycle).Start\n\tinternal/cmd/manager/instance/run/lifecycle/lifecycle.go:99\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/runnable_group.go:219"}`

I believe this begins the chain of errors:

![image](https://user-images.githubusercontent.com/53411346/189237677-942a53d0-3c8a-456d-9296-b2cba641103b.png)

Here's the Cluster resource manifest:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-01
  namespace: cnpg-system
spec:
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-app-user
  instances: 3
  primaryUpdateStrategy: unsupervised
  resources:
    requests:
      memory: 2Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"
  storage:
    size: 8Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      volumeMode: Filesystem
  superuserSecret:
    name: cnpg-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: "s3://cnpg/cnpg/"
      s3Credentials:
        accessKeyId:
          name: cnpg-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-s3
          key: ACCESS_SECRET_KEY
```

I also attached the pod logs that fails.

[logs.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/9531003/logs.txt)
