### ISSUE TITLE
[Bug]:  provided user name (app) and authenticated user name (cnpg_pooler_pgbouncer) do not match

### ISSUE THREAD

**Issue by pavaneeshwar7077** [cloudnative-pg/cloudnative-pg#7152]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

pavaneeasdasdshwar7077@gmail.com

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

I am trying to login with pgadmin using SSL , 
I had supplied root certificate as ca certificate and ssl mode as verify full

I don't know why app user is being used for login because pgbouncer sits in between pgadmin and postgres it should use cnpg pg bouncer user. This is causing our production to delay. 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pgbouncer
  namespace: {{.Values.namespace.name}}
spec:
  cluster:
    name: {{.Values.cluster.name}}
  instances: 1                            # total no of instances , independent of cluster nodes
  type: rw                                # target primary cluster
  pgbouncer:
    poolMode: session                     # maintain connections for each session
    parameters:
      max_client_conn: "1000"             # per instance
      default_pool_size: "30"             # total connection pool
---------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-pgbouncer-lb
  namespace: {{.Values.namespace.name}}
spec:
  type: LoadBalancer 
  selector:
    cnpg.io/poolerName: postgres-pgbouncer
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 5432
-----------------------

{{- if eq .Values.cluster.mode "init" }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{.Values.cluster.name}}
  namespace: {{.Values.namespace.name}}
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  enableSuperuserAccess: true
  certificates:
    serverAltDNSNames:
      - postgres3.altiushub.com
      - postgres.altiushub.com
      - database-test.altiushub.com
      - postgres-pgbouncer-lb
      - postgres-pgbouncer-lb.altiushub-blob-incremental
      - postgres-pgbouncer-lb.altiushub-blob-incremental.svc
      - postgres-pgbouncer-lb.altiushub-blob-incremental.svc.cluster.local
      - postgres-pgbouncer
      - postgres-pgbouncer.altiushub-blob-incremental
      - postgres-pgbouncer.altiushub-blob-incremental.svc
      - postgres-pgbouncer.altiushub-blob-incremental.cluster.local
      - 20.235.192.238
  superuserSecret:
    name: postgres-superuser-secret
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
      postInitSQL:
      # Users and Databases Creation
      {{- range $dbName, $db := .Values.databases }}
      {{- if ne $db.name "postgres" }}
      - CREATE USER {{ $db.user.username }} WITH PASSWORD '{{ $db.user.password }}';
      - CREATE DATABASE {{ $db.name }} OWNER {{ $db.user.username }};
      {{- end }}
      {{- end }}
      
      # create pgbouncer role 
      - CREATE ROLE cnpg_pooler_pgbouncer WITH LOGIN;

      # Grant connection to pgbouncer user
      {{- range $dbName, $db := .Values.databases }}
      - SET search_path TO {{ $db.name }};
      - GRANT CONNECT ON DATABASE {{ $db.name }} TO cnpg_pooler_pgbouncer;
      {{- end }}

      # Add pgbouncer config
      {{- range $dbName, $db := .Values.databases }}
      - SET search_path TO {{ $db.name }};
      - {{ $.Values.sql.poolerSetup | indent 8 | trim }}
      {{- end }}


  affinity:
    nodeSelector:
      pool_name: {{.Values.pool.name}}
  probes:
    startup:
      periodSeconds: 3                    # periodic check for startup
      timeoutSeconds: 3                   # timeout for each checks
      failureThreshold: 10                # maximum failures to make a node mark as failed
    liveness:                             # to check whether all instances are properly working or not
      periodSeconds: 10                   # periodic check for liveness
      timeoutSeconds: 10                  # timeout for each check
      failureThreshold: 10                # maximum failures to make a node mark as failed, as this should be alive always
    readiness:                            # to check whether all instances are ready to accept traffic or not
      periodSeconds: 10                   # periodic check for readiness
      timeoutSeconds: 10                  # timeout for each check
      failureThreshold: 20                # maximum failures to make a node mark as failed, as this should be accept the traffic
  failoverDelay : 0                       # time to start the failover procedure when this node is marked as unhealthy
  smartShutdownTimeout: 180               # stop new connections from assigning to a deleted node
  stopDelay: 1800                         # for deleting all connections and streaming WAL and later forcibly shut down
  switchoverDelay: 3600                   # promoting other node as primary node
  primaryUpdateStrategy: unsupervised     # kubernetes handles the rolling update of the spec changes
  primaryUpdateMethod: switchover         # after updating the replicas primary node to switched to one of the replica
  replicationSlots: 
    updateInterval: 30                    # how often WAL slots are replicated on local storage of standby nodes from primary nodes
    highAvailability: 
      enabled: true                       # enable replication of slots on standby nodes
  
  backup:
    volumeSnapshot:
      className: postgres-volume-storage-class-snap
    target: "prefer-standby"              # prefer latest standby node for backup, not primary because there may be chance of shuttind down in case of cold backup
    barmanObjectStore:
      destinationPath: "{{.Values.azure.destinationPath}}"
      serverName: {{.Values.azure.serverName}}
      azureCredentials:
        connectionString:
          name: azure-creds
          key: AZURE_STORAGE_CONNECTION_STRING
      wal:                                 # properties for storing the WAL backups , these are taken as incremental 
        compression: gzip
        encryption: AES256
    retentionPolicy: "30m"                 # retention of each backup

  postgresql:
    pg_hba:
      - hostssl all all all cert
    synchronous:                           # synchronous replication
      method: any                          # transaction commits wait until their WAL records are replicated to available nodes
      number: 1                            # wait for total nodes on which replication should happen
      dataDurability: required             # each write commit should be ack by above number of standby nodes to commit in primary node
      maxStandbyNamesFromCluster: 1        
      standbyNamesPre:                     # standby node naming
        - pg-standby
  monitoring:
    enablePodMonitor: true                 # show grafana dashboard
  resources:
    requests:                              # minimum amount of resources to assign a pod to a node
      memory: "12288Mi"
      cpu: 1
    limits:                                # maximum amount of resources assigned to a pod
      memory: "15360Mi"
      cpu: 2
  storage:                                 # postgres data storage
    storageClass: postgres-storage-class-snap
    size: "1Gi"
  walStorage:                              # postgres WAL storage
    storageClass: postgres-storage-class-snap
    size: "1Gi"
{{- end }}
--------------------
# node pool
pool: 
  name: databasesnap

# namespace
namespace:
  name: altiushub-blob-incremental


# app
temp:
  user: app
  password: "Test@123"

# cluster
cluster:
  name: postgres-cluster-blob-incremental
  mode: init  
  time: "2025-03-11 09:29:59"    


# azure credentials
azure:
  destinationPath: 
  serverName: altiushub-blob-incremental
  secrets:
    AZURE_STORAGE_CONNECTION_STRING: 
    AZURE_STORAGE_ACCOUNT_NAME: 
    AZURE_STORAGE_ACCOUNT_KEY: 


# database secrets
databases:
  postgres:
    name: postgres
    user: 
      username: postgres                
      password: "Test@123"              
  development:
    name: development
    user: 
      username: dev_usr
      password: "Test@123"
  staging:
    name: staging
    user:
      username: staging_usr
      password: "Test@123"
  prod:
    name: production
    user:
      username: prod_usr
      password: "Test@123"

# pgbouncer init for databases
sql:
  poolerSetup: |
    CREATE OR REPLACE FUNCTION public.user_search(uname TEXT)
      RETURNS TABLE (usename name, passwd text)
      LANGUAGE sql SECURITY DEFINER AS
      'SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1;';
    REVOKE ALL ON FUNCTION public.user_search(text) FROM public;
    GRANT EXECUTE ON FUNCTION public.user_search(text) TO cnpg_pooler_pgbouncer;
```

### Cluster resource

```shell

```

### Relevant log output

```shell
{"level":"info","ts":"2025-03-15T20:36:23.960586651Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-blob-incremental-1","record":{"log_time":"2025-03-15 20:36:23.960 UTC","user_name":"app","database_name":"app","process_id":"6703","connection_from":"10.224.0.238:59952","session_id":"67d5e4c7.1a2f","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-03-15 20:36:23 UTC","virtual_transaction_id":"6/921","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"provided user name (app) and authenticated user name (cnpg_pooler_pgbouncer) do not match","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-03-15T20:36:23.960625684Z","logger":"postgres","msg":"record","logging_pod":"postgres-cluster-blob-incremental-1","record":{"log_time":"2025-03-15 20:36:23.960 UTC","user_name":"app","database_name":"app","process_id":"6703","connection_from":"10.224.0.238:59952","session_id":"67d5e4c7.1a2f","session_line_num":"2","command_tag":"authentication","session_start_time":"2025-03-15 20:36:23 UTC","virtual_transaction_id":"6/921","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28000","message":"certificate authentication failed for user \"app\"","detail":"Connection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 19: \"hostssl all all all cert\"","backend_type":"client backend","query_id":"0"}}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
