### ISSUE TITLE
[Bug]: Unable to connect with LDAP enabled and though Pooler instances.

### ISSUE THREAD

**Issue by metalshanked** [cloudnative-pg/cloudnative-pg#7156]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Connecting through the pooler instance with LDAP enabled gives an Authentication failure
I understand PG only allows 1 auth at a time so in the below settings it will only use the pg_hba settings which has "all".

However, removing those pg_hba settings and using only LDAP seems to cause the Auth failure with the Pooler
Direct connection to CNPG cluster service --> Works with LDAP
Connection Through Pooler --> Auth Failure with LDAP

Example Config.
```
postgresql:
    #New sync method instead of old quorum based minsync and maxsync replica
    synchronous:
      method: any
      number: 1
      dataDurability: preferred
    pg_hba:
       # Remove all to use LDAP
       #host db  user      clientip    auth+encrypt-method
      - host all postgres 0.0.0.0/0 scram-sha-256
      - host all postgres ::/0 scram-sha-256
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
    # LDAP wont be used if above pga_hba has "all" for users since PG only supports 1 auth type at time for users
    ldap:
      server: 'ldap_server'
      scheme: 'ldap/s'
      port: 123
      tls: false
      bindSearchAuth:
        baseDN: 'OU=people,DC=org,DC=net'
        bindDN: 'CN=du,OU=people,DC=org,DC=net'
        bindPassword:
        searchAttribute: 'uid'
```

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
