### ISSUE TITLE
[Feature]: Dynamic loading of PostgreSQL extensions

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#7188]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently, extensions must be part of the base image of the operand, requiring pre-determination of the entire content of the Postgres image and preventing dynamic loading of extensions.

The reason is detailed in this blog article that I wrote: https://www.gabrielebartolini.it/articles/2025/03/the-immutable-future-of-postgresql-extensions-in-kubernetes-with-cloudnativepg/

### Describe the solution you'd like

Following the exploration work done in #6546 and the PostgreSQL 18 feature for `extension_control_path` we contributed to (see https://github.com/postgres/postgres/commit/4f7f7b0375854e2f89876473405a8f21c95012af), we should enable dynamic loading of extensions via the new `ImageVolume` feature introduced in Kubernetes 1.33. This guarantees immutability of container images.

Rollout is required by image volumes.

This feature will only be available with Postgres 18 and Kubernetes 1.33+. Also, extensions must be distributed as self-contained images - this is part of another initiative, outside CloudNativePG.

Image catalogs must be considered as well.

### Describe alternatives you've considered

We have considered mutable solutions (use a mutable volume to install needed extensions), but we preferred to contribute to Postgres improvements and exploit innovation in Kubernetes with Image Volumes.

### Additional context

See the blog article cited above.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
My initial (unbinding) proposal is to enable the definition of extension images at the following two layers:
 
- Image Catalog (either global or local in the namespace)
- Directly in the extension definition (`.spec.postgresql.extension`), overriding the above when defined

The following scenarios could provide some ideas and help elaborate on the solution to the problem.

## No image catalog involved

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg18
spec:
  instances: 1
  imageName: # ... PostgreSQL 18 container image
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: # ...pgvector container image for PostgreSQL 18
  storage:
    size: 1Gi
```

The operator will mount the referenced image as a volume.

## With image catalog

Consider the following catalog:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: default
spec:
  images:
    # ...
    - major: 18
      image: # ... PostgreSQL 18 container image
      extensions:
        - name: pgvector
          image: # ...pgvector container image for PostgreSQL 18
```

A possible cluster definition could be:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg18
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 18
  postgresql:
    extensions:
      - name: pgvector
  storage:
    size: 1Gi
```

Given that the `Cluster` already points to a catalog definition for version 18 and requires the `pgvector` extension, the operator will point to the only `pgvector` extension image declared in the catalog for PostgreSQL 18. If no such extension exists, the change fails.

Theoretically, we could also enable overriding the extension definition in the `.spec.postgresql.extensions` stanza, like in the following example.

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg18-direct-extension
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 18
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: # ... alternative pgvector container image for PostgreSQL 18
  storage:
    size: 1Gi
```

The override here will request a different image from the one in the catalog.

<strike>
## Extension version specification

A catalog might enable the specification of multiple versions of an extension:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: default
spec:
  images:
    # ...
    - major: 18
      image: # ... PostgreSQL 18 container image
      extensions:
        - name: pgvector
          version: x
          image: # ... pgvector version x container image for PostgreSQL 18
        - name: pgvector
          version: y
          image: # ... pgvector version y container image for PostgreSQL 18
```

NOTE: Should we enforce x and y to be specific versions of the extension like 0.8.0? Or leave it at the discretion of the catalog maintainer?

When versions are specified, we should make sure that ambiguity is removed at the Cluster level. Take this example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg18-direct-extension
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 18
  postgresql:
    extensions:
      - name: pgvector
        version: y
        image:
          reference: # ... alternative pgvector container image for PostgreSQL 18
  storage:
    size: 1Gi
```

In this case, the "y" version of the extension image is selected.

We need to decide what to do when the version is defined in just one of the locations:

- defined in the image catalog, not defined in the cluster definition
- vice-versa

A conservative approach is to reject any change and request that the catalog image and the cluster definition be both versioned, or not.
</strike>

**Comment by gbartolini** [comment]
Thanks for your time @theory.

> * Does the catalog need a way to specify the default version of an extension when it has multiple versions? This would hand the case where the Cluster doesn't declare a version.

That could be a good idea indeed. Something like:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: default
spec:
  images:
    # ...
    - major: 18
      image: # ... PostgreSQL 18 container image
      extensions:
        - name: pgvector
          version: x
          image: # ... pgvector version x container image for PostgreSQL 18
        - name: pgvector
          version: y
          image: # ... pgvector version y container image for PostgreSQL 18
          default: true
```

> * Regarding your question about enforcing the version spec in the catalog, I think no, since there is no standard for Postgres extension version formats (alas).

👍🏻 

> * In the last example, the `.spec.postgresql.extensions` stanza has an item that declares both a version and a reference. Seems like the version would be ignored in this case, right? Maybe it should be disallowed when the image reference is present.

I guess we could use the version as a suffix in the mount point. For example, "pgvector-x". In case we want to mount multiple versions of the same extensions (see next item).

> * Oh, I see, maybe you're suggesting that it would use the version from the catalog if it exists, and if not fall back on the image reference? Honestly that feels a little dodgy to me; it makes the Cluster manifest less deterministic.

I am suggesting to override the catalog. But, it is up to us. If it complicates the interface, it is probably better to start with a conservative approach. Either you use the catalog or not.

> Also, with a list of extensions in the `Cluster` manifest, what would this configuration do?
> 
>       - name: pgvector
>         version: x
>       - name: pgvector
>         version: y
> Seems like the same name should be disallowed, yes? In which case maybe it should be an object rather than an array?

You have more experience than me on this topic. I was thinking of enabling multiple versions of the same extension, in different paths. If you don't think there's a use case for that, we can simplify the implementation a lot.

**Comment by theory** [comment]
> That could be a good idea indeed. Something like:

Yeah, or else list versions:

```yaml
      extensions:
        pgvector:
          default_version: x
          versions:
            - version: x
              image: # ... pgvector version x container image for PostgreSQL 18
            - version: y
              image: # ... pgvector version y container image for PostgreSQL 18
```

Which is perhaps easier to validate.

> I am suggesting to override the catalog. But, it is up to us. If it complicates the interface, it is probably better to start with a conservative approach. Either you use the catalog or not.

I say start conservative and see where demand leads.

> You have more experience than me on this topic. I was thinking of enabling multiple versions of the same extension, in different paths. If you don't think there's a use case for that, we can simplify the implementation a lot.

Postgres doesn't really support that pattern. If, for example, we have

```ini
extension_control_path = '$system:/extensions/vector-0.6.5/share:/extensions/vector-0.7.0/share'
```

When someone executes `CREATE EXTENSION vector`, Postgres will find the control file in `/extensions/vector-0.6.5/share` and never even search `/extensions/vector-0.7.0/share`.

Until Postgres itself supports this pattern, I wouldn't bother supporting multipole versions, either.

**Comment by gbartolini** [comment]
Based on your reply, I would start with a simple approach for now that doesn't consider versions. I have struck through that section above.

**Comment by itay-grudev** [comment]
In addition to what's discussed here I want to raise your attention to another problem. This is the sequence of events when we perform a rolling upgrade with a switchover and the new Docker image ships a new version of a shared preload library that contains non-backwards compatible ABI changes:

1. Replica 1 is upgraded to the new Docker Image
2. Replica 2 is upgraded to the new Docker Image
3. Switchover of the current primary to Replica 1
4. `ALTER EXTENSION UPDATE TO ...` on the new primary
5. Old primary is upgraded to the new Docker Image

Between step 1 and step 4, there are two read-only replicas that are in a state, where they are running the new version of a shared preload library extension before its schema is upgraded (as that can only happen after a switchover with an upgraded primary).

Any calls to functions with a changed signature will result in a Postgres FATAL crash. There is a failure scenario where standby replicas would continuously crash preventing a switchover. This could partially cripple the cluster.

I raised this as a potential problem in the May 21 and June 19 meetings. I was investigating an option to disable connections to un-upgraded instances by modifying Ready-ness probes, so they are not included in their corresponding Kubernetes services. But that won't work, as the operator won't promote an replica that's not ready.

In the latter meeting @gbartolini proposed a much better alternative solution by modifying the `pg_hba` file to prevent connections to replicas that haven't received the `ALTER EXTENSION UPDATE` changes. This behavior can be toggled with a configuration option called `disableConnectionsIfNotAligned` on your proposed new extension configuration. I also believe the option should be `false` by default, as enabling it would decrease the cluster's read-only query capacity during upgrades. And while this is a potentially dangerous scenario it is unlikely to happen as it requires: (1) And extension upgrade with non-backwards compatible ABI changes and (2) queries that constantly call the problematic functions. I think such a situation is rare, and the configuration option should only be enabled on extensions known to have changes.

**Comment by theory** [comment]
Seems like yet another example of the overall challenge of ABI/API compatibility of extension upgrades. I like the `disableConnectionsIfNotAligned` proposal, though it will have to be aware of what's installed in every database in a cluster. Not a big deal, I suppose. I agree it should be false by default, as many extensions have no compatibility issues. But maybe we want to have some sort of per-extension configuration to indicate that `ALTER EXTENSION UPDATE` is required. Would be super useful in metadata in each extension image.

**Comment by gbartolini** [comment]
> Seems like yet another example of the overall challenge of ABI/API compatibility of extension upgrades. I like the `disableConnectionsIfNotAligned` proposal, though it will have to be aware of what's installed in every database in a cluster. Not a big deal, I suppose. I agree it should be false by default, as many extensions have no compatibility issues. But maybe we want to have some sort of per-extension configuration to indicate that `ALTER EXTENSION UPDATE` is required. Would be super useful in metadata in each extension image.

Let's keep the option open for this feature, although I would postpone this for the next release.

**Comment by gbartolini** [comment]
I spoke with @NiccoloFei and @mnencia this morning. We plan to prioritise an initial implementation that only covers the `.spec.postgresql.extension` definition, deferring the image catalog implementation to a later moment, potentially even the 1.28 release (at the end of the day, the image catalog is nothing but a default definition of an extension image).

**Comment by gbartolini** [comment]
# Proposal of configuration control

During the call, we also talked about keeping open the possibility to host multiple extensions in a single image.

The idea is to propose three more fields:

- `extension_control_path` (default: `['share']`): list of local paths (relative to the image root folder) containing `.control` files
- `dynamic_library_path` (default: `['lib']`): list of local paths to dynamic libraries
- `ld_library_path` (default: `[]`): list of local paths to system libraries (to set `LD_LIBRARY_PATH` environment variable for the main postgres process)

## Example of a single extension image

By default, images will have content directly in the root directory (e.g. `share` and `lib`), as per our current recommendation.

For example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
# ...
  postgresql:
    extensions:
      - name: acdc
        #extension_control_path: ['share']
        #dynamic_library_path: ['lib']
        #ld_library_path: []
        image:
          # ...
# ...
```

The idea is that the above extension image will be mounted under `/extensions/acdc`.

The `acdc` image will have two folders in the root directory: `share` and `libs`. CloudNativePG will set the `extension_control_path` and `dynamic_library_path` as follows:

- `extension_control_path: /extensions/hardrock/acdc/share:$system`
- `dynamic_library_path: /extensions/hardrock/acdc/lib:$libdir`

## Example of multi-extension image

The three proposed options (`extension_control_path`, `dynamic_library_path`, and `ld_library_path`) will enable mounting images with multiple extensions, like in the following example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
# ...
  postgresql:
    extensions:
      - name: hardrock
        extension_control_path: ['acdc/share', 'deep-purple/share']
        dynamic_library_path: ['acdc/lib', 'deep-purple/lib']
        image:
          # ...
# ...
```

The container image will have two subfolders (`acdc` and `deep-purple`), each with its standard structure (`share` and `lib`), and CloudNativePG will mount it under `/extensions/hardrock`. CloudNativePG will set the `extension_control_path` and `dynamic_library_path` as follows:

- `extension_control_path: /extensions/hardrock/acdc/share:/extensions/hardrock/deep-purple/share:$system`
- `dynamic_library_path: /extensions/hardrock/acdc/lib:/extensions/hardrock/deep-purple/lib:$libdir`

## Example of library-only image

There can also be extensions that do not need any `extension_control_path` but need `dynamic_library_path`. One example is `pg_failover_slots` (supposing the libraries are in the suggested `lib` folder in the image).

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
# ...
  postgresql:
    extensions:
      - name: pg_failover_slots
        extension_control_path: []
        #dynamic_library_path: ['lib']
        #ld_library_path: []
        image:
          # ...
# ...
```
