### ISSUE TITLE
[Bug]: restoring databases via pgBouncer throws errors related to user_search

### ISSUE THREAD

**Issue by maximemoreillon** [cloudnative-pg/cloudnative-pg#7264]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24 (latest patch)

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Self-managed (Microk8s)

### How did you install the operator?

Helm

### What happened?

Hello,

Thank you very much for CNPG, it's by far my favorite way to run HA PostgreSQL!

I am having issues when restoring a database with tools like pgAdmin or DBeaver. I get am getting the following error (in this case, using pgAdmin) when doing so:

```
pg_restore: connecting to database for restore
pg_restore: creating FUNCTION "public.user_search(text)"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 216; 1255 184144 FUNCTION user_search(text) postgres
pg_restore: error: could not execute query: ERROR: function "user_search" already exists with same argument types
Command was: CREATE FUNCTION public.user_search(uname text) RETURNS TABLE(usename name, passwd text)
LANGUAGE sql SECURITY DEFINER
AS $_$SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1;$_$;
pg_restore: creating TABLE "public.bananas"
pg_restore: processing data for table "public.bananas"
pg_restore: creating ACL "public.FUNCTION user_search(uname text)"
pg_restore: from TOC entry 3330; 0 0 ACL FUNCTION user_search(uname text) postgres
pg_restore: error: could not execute query: ERROR: permission denied for function user_search
Command was: REVOKE ALL ON FUNCTION public.user_search(uname text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.user_search(uname text) TO cnpg_pooler_pgbouncer;
pg_restore: warning: errors ignored on restore: 2
```

My CNPG cluster was installed with the following manifest:

```YAML
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
spec:
  enableSuperuserAccess: true
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn-single-local
```

I am accessing it through pgBouncer, installed with this manifest

```YAML
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgresql-cluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
```

The user account I am using is non-superuser and has been created with the following query:

```sql
CREATE ROLE myser WITH LOGIN PASSWORD 'mypassword' NOSUPERUSER CREATEDB CREATEROLE INHERIT;
```

Is there something I am doing wrong?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
