### ISSUE TITLE
[Feature]: Pooler - set affinity / tolerations without providing full PodSpec

### ISSUE THREAD

**Issue by max-ae** [cloudnative-pg/cloudnative-pg#7279]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I want to set a taint toleration on a `Pooler`

With the current API, I can only set this if I provide `.spec.template.spec.tolerations`, but this requires me to provide the full `.spec.template.spec.containers` as well - something I want the operator to handle

### Describe the solution you'd like

Make the `.spec.affinity` handling from the `Cluster` resource available on the `Pooler` resource as well

### Describe alternatives you've considered

Duplicating the operator-generated `.spec.template.spec` section for the `Pooler` resource and make my desired changes

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by timothyrr** [comment]
I also would like this feature.

**Comment by ryan-grenz-evelyn** [comment]
I just ran into this also - we have strict node usage in our cluster and so need a toleration set to work properly

**Comment by ryan-grenz-evelyn** [comment]
bump - please don't go stale :)

**Comment by JensErat** [comment]
While the documentation is pretty confusing, this is indeed possible without giving the full pod spec. For example, this defines both node affinity and pod antiaffinity, while leaving all remaining settings untouched. The only restriction (by API design of the embedded podspec) is to have a single container, which only needs to have a name. `pgbouncer` is what will be created by the operator anyway.

Code reference: https://github.com/cloudnative-pg/cloudnative-pg/blob/eb5837c5c959951014921ae644bb845700f9dd77/pkg/specs/pgbouncer/deployments.go#L53

```
    poolers:
    - name: rw
      type: rw
      instances: 2
      monitoring:
        enabled: true
      template:
        spec:
          containers:
          - name: pgbouncer
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                    - someregion
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: cnpg.io/poolerName
                    operator: In
                    values:
                    - postgresql-some-cluster-pooler-rw
                topologyKey: kubernetes.io/hostname
```
