### ISSUE TITLE
[Feature]: ability to run sql after database and role creations

### ISSUE THREAD

**Issue by baran81** [cloudnative-pg/cloudnative-pg#7289]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We are able to run sql command after database creation in bootstrap phase with postInitApplicationSQL* spec.
But when the query are fiered, the roles managed by the operator are not yet created.
It's impossible for example create a post db creation script that give default privileges to another role.

### Describe the solution you'd like

2 possible solution:

Add a spec on Database-CRD to run sql command after database creation 

```YAML
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Database
metadata:
  name: mydb
spec:
  name: mydb
  owner: role_own
  cluster:
    name: mycluster
  encoding: 'UTF8'
  tablespace: my-tbs
  postCreationSql:
    - create schema myschema
    - grant all privileges on schema myschema to role_own
    - grant usage on schema myschema  to role_app
    - ALTER DEFAULT PRIVILEGES FOR USER role_own IN SCHEMA myschema  GRANT SELECT ON TABLES TO role_app
```

or add a spec on Cluster-CRD to run sql command after roles creation

### Describe alternatives you've considered

Only alternative is to run another automation outside kubernetes at the end of database creation.
that require to enable superuser access.

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
