### ISSUE TITLE
Need a way to specify the app password when bootstrap a cluster from recovery or pg_basebackup 

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#73]
When boostrapping a new cluster from a recovery or pg_basebackup, we need a way to specify the app password secret together with Owner and Database in the BootstrapRecovery configuration and BootstrapPgBaseBackup configuration

**Comment by litaocdl** [comment]
There are different ways could be considered and want to hear more voice


We do support application database setup during initdb in this way
```
bootstrap:
    initdb:
       database: app
       owner: app
       secret:
           name: existed-secret-name
```

we want do similar for recovery and pg_basebackup 

#1, one way we can choose is to have `database` `owner` `secret` added redundantly under `recovery`, `pg_basebackup`, we also want a new flag to indicates whether user want to `setup` the application database after restore. 

```
bootstrap:
    recovery:
       database: app
       owner: app
     
bootstrap:
    pg_basebackup:
       database: app
       owner: app
```

#2, Exract the application database information into new struct, `databaseInfo`, and change the way `initdb` reference application db. 
      The benifit of this way is we reduce the redundant, and it is easy for user to decided setup a application databse or not after recovery (by specific databaseInfo or not )
      The concern of this way is , we changed the way to specific appllication database for initDB, which could be a problem for existing clusters. 
```

---
bootstrap:
    initdb:
       databaseinfo:
            name: app
            owner: app
            secret: 
                name: existed-secret-name

---
bootstrap:
    recovery:
       databaseinfo:
            name: app 
            owner: app 
            secret: 
                name: existed-secret-name

---
bootstrap:
    pg_basebackup:
       databaseinfo:
            name: app
            owner: app
            secret: 
                name: existed-secret-name

```
