### ISSUE TITLE
[Bug]: major upgrade don't work using imageCatalogs with custom image tags

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#7391]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

leonardo.cecchi@enterprisedb.com

### Version

1.26.0-rc1

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Given the following image catalog:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb-other
spec:
  images:
  - image: docker.io/timescale/timescaledb:2.18.2-pg17
    major: 17
  - image: docker.io/timescale/timescaledb:2.18.2-pg16
    major: 16
```

And the following cluster definition:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 16
    name: timescaledb-other
  managed:
    services:
      disabledDefaultServices: ['ro','r']
  postgresql:
    shared_preload_libraries:
    - timescaledb
  postgresUID: 70
  postgresGID: 70
  storage:
    size: 8Gi
```

After triggering a major upgrade to version `17`, the cluster with:

```
cloudnative-pg $ k get pods
NAME                                               READY   STATUS             RESTARTS        AGE
test-1                                             1/1     Running            0               15m
test-2                                             1/1     Running            0               15m
test-3                                             0/1     CrashLoopBackOff   7 (3m24s ago)   14m
```

The log of `test-3` contains the following messages:

```
{"level":"info","ts":"2025-04-17T16:07:41.892299669Z","logger":"postgres","msg":"2025-04-17 16:07:41.892 UTC [26] FATAL:  database files are incompatible with server","pipe":"stderr","logging_pod":"test-3"}    {"level":"info","ts":"2025-04-17T16:07:41.89235554Z","logger":"postgres","msg":"2025-04-17 16:07:41.892 UTC [26] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible wit
h this version 17.3.","pipe":"stderr","logging_pod":"test-3"}                                                                                                                                                     {"level":"info","ts":"2025-04-17T16:07:41.894392076Z","msg":"postmaster exited","logger":"instance-manager","logging_pod":"test-3","postmasterExitStatus":"exit status 1","postMasterPID":26}
```

It looks like the operator is not understanding that this is a major upgrade and proceeds with a plain rolling deployment.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
