### ISSUE TITLE
[Bug]: Split brain in case of network partition

### ISSUE THREAD

**Issue by NikolayS** [cloudnative-pg/cloudnative-pg#7407]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

nik@postgres.ai

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

## Split brain
If the primary has lost network, then it remains the primary, allowing writes, and a replica is promoted – a typical split brain

How to reproduce:

Set up in dind, details:
- kubectl version: v1.32.3
- Kustomize Version: v5.5.0
- Server Version: v1.32.2
- kind version 0.27.0
- kind-config.yaml – below

```yaml
kind: Cluster
apiVersion: [kind.x-k8s.io/v1alpha4](http://kind.x-k8s.io/v1alpha4)
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
cat cnpg_test_cluster.yaml
apiVersion: [postgresql.cnpg.io/v1](http://postgresql.cnpg.io/v1)
kind: Cluster
metadata:
  name: cnpg-test-cluster
spec:
  instances: 3
  storage:
    size: 1Gi
```

Steps:
1. Create the cluster: `kind create cluster --config kind-config.yaml`
2.  Install CNPG operator: `kubectl apply --server-side -f   https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.25/releases/cnpg-1.25.1.yaml`
3. Deploy `kubectl apply -f cnpg_test_cluster.yaml`
4.  Identify the primary node and disconnect it from the network using `docker network disconnect kind kind-worker-xxx`
5. Observe that CNPG promoted a new primary node.
6.  Bash into the old primary node using docker exec, and bash into the postgres pod inside the node. Postgres on this node is still primary.

This is a typical split brain. Any workload that origins from the same VM (e.g., pod is on the same node as the old primary) can generate writes to the old primary.

Of course, in some cases, it is ok to live with this – e.g., forbidding app pods to be on the same node setting up AntiAffinity, but it is not possible in all the cases.

And it becomes even worse if we use, say, pg_cron, and have some periodic jobs generating some writes – this workload happens inside Postgres, and split brain becomes inevitable.

2. The term "fencing" used in the docs looks like "manual fencing" rather than what one could expect from a system with auto-failover. And it won't be possible to use if, again, the primary lost network – imagine it happened, how will fencing works? The note is not achieavable.

A personal note: I came from the Patroni world and see these problems as a show-stopper. We (Postgres.AI) have several customers of various sizes that seriously consider to use CNPG. I'm very curious what the maintainers think about these findings and if it can be solved somehow in the future. Thanks.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
