### ISSUE TITLE
[Bug]: Managed role is not created

### ISSUE THREAD

**Issue by Sleepful** [cloudnative-pg/cloudnative-pg#7467]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

does not create the `postgraphile_user` role! 
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: default
spec:
  managed:
    roles:
    - name: postgraphile_user
      ensure: present
      login: true
      passwordSecret:
        name: cnpg-postgraphile-user-secret

```

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: cnpg-postgraphile-user-secret
    namespace: default
    labels:
      cnpg.io/reload: "true"
stringData:
  username: postgraphile_user
  password: ,,,
```
I check with
```
kubectl cnpg psql cnpg-cluster
\du
```
and I only get the bootstrap role.

I tried with `kubectl cnpg reload cnpg-cluster` and `kubectl cnpg restart cnpg-cluster` to no avail.

`kubectl cnpg logs cluster cnpg-cluster` does not show anything relevant to roles. Other than this very outdated log msg:

```
{"level":"info","ts":"2025-04-30T05:59:34.475440504Z","logger":"roles_reconciler","msg":"starting up the runnable","logger":"instance-manager","logging_pod":"cnpg-cluster-1"}
{"level":"info","ts":"2025-04-30T05:59:34.475540254Z","logger":"roles_reconciler","msg":"setting up RoleSynchronizer loop","logger":"instance-manager","logging_pod":"cnpg-cluster-1"}
```

the roles don't reconcile tho...

No idea what to do from here

I get the following from `kubectl cnpg status cnpg-cluster -v `
```
Managed roles status
No roles managed
```

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
