### ISSUE TITLE
[Docs]: postgres-versions-updater causes major version inconsistencies

### ISSUE THREAD

**Issue by atimofeev** [cloudnative-pg/cloudnative-pg#7510]
### Is there an existing issue already for your request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

Current documentation shows inconsistencies in postgres versions:

https://cloudnative-pg.io/documentation/current/image_catalog/
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: default
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.6
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:17.4
```

Example of commit made by github-actions: 0b56b77

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/current/image_catalog/

### Backport?

Yes

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
