### ISSUE TITLE
[Bug]: The microservice type import doesnt work as expected

### ISSUE THREAD

**Issue by radhupr** [cloudnative-pg/cloudnative-pg#7555]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: k0s

### How did you install the operator?

Helm

### What happened?

My source DB is of version 16.4 and I'm testing main version upgrade using the import method
```
psql (16.4 (Debian 16.4-1.pgdg110+2))
Type "help" for help.

postgres=# \l
                                                        List of databases
   Name    |  Owner   | Encoding | Locale Provider | Collate | Ctype | ICU Locale | ICU Rules |        Access privileges
-----------+----------+----------+-----------------+---------+-------+------------+-----------+----------------------------------
 postgres  | postgres | UTF8     | libc            | C       | C     |            |           | =Tc/postgres                    +
           |          |          |                 |         |       |            |           | postgres=CTc/postgres           +
           |          |          |                 |         |       |            |           | cnpg_pooler_pgbouncer=c/postgres
 template0 | postgres | UTF8     | libc            | C       | C     |            |           | =c/postgres                     +
           |          |          |                 |         |       |            |           | postgres=CTc/postgres
 template1 | postgres | UTF8     | libc            | C       | C     |            |           | =c/postgres                     +
           |          |          |                 |         |       |            |           | postgres=CTc/postgres
 testapp   | testapp  | UTF8     | libc            | C       | C     |            |           |
(4 rows)
```

I used below yaml for creating a DB to import database testapp
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: testdb-17
  namespace: database
spec:
  instances: 2
  resources:
    limits:
      ephemeral-storage: 10Gi
      memory: 8Gi
    requests:
      cpu: 2000m
      ephemeral-storage: 3Gi
      memory: 3Gi
  storage:
    size: 2Gi
    storageClass: ontap-nas
  bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - testapp
        source:
          externalCluster: testdb
  externalClusters:
  - name: testdb
    connectionParameters:
      host: testdb-rw.database.svc
      user: postgres
      dbname: postgres
    password:
      name: testdb-superuser
      key: password
```
When the new cluster is created, its missing `testapp` but have `app` DB
```
postgres=# \l
                                                List of databases
   Name    |  Owner   | Encoding | Locale Provider | Collate | Ctype | Locale | ICU Rules |   Access privileges
-----------+----------+----------+-----------------+---------+-------+--------+-----------+-----------------------
 app       | app      | UTF8     | libc            | C       | C     |        |           |
 postgres  | postgres | UTF8     | libc            | C       | C     |        |           |
 template0 | postgres | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |          |          |                 |         |       |        |           | postgres=CTc/postgres
 template1 | postgres | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |          |          |                 |         |       |        |           | postgres=CTc/postgres
(4 rows)
```
I tried to change it to monolith type as below, but that failed with another error: `Error: while executing logical import: error while executing pg_restore, section:pre-data, exit status 1` 
```
bootstrap:
    initdb:
      import:
        schemaOnly: true
        type: monolith
        roles:
         - testapp
        databases:
          - testapp
        source:
          externalCluster: testdb
  externalClusters:
  - name: testdb
    connectionParameters:
      host: testdb-rw.database.svc
      user: postgres
      dbname: postgres
    password:
      name: testdb-superuser
      key: password
```

Can anyone help in understanding if there is any issue in how I import the initdb from source?

### Cluster resource

```shell
#source cluster yaml

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/name: testdb
  name: testdb
  namespace: database
spec:
  affinity:
    topologyKey: topology.kubernetes.io/zone
  bootstrap:
    initdb:
      database: testapp
      encoding: UTF8
      owner: testapp
      secret:
        name: "db-creds"
  enablePDB: true
  enableSuperuserAccess: true
  #imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 2
  logLevel: warning
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  ...
  ...
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
