### ISSUE TITLE
[Bug]: walArchivingFailing with no logs, caused the database pod to Crashloop

### ISSUE THREAD

**Issue by droslean** [cloudnative-pg/cloudnative-pg#7570]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

older in 1.24.x

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  creationTimestamp: "2025-05-14T13:35:27Z"
  generation: 1
  labels:
    cnpg.io/cluster: keycloak-postgres
    cnpg.io/immediateBackup: "true"
    cnpg.io/scheduled-backup: keycloak-online-backup
  name: keycloak-online-backup-20250514133527
  namespace: keycloak
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: ScheduledBackup
    name: keycloak-online-backup
    uid: 09d5b063-d5ee-4444-a0fb-ccca8249aa9c
  resourceVersion: "816420578"
  uid: a3b4b03a-cd2e-49e7-8208-f94de128f9a2
spec:
  cluster:
    name: keycloak-postgres
  method: barmanObjectStore
  target: primary
status:
  backupName: backup-20250514133947
  destinationPath: s3://cluster-database-backups
  instanceID:
    ContainerID: containerd://5c5117b4458e9f03f95779f4760af30f3d2f84753161410b63b2404a4d610e6c
    podName: keycloak-postgres-1
  method: barmanObjectStore
  phase: walArchivingFailing
  s3Credentials:
    accessKeyId:
      key: ACCESS_KEY_ID
      name: aws-pg-backup
    secretAccessKey:
      key: SECRET_ACCESS_KEY
      name: aws-pg-backup
  serverName: keycloak-postgres
```

Logs in the cnpg pod
```
{"level":"info","ts":"2025-05-14T13:39:46Z","msg":"Starting backup","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"keycloak-online-backup-20250514133527","namespace":"keycloak"},"namespace":"keycloak","name":"keycloak-online-backup-20250514133527","reconcileID":"34db2a68-4606-404c-aaee-f62b2e3ae21b","cluster":"keycloak-postgres","pod":"keycloak-postgres-1"}
{"level":"info","ts":"2025-05-14T13:48:47Z","msg":"Backup is already running on","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"navigator-online-backup-20250514133045","namespace":"navigator"},"namespace":"navigator","name":"navigator-online-backup-20250514133045","reconcileID":"49b8b68a-00e9-4703-99da-fcd178655f65","cluster":"navigator-postgres","pod":"navigator-postgres-1","started at":"<nil>"}
{"level":"info","ts":"2025-05-14T13:48:47Z","msg":"Backup is already running on","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"keycloak-online-backup-20250514133527","namespace":"keycloak"},"namespace":"keycloak","name":"keycloak-online-backup-20250514133527","reconcileID":"f59fb244-d952-4806-aff6-04b85ebf3717","cluster":"keycloak-postgres","pod":"keycloak-postgres-1","started at":"<nil>"}

```

This backup is failing for days and caused the PV to fill up. There is no turning back from this since in Kubernetes reducing a size of a PV is impossible, so we need to increase it without any reason. 

### Cluster resource

```shell
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: keycloak-postgres
    namespace: keycloak
  spec:
    postgresql:
      parameters:
        max_connections: "500"
    instances: 1
    bootstrap:
      initdb:
        database: keycloak
        owner: keycloak
    storage:
      size: 20Gi
    backup:
      barmanObjectStore:
        destinationPath: s3://cluster-database-backups
        s3Credentials:
          accessKeyId:
            name: aws-pg-backup
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-pg-backup
            key: SECRET_ACCESS_KEY
      target: primary
      retentionPolicy: 10d
    monitoring:
      enablePodMonitor: true
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Hi @droslean, WAL archiving is a critical process that must be continuously monitored. If that does not happen, PostgreSQL accumulates them and runs out of disk space.

Unfortunately, since we rely on Barman Cloud to perform log shipping, and it only returns a status code, CloudNativePG has no visibility into the error message. This is one of the reasons, for example, why we are moving away to a plugin interface.

My advice is for you to understand why WAL archive is failing consistently. It should never happen. That is what you need to fix in my opinion.

Can you please share the output of the `pg_stat_archiver` view? or the Prometheus metric?

**Comment by droslean** [comment]
Hi @gbartolini, thank you for the response. The pg_stat_archiver is empty. The backup is still failing, and I can't find the reason. There are no logs, and there are no logs that indicate that the backup even finished with a failed status.  

Let me try to update the controller to the latest version and try again.

**Comment by droslean** [comment]
Just some extra context before trying to update to the latest version. 

```yaml
Name:         keycloak-online-backup-20250515101247
Namespace:    keycloak
Labels:       cnpg.io/cluster=keycloak-postgres
              cnpg.io/immediateBackup=true
              cnpg.io/scheduled-backup=keycloak-online-backup
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2025-05-15T10:12:47Z
  Generation:          1
  Owner References:
    API Version:     postgresql.cnpg.io/v1
    Controller:      true
    Kind:            ScheduledBackup
    Name:            keycloak-online-backup
    UID:             1e708215-cde4-4b79-8a65-3ee44891d030
  Resource Version:  817261744
  UID:               ca6e8fb9-7dce-4f43-a723-56be5018645d
Spec:
  Cluster:
    Name:  keycloak-postgres
  Method:  barmanObjectStore
  Target:  primary
Status:
  Backup Name:       backup-20250515101247
  Destination Path:  s3://cluster-database-backups
  Instance ID:
    Container ID:  containerd://5c5117b4458e9f03f95779f4760af30f3d2f84753161410b63b2404a4d610e6c
    Pod Name:      keycloak-postgres-1
  Method:          barmanObjectStore
  Phase:           walArchivingFailing
  s3Credentials:
    Access Key Id:
      Key:   ACCESS_KEY_ID
      Name:  aws-pg-backup
    Secret Access Key:
      Key:      SECRET_ACCESS_KEY
      Name:     aws-pg-backup
  Server Name:  keycloak-postgres
Events:
  Type    Reason    Age   From                   Message
  ----    ------    ----  ----                   -------
  Normal  Starting  42m   cloudnative-pg-backup  Starting backup for cluster keycloak-postgres
```

Phase is `walArchivingFailing` but there are no events for when the backup actually failed. Also, there are no logs in the controller that shows when then backup failed. In addition, the `pg_stat_archiver` metric is still null.
