### ISSUE TITLE
[Bug]: Subscription update with copy_data parameter

### ISSUE THREAD

**Issue by xabufr** [cloudnative-pg/cloudnative-pg#7585]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

thomas.loubiou@mirakl.com

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

We are creating some subscriptions like the following:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: my_sub
spec:
  cluster:
    name: my_cluster
  dbname: my_db
  externalClusterName: internal-pg12
  name: pg12_pg17
  parameters:
    copy_data: "true"
  publicationName: inter_cluster
  subscriptionReclaimPolicy: delete
```

The creation of the subscription works great, but in case of an update the reconciliation fails because of the `copy_data` field.

After investigating I've found that the [update code](https://github.com/cloudnative-pg/cloudnative-pg/blob/874528a4c98bad0eedfc80a634f4949c4330e5a6/internal/management/controller/subscription_controller_sql.go#L131)  generate a naive `ALTER SUBSCRIPTION xxx SET copy_data = true`, which is an [invalid postgreSQL statement](https://www.postgresql.org/docs/17/sql-altersubscription.html#SQL-ALTERSUBSCRIPTION-PARAMS-SET). Indeed `ALTER SUBSCRIPTION` cannot change the `copy_data` parameter, from the official doc:

> The parameters that can be altered are [slot_name](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-SLOT-NAME), [synchronous_commit](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-SYNCHRONOUS-COMMIT), [binary](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-BINARY), [streaming](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-STREAMING), [disable_on_error](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-DISABLE-ON-ERROR), [password_required](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-PASSWORD-REQUIRED), [run_as_owner](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-RUN-AS-OWNER), [origin](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-ORIGIN), and [failover](https://www.postgresql.org/docs/17/sql-createsubscription.html#SQL-CREATESUBSCRIPTION-PARAMS-WITH-FAILOVER). Only a superuser can set password_required = false.

Please note that we don't change this `copy_data` parameter.

The subscription seems to be created by the 1st reconciliation, but after it is impossible to update it using the operator.

Here is the observed status:

```yaml
status:
  applied: false
  message: 'while patching subscription: ERROR: unrecognized subscription parameter:
    "copy_data" (SQLSTATE 42601)'
  observedGeneration: 1
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
