### ISSUE TITLE
[Feature]: metadata in pvcTemplate

### ISSUE THREAD

**Issue by brightdroid** [cloudnative-pg/cloudnative-pg#7622]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I'd like to exclude PVs from velero.

### Describe the solution you'd like

Allow [metadata config](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-Metadata) for pvcTemplate as well.

### Describe alternatives you've considered

Manual add label to provisioned PVs.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by brightdroid** [comment]
I found a solution to exclude all resources:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg17
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  inheritedMetadata:
    labels:
      velero.io/exclude-from-backup: "true"
# ...
```
