### ISSUE TITLE
[Feature]: Cascading extensions

### ISSUE THREAD

**Issue by blmhemu** [cloudnative-pg/cloudnative-pg#7696]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Add support for cascading extension installs in database resource.

### Describe the solution you'd like

A simple flag like so in database resource.
```
spec:
  extensions:
    - name: <name>
      ensure: present | absent | cascade
```
or
```
spec:
  extensions:
    - name: <name>
      ensure: present | absent
      cascade: true | false
```

### Describe alternatives you've considered

Manually setting every extension. (or)

```
spec:
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
```

### Additional context

https://github.com/tensorchord/cloudnative-vectorchord

The vchord extension depends on vectors extension it would be nice if there was cascade support.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes (might need some initial hand-hold)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
