### ISSUE TITLE
[Docs]: No information on triggering rollouts of db clusters with operator upgrade (with enabled in-place update)

### ISSUE THREAD

**Issue by maryam-ismayilova-m10** [cloudnative-pg/cloudnative-pg#7727]
### Is there an existing issue already for your request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

I have tried to upgrade the operator from version 1.25.1 to 1.26 (using the helm chart version 0.24.0) and this triggered an update on all my database clusters. This all despite the fact that i have enabled `ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES` set to true . 

I see the mention of probe changes in the release note(which probably is the reason for the need of a restart), but personally i did not expect it to be applied to any **exisiting** clusters. And even if so, I expected to be notified about this feature "breaking" the expectation that an operator upgrade is not going to trigger a rollout when inplace update is used. 
I believe your documentation on upgrade steps and the release notes are missing this crucial information. 

And perhaps it would be better to have the user decide whether such an enhancement need to be applied to all clusters or not (just like one can do turn of a restart using inplace update of instance manager)

### Describe what additions need to be done to the documentation

I would expect this to be mentioned in installation and upgrade documentation [here](https://cloudnative-pg.io/documentation/1.26/installation_upgrade/) , as well as inside the release notes [here](https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.26.0)

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/1.26/installation_upgrade/

### Additional context

Previous version of cnpg operator: 1.25.1 with helm chart version 0.23.2
cnpg clusters deployed with cnpg cluster helm chart version 0.3.0

Log in cnpg operator pods with mention of a rollout needed:
original and target PodSpec differ in containers: container postgres differs in startup-probe

### Backport?

N/A

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by usiegl00** [comment]
We experienced a similar issue where we had both the `ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES` env set to `true` and `primaryUpdateStrategy` set to `supervised` on all our clusters. However, once we upgraded the operator the replicas were restarted to the newer 1.26 version immediately and the primary was left at our previous 1.25 version `waiting for user action`. We checked `/run/manager version` to see if the primary had been in-place updated, but found the version remained at 1.25. The cnpg cli plugin has two options for completing the supervised update, but neither allow for performing the in-place manager update on its own.

Running the `kubectl cnpg restart` command on the primary does perform the in-place update, but the postmaster was also restarted, which we did not expect to experience. Finally, the cluster status remained `waiting for user action` after the restart and required a `kubectl cnpg promote` of the follower to return to healthy.

**Comment by l00ptr** [comment]
We've observed the same behavior: our clusters were restarted after upgrading from CNPG 1.25.2 to 1.26.0, despite having ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES set to true.

Upon inspection, the logs indicate that a Pod rollout was triggered due to a change in the startup probe configuration.

Specifically, we noticed the following difference in the probes before and after the upgrade:

Before upgrade:
``` yaml
Liveness:   http-get https://:8000/healthz delay=0s timeout=5s period=10s #success=1 #failure=3  
Readiness:  http-get https://:8000/readyz  delay=0s timeout=5s period=10s #success=1 #failure=3  
Startup:    http-get https://:8000/healthz delay=0s timeout=5s period=10s #success=1 #failure=360
```

After upgrade:

``` yaml
Liveness:   http-get https://:8000/healthz delay=0s timeout=5s period=10s #success=1 #failure=3  
Readiness:  http-get https://:8000/readyz  delay=0s timeout=5s period=10s #success=1 #failure=3  
Startup:    http-get https://:8000/startupz delay=0s timeout=5s period=10s #success=1 #failure=360
```

This change in the startup probe endpoint from /healthz to /startupz appears to be the cause of the rollout. Since we seem to know the [origin of that problem](https://github.com/cloudnative-pg/cloudnative-pg/pull/6623), i am gonna make a merge request to say a few word about that problem into the upgrade documentation.
