### ISSUE TITLE
[Bug]: ScheduledBackup ignores `barmanObjectName`, sending base backups to the WAL object store

### ISSUE THREAD

**Issue by munjalpatel** [cloudnative-pg/cloudnative-pg#7778]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.26 (latest patch)

### What version of Kubernetes are you using?

1.33

### What is your Kubernetes environment?

Cloud: Azure AKS

### How did you install the operator?

Helm

### What happened?

When using the Barman Cloud plugin, a `ScheduledBackup` resource configured to use a specific `barmanObjectName` for base backups appears to ignore this setting. Instead of sending the backup to the designated object store, it sends it to the object store configured for WAL archiving in the `Cluster`'s `spec.plugins` section.

### Cluster resource

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mdb
  namespace: ...
  image: ghcr.io/.../simple-pg:17.5.0-simple.43
  instances: 3
  lastFailedBackup: '2025-06-03T21:03:35Z'
  latestGeneratedNode: 3
  pgDataImageInfo:
    image: ghcr.io/.../simple-pg:17.5.0-simple.43
    majorVersion: 17
spec:
  bootstrap:
    initdb:
      dataChecksums: true
      database: ...
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: ...
      secret:
        name: ...
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 17
    name: simple-postgres
  instances: 3
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: os-wal
  postgresGID: 26
  postgresUID: 26

---

apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: os-base
  namespace: simple-db
spec:
  configuration:
    azureCredentials:
      storageAccount:
        key: AZURE_STORAGE_ACCOUNT
        name: base-azure-creds
      storageKey:
        key: AZURE_STORAGE_KEY
        name: base-azure-creds
    destinationPath: https://base.blob.core.windows.net/simple-mdb
    wal:
      compression: gzip
  retentionPolicy: 180d

---

apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: os-wal
  namespace: simple-db
spec:
  configuration:
    azureCredentials:
      storageAccount:
        key: AZURE_STORAGE_ACCOUNT
        name: wal-azure-creds
      storageKey:
        key: AZURE_STORAGE_KEY
        name: wal-azure-creds
    destinationPath: https://wal.blob.core.windows.net/simple-mdb
    wal:
      compression: gzip
  retentionPolicy: 30d

---

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mdb
  namespace: simple-db
status:
  lastCheckTime: '2025-06-07T21:30:00Z'
  lastScheduleTime: '2025-06-07T21:30:00Z'
  nextScheduleTime: '2025-06-14T21:30:00Z'
spec:
  backupOwnerReference: self
  cluster:
    name: mdb
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: os-base
  schedule: 0 30 21 * * 6
```

### Relevant log output

**To Reproduce**

1.  Create two separate `ObjectStore` resources: one for base backups and one for WAL archives, pointing to different Azure Blob Storage containers.
2.  Configure a `Cluster` resource to use the WAL object store for continuous archiving via `spec.plugins`.
3.  Create a `ScheduledBackup` resource that targets the cluster and explicitly sets the `pluginConfiguration` to use the base backup object store via its `barmanObjectName`.
4.  Trigger the backup.
5.  Observe that the backup artifact has been uploaded to the WAL object store instead of the base backup object store.

**Expected behavior**
The base backup created by the `ScheduledBackup` resource should be stored in the Azure storage account defined in the `os-base` `ObjectStore`. The separate WAL archive (`os-wal`) should only contain the WAL files.

**Actual behavior**
The base backup was incorrectly sent to the destination configured in the `os-wal` `ObjectStore`, which is intended only for WAL segments. The `barmanObjectName` parameter in the `ScheduledBackup` spec was seemingly ignored.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
