### ISSUE TITLE
[Bug]: Cannot create cluster because wrong resource limit validation

### ISSUE THREAD

**Issue by Jean-Daniel** [cloudnative-pg/cloudnative-pg#7862]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.26 (latest patch)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The operator refuse to create the cluster despite having declared enough resources:

Cluster resource declarations:
```yaml
      resources:
        requests:
          cpu: 8
          memory: 64Gi
        limits:
          cpu: 16
          memory: 64Gi
          hugepages-1Gi: 128Gi
```

Cluster pg_conf:
```yaml
        huge_pages: on
        huge_page_size: 1GB
        shared_buffers: 128GB
```

But the operator refuse to create the pod with the following error message:

` Invalid value: "64Gi": Memory request is lower than PostgreSQL `shared_buffers` value`

As the shared buffer are required to use huge pages (huge_pages: on) there is no reason to enforce a memory limit higher than shared_buffer request.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
