### ISSUE TITLE
[Docs]: Add a working example for configuring pg_failover_slots with CloudNativePG

### ISSUE THREAD

**Issue by gdsantoro** [cloudnative-pg/cloudnative-pg#7866]
### Is there an existing issue already for your request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

To the best of my understanding, the current way to automatically synchronize replication slots between the primary and the standby in CloudNativePG is through the `pg_failover_slots` plugin (at least until `synchronized_standby_slots` is supported by CNPG itself).

In the current documentation (https://cloudnative-pg.io/documentation/1.26/postgresql_conf/#enabling-pg_failover_slots), the only guidance provided is:

> `Please refer to the pg_failover_slots documentation for details on this extension.`

Unfortunately, integrating `pg_failover_slots` correctly in a CNPG-managed cluster requires more than just following the upstream plugin docs. It took me quite a bit of time to figure out the necessary setup and get it working, so I think the CNPG documentation could benefit from some improvements here.

### Describe what additions need to be done to the documentation

1. __Clarify prerequisites__

Mention that `cert-manager` must be installed in the cluster, as it's required for the SSL-based authentication used by `pg_failover_slots`.

2. __Provide a minimal working configuration example__, something along these lines:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-example-cluster
spec:
  description: "Example cluster with pg_failover_slots"
  instances: 2

  postgresql:
    parameters:
      wal_level: "logical"             # Required for logical replication
      hot_standby_feedback: "on"       # Required by pg_failover_slots
      # sync_replication_slots: "true" # Not supported in CNPG yet

      # pg_failover_slots configuration
      pg_failover_slots.drop_extra_slots: "true"
      # Match replication slots created with pgoutput
      # pg_failover_slots.synchronize_slot_names: "plugin:pgoutput"
      # Or match by name
      pg_failover_slots.synchronize_slot_names: "name_like:%debezium%"

    pg_hba:
      # Enable streaming replication with cert authentication
      # All DBs
      # - hostssl all streaming_replica all cert
      # "app" DB
      - hostssl app streaming_replica all cert
```

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/1.26/postgresql_conf/#enabling-pg_failover_slots

### Additional context

This would greatly help other users avoid trial-and-error and better understand how to integrate `pg_failover_slots` in CNPG clusters.

Thanks for the great work on CloudNativePG!

### Backport?

Yes

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
