### ISSUE TITLE
[Feature]: Support for `CREATE` and `USAGE` grants on database schemas

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#7872]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Right now, the `Database` CRD only manages the `owner` of the schema.

PostgreSQL provides two privileges as part of the `GRANT` command on schemas: `CREATE` and `USAGE`. See ["SQL Grant"](https://www.postgresql.org/docs/current/sql-grant.html).

Users are now using the post initialization scripts for this, making it imperative, one-off and thus fragile.

### Describe the solution you'd like

Providing usage permissions on managed schema objects as part of the `Database` CRD.

The `GRANT` SQL command in Postgres has the following syntax:

```sql
GRANT { { CREATE | USAGE } [, ...] | ALL [ PRIVILEGES ] }
    ON SCHEMA schema_name [, ...]
    TO role_specification [, ...] [ WITH GRANT OPTION ]
    [ GRANTED BY role_specification ]
```

Both `GRANTED BY` and `WITH GRANT OPTION` are not suitable for a declarative environment typical of CloudNativePG, so we will focus only on `CREATE` and `USAGE`.

A possible implementation could be:

```yaml
# ...
spec:
  schemas:
  - name: app
    owner: app
    create:
    - name: angus
      type: grant
    - name: brian
      type: revoke
    usage:
    - name: angus
      type: grant
    - name: brian
      type: grant
# ...
```

The default `type` is `grant`.

For example, the above will check that `angus` hasn't got yet the `create` privilege for the `app` database and run the required `GRANT CREATE ON app TO angus`. Similarly, if `brian` has `create` usage on the same `app` schema, it will run `REVOKE CREATE ON app FROM angus`.

See: [`REVOKE`](https://www.postgresql.org/docs/current/sql-revoke.html).

Please feel free to change the above proposal if you have a better idea.

### Describe alternatives you've considered

We could do nothing, and delegate this operation to another tool.

However, I personally think that this is a good responsibility for the `schema` management feature in the `Database` CRD.

### Additional context

N/A

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This could actually be a project for a future mentorship program.

**Comment by vitorfloriano** [comment]
> This could actually be a project for a future mentorship program.

@gbartolini I had just started working on this for my first PR 😆 Should I pick another one?

**Comment by dikshant182004** [comment]
Hi @gbartolini ,I would like to contribute on this project .I do have good knowledge of postgresql and schema management .It would be great if u can guide me from where i can start .and is there any conversationn channel where we can have our future conversation regarding this project .

**Comment by gbartolini** [comment]
> Hi [@gbartolini](https://github.com/gbartolini) ,I would like to contribute on this project .I do have good knowledge of postgresql and schema management .It would be great if u can guide me from where i can start .and is there any conversationn channel where we can have our future conversation regarding this project .

Hi @dikshant182004, thanks for volunteering. Here you have more information on the mentorship program: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/contribute/lfx-mentorship-program.md

**Comment by dikshant182004** [comment]
hi @gbartolini thanks for the resources ,i will look into it and starts contributing.Just wanted to confirm one thing ,Is this project for next year program.

**Comment by PhantomInTheWire** [comment]
Hi @gbartolini @mnencia , this looks very interesting. I would love to work on this as a part of LFX; I just have some questions regarding the specifics of this issue:
 
1. Do we want the older brittle systems to migrate to the newer declarative approach completely? Should we have automated scripts for this, or will they have to figure it out manually?

2. What happens if someone manually changes privileges? Should we detect these and provide warnings?
 
3. How should this interact with existing role management? Should we validate things first, or just override them?
 
Regardless of how we decide to handle them, given a chance, I'm really excited to work with you on this. I'll try working some good first issues meanwhile to familiarize myself with the ecosystem.
For context I've worked with some big OSS projects(wasmedge, wasmtime, containerd) in this space.

**Comment by THE-BRAHMA** [comment]
PostgreSQL uses `GRANT` and `REVOKE` as operations on privilege types(`CREATE`, `USAGE`). 
What's the opinion on  below layout as it mirrors that structure exactly.

```
spec:
  schemas:
  - name: app
    owner: app
    privileges:
      create:
        grant: [developer_role, admin_role]
        revoke: [readonly_role]
      usage:
        grant: [developer_role, readonly_role, service_account]
```

Cc @gbartolini

**Comment by gaurangkudale** [comment]
Hi @gbartolini ,
I’d like to propose a simpler and more user-friendly YAML model for managing schema privileges in the Database CRD.
Instead of exposing SQL-level grant / revoke semantics in the API, we could let users declare which privileges a role should have, and let the controller reconcile the rest.
- Proposed YAML

```yaml
spec:
  schemas:
  - name: app
    owner: app
    privileges:
      angus:
        - usage
        - create
      brian:
        - usage

```
Semantics

- Privileges listed for a role are GRANTED
- Privileges not listed are REVOKED
- The CRD expresses desired state, not SQL operations

This would internally translate to:

```bash
GRANT USAGE, CREATE ON SCHEMA app TO angus;
GRANT USAGE ON SCHEMA app TO brian;
REVOKE CREATE ON SCHEMA app FROM brian;
```

- Simplifies reconciliation logic (presence = grant, absence = revoke)
- Makes validation easier (e.g. CREATE implies USAGE)

Happy to iterate on naming (privileges, schemaPrivileges, etc.) or validation rules if this direction makes sense.

**Comment by jeremych1000** [comment]
This would be a great addition :)

**Comment by AlyHKafoury** [comment]
@gbartolini I am interested in tackling this issue can I start on it ?

**Comment by ghost** [comment]
Hi,

I think it is also important to handle the connect privilege on the database CR for users.
Otherwise and as of my knowledge, just the owner is able to connect to the database. Other users need to be granted access manually and in a not declarative way.

Any thoughts about this ?

BR
Marijo

**Comment by sarthakNaikare** [comment]
Hey, I've been reading through this issue as part of preparing to apply for the LFX Term 2 mentorship and wanted to raise something I haven't seen come up in the discussion yet.

Most of the conversation has been around what the API should look like for `CREATE` and `USAGE` grants, which makes sense. But I kept thinking about what happens during reconciliation, and I think there's a subtle problem worth considering early.

PostgreSQL stores schema-level grant state in `pg_namespace.nspacl` as an `aclitem[]`. The thing is, every time you run `GRANT` or `REVOKE`, even if the privilege already exists or was already removed, PostgreSQL writes a new tuple to `pg_namespace`. Those dead tuples accumulate until `VACUUM` cleans them up. So if the operator blindly re-applies grants on every reconciliation loop without checking current state first, it'll slowly bloat `pg_namespace` in a way that's really hard to diagnose later.

The cleaner approach would be to diff against the catalog before touching anything:

```sql
SELECT n.nspname,
       acl.grantee,
       acl.privilege_type
FROM pg_namespace n
CROSS JOIN aclexplode(COALESCE(n.nspacl, acldefault('n', n.nspowner))) acl
WHERE n.nspname = 'myschema';
```

That gives you the current grant state, so the reconciler only applies what's actually missing or needs to be revoked.

The other thing I wanted to bring up is `ALTER DEFAULT PRIVILEGES`. The `GRANT USAGE` and `GRANT SELECT ON ALL TABLES` pattern only applies to objects that exist at the time the grant runs. Anything created after that point gets no privileges for the grantee, which causes silent failures that are genuinely confusing to debug because the grant looks correct when you inspect it.

The full pattern that actually works in production is:

```sql
GRANT USAGE ON SCHEMA myschema TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA myschema TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app IN SCHEMA myschema
    GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app IN SCHEMA myschema
    GRANT USAGE ON SEQUENCES TO readonly;
```

The `FOR ROLE app` part matters here. `ALTER DEFAULT PRIVILEGES` only applies to objects created by that specific role, not anyone who creates objects in the schema. So the schema owner needs to be tracked explicitly in the spec.

Without this piece, the grant implementation would be correct for static schemas but would silently break as soon as any application runs a migration and creates new tables.

If it's in scope, something like this in the Database spec would cover both concerns:

```yaml
schemas:
  - name: myschema
    owner: app
    grants:
      - role: readonly
        privileges: [USAGE]
    defaultPrivileges:
      - forRole: app
        role: readonly
        on: TABLES
        privileges: [SELECT]
      - forRole: app
        role: readonly
        on: SEQUENCES
        privileges: [USAGE]
```

Happy to dig into the reconciliation side further if it's useful. I've been working with PostgreSQL internals for a while and this kind of catalog-level grant management is something I find genuinely interesting to think through.

**Comment by BRGOVIND** [comment]
﻿Hi! I'd like to implement this. The plan: extend the `Database` CRD spec with a `schemaGrants` field (list of schema + roles + privileges), and in the reconciler emit `GRANT CREATE/USAGE ON SCHEMA ... TO ...` after the schema is created. I'll open a PR shortly.

**Comment by gbartolini** [comment]
Please stick to the proposed API, which should be based on this #10829, and reused by #10826

**Comment by gbartolini** [comment]
Follow-up idea for this feature, not part of this PR: extend permissions with table-level grants scoped to `ALL TABLES IN SCHEMA` only (never naming individual tables, as CNPG should never need to know about, let alone create, application tables). Something like:

```yaml
  permissions:
    usage: [...]
    create: [...]
    tables:
      select: [...]
      insert: [...]
      update: [...]
      delete: [...]
      truncate: [...]
      references: [...]
      trigger: [...]
      maintain: [...]
      all: [...]
```

Each list reuses the existing grant/revoke UsageSpec shape, and maps directly onto GRANT/REVOKE <PRIVILEGE> ON ALL TABLES IN SCHEMA ... TO/FROM ....

The open question before this is buildable: ALL TABLES IN SCHEMA only affects tables that exist when the GRANT runs. Tables are created by the application, not by CNPG, on their own schedule. So this only works if something re-applies the grant periodically.

Today, the Database reconciler doesn't do that: once a Database is applied, it goes fully idle until the next spec change (no steady-state polling). Making this feature actually catch newly created tables means adding real always-on periodic reconciliation for Database objects that opt into table-level grants, which has its own cost/interval trade-offs (grant cost scales with table count in the schema, unlike the O(1) schema-level grants). Needs its own design pass before implementation.

In my opinion, this is another reason why these operations should not be under CNPG's scope.
