### ISSUE TITLE
Create the `pgbench` command for kubectl plugin

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#847]
Add a new command for the `kubectl` plugin called `pgbench` with the following syntax:

```console
kubectl cnpg pgbench [--dry-run] [--name <JOBNAME>] [--dbname <DBNAME>] <CLUSTER> <PGBENCH OPTIONS>
```

which creates a Job object like the following:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: <JOBNAME>
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pgbench
        image: <SAME IMAGE AS THE CLUSTER>
        env:
        - name: PGHOST
          value: <CLUSTER>-rw
        - name: PGDATABASE
          value: <DBNAME>
        - name: PGPORT
          value: '5432'
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: <CLUSTER>-app
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: <CLUSTER>-app
              key: password
        command:
        - pgbench
        - <PGBENCH OPTIONS - one per line>
```

Where JOBNAME by default is <CLUSTER>-pgbench-XXXXX and <DBNAME> by default is `pgbench`.

If `--dry-run` is specified, we output the YAML content, otherwise we create the `Job`.

Please add a "benchmarking" section to the docs with some examples.
