### ISSUE TITLE
Cannot import database: language \"plpgsql\" does not exist

### ISSUE THREAD

**Issue by jacobfederer** [cloudnative-pg/cloudnative-pg#869]
Hello fellow people,

I'm trying to import an existing database with the following config: 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-tbnext-test
  namespace: test
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:14.5

  postgresql:
    parameters:
      shared_buffers: 32MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '4s'


  bootstrap:
    initdb:
      owner: superuser
      import:
        type: microservice
        databases:
          - postgres
        source:
          externalCluster: postgres-test-10

  externalClusters:
    - name: postgres-test-10
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: postgresql.test.svc.cluster.local
        user: admin
        dbname: postgres
        sslmode: disable

      password:
        name: db-test-secret-new
        key: password

  storage:
    size: 1Gi
    storageClass: pd-standard

  resources:
    requests:
      memory: "128Mi"
      cpu: "0.1"
    limits:
      memory: "128Mi"
      cpu: "0.1"
```

Dumping the data from the old database now runs smooth, but recovering into the new db runs into an issue. Some key functionalities of our application are written in plpgsql. Somehow the current container does not accept these (**ERROR:  language \"plpgsql\" does not exist"**) with the remark to use the 'CREATE EXTENSION' method. But at this stage this is impossible for me. 

How can I solve this issue?

Here are the logs:

```
{"level":"info","ts":1665755637.0472665,"logger":"pg_restore","msg":"pg_restore: from TOC entry 437; 1255 1157999 FUNCTION abc_method(integer, date, integer, integer, uuid) admin","pipe":"stderr","logging_pod":"__"}
{"level":"info","ts":1665755637.047276,"logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  language \"plpgsql\" does not exist","pipe":"stderr","logging_pod":"postgresql-tbnext-test-1"}
{"level":"info","ts":1665755637.0472832,"logger":"pg_restore","msg":"HINT:  Use CREATE EXTENSION to load the language into the database.","pipe":"stderr","logging_pod":"__"}
{"level":"info","ts":1665755637.0472946,"logger":"pg_restore","msg":"Command was: CREATE FUNCTION sdfkj_method(integer,  date,  integer,  integer,  uuid) RETURNS TABLE(id integer)","pipe":"stderr","logging_pod":"__"}
```
