### ISSUE TITLE
The validation webhook allows creating Clusters with no storage configuration

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#884]
We are not preventing this CR to be applied:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pippo
spec:
  imageName: 'ghcr.io/cloudnative-pg/postgresql:14.3'
```

And with this the operator is not going to work because the PVC can't be created.
