### ISSUE TITLE
Size vs PVC Templates

### ISSUE THREAD

**Issue by till** [cloudnative-pg/cloudnative-pg#904]
Using one of your examples:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-test
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  # Persistent storage configuration
  storage:
    # !!!
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem
```

I had missed that I also need to set `Size` when I setup a cluster:

```
{"level":"error","ts":1666283562.0588248,"msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","cluster":{"name":"db-test","namespace":"test"},"namespace":"test","name":"db-test","reconcileID":"bf6ccf11-1ad3-4993-b41b-a60cfefeeca5","error":"while parsing PVC size : quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

I am guessing that because `Size` is a string, it gets evaluated by the API. But maybe that requirement can be lifted? It seems redundant, or is there another reason?
