### ISSUE TITLE
Mismatch between Docker pgbouncer user and security group

### ISSUE THREAD

**Issue by mikeyk** [cloudnative-pg/cloudnative-pg#921]
I have a simple Pooler added to my cluster:
```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg-pooler-rw
  labels:
    app: pg-pooler-rw
spec:
  cluster:
    name: pg-cluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "10000"
      default_pool_size: "30"
      client_idle_timeout: "600"
```

I'd like to connect to the `pgbouncer` database to get access to the connection pooler stats. However, when I try to access the pod using `kubectl exec`, I see that I am user 998 (`I have no name!` it says), and pgbouncer is expecting user `1000` (given the Dockerfile):

```
I have no name!@pg-pooler-ro-79684b945c-stzx7:/$ cat /etc/passwd | grep pgbouncer
pgbouncer:x:1000:1000:,,,:/home/pgbouncer:/bin/bash
```

```
I have no name!@pg-pooler-ro-79684b945c-stzx7:/$ whoami
whoami: cannot find name for user ID 998
```

If I look at the generated Pod yaml (using `k9s`'s edit command) I see that the pod has been started with:
```
  securityContext:
    fsGroup: 996
    runAsGroup: 996
    runAsNonRoot: true
    runAsUser: 998
```

Which is where the 998 is coming from. Is anyone else experiencing this? Is there a way to override that `runAsUser` to match pgbouncer's 1000 UID? I tried specifying a securityContext in the `spec` part of the Pooler but it didn't override the definition. Many thanks!
