### ISSUE TITLE
Backup to nutanix s3 objects not working

### ISSUE THREAD

**Issue by HanssenKai** [cloudnative-pg/cloudnative-pg#972]
Possible duplicate of #734, but i'm having issues with WAL errors when using backup. The object storage in question is nutanix object store, which supports s3 api.

CNPG version: 1.17.0   
 
**notable errors:** (also attached pod logs(trace), grepped for wal and deduped)
`{"level":"info""logger":"barman-cloud-check-wal-archive","msg":"2022-11-09 07:52:22,423 [85] ERROR: Barman cloud WAL archive check exception: An HTTP Client raised an unhandled exception: Invalid header value b'AWS4-HMAC-SHA256 Credential=<my-s3-access-key-id>\\n/20221109/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=34a14c018c2473f4748b9ded0f3308f8ab07f67793d86e64b03cc5d04635588e'","pipe":"stderr","logging_pod":"wikijs-backup-test-1"}`  

`{"level":"error""logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"wikijs-backup-test-1","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:82\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/proc.go:250"}`  
  
Tried looking for more logs in /controller/log/postgres[.csv/.json], but they are empty.

My cluster backup section: (tried both http and https)
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wikijs-backup-test
  ...
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://velero-backup/k0
      endpointCA:
        key: ca.pem
        name: nutanix-s3-ca
      endpointURL: https://nutanix-obj-s3.obj-s3-proxy.svc.cluster.local:443
      s3Credentials:
        accessKeyId:
          key: access_key
          name: nutanix-s3
        inheritFromIAMRole: false
        secretAccessKey:
          key: access_secret
          name: nutanix-s3
  ...
```
I've testet backups manually from within the pod with success:  
```
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
barman-cloud-wal-archive  --cloud-provider aws-s3 s3://velero-backup/k0 \
 --endpoint-url http://nutanix-obj-s3.obj-s3-proxy.svc.cluster.local:80 \
   wikijs-backup-test \ 
   /var/lib/postgresql/data/pgdata/pg_wal/000000010000000000000001
```
And i've had no problems using the object store with velero backups. A bit lost on further troubleshooting at the moment, appreciate any help! 

[wal-logs.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/9968917/wal-logs.txt)
